traccc::measurement_creation Class Reference
#include <measurement_creation.hpp>
Public Member Functions
measurement_creation (vecmem::memory_resource &mr)
output_type operator() (const cluster_container_types::host &clusters, const cell_module_collection_types::host &modules) const override
Private Attributes
std::reference_wrapper< vecmem::memory_resource > m_mr
The memory resource used by the algorithm.
Detailed Description
Measurement creation out of clusters
This algorithm can create measurements for a single detector module for all of the clusters that were identified in that one detector module.
Constructor & Destructor Documentation
measurement_creation()
traccc::measurement_creation::measurement_creation (vecmem::memory_resource & mr)
Measurement_creation algorithm constructor
Parameters
mr The memory resource to use in the algorithm
    : m_mr(mr) {}
Member Function Documentation
operator()()
measurement_creation::output_type traccc::measurement_creation::operator() (const cluster_container_types::host & clusters, const cell_module_collection_types::host & modules) const [override]
Callable operator for the connected component, based on one single module
Parameters
clusters Container of cells. Each subvector of cells corresponds to a cluster
modules Collection of detector modules the clusters link to.
C++20 piping interface
Returns
a measurement collection - usually same size or sometime slightly smaller than the input
                                                           {
    // Create the result object.
    output_type result(&(m_mr.get()));
    result.reserve(clusters.size());
    // Process the clusters one-by-one.
    for (std::size_t i = 0; i < clusters.size(); ++i) {
        // To calculate the mean and variance with high numerical stability
        // we use a weighted variant of Welford's algorithm. This is a
        // single-pass online algorithm that works well for large numbers
        // of samples, as well as samples with very high values.
        //
        // To learn more about this algorithm please refer to:
        // [1] https://doi.org/10.1080/00401706.1962.10490022
        // [2] The Art of Computer Programming, Donald E. Knuth, second
        // edition, chapter 4.2.2.
        // Get the cluster.
        cluster_container_types::host::item_vector::const_reference cluster =
            clusters.at(i).items;
        // A security check.
        assert(cluster.empty() == false);
        // Get the cell module
        const auto module_link = cluster.at(0).module_link;
        const auto &module = modules.at(module_link);
        // Fill measurement from cluster
        detail::fill_measurement(result, cluster, module, module_link);
    }
    return result;
}
References traccc::host_container< header_t, item_t >::at(), traccc::detail::fill_measurement(), traccc::container_element< header_reference_t, vector_reference_t >::items, m_mr, and traccc::host_container< header_t, item_t >::size().
Member Data Documentation
m_mr
std::reference_wrapper<vecmem::memory_resource> traccc::measurement_creation::m_mr [private]
The memory resource used by the algorithm.
Referenced by operator()().
The documentation for this class was generated from the following files:
core/include/traccc/clusterization/measurement_creation.hpp
core/src/clusterization/measurement_creation.cpp