traccc::host_container< header_t, item_t > Class Template Reference
Host container describing objects in a given event.
#include <host_container.hpp>
Public Types
using base_type = container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >
Base class type.
Public Member Functions
TRACCC_HOST base_type::element_view at (typename base_type::size_type i)
Bounds-checking mutable element accessor.
TRACCC_HOST base_type::const_element_view at (typename base_type::size_type i) const
Bounds-checking immutable element accessor.
TRACCC_HOST base_type::item_type & at (const typename base_type::link_type &link)
Bounds-checking mutable item vector element accessor.
TRACCC_HOST const base_type::item_type & at (const typename base_type::link_type &link) const
Bounds-checking immutable item vector element accessor.
TRACCC_HOST base_type::element_view operator[] (typename base_type::size_type i)
Mutable element accessor.
TRACCC_HOST base_type::const_element_view operator[] (typename base_type::size_type i) const
Immutable element accessor.
TRACCC_HOST base_type::item_type & operator[] (const typename base_type::link_type &link)
Mutable item vector element accessor.
TRACCC_HOST const base_type::item_type & operator[] (const typename base_type::link_type &link) const
Immutable item vector element accessor.
TRACCC_HOST base_type::size_type size (void) const
Return the size of the container.
TRACCC_HOST void reserve (typename base_type::size_type s)
Reserve space in both vectors.
TRACCC_HOST void resize (typename base_type::size_type s)
Resize space in both vectors.
template<typename h_prime , typename v_prime >
TRACCC_HOST void push_back (h_prime &&new_header, v_prime &&new_items)
Push a header and a vector into the container.
TRACCC_HOST base_type::size_type total_size () const
Additional Inherited Members
Detailed Description
template<typename header_t, typename item_t>
class traccc::host_container< header_t, item_t >
Host container describing objects in a given event.
Member Typedef Documentation
base_type
template<typename header_t , typename item_t >
using traccc::host_container< header_t, item_t >::base_type = container_base<header_t, item_t, vecmem::vector, vecmem::jagged_vector>
Base class type.
Member Function Documentation
at() [1/4]
template<typename header_t , typename item_t >
TRACCC_HOST base_type::item_type& traccc::host_container< header_t, item_t >::at (const typename base_type::link_type & link) [inline]
Bounds-checking mutable item vector element accessor.
                                                 {
        return this->m_items.at(link.first).at(link.second);
    }
References traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::m_items.
at() [2/4]
template<typename header_t , typename item_t >
TRACCC_HOST const base_type::item_type& traccc::host_container< header_t, item_t >::at (const typename base_type::link_type & link) const [inline]
Bounds-checking immutable item vector element accessor.
                                                       {
        return this->m_items.at(link.first).at(link.second);
    }
References traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::m_items.
at() [3/4]
template<typename header_t , typename item_t >
TRACCC_HOST base_type::element_view traccc::host_container< header_t, item_t >::at (typename base_type::size_type i) [inline]
Bounds-checking mutable element accessor.
                                                                     {
        return {this->m_headers.at(i), this->m_items.at(i)};
    }
References traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::m_headers, and traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::m_items.
Referenced by main(), traccc::futhark::spacepoint_formation::operator()(), traccc::measurement_creation::operator()(), seq_run(), and TEST_P().
at() [4/4]
template<typename header_t , typename item_t >
TRACCC_HOST base_type::const_element_view traccc::host_container< header_t, item_t >::at (typename base_type::size_type i) const [inline]
Bounds-checking immutable element accessor.
                                             {
        return {this->m_headers.at(i), this->m_items.at(i)};
    }
References traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::m_headers, and traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::m_items.
operator[]() [1/4]
template<typename header_t , typename item_t >
TRACCC_HOST base_type::item_type& traccc::host_container< header_t, item_t >::operator[] (const typename base_type::link_type & link) [inline]
Mutable item vector element accessor.
                                                 {
        return this->m_items[link.first][link.second];
    }
References traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::m_items.
operator[]() [2/4]
template<typename header_t , typename item_t >
TRACCC_HOST const base_type::item_type& traccc::host_container< header_t, item_t >::operator[] (const typename base_type::link_type & link) const [inline]
Immutable item vector element accessor.
                                                       {
        return this->m_items[link.first][link.second];
    }
References traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::m_items.
operator[]() [3/4]
template<typename header_t , typename item_t >
TRACCC_HOST base_type::element_view traccc::host_container< header_t, item_t >::operator[] (typename base_type::size_type i) [inline]
Mutable element accessor.
                                       {
        return {this->m_headers[i], this->m_items[i]};
    }
References traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::m_headers, and traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::m_items.
operator[]() [4/4]
template<typename header_t , typename item_t >
TRACCC_HOST base_type::const_element_view traccc::host_container< header_t, item_t >::operator[] (typename base_type::size_type i) const [inline]
Immutable element accessor.
                                             {
        return {this->m_headers[i], this->m_items[i]};
    }
References traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::m_headers, and traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::m_items.
push_back()
template<typename header_t , typename item_t >
template<typename h_prime , typename v_prime >
TRACCC_HOST void traccc::host_container< header_t, item_t >::push_back (h_prime && new_header, v_prime && new_items) [inline]
Push a header and a vector into the container.
                                                                          {
        this->m_headers.push_back(
            std::forward<typename base_type::header_type>(new_header));
        this->m_items.push_back(
            std::forward<typename base_type::item_vector::value_type>(
                new_items));
    }
References traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::m_headers, and traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::m_items.
Referenced by traccc::event_map2::generate_truth_candidates(), traccc::fitting_algorithm< fitter_t >::operator()(), and traccc::finding_algorithm< stepper_t, navigator_t >::operator()().
reserve()
template<typename header_t , typename item_t >
TRACCC_HOST void traccc::host_container< header_t, item_t >::reserve (typename base_type::size_type s) [inline]
Reserve space in both vectors.
                                                {
        this->m_headers.reserve(s);
        this->m_items.reserve(s);
    }
References traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::m_headers, and traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::m_items.
Referenced by traccc::fitting_algorithm< fitter_t >::operator()(), and traccc::finding_algorithm< stepper_t, navigator_t >::operator()().
resize()
template<typename header_t , typename item_t >
TRACCC_HOST void traccc::host_container< header_t, item_t >::resize (typename base_type::size_type s) [inline]
Resize space in both vectors.
                                               {
        this->m_headers.resize(s);
        this->m_items.resize(s);
    }
References traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::m_headers, and traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::m_items.
Referenced by traccc::finding_algorithm< stepper_t, navigator_t >::operator()().
size()
template<typename header_t , typename item_t >
TRACCC_HOST base_type::size_type traccc::host_container< header_t, item_t >::size (void) const [inline]
Return the size of the container.
In principle, the size of the two internal vectors should always be equal, but we can assert this at runtime for debug builds.
                                                 {
        assert(this->m_headers.size() == this->m_items.size());
        return this->m_headers.size();
    }
References traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::m_headers.
Referenced by main(), traccc::futhark::spacepoint_formation::operator()(), traccc::fitting_algorithm< fitter_t >::operator()(), traccc::measurement_creation::operator()(), seq_run(), and TEST_P().
total_size()
template<typename header_t , typename item_t >
TRACCC_HOST base_type::size_type traccc::host_container< header_t, item_t >::total_size () const [inline]
@breif Get number of items of jagged vector
                                                   {
        typename base_type::size_type ret = 0;
        for (const typename base_type::item_vector::value_type& item :
             this->m_items) {
            ret += item.size();
        }
        return ret;
    }
References traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::m_items.
The documentation for this class was generated from the following file:
core/include/traccc/edm/details/host_container.hpp