traccc::track_state< algebra_t > Struct Template Reference
Fitting result per measurement.
#include <track_state.hpp>
Public Types
using bound_track_parameters_type = detray::bound_track_parameters< algebra_t >
using bound_matrix = typename bound_track_parameters_type::covariance_type
using scalar_type = typename algebra_t::scalar_type
using matrix_operator = typename algebra_t::matrix_actor
using size_type = typename matrix_operator::size_ty
template<size_type ROWS, size_type COLS>
using matrix_type = typename matrix_operator::template matrix_type< ROWS, COLS >
Public Member Functions
track_state ()=default
TRACCC_HOST_DEVICE track_state (const track_candidate &trk_cand)
Construction with track candidate.
TRACCC_HOST_DEVICE detray::geometry::barcode surface_link () const
TRACCC_HOST_DEVICE const measurement & get_measurement () const
template<size_type D>
TRACCC_HOST_DEVICE matrix_type< D, 1 > measurement_local () const
template<size_type D>
TRACCC_HOST_DEVICE matrix_type< D, D > measurement_covariance () const
TRACCC_HOST_DEVICE bound_track_parameters_type & predicted ()
TRACCC_HOST_DEVICE const bound_track_parameters_type & predicted () const
TRACCC_HOST_DEVICE bound_matrix & jacobian ()
TRACCC_HOST_DEVICE const bound_matrix & jacobian () const
TRACCC_HOST_DEVICE scalar_type & filtered_chi2 ()
TRACCC_HOST_DEVICE const scalar_type & filtered_chi2 () const
TRACCC_HOST_DEVICE bound_track_parameters_type & filtered ()
TRACCC_HOST_DEVICE const bound_track_parameters_type & filtered () const
TRACCC_HOST_DEVICE scalar_type & smoothed_chi2 ()
TRACCC_HOST_DEVICE const scalar_type & smoothed_chi2 () const
TRACCC_HOST_DEVICE bound_track_parameters_type & smoothed ()
TRACCC_HOST_DEVICE const bound_track_parameters_type & smoothed () const
Public Attributes
bool is_hole {true}
Private Attributes
detray::geometry::barcode m_surface_link
measurement m_measurement
bound_matrix m_jacobian
bound_track_parameters_type m_predicted
scalar_type m_filtered_chi2
bound_track_parameters_type m_filtered
scalar_type m_smoothed_chi2
bound_track_parameters_type m_smoothed
Detailed Description
template<typename algebra_t>
struct traccc::track_state< algebra_t >
Fitting result per measurement.
Member Typedef Documentation
bound_matrix
template<typename algebra_t >
using traccc::track_state< algebra_t >::bound_matrix = typename bound_track_parameters_type::covariance_type
bound_track_parameters_type
template<typename algebra_t >
using traccc::track_state< algebra_t >::bound_track_parameters_type = detray::bound_track_parameters<algebra_t>
matrix_operator
template<typename algebra_t >
using traccc::track_state< algebra_t >::matrix_operator = typename algebra_t::matrix_actor
matrix_type
template<typename algebra_t >
template<size_type ROWS, size_type COLS>
using traccc::track_state< algebra_t >::matrix_type = typename matrix_operator::template matrix_type<ROWS, COLS>
scalar_type
template<typename algebra_t >
using traccc::track_state< algebra_t >::scalar_type = typename algebra_t::scalar_type
size_type
template<typename algebra_t >
using traccc::track_state< algebra_t >::size_type = typename matrix_operator::size_ty
Constructor & Destructor Documentation
track_state() [1/2]
template<typename algebra_t >
traccc::track_state< algebra_t >::track_state () [default]
track_state() [2/2]
template<typename algebra_t >
TRACCC_HOST_DEVICE traccc::track_state< algebra_t >::track_state (const track_candidate & trk_cand) [inline]
Construction with track candidate.
        : m_surface_link(trk_cand.surface_link), m_measurement(trk_cand) {
        m_predicted.set_surface_link(m_surface_link);
        m_filtered.set_surface_link(m_surface_link);
        m_smoothed.set_surface_link(m_surface_link);
    }
References traccc::track_state< algebra_t >::m_filtered, traccc::track_state< algebra_t >::m_predicted, traccc::track_state< algebra_t >::m_smoothed, and traccc::track_state< algebra_t >::m_surface_link.
Member Function Documentation
filtered() [1/2]
template<typename algebra_t >
TRACCC_HOST_DEVICE bound_track_parameters_type& traccc::track_state< algebra_t >::filtered () [inline]
Returns
the non-const filtered parameter
{ return m_filtered; }
References traccc::track_state< algebra_t >::m_filtered.
Referenced by traccc::gain_matrix_smoother< algebra_t >::smoothe(), and traccc::gain_matrix_updater< algebra_t >::update().
filtered() [2/2]
template<typename algebra_t >
TRACCC_HOST_DEVICE const bound_track_parameters_type& traccc::track_state< algebra_t >::filtered () const [inline]
Returns
the const filtered parameter
                                                               {
        return m_filtered;
    }
References traccc::track_state< algebra_t >::m_filtered.
filtered_chi2() [1/2]
template<typename algebra_t >
TRACCC_HOST_DEVICE scalar_type& traccc::track_state< algebra_t >::filtered_chi2 () [inline]
Returns
the non-const chi square of filtered parameter
{ return m_filtered_chi2; }
References traccc::track_state< algebra_t >::m_filtered_chi2.
Referenced by traccc::stat_plot_tool::fill(), and traccc::gain_matrix_updater< algebra_t >::update().
filtered_chi2() [2/2]
template<typename algebra_t >
TRACCC_HOST_DEVICE const scalar_type& traccc::track_state< algebra_t >::filtered_chi2 () const [inline]
Returns
the const chi square of filtered parameter
{ return m_filtered_chi2; }
References traccc::track_state< algebra_t >::m_filtered_chi2.
get_measurement()
template<typename algebra_t >
TRACCC_HOST_DEVICE const measurement& traccc::track_state< algebra_t >::get_measurement () const [inline]
Returns
the measurement
{ return m_measurement; }
References traccc::track_state< algebra_t >::m_measurement.
Referenced by traccc::stat_plot_tool::fill(), traccc::statistics_updater< algebra_t >::operator()(), traccc::gain_matrix_updater< algebra_t >::operator()(), traccc::gain_matrix_smoother< algebra_t >::operator()(), traccc::gain_matrix_smoother< algebra_t >::smoothe(), and traccc::gain_matrix_updater< algebra_t >::update().
jacobian() [1/2]
template<typename algebra_t >
TRACCC_HOST_DEVICE bound_matrix& traccc::track_state< algebra_t >::jacobian () [inline]
Returns
the non-const transport jacobian
{ return m_jacobian; }
References traccc::track_state< algebra_t >::m_jacobian.
Referenced by traccc::gain_matrix_smoother< algebra_t >::smoothe().
jacobian() [2/2]
template<typename algebra_t >
TRACCC_HOST_DEVICE const bound_matrix& traccc::track_state< algebra_t >::jacobian () const [inline]
Returns
the const transport jacobian
{ return m_jacobian; }
References traccc::track_state< algebra_t >::m_jacobian.
measurement_covariance()
template<typename algebra_t >
template<size_type D>
TRACCC_HOST_DEVICE matrix_type<D, D> traccc::track_state< algebra_t >::measurement_covariance () const [inline]
Returns
the covariance of local position of measurement
                                                                               {
        static_assert(((D == 1u) || (D == 2u)),
                      "The measurement dimension should be 1 or 2");
        matrix_type<D, D> ret;
        matrix_operator().element(ret, 0, 0) = m_measurement.variance[0];
        if constexpr (D == 2u) {
            matrix_operator().element(ret, 0, 1) = 0.f;
            matrix_operator().element(ret, 1, 0) = 0.f;
            matrix_operator().element(ret, 1, 1) = m_measurement.variance[1];
        }
        return ret;
    }
References traccc::track_state< algebra_t >::m_measurement, and traccc::measurement::variance.
measurement_local()
template<typename algebra_t >
template<size_type D>
TRACCC_HOST_DEVICE matrix_type<D, 1> traccc::track_state< algebra_t >::measurement_local () const [inline]
Returns
the local position of measurement with 2 X 1 matrix
                                                                          {
        static_assert(((D == 1u) || (D == 2u)),
                      "The measurement dimension should be 1 or 2");
        matrix_type<D, 1> ret;
        matrix_operator().element(ret, 0, 0) = m_measurement.local[0];
        if constexpr (D == 2u) {
            matrix_operator().element(ret, 1, 0) = m_measurement.local[1];
        }
        return ret;
    }
References traccc::measurement::local, and traccc::track_state< algebra_t >::m_measurement.
predicted() [1/2]
template<typename algebra_t >
TRACCC_HOST_DEVICE bound_track_parameters_type& traccc::track_state< algebra_t >::predicted () [inline]
Returns
the non-const reference of predicted track state
{ return m_predicted; }
References traccc::track_state< algebra_t >::m_predicted.
Referenced by traccc::gain_matrix_smoother< algebra_t >::smoothe(), and traccc::gain_matrix_updater< algebra_t >::update().
predicted() [2/2]
template<typename algebra_t >
TRACCC_HOST_DEVICE const bound_track_parameters_type& traccc::track_state< algebra_t >::predicted () const [inline]
Returns
the const reference of predicted track state
                                                                {
        return m_predicted;
    }
References traccc::track_state< algebra_t >::m_predicted.
smoothed() [1/2]
template<typename algebra_t >
TRACCC_HOST_DEVICE bound_track_parameters_type& traccc::track_state< algebra_t >::smoothed () [inline]
Returns
the non-const smoothed parameter
{ return m_smoothed; }
References traccc::track_state< algebra_t >::m_smoothed.
Referenced by traccc::gain_matrix_smoother< algebra_t >::smoothe().
smoothed() [2/2]
template<typename algebra_t >
TRACCC_HOST_DEVICE const bound_track_parameters_type& traccc::track_state< algebra_t >::smoothed () const [inline]
Returns
the const smoothed parameter
                                                               {
        return m_smoothed;
    }
References traccc::track_state< algebra_t >::m_smoothed.
smoothed_chi2() [1/2]
template<typename algebra_t >
TRACCC_HOST_DEVICE scalar_type& traccc::track_state< algebra_t >::smoothed_chi2 () [inline]
Returns
the non-const chi square of smoothed parameter
{ return m_smoothed_chi2; }
References traccc::track_state< algebra_t >::m_smoothed_chi2.
Referenced by traccc::stat_plot_tool::fill(), traccc::statistics_updater< algebra_t >::operator()(), and traccc::gain_matrix_smoother< algebra_t >::smoothe().
smoothed_chi2() [2/2]
template<typename algebra_t >
TRACCC_HOST_DEVICE const scalar_type& traccc::track_state< algebra_t >::smoothed_chi2 () const [inline]
Returns
the const chi square of smoothed parameter
{ return m_smoothed_chi2; }
References traccc::track_state< algebra_t >::m_smoothed_chi2.
surface_link()
template<typename algebra_t >
TRACCC_HOST_DEVICE detray::geometry::barcode traccc::track_state< algebra_t >::surface_link () const [inline]
Returns
the surface link
                                                      {
        return m_surface_link;
    }
References traccc::track_state< algebra_t >::m_surface_link.
Member Data Documentation
is_hole
template<typename algebra_t >
bool traccc::track_state< algebra_t >::is_hole {true}
Referenced by traccc::statistics_updater< algebra_t >::operator()().
m_filtered
template<typename algebra_t >
bound_track_parameters_type traccc::track_state< algebra_t >::m_filtered [private]
Referenced by traccc::track_state< algebra_t >::filtered(), and traccc::track_state< algebra_t >::track_state().
m_filtered_chi2
template<typename algebra_t >
scalar_type traccc::track_state< algebra_t >::m_filtered_chi2 [private]
Referenced by traccc::track_state< algebra_t >::filtered_chi2().
m_jacobian
template<typename algebra_t >
bound_matrix traccc::track_state< algebra_t >::m_jacobian [private]
Initial value:
=
        matrix_operator().template zero<e_bound_size, e_bound_size>()
Referenced by traccc::track_state< algebra_t >::jacobian().
m_measurement
template<typename algebra_t >
measurement traccc::track_state< algebra_t >::m_measurement [private]
Referenced by traccc::track_state< algebra_t >::get_measurement(), traccc::track_state< algebra_t >::measurement_covariance(), and traccc::track_state< algebra_t >::measurement_local().
m_predicted
template<typename algebra_t >
bound_track_parameters_type traccc::track_state< algebra_t >::m_predicted [private]
Referenced by traccc::track_state< algebra_t >::predicted(), and traccc::track_state< algebra_t >::track_state().
m_smoothed
template<typename algebra_t >
bound_track_parameters_type traccc::track_state< algebra_t >::m_smoothed [private]
Referenced by traccc::track_state< algebra_t >::smoothed(), and traccc::track_state< algebra_t >::track_state().
m_smoothed_chi2
template<typename algebra_t >
scalar_type traccc::track_state< algebra_t >::m_smoothed_chi2 [private]
Referenced by traccc::track_state< algebra_t >::smoothed_chi2().
m_surface_link
template<typename algebra_t >
detray::geometry::barcode traccc::track_state< algebra_t >::m_surface_link [private]
Referenced by traccc::track_state< algebra_t >::surface_link(), and traccc::track_state< algebra_t >::track_state().
The documentation for this struct was generated from the following file:
core/include/traccc/edm/track_state.hpp