traccc::fitting_algorithm< fitter_t > Class Template Reference
Fitting algorithm for a set of tracks.
#include <fitting_algorithm.hpp>
Public Types
using transform3_type = typename fitter_t::transform3_type
using bfield_type = typename fitter_t::bfield_type
using config_type = typename fitter_t::config_type
Configuration type.
Public Member Functions
fitting_algorithm (const config_type &cfg)
track_state_container_types::host operator() (const typename fitter_t::detector_type &det, const typename fitter_t::bfield_type &field, const typename track_candidate_container_types::host &track_candidates) const override
Public Attributes
config_type m_cfg
Config object.
Detailed Description
template<typename fitter_t>
class traccc::fitting_algorithm< fitter_t >
Fitting algorithm for a set of tracks.
Member Typedef Documentation
bfield_type
template<typename fitter_t >
using traccc::fitting_algorithm< fitter_t >::bfield_type = typename fitter_t::bfield_type
config_type
template<typename fitter_t >
using traccc::fitting_algorithm< fitter_t >::config_type = typename fitter_t::config_type
Configuration type.
transform3_type
template<typename fitter_t >
using traccc::fitting_algorithm< fitter_t >::transform3_type = typename fitter_t::transform3_type
Constructor & Destructor Documentation
fitting_algorithm()
template<typename fitter_t >
traccc::fitting_algorithm< fitter_t >::fitting_algorithm (const config_type & cfg) [inline]
Constructor for the fitting algorithm
Parameters
cfg Configuration object
: m_cfg(cfg) {}
Member Function Documentation
operator()()
template<typename fitter_t >
track_state_container_types::host traccc::fitting_algorithm< fitter_t >::operator() (const typename fitter_t::detector_type & det, const typename fitter_t::bfield_type & field, const typename track_candidate_container_types::host & track_candidates) const [inline], [override]
Run the algorithm
Parameters
track_candidates the candidate measurements from track finding
Returns
the container of the fitted track parameters
                       {
        fitter_t fitter(det, field, m_cfg);
        track_state_container_types::host output_states;
        // The number of tracks
        std::size_t n_tracks = track_candidates.size();
        // Iterate over tracks
        for (std::size_t i = 0; i < n_tracks; i++) {
            // Seed parameter
            const auto& seed_param = track_candidates[i].header;
            // Make a vector of track state
            auto& cands = track_candidates[i].items;
            vecmem::vector<track_state<transform3_type>> input_states;
            input_states.reserve(cands.size());
            for (auto& cand : cands) {
                input_states.emplace_back(cand);
            }
            // Make a fitter state
            typename fitter_t::state fitter_state(std::move(input_states));
            // Run fitter
            fitter.fit(seed_param, fitter_state);
            output_states.push_back(
                std::move(fitter_state.m_fit_info),
                std::move(fitter_state.m_fit_actor_state.m_track_states));
        }
        return output_states;
    }
References traccc::fitting_algorithm< fitter_t >::m_cfg, traccc::host_container< header_t, item_t >::push_back(), traccc::host_container< header_t, item_t >::reserve(), and traccc::host_container< header_t, item_t >::size().
Member Data Documentation
m_cfg
template<typename fitter_t >
config_type traccc::fitting_algorithm< fitter_t >::m_cfg
Config object.
Referenced by traccc::fitting_algorithm< fitter_t >::operator()().
The documentation for this class was generated from the following file:
core/include/traccc/fitting/fitting_algorithm.hpp