traccc::io Namespace Reference
Namespaces
 csv
 details
 json
Classes
struct cell_reader_output
struct measurement_reader_output
struct spacepoint_reader_output
Functions
void read (demonstrator_input &out, std::size_t events, std::string_view directory, std::string_view detector_file, std::string_view digi_config_file, data_format format=data_format::csv)
void read_cells (cell_reader_output &out, std::size_t event, std::string_view directory, data_format format=data_format::csv, const geometry *geom=nullptr, const digitization_config *dconfig=nullptr)
void read_cells (cell_reader_output &out, std::string_view filename, data_format format=data_format::csv, const geometry *geom=nullptr, const digitization_config *dconfig=nullptr)
digitization_config read_digitization_config (std::string_view filename, data_format format=data_format::json)
geometry read_geometry (std::string_view filename, data_format format=data_format::csv)
template<typename detector_t >
geometry alt_read_geometry (const detector_t &det)
Read in the detector geometry description from a detector object.
void read_measurements (measurement_reader_output &out, std::size_t event, std::string_view directory, data_format format=data_format::csv)
void read_measurements (measurement_reader_output &out, std::string_view filename, data_format format=data_format::csv)
particle_collection_types::host read_particles (std::size_t event, std::string_view directory, data_format format=data_format::csv, vecmem::memory_resource *mr=nullptr)
particle_collection_types::host read_particles (std::string_view filename, data_format format=data_format::csv, vecmem::memory_resource *mr=nullptr)
void read_spacepoints (spacepoint_reader_output &out, std::size_t event, std::string_view directory, const geometry &geom, data_format format=data_format::csv)
void read_spacepoints (spacepoint_reader_output &out, std::string_view filename, std::string_view meas_filename, std::string_view meas_hit_map_filename, const geometry &geom, data_format format=data_format::csv)
const std::string & data_directory ()
std::string get_event_filename (std::size_t event, std::string_view suffix)
void write (std::size_t event, std::string_view directory, traccc::data_format format, traccc::cell_collection_types::const_view cells, traccc::cell_module_collection_types::const_view modules)
Detailed Description
TRACCC library, part of the ACTS project (R&D line)
(c) 2021-2022 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
TRACCC library, part of the ACTS project (R&D line)
(c) 2022 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
TRACCC library, part of the ACTS project (R&D line)
(c) 2023 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
Function Documentation
alt_read_geometry()
template<typename detector_t >
geometry traccc::io::alt_read_geometry (const detector_t & det)
Read in the detector geometry description from a detector object.
                                                  {
    const auto transforms = det.transform_store();
    const auto surfaces = det.surface_lookup();
    std::map<traccc::geometry_id, traccc::transform3> maps;
    using cxt_t = typename detector_t::geometry_context;
    const cxt_t ctx0{};
    for (const auto& sf_desc : surfaces) {
        const detray::surface<detector_t> sf{det, sf_desc.barcode()};
        maps.insert({sf.barcode().value(), sf.transform(ctx0)});
    }
    return maps;
}
Referenced by seq_run().
data_directory()
const std::string & traccc::io::data_directory ()
Get the data directory to use in the application
Returns
The directory name to find data files in
                                  {
    // Establish the directory name only once for the application.
    static const std::string data_dir = [] {
        // Look for an environment variable specifying the directory name.
        const char* env_dir = std::getenv("TRACCC_TEST_DATA_DIR");
        if (env_dir == nullptr) {
            // If an environment variable is not set, rely on the definition
            // coming from the build system.
            return std::string(TRACCC_TEST_DATA_DIR) + "/";
        }
        // Initialise the directory name using the environment variable.
        return std::string(env_dir) + "/";
    }();
    // Return the previously initialised variable.
    return data_dir;
}
Referenced by main(), read_cells(), read_digitization_config(), read_geometry(), read_measurements(), read_particles(), read_spacepoints(), seq_run(), traccc::tests::data_test::SetUp(), TEST(), and write().
get_event_filename()
std::string traccc::io::get_event_filename (std::size_t event, std::string_view suffix)
Get the name of a data file for a specific event ID
Parameters
event The event number to get the file name for
suffix A suffix for the file name
Returns
A standardized name for a data file to use as input.
                                                                     {
    std::ostringstream stream;
    stream << "event" << std::setfill('0') << std::setw(9) << event << suffix;
    return stream.str();
}
Referenced by traccc::event_map2::event_map2(), traccc::generate_hit_cell_map(), traccc::generate_hit_map(), traccc::generate_hit_particle_map(), traccc::generate_particle_map(), GTEST_TEST(), read_cells(), read_measurements(), read_particles(), read_spacepoints(), TEST(), TEST_P(), and write().
read()
void traccc::io::read (demonstrator_input & out, std::size_t events, std::string_view directory, std::string_view detector_file, std::string_view digi_config_file, data_format format = data_format::csv)
Read input data for a specified number of events
This function can read data about multiple events into memory at the same time. Even using (OpenMP) parallelism for the reading if possible.
Parameters
out An object with the requested events worth of input
events The number of events to read input data for
directory The directory to read the cell data from
detector_file The file describing the detector geometry
digi_config_file The file describing the detector digitization
format The format of the event file(s)
                                                               {
    // Read in the detector configuration.
    const geometry geom = io::read_geometry(detector_file);
    const digitization_config digi_cfg =
        io::read_digitization_config(digi_config_file);
    assert(out.size() >= events);
    // Read in the cell data for all events. In parallel if possible.
#pragma omp parallel for
    for (std::size_t event = 0; event < events; ++event) {
        io::read_cells(out[event], event, directory, format, &geom, &digi_cfg);
    }
}
References detector_file, digi_config_file, event, read_cells(), read_digitization_config(), and read_geometry().
Referenced by traccc::throughput_mt(), and traccc::throughput_st().
read_cells() [1/2]
void traccc::io::read_cells (cell_reader_output & out, std::size_t event, std::string_view directory, data_format format = data_format::csv, const geometry * geom = nullptr, const digitization_config * dconfig = nullptr)
Read cell data into memory
The file to read is selected according the naming conventions used in our data.
Parameters
out A cell & a cell_module (host) collections
event The event ID to read in the cells for
directory The directory holding the cell data files
format The format of the cell data files (to read)
geom The description of the detector geometry
dconfig The detector's digitization configuration
                                                                          {
    switch (format) {
        case data_format::csv: {
            read_cells(out,
                       data_directory() + directory.data() +
                           get_event_filename(event, "-cells.csv"),
                       format, geom, dconfig);
            break;
        }
        case data_format::binary: {
            details::read_binary_collection<cell_collection_types::host>(
                out.cells, data_directory() + directory.data() +
                               get_event_filename(event, "-cells.dat"));
            details::read_binary_collection<cell_module_collection_types::host>(
                out.modules, data_directory() + directory.data() +
                                 get_event_filename(event, "-modules.dat"));
            break;
        }
        default:
            throw std::invalid_argument("Unsupported data format");
    }
}
References traccc::binary, traccc::io::cell_reader_output::cells, traccc::csv, data_directory(), event, get_event_filename(), and traccc::io::cell_reader_output::modules.
Referenced by create_binaries(), traccc::generate_measurement_cell_map(), main(), par_run(), read(), seq_run(), TEST(), ConnectedComponentAnalysisTests::test_connected_component_analysis(), TEST_F(), and TEST_P().
read_cells() [2/2]
void traccc::io::read_cells (cell_reader_output & out, std::string_view filename, data_format format = data_format::csv, const geometry * geom = nullptr, const digitization_config * dconfig = nullptr)
Read cell data into memory
The file name is selected explicitly by the user.
Parameters
out A cell & a cell_module (host) collections
filename The file to read the cell data from
format The format of the cell data files (to read)
geom The description of the detector geometry
dconfig The detector's digitization configuration
                                                    {
    switch (format) {
        case data_format::csv:
            return csv::read_cells(out, filename, geom, dconfig);
        default:
            throw std::invalid_argument("Unsupported data format");
    }
}
References traccc::csv, and traccc::io::csv::read_cells().
read_digitization_config()
digitization_config traccc::io::read_digitization_config (std::string_view filename, data_format format = data_format::json)
Read the detector digitization configuration from an input file
Parameters
filename The name of the file to read the data from
format The format of the input file
Returns
An object describing the digitization configuration of the detector
                                                                 {
    // Construct the full filename.
    std::string full_filename = data_directory() + filename.data();
    // Decide how to read the file.
    switch (format) {
        case data_format::json:
            return json::read_digitization_config(full_filename);
        default:
            throw std::invalid_argument("Unsupported data format");
    }
}
References data_directory(), traccc::json, and traccc::io::json::read_digitization_config().
Referenced by create_binaries(), traccc::generate_measurement_cell_map(), par_run(), read(), seq_run(), TEST(), and TEST_P().
read_geometry()
geometry traccc::io::read_geometry (std::string_view filename, data_format format = data_format::csv)
Read in the detector geometry description from an input file
Parameters
filename The name of the input file to read
format The format of the input file
Returns
A description of the detector modules
                                                                    {
    // Construct the full file name.
    const std::string full_filename = data_directory() + filename.data();
    // Read the file using another function. Relying on the auto-conversion of
    // the output type of that other function.
    return details::read_surfaces(full_filename, format);
}
References data_directory(), and traccc::io::details::read_surfaces().
Referenced by create_binaries(), traccc::generate_measurement_cell_map(), traccc::generate_measurement_particle_map(), par_run(), read(), seq_run(), TEST(), TEST_F(), and TEST_P().
read_measurements() [1/2]
void traccc::io::read_measurements (measurement_reader_output & out, std::size_t event, std::string_view directory, data_format format = data_format::csv)
Read measurement data into memory
The file to read is selected according the naming conventions used in our data.
Parameters
out A measurement & a cell_module (host) collections
event The event ID to read in the cells for
directory The directory holding the cell data files
format The format of the cell data files (to read)
                                                                     {
    switch (format) {
        case data_format::csv: {
            read_measurements(
                out,
                data_directory() + directory.data() +
                    get_event_filename(event, "-measurements.csv"),
                format);
            break;
        }
        case data_format::binary: {
            details::read_binary_collection<measurement_collection_types::host>(
                out.measurements,
                data_directory() + directory.data() +
                    get_event_filename(event, "-measurements.dat"));
            details::read_binary_collection<cell_module_collection_types::host>(
                out.modules, data_directory() + directory.data() +
                                 get_event_filename(event, "-modules.dat"));
            break;
        }
        default:
            throw std::invalid_argument("Unsupported data format");
    }
}
References traccc::binary, traccc::csv, data_directory(), event, get_event_filename(), traccc::io::measurement_reader_output::measurements, and traccc::io::measurement_reader_output::modules.
Referenced by create_binaries(), seq_run(), TEST(), TEST_F(), and TEST_P().
read_measurements() [2/2]
void traccc::io::read_measurements (measurement_reader_output & out, std::string_view filename, data_format format = data_format::csv)
Read measurement data into memory
The file name is selected explicitly by the user.
Parameters
out A measurement & a cell_module (host) collections
filename The file to read the cell data from
format The format of the cell data files (to read)
                                                                    {
    switch (format) {
        case data_format::csv:
            return csv::read_measurements(out, filename);
        default:
            throw std::invalid_argument("Unsupported data format");
    }
}
References traccc::csv, and traccc::io::csv::read_measurements().
read_particles() [1/2]
particle_collection_types::host traccc::io::read_particles (std::size_t event, std::string_view directory, data_format format = data_format::csv, vecmem::memory_resource * mr = nullptr)
Read particle data into memory
The file to read is selected according the naming conventions used in our data.
Parameters
event The event ID to read in the cells for
directory The directory holding the particle data files
format The format of the particle data files (to read)
mr The memory resource to create the host collection with
Returns
A particle (host) collection
                                                                          {
    switch (format) {
        case data_format::csv:
            return read_particles(
                data_directory() + directory.data() +
                    get_event_filename(event, "-particles.csv"),
                format, mr);
        default:
            throw std::invalid_argument("Unsupported data format");
    }
}
References traccc::csv, data_directory(), event, and get_event_filename().
Referenced by TEST_F().
read_particles() [2/2]
particle_collection_types::host traccc::io::read_particles (std::string_view filename, data_format format = data_format::csv, vecmem::memory_resource * mr = nullptr)
Read particle data into memory
The file name is selected explicitly by the user.
Parameters
filename The file to read the particle data from
format The format of the particle data files (to read)
mr The memory resource to create the host collection with
Returns
A particle (host) collection
                                                                          {
    switch (format) {
        case data_format::csv:
            return csv::read_particles(filename, mr);
        default:
            throw std::invalid_argument("Unsupported data format");
    }
}
References traccc::csv, and traccc::io::csv::read_particles().
read_spacepoints() [1/2]
void traccc::io::read_spacepoints (spacepoint_reader_output & out, std::size_t event, std::string_view directory, const geometry & geom, data_format format = data_format::csv)
Read spacepoint data into memory
The file to read is selected according the naming conventions used in our data.
Parameters
out A spacepoint & a cell_module (host) collections
event The event ID to read in the cells for
directory The directory holding the cell data files
geom The description of the detector geometry
format The format of the cell data files (to read)
                                          {
    switch (format) {
        case data_format::csv: {
            read_spacepoints(
                out,
                data_directory() + directory.data() +
                    get_event_filename(event, "-hits.csv"),
                data_directory() + directory.data() +
                    get_event_filename(event, "-measurements.csv"),
                data_directory() + directory.data() +
                    get_event_filename(event, "-measurement-simhit-map.csv"),
                geom, format);
            break;
        }
        case data_format::binary: {
            details::read_binary_collection<spacepoint_collection_types::host>(
                out.spacepoints, data_directory() + directory.data() +
                                     get_event_filename(event, "-hits.dat"));
            details::read_binary_collection<cell_module_collection_types::host>(
                out.modules, data_directory() + directory.data() +
                                 get_event_filename(event, "-modules.dat"));
            break;
        }
        default:
            throw std::invalid_argument("Unsupported data format");
    }
}
References traccc::binary, traccc::csv, data_directory(), event, get_event_filename(), traccc::io::spacepoint_reader_output::modules, and traccc::io::spacepoint_reader_output::spacepoints.
Referenced by create_binaries(), traccc::generate_measurement_particle_map(), seq_run(), TEST(), TEST_F(), and TEST_P().
read_spacepoints() [2/2]
void traccc::io::read_spacepoints (spacepoint_reader_output & out, std::string_view filename, std::string_view meas_filename, std::string_view meas_hit_map_filename, const geometry & geom, data_format format = data_format::csv)
Read spacepoint data into memory
The file name is selected explicitly by the user.
Parameters
out A spacepoint & a cell_module (host) collections
filename The file to read the cell data from
geom The description of the detector geometry
format The format of the cell data files (to read)
                                                                {
    switch (format) {
        case data_format::csv:
            return csv::read_spacepoints(out, filename, meas_filename,
                                         meas_hit_map_filename, geom);
        default:
            throw std::invalid_argument("Unsupported data format");
    }
}
References traccc::csv, and traccc::io::csv::read_spacepoints().
write()
void traccc::io::write (std::size_t event, std::string_view directory, traccc::data_format format, traccc::cell_collection_types::const_view cells, traccc::cell_module_collection_types::const_view modules)
Function for cell file writing
Parameters
event is the event index
directory is the directory for the output cell file
format is the data format (e.g. csv or binary) of output file
cells is the cell collection to write
modules is the module collection to write
Function for hit file writing
Parameters
event is the event index
directory is the directory for the output spacepoint file
format is the data format (e.g. csv or binary) of output file
spacepoints is the spacepoint collection to write
modules is the module collection to write
Function for measurement file writing
Parameters
event is the event index
directory is the directory for the output measurement file
format is the data format (e.g. csv or binary) of output file
measurements is the measurement collection to write
modules is the module collection to write
                                                                 {
    switch (format) {
        case data_format::binary:
            details::write_binary_collection(
                data_directory() + directory.data() +
                    get_event_filename(event, "-cells.dat"),
                traccc::cell_collection_types::const_device{cells});
            details::write_binary_collection(
                data_directory() + directory.data() +
                    get_event_filename(event, "-modules.dat"),
                traccc::cell_module_collection_types::const_device{modules});
            break;
        default:
            throw std::invalid_argument("Unsupported data format");
    }
}
References traccc::binary, data_directory(), event, get_event_filename(), and traccc::io::details::write_binary_collection().
Referenced by create_binaries(), and TEST().