traccc::io::csv Namespace Reference
Classes
struct cell
Type used in reading CSV data into memory.
struct hit
Type to read information into about Fatras hits.
struct measurement
Type used in reading CSV measurement data into memory.
struct measurement_hit_id
Type used in reading CSV measurement-to-hit ID data into memory.
struct particle
Type used in reading CSV particle data into memory.
struct surface
Type to read information into about the detector modules/surfaces.
Functions
dfe::NamedTupleCsvReader< cell > make_cell_reader (std::string_view filename)
dfe::NamedTupleCsvReader< hit > make_hit_reader (std::string_view filename)
dfe::NamedTupleCsvReader< measurement_hit_id > make_measurement_hit_id_reader (std::string_view filename)
dfe::NamedTupleCsvReader< measurement > make_measurement_reader (std::string_view filename)
dfe::NamedTupleCsvReader< particle > make_particle_reader (std::string_view filename)
dfe::NamedTupleCsvReader< surface > make_surface_reader (std::string_view filename)
void read_cells (cell_reader_output &out, std::string_view filename, const geometry *geom, const digitization_config *dconfig)
void read_measurements (measurement_reader_output &out, std::string_view filename, const bool do_sort)
measurement_container_types::host read_measurements_container (std::string_view filename, vecmem::memory_resource *mr)
particle_collection_types::host read_particles (std::string_view filename, vecmem::memory_resource *mr)
void read_spacepoints (spacepoint_reader_output &out, std::string_view filename, std::string_view meas_filename, std::string_view meas_hit_map_filename, const geometry &geom)
std::map< geometry_id, transform3 > read_surfaces (std::string_view filename)
Read the geometry information per module and fill into a map.
Detailed Description
TRACCC library, part of the ACTS project (R&D line)
(c) 2022 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
TRACCC library, part of the ACTS project (R&D line)
(c) 2023 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
Function Documentation
make_cell_reader()
dfe::NamedTupleCsvReader< cell > traccc::io::csv::make_cell_reader (std::string_view filename)
Set up an object for reading a CSV file containing cell information
Parameters
filename The name of the file to read
Returns
An object that can read the specified CSV file
                                                                       {
    return {
        filename.data(),
        {"geometry_id", "hit_id", "cannel0", "channel1", "timestamp", "value"}};
}
Referenced by traccc::generate_hit_cell_map(), and read_cells().
make_hit_reader()
dfe::NamedTupleCsvReader< hit > traccc::io::csv::make_hit_reader (std::string_view filename)
Set up an object for reading a CSV file containing hit information
Parameters
filename The name of the file to read
Returns
An object that can read the specified CSV file
                                                                     {
    return {filename.data(),
            {"particle_id", "geometry_id", "tx", "ty", "tz", "tt", "tpx", "tpy",
             "tpz", "te", "deltapx", "deltapy", "deltapz", "deltae", "index"}};
}
Referenced by traccc::event_map2::event_map2(), traccc::generate_hit_map(), traccc::generate_hit_particle_map(), GTEST_TEST(), and read_spacepoints().
make_measurement_hit_id_reader()
dfe::NamedTupleCsvReader< measurement_hit_id > traccc::io::csv::make_measurement_hit_id_reader (std::string_view filename)
Set up a reader for measurement<->hit association information
Parameters
filename The name of the file to read
Returns
An object that can read the specified CSV file
                             {
    return {filename.data(), {"measurement_id", "hit_id"}};
}
Referenced by traccc::event_map2::event_map2(), traccc::generate_hit_map(), GTEST_TEST(), and read_spacepoints().
make_measurement_reader()
dfe::NamedTupleCsvReader< measurement > traccc::io::csv::make_measurement_reader (std::string_view filename)
Set up an object for reading a CSV file containing measurement information
Parameters
filename The name of the file to read
Returns
An object that can read the specified CSV file
                             {
    return {filename.data(),
            {"measurement_id", "geometry_id", "local_key", "local0", "local1",
             "phi", "theta", "time", "var_local0", "var_local1", "var_phi",
             "var_theta", "var_time"}};
}
Referenced by traccc::event_map2::event_map2(), GTEST_TEST(), read_measurements(), read_measurements_container(), and TEST_P().
make_particle_reader()
dfe::NamedTupleCsvReader< particle > traccc::io::csv::make_particle_reader (std::string_view filename)
Set up an object for reading a CSV file containing particle information
Parameters
filename The name of the file to read
Returns
An object that can read the specified CSV file
                             {
    return {filename.data(),
            {"particle_id", "particle_type", "process", "vx", "vy", "vz", "vt",
             "px", "py", "pz", "m", "q"}};
}
Referenced by traccc::event_map2::event_map2(), traccc::generate_particle_map(), GTEST_TEST(), and read_particles().
make_surface_reader()
dfe::NamedTupleCsvReader< surface > traccc::io::csv::make_surface_reader (std::string_view filename)
Set up an object for reading a CSV file containing surface information
Parameters
filename The name of the file to read
Returns
An object that can read the specified CSV file
                             {
    return {filename.data(),
            {"geometry_id", "cx", "cy", "cz", "rot_xu", "rot_xv", "rot_xw",
             "rot_zu", "rot_zv", "rot_zw"}};
}
Referenced by read_surfaces().
read_cells()
void traccc::io::csv::read_cells (cell_reader_output & out, std::string_view filename, const geometry * geom = nullptr, const digitization_config * dconfig = nullptr)
Read cell information from a specific CSV file
Parameters
out A cell (host) collection & a cell_module collection
filename The file to read the cell data from
geom The description of the detector geometry
dconfig The detector's digitization configuration
                                                                          {
    // Construct the cell reader object.
    auto reader = make_cell_reader(filename);
    // Create cell counter vector.
    std::vector<unsigned int> cellCounts;
    cellCounts.reserve(5000);
    cell_module_collection_types::host& result_modules = out.modules;
    result_modules.reserve(5000);
    // Create a cell collection, which holds on to a flat list of all the cells
    // and the position of their respective cell counter & module.
    std::vector<std::pair<csv::cell, unsigned int>> allCells;
    allCells.reserve(50000);
    // Read all cells from input file.
    csv::cell iocell;
    while (reader.read(iocell)) {
        // Look for current module in cell counter vector.
        auto rit = std::find_if(result_modules.rbegin(), result_modules.rend(),
                                [&iocell](const cell_module& mod) {
                                    return mod.surface_link.value() ==
                                           iocell.geometry_id;
                                });
        if (rit == result_modules.rend()) {
            // Add new cell and new cell counter if a new module is found
            const cell_module mod = get_module(iocell, geom, dconfig);
            allCells.push_back({iocell, result_modules.size()});
            result_modules.push_back(mod);
            cellCounts.push_back(1);
        } else {
            // Add a new cell and update cell counter if repeat module is found
            const unsigned int pos =
                std::distance(result_modules.begin(), rit.base()) - 1;
            allCells.push_back({iocell, pos});
            ++(cellCounts[pos]);
        }
    }
    // Transform the cellCounts vector into a prefix sum for accessing
    // positions in the result vector.
    std::partial_sum(cellCounts.begin(), cellCounts.end(), cellCounts.begin());
    // The total number cells.
    const unsigned int totalCells = allCells.size();
    // Construct the result collection.
    cell_collection_types::host& result_cells = out.cells;
    result_cells.resize(totalCells);
    // Member "-1" of the prefix sum vector
    unsigned int nCellsZero = 0;
    // Fill the result object with the read csv cells
    for (unsigned int i = 0; i < totalCells; ++i) {
        const csv::cell& c = allCells[i].first;
        // The position of the cell counter this cell belongs to
        const unsigned int& counterPos = allCells[i].second;
        unsigned int& prefix_sum_previous =
            counterPos == 0 ? nCellsZero : cellCounts[counterPos - 1];
        result_cells[prefix_sum_previous++] = traccc::cell{
            c.channel0, c.channel1, c.value, c.timestamp, counterPos};
    }
    if (cellCounts.size() == 0) {
        return;
    }
    /* This is might look a bit overcomplicated, and could be made simpler by
     * having a copy of the prefix sum vector before incrementing its value when
     * filling the vector. however this seems more efficient, but requires
     * manually setting the 1st & 2nd modules instead of just the 1st.
     */
    // Sort the cells belonging to the first module.
    std::sort(result_cells.begin(), result_cells.begin() + nCellsZero, comp);
    // Sort the cells belonging to the second module.
    std::sort(result_cells.begin() + nCellsZero,
              result_cells.begin() + cellCounts[0], comp);
    // Sort cells belonging to all other modules.
    for (unsigned int i = 1; i < cellCounts.size() - 1; ++i) {
        std::sort(result_cells.begin() + cellCounts[i - 1],
                  result_cells.begin() + cellCounts[i], comp);
    }
}
References traccc::io::cell_reader_output::cells, traccc::io::csv::cell::channel0, traccc::io::csv::cell::channel1, make_cell_reader(), traccc::io::cell_reader_output::modules, traccc::io::csv::cell::timestamp, and traccc::io::csv::cell::value.
Referenced by traccc::io::read_cells().
read_measurements()
void traccc::io::csv::read_measurements (measurement_reader_output & out, std::string_view filename, const bool do_sort = true)
Read measurement information from a specific CSV file
Parameters
out A measurement & a cell_module (host) collections
filename The file to read the measurement data from
do_sort Whether to sort the measurements or not
                                                                    {
    // Construct the measurement reader object.
    auto reader = make_measurement_reader(filename);
    // Create the result collection.
    measurement_collection_types::host& result_measurements = out.measurements;
    cell_module_collection_types::host& result_modules = out.modules;
    std::map<geometry_id, unsigned int> m;
    // Read the measurements from the input file.
    csv::measurement iomeas;
    while (reader.read(iomeas)) {
        unsigned int link;
        auto it = m.find(iomeas.geometry_id);
        if (it != m.end()) {
            link = (*it).second;
        } else {
            link = result_modules.size();
            m[iomeas.geometry_id] = link;
            cell_module mod;
            mod.surface_link = detray::geometry::barcode{iomeas.geometry_id};
            result_modules.push_back(mod);
        }
        // Construct the measurement object.
        traccc::measurement meas;
        std::array<typename transform3::size_type, 2u> indices{0u, 0u};
        meas.meas_dim = 0u;
        // Local key is a 8 bit char and first and last bit are dummy value. 2 -
        // 7th bits are for 6 bound track parameters.
        // Ex1) 0000010 or 2 -> meas dim = 1 and [loc0] active -> strip or wire
        // Ex2) 0000110 or 6 -> meas dim = 2 and [loc0, loc1] active -> pixel
        // Ex3) 0000100 or 4 -> meas dim = 1 and [loc1] active -> annulus
        for (unsigned int ipar = 0; ipar < 2u; ++ipar) {
            if (((iomeas.local_key) & (1 << (ipar + 1))) != 0) {
                switch (ipar) {
                    case e_bound_loc0: {
                        meas.local[0] = iomeas.local0;
                        meas.variance[0] = iomeas.var_local0;
                        indices[meas.meas_dim++] = ipar;
                    }; break;
                    case e_bound_loc1: {
                        meas.local[1] = iomeas.local1;
                        meas.variance[1] = iomeas.var_local1;
                        indices[meas.meas_dim++] = ipar;
                    }; break;
                }
            }
        }
        meas.subs.set_indices(indices);
        meas.surface_link = detray::geometry::barcode{iomeas.geometry_id};
        meas.module_link = link;
        result_measurements.push_back(meas);
    }
    if (do_sort) {
        std::sort(result_measurements.begin(), result_measurements.end(),
                  measurement_sort_comp());
    }
}
References traccc::e_bound_loc0, traccc::e_bound_loc1, traccc::io::csv::measurement::geometry_id, traccc::measurement::local, traccc::io::csv::measurement::local0, traccc::io::csv::measurement::local1, traccc::io::csv::measurement::local_key, make_measurement_reader(), traccc::measurement::meas_dim, traccc::io::measurement_reader_output::measurements, traccc::measurement::module_link, traccc::io::measurement_reader_output::modules, traccc::subspace< algebra_t, kFullSize, kSize >::set_indices(), traccc::measurement::subs, traccc::cell_module::surface_link, traccc::measurement::surface_link, traccc::io::csv::measurement::var_local0, traccc::io::csv::measurement::var_local1, and traccc::measurement::variance.
Referenced by traccc::io::read_measurements(), and read_spacepoints().
read_measurements_container()
measurement_container_types::host traccc::io::csv::read_measurements_container (std::string_view filename, vecmem::memory_resource * mr)
                                                        {
    // Construct the measurement reader object.
    auto reader = make_measurement_reader(filename);
    // Create the result container.
    measurement_container_types::host result;
    if (mr != nullptr) {
        result = measurement_container_types::host{mr};
    }
    // Read the measurements from the input file.
    csv::measurement iomeas;
    while (reader.read(iomeas)) {
        // Construct the module ID for the measurement.
        cell_module module;
        module.surface_link = detray::geometry::barcode{iomeas.geometry_id};
        // Construct the measurement object.
        const traccc::measurement meas{
            point2{iomeas.local0, iomeas.local1},
            variance2{iomeas.var_local0, iomeas.var_local1},
            detray::geometry::barcode{iomeas.geometry_id}};
        // Find the detector module that this measurement belongs to.
        const measurement_container_types::host::header_vector& headers =
            result.get_headers();
        auto rit = std::find(headers.rbegin(), headers.rend(), module);
        // Add the measurement to the correct place in the container.
        if (rit == headers.rend()) {
            if (mr != nullptr) {
                result.push_back(
                    module,
                    measurement_container_types::host::item_vector::value_type(
                        {meas}, mr));
            } else {
                result.push_back(
                    module,
                    measurement_container_types::host::item_vector::value_type(
                        {meas}));
            }
        } else {
            // The reverse iterator.base() returns the equivalent normal
            // iterator shifted by 1, so that the (r)end and (r)begin iterators
            // match consistently, due to the extra past-the-last element
            auto idx = std::distance(headers.begin(), rit.base()) - 1;
            result.at(idx).items.push_back(meas);
        }
    }
    // Return the container.
    return result;
}
References traccc::io::csv::measurement::geometry_id, traccc::io::csv::measurement::local0, traccc::io::csv::measurement::local1, make_measurement_reader(), traccc::cell_module::surface_link, traccc::io::csv::measurement::var_local0, and traccc::io::csv::measurement::var_local1.
read_particles()
particle_collection_types::host traccc::io::csv::read_particles (std::string_view filename, vecmem::memory_resource * mr = nullptr)
Read particle information from a specific CSV file
Parameters
filename The file to read the particle data from
mr The memory resource to create the host collection with
Returns
A particle (host) collection
                                                                          {
    // Construct the particle reader object.
    auto reader = make_particle_reader(filename);
    // Create the result collection.
    particle_collection_types::host result;
    if (mr != nullptr) {
        result = particle_collection_types::host{mr};
    }
    // Read the particles from the input file.
    csv::particle part;
    while (reader.read(part)) {
        result.push_back({part.particle_id, part.particle_type, part.process,
                          point3{part.vx, part.vy, part.vz}, part.vt,
                          vector3{part.px, part.py, part.pz}, part.m, part.q});
    }
    // Return the collection.
    return result;
}
References traccc::io::csv::particle::m, make_particle_reader(), traccc::io::csv::particle::particle_id, traccc::io::csv::particle::particle_type, traccc::io::csv::particle::process, traccc::io::csv::particle::px, traccc::io::csv::particle::py, traccc::io::csv::particle::pz, traccc::io::csv::particle::q, traccc::io::csv::particle::vt, traccc::io::csv::particle::vx, traccc::io::csv::particle::vy, and traccc::io::csv::particle::vz.
Referenced by traccc::io::read_particles().
read_spacepoints()
void traccc::io::csv::read_spacepoints (spacepoint_reader_output & out, std::string_view filename, std::string_view meas_filename, std::string_view meas_hit_map_filename, const geometry & geom)
Read spacepoint information from a specific CSV file
Parameters
out A spacepoint & a cell_module (host) collections
filename The file to read the spacepoint data from
geom The description of the detector geometry
                                            {
    // Read measurements
    measurement_reader_output meas_reader_out;
    read_measurements(meas_reader_out, meas_filename, false);
    // Measurement hit id reader
    auto mhid_reader =
        io::csv::make_measurement_hit_id_reader(meas_hit_map_filename);
    std::vector<traccc::io::csv::measurement_hit_id> measurement_hit_ids;
    traccc::io::csv::measurement_hit_id io_mh_id;
    while (mhid_reader.read(io_mh_id)) {
        measurement_hit_ids.push_back(io_mh_id);
    }
    // Construct the spacepoint reader object.
    auto reader = make_hit_reader(filename);
    // Create the result collection.
    spacepoint_collection_types::host& result_spacepoints = out.spacepoints;
    cell_module_collection_types::host& result_modules = out.modules;
    std::map<geometry_id, unsigned int> m;
    // Read the spacepoints from the input file.
    hit iohit;
    while (reader.read(iohit)) {
        unsigned int link;
        auto it = m.find(iohit.geometry_id);
        if (it != m.end()) {
            link = (*it).second;
        } else {
            link = result_modules.size();
            m[iohit.geometry_id] = link;
            cell_module mod;
            mod.surface_link = detray::geometry::barcode{iohit.geometry_id};
            mod.placement = geom[iohit.geometry_id];
            result_modules.push_back(mod);
        }
        // Construct the global 3D position of the spacepoint.
        const point3 pos{iohit.tx, iohit.ty, iohit.tz};
        // Construct the local 3D(2D) position of the measurement.
        measurement meas;
        for (auto const [meas_id, hit_id] : measurement_hit_ids) {
            if (hit_id == result_spacepoints.size()) {
                meas = meas_reader_out.measurements[meas_id];
            }
        }
        // Create the spacepoint object (with its member measurement) from all
        // this information.
        const traccc::spacepoint sp{pos, meas};
        result_spacepoints.push_back(sp);
    }
}
References traccc::io::csv::hit::geometry_id, make_hit_reader(), make_measurement_hit_id_reader(), traccc::io::measurement_reader_output::measurements, traccc::io::spacepoint_reader_output::modules, traccc::cell_module::placement, read_measurements(), traccc::io::spacepoint_reader_output::spacepoints, traccc::cell_module::surface_link, traccc::io::csv::hit::tx, traccc::io::csv::hit::ty, and traccc::io::csv::hit::tz.
Referenced by traccc::io::read_spacepoints().
read_surfaces()
std::map< geometry_id, transform3 > traccc::io::csv::read_surfaces (std::string_view filename)
Read the geometry information per module and fill into a map.
                                                                       {
    // Construct the surface reader object.
    auto reader = make_surface_reader(filename);
    // Fill an std::map with entries from the file.
    std::map<geometry_id, transform3> result;
    surface surf;
    while (reader.read(surf)) {
        result.insert(
            {surf.geometry_id,
             transform3{vector3{surf.cx, surf.cy, surf.cz},
                        vector3{surf.rot_xw, surf.rot_yw, surf.rot_zw},
                        vector3{surf.rot_xu, surf.rot_yu, surf.rot_zu}}});
    }
    return result;
}
References traccc::io::csv::surface::cx, traccc::io::csv::surface::cy, traccc::io::csv::surface::cz, traccc::io::csv::surface::geometry_id, make_surface_reader(), traccc::io::csv::surface::rot_xu, traccc::io::csv::surface::rot_xw, traccc::io::csv::surface::rot_yu, traccc::io::csv::surface::rot_yw, traccc::io::csv::surface::rot_zu, and traccc::io::csv::surface::rot_zw.
Referenced by traccc::io::details::read_surfaces().