traccc::gain_matrix_smoother< algebra_t > Struct Template Reference
#include <gain_matrix_smoother.hpp>
Public Types
using matrix_operator = typename algebra_t::matrix_actor
using size_type = typename matrix_operator::size_ty
template<size_type ROWS, size_type COLS>
using matrix_type = typename matrix_operator::template matrix_type< ROWS, COLS >
using scalar_type = typename algebra_t::scalar_type
Public Member Functions
template<typename mask_group_t , typename index_t >
TRACCC_HOST_DEVICE void operator() (const mask_group_t &, const index_t &, track_state< algebra_t > &cur_state, const track_state< algebra_t > &next_state)
Based on `Application of Kalman filtering to track and vertex
fitting`, R.Frühwirth, NIM A.
template<size_type D, typename shape_t >
TRACCC_HOST_DEVICE void smoothe (track_state< algebra_t > &cur_state, const track_state< algebra_t > &next_state) const
Detailed Description
template<typename algebra_t>
struct traccc::gain_matrix_smoother< algebra_t >
Type unrolling functor to smooth the track parameters after the Kalman filtering
Member Typedef Documentation
matrix_operator
template<typename algebra_t >
using traccc::gain_matrix_smoother< algebra_t >::matrix_operator = typename algebra_t::matrix_actor
matrix_type
template<typename algebra_t >
template<size_type ROWS, size_type COLS>
using traccc::gain_matrix_smoother< algebra_t >::matrix_type = typename matrix_operator::template matrix_type<ROWS, COLS>
scalar_type
template<typename algebra_t >
using traccc::gain_matrix_smoother< algebra_t >::scalar_type = typename algebra_t::scalar_type
size_type
template<typename algebra_t >
using traccc::gain_matrix_smoother< algebra_t >::size_type = typename matrix_operator::size_ty
Member Function Documentation
operator()()
template<typename algebra_t >
template<typename mask_group_t , typename index_t >
TRACCC_HOST_DEVICE void traccc::gain_matrix_smoother< algebra_t >::operator() (const mask_group_t & , const index_t & , track_state< algebra_t > & cur_state, const track_state< algebra_t > & next_state) [inline]
Based on `Application of Kalman filtering to track and vertex
fitting`, R.Frühwirth, NIM A.
Gain matrix smoother operation
Parameters
mask_group mask group that contains the mask of the current surface
index mask index of the current surface
cur_state track state of the current surface
next_state track state of the next surface
Returns
true if the update succeeds
                                                  {
        using shape_type = typename mask_group_t::value_type::shape;
        const auto D = cur_state.get_measurement().meas_dim;
        assert(D == 1u || D == 2u);
        if (D == 1u) {
            smoothe<1u, shape_type>(cur_state, next_state);
        } else if (D == 2u) {
            smoothe<2u, shape_type>(cur_state, next_state);
        }
    }
References traccc::track_state< algebra_t >::get_measurement().
smoothe()
template<typename algebra_t >
template<size_type D, typename shape_t >
TRACCC_HOST_DEVICE void traccc::gain_matrix_smoother< algebra_t >::smoothe (track_state< algebra_t > & cur_state, const track_state< algebra_t > & next_state) const [inline]
                                                        {
        const auto meas = cur_state.get_measurement();
        static_assert(((D == 1u) || (D == 2u)),
                      "The measurement dimension should be 1 or 2");
        const auto& next_smoothed = next_state.smoothed();
        const auto& next_predicted = next_state.predicted();
        const auto& cur_filtered = cur_state.filtered();
        // Next track state parameters
        const matrix_type<e_bound_size, e_bound_size>& next_jacobian =
            next_state.jacobian();
        const matrix_type<e_bound_size, 1>& next_smoothed_vec =
            next_smoothed.vector();
        const matrix_type<e_bound_size, e_bound_size>& next_smoothed_cov =
            next_smoothed.covariance();
        const matrix_type<e_bound_size, 1>& next_predicted_vec =
            next_predicted.vector();
        const matrix_type<e_bound_size, e_bound_size>& next_predicted_cov =
            next_predicted.covariance();
        // Current track state parameters
        const matrix_type<e_bound_size, 1>& cur_filtered_vec =
            cur_filtered.vector();
        const matrix_type<e_bound_size, e_bound_size>& cur_filtered_cov =
            cur_filtered.covariance();
        // Regularization matrix for numerical stability
        static constexpr scalar_type epsilon = 1e-13f;
        const matrix_type<e_bound_size, e_bound_size> regularization =
            matrix_operator().template identity<e_bound_size, e_bound_size>() *
            epsilon;
        const matrix_type<e_bound_size, e_bound_size>
            regularized_predicted_cov = next_predicted_cov + regularization;
        // Calculate smoothed parameter for current state
        const matrix_type<e_bound_size, e_bound_size> A =
            cur_filtered_cov * matrix_operator().transpose(next_jacobian) *
            matrix_operator().inverse(regularized_predicted_cov);
        const matrix_type<e_bound_size, 1> smt_vec =
            cur_filtered_vec + A * (next_smoothed_vec - next_predicted_vec);
        const matrix_type<e_bound_size, e_bound_size> smt_cov =
            cur_filtered_cov + A * (next_smoothed_cov - next_predicted_cov) *
                                   matrix_operator().transpose(A);
        cur_state.smoothed().set_vector(smt_vec);
        cur_state.smoothed().set_covariance(smt_cov);
        matrix_type<D, e_bound_size> H = meas.subs.template projector<D>();
        // Correct sign for line detector
        if constexpr (std::is_same_v<shape_t, detray::line<true>> ||
                      std::is_same_v<shape_t, detray::line<false>>) {
            if (getter::element(smt_vec, e_bound_loc0, 0u) < 0) {
                getter::element(H, 0u, e_bound_loc0) = -1;
            }
        }
        // Calculate smoothed chi square
        const matrix_type<D, 1>& meas_local =
            cur_state.template measurement_local<D>();
        const matrix_type<D, D>& V =
            cur_state.template measurement_covariance<D>();
        const matrix_type<D, 1> residual = meas_local - H * smt_vec;
        const matrix_type<D, D> R =
            V - H * smt_cov * matrix_operator().transpose(H);
        const matrix_type<1, 1> chi2 = matrix_operator().transpose(residual) *
                                       matrix_operator().inverse(R) * residual;
        cur_state.smoothed_chi2() = matrix_operator().element(chi2, 0, 0);
        return;
    }
References traccc::e_bound_loc0, traccc::track_state< algebra_t >::filtered(), traccc::track_state< algebra_t >::get_measurement(), traccc::track_state< algebra_t >::jacobian(), traccc::track_state< algebra_t >::predicted(), traccc::track_state< algebra_t >::smoothed(), and traccc::track_state< algebra_t >::smoothed_chi2().
The documentation for this struct was generated from the following file:
core/include/traccc/fitting/kalman_filter/gain_matrix_smoother.hpp