traccc::seed_selecting_helper Struct Reference
#include <seed_selecting_helper.hpp>
Static Public Member Functions
static TRACCC_HOST_DEVICE void seed_weight (const seedfilter_config &filter_config, const internal_spacepoint< spacepoint > &, const internal_spacepoint< spacepoint > &spB, const internal_spacepoint< spacepoint > &spT, scalar &triplet_weight)
static TRACCC_HOST_DEVICE bool single_seed_cut (const seedfilter_config &filter_config, const internal_spacepoint< spacepoint > &, const internal_spacepoint< spacepoint > &spB, const internal_spacepoint< spacepoint > &, const scalar &triplet_weight)
template<typename spacepoint_collection_t >
static TRACCC_HOST_DEVICE bool cut_per_middle_sp (const seedfilter_config &filter_config, const spacepoint_collection_t &sp_collection, const seed &seed, const scalar &triplet_weight)
Member Function Documentation
cut_per_middle_sp()
template<typename spacepoint_collection_t >
static TRACCC_HOST_DEVICE bool traccc::seed_selecting_helper::cut_per_middle_sp (const seedfilter_config & filter_config, const spacepoint_collection_t & sp_collection, const seed & seed, const scalar & triplet_weight) [inline], [static]
Cut triplets with criteria
Parameters
filter_config seed filtering configuration parameters
sp_collection spacepoint collection
seed current seed to possibly cut
triplet_weight triplets' weight
Returns
boolean value
                                      {
        const auto& spB = sp_collection.at(seed.spB_link);
        return (triplet_weight > filter_config.seed_min_weight ||
                spB.radius() > filter_config.spB_min_radius);
    }
References traccc::seedfilter_config::seed_min_weight, traccc::seed::spB_link, and traccc::seedfilter_config::spB_min_radius.
Referenced by traccc::device::select_seeds().
seed_weight()
static TRACCC_HOST_DEVICE void traccc::seed_selecting_helper::seed_weight (const seedfilter_config & filter_config, const internal_spacepoint< spacepoint > & , const internal_spacepoint< spacepoint > & spB, const internal_spacepoint< spacepoint > & spT, scalar & triplet_weight) [inline], [static]
Update the weights of triplets
Parameters
filter_config is seed filtering configuration parameters
spM is middle (internal) spacepoint
spB is bottom (internal) spacepoint
spT is top (internal) spacepoint
triplet_weight is the weight of triplet to be updated
                                                                            {
        scalar weight = 0;
        if (spB.radius() > filter_config.good_spB_min_radius) {
            weight = filter_config.good_spB_weight_increase;
        }
        if (spT.radius() < filter_config.good_spT_max_radius) {
            weight = filter_config.good_spT_weight_increase;
        }
        triplet_weight += weight;
        return;
    }
References traccc::seedfilter_config::good_spB_min_radius, traccc::seedfilter_config::good_spB_weight_increase, traccc::seedfilter_config::good_spT_max_radius, traccc::seedfilter_config::good_spT_weight_increase, and traccc::internal_spacepoint< spacepoint_t >::radius().
Referenced by traccc::seed_filtering::operator()(), and traccc::device::select_seeds().
single_seed_cut()
static TRACCC_HOST_DEVICE bool traccc::seed_selecting_helper::single_seed_cut (const seedfilter_config & filter_config, const internal_spacepoint< spacepoint > & , const internal_spacepoint< spacepoint > & spB, const internal_spacepoint< spacepoint > & , const scalar & triplet_weight) [inline], [static]
Cut triplets with criteria
Parameters
filter_config is seed filtering configuration parameters
spM is middle (internal) spacepoint
spB is bottom (internal) spacepoint
spT is top (internal) spacepoint
triplet_weight is the weight of triplet
Returns
boolean value
                                                                              {
        return !(spB.radius() > filter_config.good_spB_min_radius &&
                 triplet_weight < filter_config.good_spB_min_weight);
    }
References traccc::seedfilter_config::good_spB_min_radius, traccc::seedfilter_config::good_spB_min_weight, and traccc::internal_spacepoint< spacepoint_t >::radius().
Referenced by traccc::seed_filtering::operator()(), and traccc::device::select_seeds().
The documentation for this struct was generated from the following file:
core/include/traccc/seeding/seed_selecting_helper.hpp