traccc::device Namespace Reference
Namespaces
 details
 experimental
Classes
class container_d2h_copy_alg
class container_h2d_copy_alg
struct device_doublet
Doublet of middle-bottom or middle-top spacepoints.
struct device_triplet
Triplets of bottom, middle and top spacepoints.
struct doublet_counter
Number of doublets for one specific middle spacepoint.
struct finding_global_counter
struct prefix_sum_buffer
struct seeding_global_counter
Total number of doublets and triplets found in seeding.
struct triplet_counter
Number of triplets for one specific Mid-Bottom Doublet.
struct triplet_counter_spM
Number of triplets for one specific middle spacepoint.
Typedefs
typedef thrust::pair< std::size_t, std::size_t > prefix_sum_element_t
Type for the individual elements in the prefix sum vector.
typedef vecmem::vector< prefix_sum_element_t > prefix_sum_t
Convenience type definition for the return value of the helper function.
using prefix_sum_size_t = vecmem::data::vector_view< int >::size_type
using prefix_sum_buffer_t = prefix_sum_buffer
using device_doublet_collection_types = collection_types< device_doublet >
Declare all device doublet collection types.
using device_triplet_collection_types = collection_types< device_triplet >
Declare all device triplet collection types.
using doublet_counter_collection_types = collection_types< doublet_counter >
Declare all doublet counter collection types.
using triplet_counter_spM_collection_types = collection_types< triplet_counter_spM >
Declare all triplet counter spM collection types.
using triplet_counter_collection_types = collection_types< triplet_counter >
Declare all triplet counter collection types.
Functions
TRACCC_HOST_DEVICE void aggregate_cluster (const cell_collection_types::const_device &cells, const cell_module_collection_types::const_device &modules, const vecmem::data::vector_view< unsigned short > f_view, const unsigned int start, const unsigned int end, const unsigned short cid, measurement &out, vecmem::data::vector_view< unsigned int > cell_links, const unsigned int link)
template<typename barrier_t >
TRACCC_DEVICE void ccl_kernel (const index_t threadId, const index_t blckDim, const unsigned int blockId, const cell_collection_types::const_view cells_view, const cell_module_collection_types::const_view modules_view, const index_t max_cells_per_partition, const index_t target_cells_per_partition, unsigned int &partition_start, unsigned int &partition_end, unsigned int &outi, index_t *f, index_t *gf, barrier_t &barrier, measurement_collection_types::view measurements_view, unsigned int &measurement_count, vecmem::data::vector_view< unsigned int > cell_links)
TRACCC_HOST_DEVICE void form_spacepoints (const std::size_t globalIndex, measurement_collection_types::const_view measurements_view, cell_module_collection_types::const_view modules_view, const unsigned int measurement_count, spacepoint_collection_types::view spacepoints_view)
template<typename barrier_t >
TRACCC_DEVICE void fast_sv_1 (index_t *f, index_t *gf, unsigned char adjc[MAX_CELLS_PER_THREAD], index_t adjv[MAX_CELLS_PER_THREAD][8], const index_t tid, const index_t blckDim, barrier_t &barrier)
TRACCC_HOST_DEVICE bool is_adjacent (channel_id ac0, channel_id ac1, channel_id bc0, channel_id bc1)
TRACCC_HOST_DEVICE void reduce_problem_cell (const cell_collection_types::const_device &cells, const unsigned short cid, const unsigned int start, const unsigned int end, unsigned char &adjc, unsigned short adjv[8])
TRACCC_HOST_DEVICE void fill_prefix_sum (const std::size_t globalIndex, const vecmem::data::vector_view< const prefix_sum_size_t > &sizes_view, vecmem::data::vector_view< prefix_sum_element_t > ps_view)
TRACCC_HOST prefix_sum_buffer_t make_prefix_sum_buffer (const std::vector< prefix_sum_size_t > &sizes, vecmem::copy &copy, const traccc::memory_resource &mr)
template<typename detector_t >
TRACCC_DEVICE void apply_interaction (std::size_t globalIndex, typename detector_t::view_type det_data, vecmem::data::jagged_vector_view< detray::intersection2D< typename detector_t::surface_type, typename detector_t::transform3 >> nav_candidates_buffer, const int n_params, bound_track_parameters_collection_types::view params_view)
TRACCC_DEVICE void build_tracks (std::size_t globalIndex, measurement_collection_types::const_view measurements_view, bound_track_parameters_collection_types::const_view seeds_view, vecmem::data::jagged_vector_view< const candidate_link > links_view, vecmem::data::jagged_vector_view< const unsigned int > param_to_link_view, vecmem::data::vector_view< const typename candidate_link::link_index_type > tips_view, track_candidate_container_types::view track_candidates_view)
TRACCC_DEVICE void count_measurements (std::size_t globalIndex, bound_track_parameters_collection_types::const_view params_view, vecmem::data::vector_view< const detray::geometry::barcode > barcodes_view, vecmem::data::vector_view< const unsigned int > upper_bounds_view, const unsigned int n_in_params, vecmem::data::vector_view< unsigned int > n_measurements_view, vecmem::data::vector_view< unsigned int > ref_meas_idx_view, unsigned int &n_measurements_sum)
template<typename detector_t , typename config_t >
TRACCC_DEVICE void find_tracks (std::size_t globalIndex, const config_t cfg, typename detector_t::view_type det_data, measurement_collection_types::const_view measurements_view, bound_track_parameters_collection_types::const_view in_params_view, vecmem::data::vector_view< const unsigned int > n_measurements_prefix_sum_view, vecmem::data::vector_view< const unsigned int > ref_meas_idx_view, const unsigned int step, const unsigned int &n_max_candidates, bound_track_parameters_collection_types::view out_params_view, vecmem::data::vector_view< candidate_link > links_view, unsigned int &n_candidates)
TRACCC_DEVICE void make_barcode_sequence (std::size_t globalIndex, measurement_collection_types::const_view uniques_view, vecmem::data::vector_view< detray::geometry::barcode > barcodes_view)
template<typename propagator_t , typename bfield_t , typename config_t >
TRACCC_DEVICE void propagate_to_next_surface (std::size_t globalIndex, const config_t cfg, typename propagator_t::detector_type::view_type det_data, bfield_t field_data, vecmem::data::jagged_vector_view< typename propagator_t::intersection_type > nav_candidates_buffer, bound_track_parameters_collection_types::const_view in_params_view, vecmem::data::vector_view< const candidate_link > links_view, const unsigned int step, const unsigned int &n_in_params, bound_track_parameters_collection_types::view out_params_view, vecmem::data::vector_view< unsigned int > param_to_link_view, vecmem::data::vector_view< typename candidate_link::link_index_type > tips_view, unsigned int &n_out_params)
template<typename fitter_t , typename detector_view_t >
TRACCC_HOST_DEVICE void fit (std::size_t globalIndex, detector_view_t det_data, const typename fitter_t::bfield_type field_data, const typename fitter_t::config_type cfg, vecmem::data::jagged_vector_view< typename fitter_t::intersection_type > nav_candidates_buffer, track_candidate_container_types::const_view track_candidates_view, track_state_container_types::view track_states_view)
TRACCC_HOST_DEVICE void count_doublets (std::size_t globalIndex, const seedfinder_config &config, const sp_grid_const_view &sp_view, const vecmem::data::vector_view< const prefix_sum_element_t > &sp_ps_view, doublet_counter_collection_types::view doublet_view, unsigned int &nMidBot, unsigned int &nMidTop)
TRACCC_HOST_DEVICE void count_grid_capacities (const std::size_t globalIndex, const seedfinder_config &config, const sp_grid::axis_p0_type &phi_axis, const sp_grid::axis_p1_type &z_axis, const spacepoint_collection_types::const_view &spacepoints, vecmem::data::vector_view< unsigned int > grid_capacities)
TRACCC_HOST_DEVICE void count_triplets (std::size_t globalIndex, const seedfinder_config &config, const sp_grid_const_view &sp_view, const doublet_counter_collection_types::const_view &dc_view, const device_doublet_collection_types::const_view &mid_bot_doublet_view, const device_doublet_collection_types::const_view &mid_top_doublet_view, triplet_counter_spM_collection_types::view spM_tc, triplet_counter_collection_types::view mb_tc)
TRACCC_HOST_DEVICE void estimate_track_params (const std::size_t globalIndex, const spacepoint_collection_types::const_view &spacepoints_view, const seed_collection_types::const_view &seeds_view, const vector3 &bfield, const std::array< traccc::scalar, traccc::e_bound_size > &stddev, bound_track_parameters_collection_types::view params_view)
TRACCC_HOST_DEVICE void find_doublets (std::size_t globalIndex, const seedfinder_config &config, const sp_grid_const_view &sp_view, const doublet_counter_collection_types::const_view &dc_view, device_doublet_collection_types::view mb_doublets_view, device_doublet_collection_types::view mt_doublets_view)
TRACCC_HOST_DEVICE void find_triplets (std::size_t globalIndex, const seedfinder_config &config, const seedfilter_config &filter_config, const sp_grid_const_view &sp_view, const doublet_counter_collection_types::const_view &dc_view, const device_doublet_collection_types::const_view &mid_top_doublet_view, const triplet_counter_spM_collection_types::const_view &spM_tc_view, const triplet_counter_collection_types::const_view &tc_view, device_triplet_collection_types::view triplet_view)
TRACCC_DEVICE void populate_grid (unsigned int globalIndex, const seedfinder_config &config, const spacepoint_collection_types::const_view &spacepoints_view, sp_grid_view grid_view)
TRACCC_HOST_DEVICE void reduce_triplet_counts (const std::size_t globalIndex, const doublet_counter_collection_types::const_view &dc_view, triplet_counter_spM_collection_types::view spM_tc_view, unsigned int &num_triplets)
TRACCC_HOST_DEVICE void select_seeds (const std::size_t globalIndex, const seedfilter_config &filter_config, const spacepoint_collection_types::const_view &spacepoints_view, const sp_grid_const_view &internal_sp_view, const triplet_counter_spM_collection_types::const_view &spM_tc_view, const triplet_counter_collection_types::const_view &tc_view, const device_triplet_collection_types::const_view &triplet_view, triplet *data, seed_collection_types::view seed_view)
TRACCC_HOST_DEVICE void update_triplet_weights (const std::size_t globalIndex, const seedfilter_config &filter_config, const sp_grid_const_view &sp_view, const triplet_counter_spM_collection_types::const_view &spM_tc_view, const triplet_counter_collection_types::const_view &tc_view, scalar *data, device_triplet_collection_types::view triplet_view)
Detailed Description
TRACCC library, part of the ACTS project (R&D line)
(c) 2022 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
TRACCC library, part of the ACTS project (R&D line)
(c) 2022-2023 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
TRACCC library, part of the ACTS project (R&D line)
(c) 2023 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
TRACCC library, part of the ACTS project (R&D line)
(c) 2021-2023 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
TRACCC library, part of the ACTS project (R&D line)
(c) 2021-2022 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
Typedef Documentation
device_doublet_collection_types
using traccc::device::device_doublet_collection_types = typedef collection_types<device_doublet>
Declare all device doublet collection types.
device_triplet_collection_types
using traccc::device::device_triplet_collection_types = typedef collection_types<device_triplet>
Declare all device triplet collection types.
doublet_counter_collection_types
using traccc::device::doublet_counter_collection_types = typedef collection_types<doublet_counter>
Declare all doublet counter collection types.
prefix_sum_buffer_t
using traccc::device::prefix_sum_buffer_t = typedef prefix_sum_buffer
prefix_sum_element_t
typedef thrust::pair<std::size_t, std::size_t> traccc::device::prefix_sum_element_t
Type for the individual elements in the prefix sum vector.
prefix_sum_size_t
using traccc::device::prefix_sum_size_t = typedef vecmem::data::vector_view<int>::size_type
prefix_sum_t
typedef vecmem::vector<prefix_sum_element_t> traccc::device::prefix_sum_t
Convenience type definition for the return value of the helper function.
triplet_counter_collection_types
using traccc::device::triplet_counter_collection_types = typedef collection_types<triplet_counter>
Declare all triplet counter collection types.
triplet_counter_spM_collection_types
using traccc::device::triplet_counter_spM_collection_types = typedef collection_types<triplet_counter_spM>
Declare all triplet counter spM collection types.
Function Documentation
aggregate_cluster()
TRACCC_HOST_DEVICE void traccc::device::aggregate_cluster (const cell_collection_types::const_device & cells, const cell_module_collection_types::const_device & modules, const vecmem::data::vector_view< unsigned short > f_view, const unsigned int start, const unsigned int end, const unsigned short cid, measurement & out, vecmem::data::vector_view< unsigned int > cell_links, const unsigned int link) [inline]
Function which looks for cells which share the same `parent` index and aggregates them into a cluster.
Parameters
 in cells collection of cells
 in modules collection of modules to which the cells are linked to
 in f array of `parent` indices for all cells in this partition
 in start partition start point this cell belongs to
 in end partition end point this cell belongs to
 in cid current cell id
 out out cluster to fill
                             {
    const vecmem::device_vector<unsigned short> f(f_view);
    vecmem::device_vector<unsigned int> cell_links_device(cell_links);
    /*
     * Now, we iterate over all other cells to check if they belong
     * to our cluster. Note that we can start at the current index
     * because no cell is ever a child of a cluster owned by a cell
     * with a higher ID.
     */
    scalar totalWeight = 0.;
    point2 mean{0., 0.}, var{0., 0.};
    const auto module_link = cells[cid + start].module_link;
    const cell_module this_module = modules.at(module_link);
    const unsigned short partition_size = end - start;
    channel_id maxChannel1 = std::numeric_limits<channel_id>::min();
    for (unsigned short j = cid; j < partition_size; j++) {
        assert(j < f.size());
        const unsigned int pos = j + start;
        /*
         * Terminate the process earlier if we have reached a cell sufficiently
         * in a different module.
         */
        if (cells[pos].module_link != module_link) {
            break;
        }
        const cell this_cell = cells[pos];
        /*
         * If the value of this cell is equal to our, that means it
         * is part of our cluster. In that case, we take its values
         * for position and add them to our accumulators.
         */
        if (f[j] == cid) {
            if (this_cell.channel1 > maxChannel1) {
                maxChannel1 = this_cell.channel1;
            }
            const float weight = traccc::detail::signal_cell_modelling(
                this_cell.activation, this_module);
            if (weight > this_module.threshold) {
                totalWeight += this_cell.activation;
                const point2 cell_position =
                    traccc::detail::position_from_cell(this_cell, this_module);
                const point2 prev = mean;
                const point2 diff = cell_position - prev;
                mean = prev + (weight / totalWeight) * diff;
                for (char i = 0; i < 2; ++i) {
                    var[i] = var[i] +
                             weight * (diff[i]) * (cell_position[i] - mean[i]);
                }
            }
            cell_links_device.at(pos) = link;
        }
        /*
         * Terminate the process earlier if we have reached a cell sufficiently
         * far away from the cluster in the dominant axis.
         */
        if (this_cell.channel1 > maxChannel1 + 1) {
            break;
        }
    }
    if (totalWeight > static_cast<scalar>(0.)) {
        for (char i = 0; i < 2; ++i) {
            var[i] /= totalWeight;
        }
        const auto pitch = this_module.pixel.get_pitch();
        var = var + point2{pitch[0] * pitch[0] / static_cast<scalar>(12.),
                           pitch[1] * pitch[1] / static_cast<scalar>(12.)};
    }
    /*
     * Fill output vector with calculated cluster properties
     */
    out.local = mean;
    out.variance = var;
    out.surface_link = this_module.surface_link;
    out.module_link = module_link;
    // The following will need to be filled properly "soon".
    out.meas_dim = 2u;
}
References traccc::cell::activation, traccc::cell::channel1, traccc::pixel_data::get_pitch(), traccc::measurement::local, traccc::measurement::meas_dim, traccc::measurement::module_link, traccc::cell_module::pixel, traccc::detail::position_from_cell(), traccc::detail::signal_cell_modelling(), traccc::cell_module::surface_link, traccc::measurement::surface_link, traccc::cell_module::threshold, and traccc::measurement::variance.
Referenced by ccl_kernel().
apply_interaction()
template<typename detector_t >
TRACCC_DEVICE void traccc::device::apply_interaction (std::size_t globalIndex, typename detector_t::view_type det_data, vecmem::data::jagged_vector_view< detray::intersection2D< typename detector_t::surface_type, typename detector_t::transform3 >> nav_candidates_buffer, const int n_params, bound_track_parameters_collection_types::view params_view) [inline]
Function applying the Pre material interaction to tracks spawned by bound track parameters
Parameters
 in globalIndex The index of the current thread
 in det_data Detector view object
 in nav_candidates_buffer Buffer for navigation candidates
 in n_params The number of parameters (or tracks)
 out params_view Collection of output bound track_parameters
                                                             {
    // Type definitions
    using transform3_type = typename detector_t::transform3;
    using intersection_type =
        detray::intersection2D<typename detector_t::surface_type,
                               transform3_type>;
    using interactor_type =
        detray::pointwise_material_interactor<transform3_type>;
    // Detector
    detector_t det(det_data);
    // Navigation candidate buffer
    vecmem::jagged_device_vector<intersection_type> nav_candidates(
        nav_candidates_buffer);
    // in param
    bound_track_parameters_collection_types::device params(params_view);
    if (globalIndex >= n_params) {
        return;
    }
    auto& bound_param = params.at(globalIndex);
    // Get intersection at surface
    const detray::surface<detector_t> sf{det, bound_param.surface_link()};
    using cxt_t = typename detector_t::geometry_context;
    const cxt_t ctx{};
    const auto free_vec = sf.bound_to_free_vector(ctx, bound_param.vector());
    const auto& mask_store = det.mask_store();
    intersection_type sfi;
    sfi.sf_desc = det.surface(bound_param.surface_link());
    sf.template visit_mask<detray::intersection_update>(
        detray::detail::ray<transform3_type>(free_vec), sfi,
        det.transform_store());
    // Apply interactor
    typename interactor_type::state interactor_state;
    interactor_type{}.update(
        bound_param, interactor_state,
        static_cast<int>(detray::navigation::direction::e_forward), sf,
        sfi.cos_incidence_angle);
}
build_tracks()
TRACCC_DEVICE void traccc::device::build_tracks (std::size_t globalIndex, measurement_collection_types::const_view measurements_view, bound_track_parameters_collection_types::const_view seeds_view, vecmem::data::jagged_vector_view< const candidate_link > links_view, vecmem::data::jagged_vector_view< const unsigned int > param_to_link_view, vecmem::data::vector_view< const typename candidate_link::link_index_type > tips_view, track_candidate_container_types::view track_candidates_view) [inline]
Function for building full tracks from the link container: The full tracks are built using the link container and tip link container. Since every link holds an information of the link from the previous step, we can build a full track by iterating from a tip link backwardly.
Parameters
 in globalIndex The index of the current thread
 in measurements_view Measurements container view
 in seeds_view Seed container view
 in link_view Link container view
 in param_to_link_view Container for param index -> link index
 in tips_view Tip link container view
 out track_candidates_view Track candidate container view
                                                               {
    measurement_collection_types::const_device measurements(measurements_view);
    bound_track_parameters_collection_types::const_device seeds(seeds_view);
    vecmem::jagged_device_vector<const candidate_link> links(links_view);
    vecmem::jagged_device_vector<const unsigned int> param_to_link(
        param_to_link_view);
    vecmem::device_vector<const typename candidate_link::link_index_type> tips(
        tips_view);
    track_candidate_container_types::device track_candidates(
        track_candidates_view);
    if (globalIndex >= tips.size()) {
        return;
    }
    const auto tip = tips.at(globalIndex);
    auto& seed = track_candidates[globalIndex].header;
    auto cands_per_track = track_candidates[globalIndex].items;
    // Get the link corresponding to tip
    auto L = links[tip.first][tip.second];
    // Resize the candidates with the exact size
    cands_per_track.resize(tip.first + 1);
    // Reversely iterate to fill the track candidates
    for (auto it = cands_per_track.rbegin(); it != cands_per_track.rend();
         it++) {
        auto& cand = *it;
        cand = {measurements.at(L.meas_idx)};
        // Break the loop if the iterator is at the first candidate and fill the
        // seed
        if (it == cands_per_track.rend() - 1) {
            seed = seeds.at(L.previous.second);
            break;
        }
        const auto l_pos = param_to_link[L.previous.first][L.previous.second];
        L = links[L.previous.first][l_pos];
    }
}
References traccc::device_container< header_t, item_t >::at().
ccl_kernel()
template<typename barrier_t >
TRACCC_DEVICE void traccc::device::ccl_kernel (const index_t threadId, const index_t blckDim, const unsigned int blockId, const cell_collection_types::const_view cells_view, const cell_module_collection_types::const_view modules_view, const index_t max_cells_per_partition, const index_t target_cells_per_partition, unsigned int & partition_start, unsigned int & partition_end, unsigned int & outi, index_t * f, index_t * gf, barrier_t & barrier, measurement_collection_types::view measurements_view, unsigned int & measurement_count, vecmem::data::vector_view< unsigned int > cell_links) [inline]
Function which reads raw detector cells and turns them into measurements.
Parameters
 in threadId current thread index
 in blckDim current thread block size
 in blckId current thread block index
 in cells_view collection of cells
 in modules_view collection of modules to which the cells are linked
 in max_cells_per_partition maximum number of cells per thread block
 in target_cells_per_partition average number of cells per thread block
   partition_start partition start point for this thread block
   partition_end partition end point for this thread block
   outi number of measurements for this partition
   f array of `parent` indices for all cells in this partition
   gf array of `grandparent` indices for all cells in this partition
   barrier A generic object for block-wide synchronisation
 out measurements_view collection of measurements
 out measurement_count number of measurements
 out cell_links collection of links to measurements each cell is put into
                                                    {
    // Get device copy of input parameters
    const cell_collection_types::const_device cells_device(cells_view);
    const cell_module_collection_types::const_device modules_device(
        modules_view);
    measurement_collection_types::device measurements_device(measurements_view);
    const unsigned int num_cells = cells_device.size();
    /*
     * First, we determine the exact range of cells that is to be examined
     * by this block of threads. We start from an initial range determined
     * by the block index multiplied by the target number of cells per
     * block. We then shift both the start and the end of the block forward
     * (to a later point in the array); start and end may be moved different
     * amounts.
     */
    if (threadId == 0) {
        unsigned int start = blockId * target_cells_per_partition;
        assert(start < num_cells);
        unsigned int end =
            std::min(num_cells, start + target_cells_per_partition);
        outi = 0;
        /*
         * Next, shift the starting point to a position further in the
         * array; the purpose of this is to ensure that we are not operating
         * on any cells that have been claimed by the previous block (if
         * any).
         */
        while (start != 0 &&
               cells_device[start - 1].module_link ==
                   cells_device[start].module_link &&
               cells_device[start].channel1 <=
                   cells_device[start - 1].channel1 + 1) {
            ++start;
        }
        /*
         * Then, claim as many cells as we need past the naive end of the
         * current block to ensure that we do not end our partition on a
         * cell that is not a possible boundary!
         */
        while (end < num_cells &&
               cells_device[end - 1].module_link ==
                   cells_device[end].module_link &&
               cells_device[end].channel1 <=
                   cells_device[end - 1].channel1 + 1) {
            ++end;
        }
        partition_start = start;
        partition_end = end;
    }
    barrier.blockBarrier();
    // Vector of indices of the adjacent cells
    index_t adjv[MAX_CELLS_PER_THREAD][8];
    /*
     * The number of adjacent cells for each cell must start at zero, to
     * avoid uninitialized memory. adjv does not need to be zeroed, as
     * we will only access those values if adjc indicates that the value
     * is set.
     */
    // Number of adjacent cells
    unsigned char adjc[MAX_CELLS_PER_THREAD];
    // It seems that sycl runs into undefined behaviour when calling
    // group synchronisation functions when some threads have already run
    // into a return. As such, we cannot use returns in this kernel.
    // Get partition for this thread group
    const index_t size = partition_end - partition_start;
    assert(size <= max_cells_per_partition);
#pragma unroll
    for (index_t tst = 0; tst < MAX_CELLS_PER_THREAD; ++tst) {
        adjc[tst] = 0;
    }
    for (index_t tst = 0, cid; (cid = tst * blckDim + threadId) < size; ++tst) {
        /*
         * Look for adjacent cells to the current one.
         */
        device::reduce_problem_cell(cells_device, cid, partition_start,
                                    partition_end, adjc[tst], adjv[tst]);
    }
#pragma unroll
    for (index_t tst = 0; tst < MAX_CELLS_PER_THREAD; ++tst) {
        const index_t cid = tst * blckDim + threadId;
        /*
         * At the start, the values of f and gf should be equal to the
         * ID of the cell.
         */
        f[cid] = cid;
        gf[cid] = cid;
    }
    /*
     * Now that the data has initialized, we synchronize again before we
     * move onto the actual processing part.
     */
    barrier.blockBarrier();
    /*
     * Run FastSV algorithm, which will update the father index to that of
     * the cell belonging to the same cluster with the lowest index.
     */
    fast_sv_1(&f[0], &gf[0], adjc, adjv, threadId, blckDim, barrier);
    barrier.blockBarrier();
    /*
     * Count the number of clusters by checking how many cells have
     * themself assigned as a parent.
     */
    for (index_t tst = 0, cid; (cid = tst * blckDim + threadId) < size; ++tst) {
        if (f[cid] == cid) {
            // Increment the summary values in the header object.
            vecmem::device_atomic_ref<unsigned int,
                                      vecmem::device_address_space::local>
                atom(outi);
            atom.fetch_add(1);
        }
    }
    barrier.blockBarrier();
    /*
     * Add the number of clusters of each thread block to the total
     * number of clusters. At the same time, a cluster id is retrieved
     * for the next data processing step.
     * Note that this might be not the same cluster as has been treated
     * previously. However, since each thread block spawns a the maximum
     * amount of threads per block, this has no sever implications.
     */
    if (threadId == 0) {
        vecmem::device_atomic_ref<unsigned int,
                                  vecmem::device_address_space::global>
            atom(measurement_count);
        outi = atom.fetch_add(outi);
    }
    barrier.blockBarrier();
    /*
     * Get the position to fill the measurements found in this thread group.
     */
    const unsigned int groupPos = outi;
    barrier.blockBarrier();
    if (threadId == 0) {
        outi = 0;
    }
    barrier.blockBarrier();
    const vecmem::data::vector_view<unsigned short> f_view(
        max_cells_per_partition, &f[0]);
    for (index_t tst = 0, cid; (cid = tst * blckDim + threadId) < size; ++tst) {
        if (f[cid] == cid) {
            /*
             * If we are a cluster owner, atomically claim a position in the
             * output array which we can write to.
             */
            vecmem::device_atomic_ref<unsigned int,
                                      vecmem::device_address_space::local>
                atom(outi);
            const unsigned int id = atom.fetch_add(1);
            device::aggregate_cluster(cells_device, modules_device, f_view,
                                      partition_start, partition_end, cid,
                                      measurements_device[groupPos + id],
                                      cell_links, groupPos + id);
        }
    }
}
References aggregate_cluster(), fast_sv_1(), and reduce_problem_cell().
count_doublets()
TRACCC_HOST_DEVICE void traccc::device::count_doublets (std::size_t globalIndex, const seedfinder_config & config, const sp_grid_const_view & sp_view, const vecmem::data::vector_view< const prefix_sum_element_t > & sp_ps_view, doublet_counter_collection_types::view doublet_view, unsigned int & nMidBot, unsigned int & nMidTop) [inline]
Function used for calculating the number of spacepoint doublets
The count is necessary for allocating the appropriate amount of memory for storing the information of the candidates in a next step.
Parameters
 in globalIndex The index of the current thread
 in config Seedfinder configuration
 in sp_view The spacepoint grid to count doublets on
 in sp_ps_view Prefix sum for iterating over the spacepoint grid
 out doublet_view Collection storing the number of doublets for each spacepoint
 out nMidBot Total number of middle-bottom doublets
 out nMidTop Total number of middle-top doublets
                           {
    // Check if anything needs to be done.
    vecmem::device_vector<const prefix_sum_element_t> sp_prefix_sum(sp_ps_view);
    if (globalIndex >= sp_prefix_sum.size()) {
        return;
    }
    // Get the middle spacepoint that we need to be looking at.
    const prefix_sum_element_t middle_sp_idx = sp_prefix_sum[globalIndex];
    // Set up the device containers.
    const const_sp_grid_device sp_grid(sp_view);
    doublet_counter_collection_types::device doublet_counter(doublet_view);
    // Get the spacepoint that we're evaluating in this thread, and treat that
    // as the "middle" spacepoint.
    const internal_spacepoint<spacepoint> middle_sp =
        sp_grid.bin(middle_sp_idx.first).at(middle_sp_idx.second);
    // The the IDs of the neighbouring bins along the phi and Z axes of the
    // grid.
    const detray::dindex_range phi_bins =
        sp_grid.axis_p0().range(middle_sp.phi(), config.neighbor_scope);
    const detray::dindex_range z_bins =
        sp_grid.axis_p1().range(middle_sp.z(), config.neighbor_scope);
    assert(z_bins[0] <= z_bins[1]);
    // The number of middle-bottom candidates found for this thread's middle
    // spacepoint.
    unsigned int n_mb_cand = 0;
    // The number of middle-top candidates found for this thread's middle
    // spacepoint.
    unsigned int n_mt_cand = 0;
    // Iterate over all of the neighboring phi bins, including the same bin that
    // the middle spacepoint is in. The loop over the phi bins needs to take
    // into account that we may iterate over the "wrap around point" of the
    // axis.
    for (detray::dindex phi_bin_iterator = phi_bins[0];
         phi_bin_iterator <=
         (phi_bins[1] +
          (phi_bins[0] > phi_bins[1] ? sp_grid.axis_p0().n_bins : 0));
         ++phi_bin_iterator) {
        // Set up the phi bin index that we are actually meant to use inside of
        // the loop. We could also use a modulo operation here, but that would
        // be slightly more expensive in this specific case.
        const detray::dindex phi_bin =
            (phi_bin_iterator >= sp_grid.axis_p0().n_bins
                 ? phi_bin_iterator - sp_grid.axis_p0().n_bins
                 : phi_bin_iterator);
        // Iterate over all of the neighboring Z bins, including the same bin
        // that the middle spacepoint is in. This is a much easier iteration, as
        // the Z axis does not "wrap around".
        for (detray::dindex z_bin = z_bins[0]; z_bin <= z_bins[1]; ++z_bin) {
            // Ask the grid for all of the spacepoints in this specific bin.
            typename const_sp_grid_device::serialized_storage::const_reference
                spacepoints = sp_grid.bin(phi_bin, z_bin);
            // Loop over all of those spacepoints.
            for (const internal_spacepoint<spacepoint> other_sp : spacepoints) {
                // Check if this spacepoint is a compatible "bottom" spacepoint
                // to the thread's "middle" spacepoint.
                if (doublet_finding_helper::isCompatible<
                        details::spacepoint_type::bottom>(middle_sp, other_sp,
                                                          config)) {
                    ++n_mb_cand;
                }
                // Check if this spacepoint is a compatible "top" spacepoint to
                // the thread's "middle" spacepoint.
                if (doublet_finding_helper::isCompatible<
                        details::spacepoint_type::top>(middle_sp, other_sp,
                                                       config)) {
                    ++n_mt_cand;
                }
            }
        }
    }
    // Add the counts if compatible bottom *AND* top candidates were found for
    // the middle spacepoint in question.
    if ((n_mb_cand > 0) && (n_mt_cand > 0)) {
        // Increment the summary values in the header object.
        vecmem::device_atomic_ref<unsigned int> numMidBot(nMidBot);
        const unsigned int posBot = numMidBot.fetch_add(n_mb_cand);
        vecmem::device_atomic_ref<unsigned int> numMidTop(nMidTop);
        const unsigned int posTop = numMidTop.fetch_add(n_mt_cand);
        // Add the number of candidates for the "current bin".
        doublet_counter.push_back(
            {{static_cast<unsigned int>(middle_sp_idx.first),
              static_cast<unsigned int>(middle_sp_idx.second)},
             n_mb_cand,
             n_mt_cand,
             posBot,
             posTop});
    }
}
References traccc::details::bottom, traccc::doublet_finding_helper::isCompatible(), traccc::seedfinder_config::neighbor_scope, traccc::internal_spacepoint< spacepoint_t >::phi(), traccc::details::top, and traccc::internal_spacepoint< spacepoint_t >::z().
count_grid_capacities()
TRACCC_HOST_DEVICE void traccc::device::count_grid_capacities (const std::size_t globalIndex, const seedfinder_config & config, const sp_grid::axis_p0_type & phi_axis, const sp_grid::axis_p1_type & z_axis, const spacepoint_collection_types::const_view & spacepoints, vecmem::data::vector_view< unsigned int > grid_capacities) [inline]
Function used for calculating the capacity for the spacepoint grid
Before filling the spacepoint grid with the spacepoints that belong to each grid bin, we need to calculate how big each of those bins are going to be.
This function needs to be called separately for every spacepoint of the event.
Parameters
 in globalIndex The index of the current thread
 in config Seedfinder configuration
 in phi_axis The circular &Phi axis describing the geometry
 in z_axis The linear Z axis describing the geometry
 in spacepoints All the spacepoints of the event
 out grid_capacities Capacity required for each spacepoint grid bin
Check out if the spacepoint can be used for seeding.
Check out if the spacepoint can be used for seeding.
                                                              {
    // Check if anything needs to be done.
    const spacepoint_collection_types::const_device spacepoints(
        spacepoints_view);
    if (globalIndex >= spacepoints.size()) {
        return;
    }
    const spacepoint sp = spacepoints.at(globalIndex);
    if (is_valid_sp(config, sp) != detray::detail::invalid_value<size_t>()) {
        // Find the grid bin that the spacepoint belongs to.
        const internal_spacepoint<spacepoint> isp(sp, globalIndex,
                                                  config.beamPos);
        const std::size_t bin_index =
            phi_axis.bin(isp.phi()) + phi_axis.bins() * z_axis.bin(isp.z());
        // Increase the capacity of the grid bin.
        vecmem::device_vector<unsigned int> grid_capacities(
            grid_capacities_view);
        vecmem::device_atomic_ref<unsigned int> bin_content(
            grid_capacities[bin_index]);
        bin_content.fetch_add(1);
    }
}
References traccc::seedfinder_config::beamPos, traccc::is_valid_sp(), traccc::internal_spacepoint< spacepoint_t >::phi(), and traccc::internal_spacepoint< spacepoint_t >::z().
Referenced by traccc::alpaka::CountGridCapacityKernel::operator()(), and traccc::kokkos::spacepoint_binning::operator()().
count_measurements()
TRACCC_DEVICE void traccc::device::count_measurements (std::size_t globalIndex, bound_track_parameters_collection_types::const_view params_view, vecmem::data::vector_view< const detray::geometry::barcode > barcodes_view, vecmem::data::vector_view< const unsigned int > upper_bounds_view, const unsigned int n_in_params, vecmem::data::vector_view< unsigned int > n_measurements_view, vecmem::data::vector_view< unsigned int > ref_meas_idx_view, unsigned int & n_measurements_sum) [inline]
Function evalulating the number of measurements to be iterated per thread and the total number of measurements
Parameters
 in globalIndex The index of the current thread
 in params_view Input parameters view object
 in barcodes_view Barcodes view object
 in upper_bounds Upper bounds of measurements w.r.t geometry ID
 out n_measurements_view The number of measurements per parameter
 out ref_meas_idx The first index of measurements per parameter
 out n_measurements_sum The sum of the number of measurements per parameter
                                      {
    bound_track_parameters_collection_types::const_device params(params_view);
    vecmem::device_vector<const detray::geometry::barcode> barcodes(
        barcodes_view);
    vecmem::device_vector<const unsigned int> upper_bounds(upper_bounds_view);
    vecmem::device_vector<unsigned int> n_measurements(n_measurements_view);
    vecmem::device_vector<unsigned int> ref_meas_idx(ref_meas_idx_view);
    if (globalIndex >= n_in_params) {
        return;
    }
    // Get barcode
    const auto bcd = params.at(globalIndex).surface_link();
    const auto lo =
        thrust::lower_bound(thrust::seq, barcodes.begin(), barcodes.end(), bcd);
    const auto bcd_id = std::distance(barcodes.begin(), lo);
    // Get the reference measurement index and the number of measurements per
    // parameter
    ref_meas_idx.at(globalIndex) =
        lo == barcodes.begin() ? 0u : upper_bounds[bcd_id - 1];
    n_measurements.at(globalIndex) =
        upper_bounds[bcd_id] - ref_meas_idx.at(globalIndex);
    // Increase the total number of measurements with atomic addition
    vecmem::device_atomic_ref<unsigned int> n_meas_sum(n_measurements_sum);
    n_meas_sum.fetch_add(n_measurements.at(globalIndex));
}
count_triplets()
TRACCC_HOST_DEVICE void traccc::device::count_triplets (std::size_t globalIndex, const seedfinder_config & config, const sp_grid_const_view & sp_view, const doublet_counter_collection_types::const_view & dc_view, const device_doublet_collection_types::const_view & mid_bot_doublet_view, const device_doublet_collection_types::const_view & mid_top_doublet_view, triplet_counter_spM_collection_types::view spM_tc, triplet_counter_collection_types::view mb_tc) [inline]
Function used for calculating the number of spacepoint triplets
The count is necessary for allocating the appropriate amount of memory for storing the information of the candidates in a next step.
Parameters
 in globalIndex The index of the current thread
 in config Seedfinder configuration
 in sp_view The spacepoint grid to count triplets on
 in dc_view Collection of doublet counters
 in mid_bot_doublet_view Collection storing the midBot doublets
 in mid_top_doublet_view Collection storing the midTop doublets
 out spM_tc Collection storing the number of triplets per middle spacepoint
 out mb_tc Collection storing the number of triplets per midBottom doublet
                                                     {
    // Create device copy of input parameters
    const device_doublet_collection_types::const_device mid_bot_doublet_device(
        mid_bot_doublet_view);
    // Check if anything needs to be done.
    if (globalIndex >= mid_bot_doublet_device.size()) {
        return;
    }
    // Get current mid bottom doublet
    const device_doublet mid_bot = mid_bot_doublet_device.at(globalIndex);
    // Create device copy of input parameters
    const device_doublet_collection_types::const_device mid_top_doublet_device(
        mid_top_doublet_view);
    const doublet_counter_collection_types::const_device dc_device(dc_view);
    // Create device copy of output parameterss
    triplet_counter_collection_types::device mb_triplet_counter(mb_tc_view);
    triplet_counter_spM_collection_types::device spM_triplet_counter(
        spM_tc_view);
    // Get all spacepoints
    const const_sp_grid_device internal_sp_device(sp_view);
    const unsigned int counter_link = mid_bot.counter_link;
    const doublet_counter doublet_counts = dc_device.at(counter_link);
    // middle spacepoint
    const sp_location spM_loc = doublet_counts.m_spM;
    const traccc::internal_spacepoint<traccc::spacepoint> spM =
        internal_sp_device.bin(spM_loc.bin_idx)[spM_loc.sp_idx];
    const sp_location spB_loc = mid_bot.sp2;
    // bottom spacepoint
    const traccc::internal_spacepoint<traccc::spacepoint> spB =
        internal_sp_device.bin(spB_loc.bin_idx)[spB_loc.sp_idx];
    // Apply the conformal transformation to middle-bot doublet
    traccc::lin_circle lb = doublet_finding_helper::transform_coordinates<
        details::spacepoint_type::bottom>(spM, spB);
    // Calculate some physical quantities required for triplet compatibility
    // check
    scalar iSinTheta2 = static_cast<scalar>(1.) + lb.cotTheta() * lb.cotTheta();
    scalar scatteringInRegion2 = config.maxScatteringAngle2 * iSinTheta2;
    scatteringInRegion2 *= config.sigmaScattering * config.sigmaScattering;
    // These two quantities are used as output parameters in
    // triplet_finding_helper::isCompatible but their values are irrelevant
    scalar curvature, impact_parameter;
    // find the reference (start) index of the mid-top doublet container
    // item vector, where the doublets are recorded
    const unsigned int mt_start_idx = doublet_counts.m_posMidTop;
    const unsigned int mt_end_idx = mt_start_idx + doublet_counts.m_nMidTop;
    // number of triplets per middle-bot doublet
    unsigned int num_triplets_per_mb = 0;
    // iterate over mid-top doublets
    for (unsigned int i = mt_start_idx; i < mt_end_idx; ++i) {
        const traccc::sp_location spT_loc = mid_top_doublet_device[i].sp2;
        const traccc::internal_spacepoint<traccc::spacepoint> spT =
            internal_sp_device.bin(spT_loc.bin_idx)[spT_loc.sp_idx];
        // Apply the conformal transformation to middle-top doublet
        traccc::lin_circle lt = doublet_finding_helper::transform_coordinates<
            details::spacepoint_type::top>(spM, spT);
        // Check if mid-bot and mid-top doublets can form a triplet
        if (triplet_finding_helper::isCompatible(
                spM, lb, lt, config, iSinTheta2, scatteringInRegion2, curvature,
                impact_parameter)) {
            num_triplets_per_mb++;
        }
    }
    // if the number of triplets per mb is larger than 0, write the triplet
    // counter into the collection
    if (num_triplets_per_mb > 0) {
        triplet_counter_spM& header = spM_triplet_counter.at(counter_link);
        vecmem::device_atomic_ref<unsigned int> nTriplets(header.m_nTriplets);
        const unsigned int posTriplets =
            nTriplets.fetch_add(num_triplets_per_mb);
        mb_triplet_counter.push_back(
            {spB_loc, counter_link, num_triplets_per_mb, posTriplets});
    }
}
References traccc::sp_location::bin_idx, traccc::details::bottom, traccc::lin_circle::cotTheta(), traccc::device::device_doublet::counter_link, traccc::triplet_finding_helper::isCompatible(), traccc::device::doublet_counter::m_nMidTop, traccc::device::triplet_counter_spM::m_nTriplets, traccc::device::doublet_counter::m_posMidTop, traccc::device::doublet_counter::m_spM, traccc::seedfinder_config::maxScatteringAngle2, traccc::seedfinder_config::sigmaScattering, traccc::device::device_doublet::sp2, traccc::sp_location::sp_idx, traccc::details::top, and traccc::doublet_finding_helper::transform_coordinates().
estimate_track_params()
TRACCC_HOST_DEVICE void traccc::device::estimate_track_params (const std::size_t globalIndex, const spacepoint_collection_types::const_view & spacepoints_view, const seed_collection_types::const_view & seeds_view, const vector3 & bfield, const std::array< traccc::scalar, traccc::e_bound_size > & stddev, bound_track_parameters_collection_types::view params_view) [inline]
Function used for calculating the bound track parameters for each seed
Parameters
 in globalIndex The index of the current thread
 in spacepoints_view Collection storing the spacepoints
 in seeds_view Collection storing the seeds
 in bfield B field
 in stddev Standard deviation of seed parameters
 out params_view Collection storing the bound track parameters
                                                             {
    // Check if anything needs to be done.
    const seed_collection_types::const_device seeds_device(seeds_view);
    if (globalIndex >= seeds_device.size()) {
        return;
    }
    const spacepoint_collection_types::const_device spacepoints_device(
        spacepoints_view);
    bound_track_parameters_collection_types::device params_device(params_view);
    const seed& this_seed = seeds_device.at(globalIndex);
    // Get bound track parameter
    bound_track_parameters track_params;
    track_params.set_vector(seed_to_bound_vector(spacepoints_device, this_seed,
                                                 bfield, PION_MASS_MEV));
    // Set Covariance
    for (std::size_t i = 0; i < e_bound_size; i++) {
        getter::element(track_params.covariance(), i, i) =
            stddev[i] * stddev[i];
    }
    // Get geometry ID for bottom spacepoint
    const auto& spB = spacepoints_device.at(this_seed.spB_link);
    track_params.set_surface_link(spB.meas.surface_link);
    // Save the object into global memory.
    params_device[globalIndex] = track_params;
}
References traccc::e_bound_size, traccc::PION_MASS_MEV, traccc::seed_to_bound_vector(), and traccc::seed::spB_link.
fast_sv_1()
template<typename barrier_t >
TRACCC_DEVICE void traccc::device::fast_sv_1 (index_t * f, index_t * gf, unsigned char adjc[MAX_CELLS_PER_THREAD], index_t adjv[MAX_CELLS_PER_THREAD][8], const index_t tid, const index_t blckDim, barrier_t & barrier)
Implementation of a FastSV algorithm with the following steps: 1) mix of stochastic and aggressive hooking 2) shortcutting
The implementation corresponds to an adapted versiion of Algorithm 3 of the following paper: https://www.sciencedirect.com/science/article/pii/S0743731520302689
                This array only gets updated at the end of the iteration
                to prevent race conditions.
Parameters
 in adjc The number of adjacent cells
 in adjv Vector of adjacent cells
 in tid The thread index
 in blckDim The block size
 in,out f array holding the parent cell ID for the current iteration.
 in,out gf array holding grandparent cell ID from the previous iteration.
 in barrier A generic object for block-wide synchronisation
                                                 {
    /*
     * The algorithm finishes if an iteration leaves the arrays unchanged.
     * This varible will be set if a change is made, and dictates if another
     * loop is necessary.
     */
    bool gf_changed;
    do {
        /*
         * Reset the end-parameter to false, so we can set it to true if we
         * make a change to the gf array.
         */
        gf_changed = false;
        /*
         * The algorithm executes in a loop of three distinct parallel
         * stages. In this first one, a mix of stochastic and aggressive
         * hooking, we examine adjacent cells and copy their grand parents
         * cluster ID if it is lower than ours, essentially merging the two
         * together.
         */
        for (index_t tst = 0; tst < MAX_CELLS_PER_THREAD; ++tst) {
            const index_t cid = tst * blckDim + tid;
            __builtin_assume(adjc[tst] <= 8);
            for (unsigned char k = 0; k < adjc[tst]; ++k) {
                index_t q = gf[adjv[tst][k]];
                if (gf[cid] > q) {
                    f[f[cid]] = q;
                    f[cid] = q;
                }
            }
        }
        /*
         * Each stage in this algorithm must be preceded by a
         * synchronization barrier!
         */
        barrier.blockBarrier();
#pragma unroll
        for (index_t tst = 0; tst < MAX_CELLS_PER_THREAD; ++tst) {
            const index_t cid = tst * blckDim + tid;
            /*
             * The second stage is shortcutting, which is an optimisation that
             * allows us to look at any shortcuts in the cluster IDs that we
             * can merge without adjacency information.
             */
            if (f[cid] > gf[cid]) {
                f[cid] = gf[cid];
            }
        }
        /*
         * Synchronize before the final stage.
         */
        barrier.blockBarrier();
#pragma unroll
        for (index_t tst = 0; tst < MAX_CELLS_PER_THREAD; ++tst) {
            const index_t cid = tst * blckDim + tid;
            /*
             * Update the array for the next generation, keeping track of any
             * changes we make.
             */
            if (gf[cid] != f[f[cid]]) {
                gf[cid] = f[f[cid]];
                gf_changed = true;
            }
        }
        /*
         * To determine whether we need another iteration, we use block
         * voting mechanics. Each thread checks if it has made any changes
         * to the arrays, and votes. If any thread votes true, all threads
         * will return a true value and go to the next iteration. Only if
         * all threads return false will the loop exit.
         */
    } while (barrier.blockOr(gf_changed));
}
Referenced by ccl_kernel().
fill_prefix_sum()
TRACCC_HOST_DEVICE void traccc::device::fill_prefix_sum (const std::size_t globalIndex, const vecmem::data::vector_view< const prefix_sum_size_t > & sizes_view, vecmem::data::vector_view< prefix_sum_element_t > ps_view) [inline]
Function filling the prefix sum for a `size vector`
This simple function is just meant to translate the received `size vector` into a `prefix sum`. I.e. into a list of index pairs that would allow visiting all elements of the jagged vector described by this `size vector`.
Parameters
 in globalIndex The index of the current thread
 in sizes_view View on the sizes of the `inner vectors` of a jagged vector
 out ps_view View on the result vector of index pairs
                                                         {
    const vecmem::device_vector<const prefix_sum_size_t> sizes(sizes_view);
    vecmem::device_vector<prefix_sum_element_t> result(ps_view);
    if (globalIndex >= sizes.size()) {
        return;
    }
    const prefix_sum_size_t previous =
        (globalIndex == 0) ? 0 : sizes[globalIndex - 1];
    const prefix_sum_size_t current = sizes[globalIndex];
    for (prefix_sum_size_t i = 0; i < current - previous; ++i) {
        result.at(previous + i) = {globalIndex, i};
    }
}
Referenced by traccc::kokkos::make_prefix_sum_buff(), and traccc::alpaka::PrefixSumBuffKernel::operator()().
find_doublets()
TRACCC_HOST_DEVICE void traccc::device::find_doublets (std::size_t globalIndex, const seedfinder_config & config, const sp_grid_const_view & sp_view, const doublet_counter_collection_types::const_view & dc_view, device_doublet_collection_types::view mb_doublets_view, device_doublet_collection_types::view mt_doublets_view) [inline]
Function finding all of the spacepoint doublets
Based on the information collected by traccc::device::count_doublets it can fill collection with the specific doublet pairs that exist in the event.
Parameters
 in globalIndex The index of the current thread
 in config Seedfinder configuration
 in sp_view The spacepoint grid to find doublets on
 in dc_view Collection with the number of doublets to find
 out mb_doublets_view Collection of middle-bottom doublets
 out mt_doublets_view Collection of middle-top doublets
                                                          {
    // Check if anything needs to be done.
    const doublet_counter_collection_types::const_device doublet_counts(
        dc_view);
    if (globalIndex >= doublet_counts.size()) {
        return;
    }
    // Get the middle spacepoint that we need to be looking at.
    const doublet_counter middle_sp_counter = doublet_counts.at(globalIndex);
    // Set up the device containers.
    const const_sp_grid_device sp_grid(sp_view);
    device_doublet_collection_types::device mb_doublets(mb_doublets_view);
    device_doublet_collection_types::device mt_doublets(mt_doublets_view);
    // Get the spacepoint that we're evaluating in this thread, and treat that
    // as the "middle" spacepoint.
    const internal_spacepoint<spacepoint> middle_sp =
        sp_grid.bin(middle_sp_counter.m_spM.bin_idx)
            .at(middle_sp_counter.m_spM.sp_idx);
    // Find the reference (start) index of the doublet container item vector,
    // where the doublets are recorded.
    const unsigned int mid_bot_start_idx = middle_sp_counter.m_posMidBot;
    const unsigned int mid_top_start_idx = middle_sp_counter.m_posMidTop;
    // The running indices for the middle-bottom and middle-top pairs.
    unsigned int mid_bot_idx = 0, mid_top_idx = 0;
    // The the IDs of the neighbouring bins along the phi and Z axes of the
    // grid.
    const detray::dindex_range phi_bins =
        sp_grid.axis_p0().range(middle_sp.phi(), config.neighbor_scope);
    const detray::dindex_range z_bins =
        sp_grid.axis_p1().range(middle_sp.z(), config.neighbor_scope);
    assert(z_bins[0] <= z_bins[1]);
    // Iterate over all of the neighboring phi bins, including the same bin that
    // the middle spacepoint is in. The loop over the phi bins needs to take
    // into account that we may iterate over the "wrap around point" of the
    // axis.
    for (detray::dindex phi_bin_iterator = phi_bins[0];
         phi_bin_iterator <=
         (phi_bins[1] +
          (phi_bins[0] > phi_bins[1] ? sp_grid.axis_p0().n_bins : 0));
         ++phi_bin_iterator) {
        // Set up the phi bin index that we are actually meant to use inside of
        // the loop. We could also use a modulo operation here, but that would
        // be slightly more expensive in this specific case.
        const detray::dindex phi_bin =
            (phi_bin_iterator >= sp_grid.axis_p0().n_bins
                 ? phi_bin_iterator - sp_grid.axis_p0().n_bins
                 : phi_bin_iterator);
        // Iterate over all of the neighboring Z bins, including the same bin
        // that the middle spacepoint is in. This is a much easier iteration, as
        // the Z axis does not "wrap around".
        for (detray::dindex z_bin = z_bins[0]; z_bin <= z_bins[1]; ++z_bin) {
            // Ask the grid for all of the spacepoints in this specific bin.
            typename const_sp_grid_device::serialized_storage::const_reference
                spacepoints = sp_grid.bin(phi_bin, z_bin);
            // Construct the "single index" that refers to this phi-Z bin.
            const unsigned int other_bin_idx =
                phi_bin + z_bin * sp_grid.axis_p0().bins();
            const unsigned int size = spacepoints.size();
            // Loop over all of those spacepoints.
            for (unsigned int other_sp_idx = 0; other_sp_idx < size;
                 ++other_sp_idx) {
                // Access the "other spacepoint".
                const internal_spacepoint<spacepoint> other_sp =
                    spacepoints.at(other_sp_idx);
                // Check if this spacepoint is a compatible "bottom" spacepoint
                // to the thread's "middle" spacepoint.
                if (doublet_finding_helper::isCompatible<
                        details::spacepoint_type::bottom>(middle_sp, other_sp,
                                                          config)) {
                    // Add it as a candidate to the middle-bottom container.
                    const unsigned int pos = mid_bot_start_idx + mid_bot_idx++;
                    assert(pos < mb_doublets.size());
                    mb_doublets.at(pos) = {
                        {other_bin_idx, other_sp_idx},
                        static_cast<unsigned int>(globalIndex)};
                }
                // Check if this spacepoint is a compatible "top" spacepoint to
                // the thread's "middle" spacepoint.
                if (doublet_finding_helper::isCompatible<
                        details::spacepoint_type::top>(middle_sp, other_sp,
                                                       config)) {
                    // Add it as a candidate to the middle-top container.
                    const unsigned int pos = mid_top_start_idx + mid_top_idx++;
                    assert(pos < mt_doublets.size());
                    mt_doublets.at(pos) = {
                        {other_bin_idx, other_sp_idx},
                        static_cast<unsigned int>(globalIndex)};
                }
            }
        }
    }
}
References traccc::sp_location::bin_idx, traccc::details::bottom, traccc::doublet_finding_helper::isCompatible(), traccc::device::doublet_counter::m_posMidBot, traccc::device::doublet_counter::m_posMidTop, traccc::device::doublet_counter::m_spM, traccc::seedfinder_config::neighbor_scope, traccc::internal_spacepoint< spacepoint_t >::phi(), traccc::sp_location::sp_idx, traccc::details::top, and traccc::internal_spacepoint< spacepoint_t >::z().
find_tracks()
template<typename detector_t , typename config_t >
TRACCC_DEVICE void traccc::device::find_tracks (std::size_t globalIndex, const config_t cfg, typename detector_t::view_type det_data, measurement_collection_types::const_view measurements_view, bound_track_parameters_collection_types::const_view in_params_view, vecmem::data::vector_view< const unsigned int > n_measurements_prefix_sum_view, vecmem::data::vector_view< const unsigned int > ref_meas_idx_view, const unsigned int step, const unsigned int & n_max_candidates, bound_track_parameters_collection_types::view out_params_view, vecmem::data::vector_view< candidate_link > links_view, unsigned int & n_candidates) [inline]
Function for combinatorial finding. If the chi2 of the measurement < chi2_max, its measurement index and the index of the link from the previous step are added to the link container.
Parameters
 in globalIndex The index of the current thread
 in cfg Track finding config object
 in det_data Detector view object
 in measurements_view Measurements container view
 in upper_bounds_view Upper bounds of measurements unique w.r.t barcode
 in in_params_view Input parameters
 in n_measurements_prefix_sum_view Prefix sum of the number of measurements per parameter
 in ref_meas_idx_view The first index of measurements per parameter
 in step Step index
 in n_max_candidates Number of maximum candidates
 out out_params_view Output parameters
 out links_view link container for the current step
 out n_candidates The number of candidates for the current step
                                {
    // Detector
    detector_t det(det_data);
    // Measurement
    measurement_collection_types::const_device measurements(measurements_view);
    // Input parameters
    bound_track_parameters_collection_types::const_device in_params(
        in_params_view);
    // Output parameters
    bound_track_parameters_collection_types::device out_params(out_params_view);
    // Links
    vecmem::device_vector<candidate_link> links(links_view);
    // Prefix sum of the number of measurements per parameter
    vecmem::device_vector<const unsigned int> n_measurements_prefix_sum(
        n_measurements_prefix_sum_view);
    // Reference (first) measurement index per parameter
    vecmem::device_vector<const unsigned int> ref_meas_idx(ref_meas_idx_view);
    // Last step ID
    const unsigned int previous_step =
        (step == 0) ? std::numeric_limits<unsigned int>::max() : step - 1;
    const unsigned int n_measurements_sum = n_measurements_prefix_sum.back();
    const unsigned int stride = globalIndex * cfg.n_measurements_per_thread;
    vecmem::device_vector<const unsigned int>::iterator lo1;
    for (unsigned int i_meas = 0; i_meas < cfg.n_measurements_per_thread;
         i_meas++) {
        const unsigned int idx = stride + i_meas;
        if (idx >= n_measurements_sum) {
            break;
        }
        if (i_meas == 0 || idx == *lo1) {
            lo1 = thrust::lower_bound(thrust::seq,
                                      n_measurements_prefix_sum.begin(),
                                      n_measurements_prefix_sum.end(), idx + 1);
        }
        const unsigned int in_param_id =
            std::distance(n_measurements_prefix_sum.begin(), lo1);
        const detray::geometry::barcode bcd =
            in_params.at(in_param_id).surface_link();
        const unsigned int offset =
            lo1 == n_measurements_prefix_sum.begin() ? idx : idx - *(lo1 - 1);
        const unsigned int meas_idx = ref_meas_idx.at(in_param_id) + offset;
        bound_track_parameters in_par = in_params.at(in_param_id);
        const auto& meas = measurements.at(meas_idx);
        track_state<typename detector_t::transform3> trk_state(meas);
        const detray::surface<detector_t> sf{det, bcd};
        // Run the Kalman update
        sf.template visit_mask<
            gain_matrix_updater<typename detector_t::transform3>>(trk_state,
                                                                  in_par);
        // Get the chi-square
        const auto chi2 = trk_state.filtered_chi2();
        if (chi2 < cfg.chi2_max) {
            // Add measurement candidates to link
            vecmem::device_atomic_ref<unsigned int> num_candidates(
                n_candidates);
            const unsigned int l_pos = num_candidates.fetch_add(1);
            if (l_pos >= n_max_candidates) {
                n_candidates = n_max_candidates;
                return;
            }
            links[l_pos] = {{previous_step, in_param_id}, meas_idx};
            out_params[l_pos] = trk_state.filtered();
        }
    }
}
find_triplets()
TRACCC_HOST_DEVICE void traccc::device::find_triplets (std::size_t globalIndex, const seedfinder_config & config, const seedfilter_config & filter_config, const sp_grid_const_view & sp_view, const doublet_counter_collection_types::const_view & dc_view, const device_doublet_collection_types::const_view & mid_top_doublet_view, const triplet_counter_spM_collection_types::const_view & spM_tc_view, const triplet_counter_collection_types::const_view & tc_view, device_triplet_collection_types::view triplet_view) [inline]
Function finding all of the spacepoint triplets
Based on the information collected by traccc::device::count_triplets it can fill collection with the specific triplets that exist in the event.
Parameters
 in globalIndex The index of the current thread
 in config Seedfinder configuration
 in filter_config Seedfilter configuration
 in sp_view The spacepoint grid to find triplets on
 in dc_view Collection of doublet counters
 in mid_top_doublet_view Collection with the mid top doublets
 in spM_tc_view Collection with the number of triplets per spM
 in tc_view Collection with the number of triplets per midBot doublet
 out triplet_view Collection of triplets
                                                      {
    // Check if anything needs to be done.
    const triplet_counter_collection_types::const_device triplet_counts(
        tc_view);
    if (globalIndex >= triplet_counts.size()) {
        return;
    }
    // Get device copy of input parameters
    const doublet_counter_collection_types::const_device doublet_counts(
        dc_view);
    const device_doublet_collection_types::const_device mid_top_doublet_device(
        mid_top_doublet_view);
    const const_sp_grid_device sp_grid(sp_view);
    const triplet_counter_spM_collection_types::const_device triplet_counts_spM(
        spM_tc_view);
    // Get the current work item information
    const triplet_counter mid_bot_counter = triplet_counts.at(globalIndex);
    const triplet_counter_spM spM_counter =
        triplet_counts_spM.at(mid_bot_counter.spM_counter_link);
    const doublet_counter doublet_count =
        doublet_counts.at(mid_bot_counter.spM_counter_link);
    const sp_location spM_loc = spM_counter.spM;
    const sp_location spB_loc = mid_bot_counter.spB;
    // middle spacepoint
    const traccc::internal_spacepoint<traccc::spacepoint> spM =
        sp_grid.bin(spM_loc.bin_idx)[spM_loc.sp_idx];
    // bottom spacepoint
    const traccc::internal_spacepoint<traccc::spacepoint> spB =
        sp_grid.bin(spB_loc.bin_idx)[spB_loc.sp_idx];
    // Set up the device result collection
    device_triplet_collection_types::device triplets(triplet_view);
    // Apply the conformal transformation to middle-bot doublet
    const traccc::lin_circle lb = doublet_finding_helper::transform_coordinates<
        details::spacepoint_type::bottom>(spM, spB);
    // Calculate some physical quantities required for triplet compatibility
    // check
    const scalar iSinTheta2 = 1 + lb.cotTheta() * lb.cotTheta();
    const scalar scatteringInRegion2 = config.maxScatteringAngle2 * iSinTheta2 *
                                       config.sigmaScattering *
                                       config.sigmaScattering;
    // These two quantities are used as output parameters in
    // triplet_finding_helper::isCompatible but their values are irrelevant
    scalar curvature, impact_parameter;
    // find the reference (start) index of the mid-top doublet collection
    // item vector, where the doublets are recorded
    const unsigned int mt_start_idx = doublet_count.m_posMidTop;
    const unsigned int mt_end_idx = mt_start_idx + doublet_count.m_nMidTop;
    // The position in which these triplets should be filled is the sum of the
    // position for all triplets which share the same middle spacepoint
    // and the one for those which also share the same bottom spacepoint.
    unsigned int posTriplets =
        mid_bot_counter.posTriplets + spM_counter.posTriplets;
    // iterate over mid-top doublets
    for (unsigned int i = mt_start_idx; i < mt_end_idx; ++i) {
        const sp_location spT_loc = mid_top_doublet_device[i].sp2;
        const traccc::internal_spacepoint<traccc::spacepoint> spT =
            sp_grid.bin(spT_loc.bin_idx)[spT_loc.sp_idx];
        // Apply the conformal transformation to middle-top doublet
        const traccc::lin_circle lt =
            doublet_finding_helper::transform_coordinates<
                details::spacepoint_type::top>(spM, spT);
        // Check if mid-bot and mid-top doublets can form a triplet
        if (triplet_finding_helper::isCompatible(
                spM, lb, lt, config, iSinTheta2, scatteringInRegion2, curvature,
                impact_parameter)) {
            // Add triplet to jagged vector
            triplets.at(posTriplets++) = device_triplet(
                {spT_loc, static_cast<unsigned int>(globalIndex), curvature,
                 -impact_parameter * filter_config.impactWeightFactor,
                 lb.Zo()});
        }
    }
}
References traccc::sp_location::bin_idx, traccc::details::bottom, traccc::lin_circle::cotTheta(), traccc::seedfilter_config::impactWeightFactor, traccc::triplet_finding_helper::isCompatible(), traccc::device::doublet_counter::m_nMidTop, traccc::device::doublet_counter::m_posMidTop, traccc::seedfinder_config::maxScatteringAngle2, traccc::device::triplet_counter_spM::posTriplets, traccc::device::triplet_counter::posTriplets, traccc::seedfinder_config::sigmaScattering, traccc::sp_location::sp_idx, traccc::device::triplet_counter::spB, traccc::device::triplet_counter_spM::spM, traccc::device::triplet_counter::spM_counter_link, traccc::details::top, traccc::doublet_finding_helper::transform_coordinates(), and traccc::lin_circle::Zo().
fit()
template<typename fitter_t , typename detector_view_t >
TRACCC_HOST_DEVICE void traccc::device::fit (std::size_t globalIndex, detector_view_t det_data, const typename fitter_t::bfield_type field_data, const typename fitter_t::config_type cfg, vecmem::data::jagged_vector_view< typename fitter_t::intersection_type > nav_candidates_buffer, track_candidate_container_types::const_view track_candidates_view, track_state_container_types::view track_states_view) [inline]
Function used for fitting a track for a given track candidates
Parameters
 in globalIndex The index of the current thread
 in det_data Detector view object
 in nav_candidates_buffer Buffer for navigation candidate objects
 in track_candidates_view The input track candidates
 out track_states_view The output of fitted track states
                                                       {
    typename fitter_t::detector_type det(det_data);
    vecmem::jagged_device_vector<typename fitter_t::intersection_type>
        nav_candidates(nav_candidates_buffer);
    track_candidate_container_types::const_device track_candidates(
        track_candidates_view);
    track_state_container_types::device track_states(track_states_view);
    fitter_t fitter(det, field_data, cfg);
    if (globalIndex >= track_states.size()) {
        return;
    }
    // Track candidates per track
    const auto& track_candidates_per_track =
        track_candidates[globalIndex].items;
    // Seed parameter
    const auto& seed_param = track_candidates[globalIndex].header;
    // Track states per track
    auto track_states_per_track = track_states[globalIndex].items;
    for (auto& cand : track_candidates_per_track) {
        track_states_per_track.emplace_back(cand);
    }
    typename fitter_t::state fitter_state(track_states_per_track);
    // Run fitting
    fitter.fit(seed_param, fitter_state, nav_candidates.at(globalIndex));
    // Get the final fitting information
    track_states[globalIndex].header = fitter_state.m_fit_info;
}
References traccc::device_container< header_t, item_t >::size().
form_spacepoints()
TRACCC_HOST_DEVICE void traccc::device::form_spacepoints (const std::size_t globalIndex, measurement_collection_types::const_view measurements_view, cell_module_collection_types::const_view modules_view, const unsigned int measurement_count, spacepoint_collection_types::view spacepoints_view) [inline]
Function for creating 3D spacepoints out of 2D measurements
Parameters
 in globalIndex The index for the current thread
 in measurements_view Collection of measurements
 in modules_view Collection of modules (which the measurements link to)
 in measurement_count Number of measurements
 out spacepoints_view Collection of spacepoints
                                                      {
    // Get device copy of input parameters
    const measurement_collection_types::const_device measurements_device(
        measurements_view);
    // Check if anything needs to be done
    if (globalIndex >= measurement_count) {
        return;
    }
    // Get device copy of input parameters
    const cell_module_collection_types::const_device modules_device(
        modules_view);
    spacepoint_collection_types::device spacepoints_device(spacepoints_view);
    // Get the measurement for this index
    const measurement& meas = measurements_device.at(globalIndex);
    // Get the current cell module
    const cell_module& mod = modules_device.at(meas.module_link);
    // Form a spacepoint based on this measurement
    point3 local_3d = {meas.local[0], meas.local[1], 0.};
    point3 global = mod.placement.point_to_global(local_3d);
    // Fill the result object with this spacepoint
    spacepoints_device[globalIndex] = {global, meas};
}
References traccc::measurement::local, traccc::measurement::module_link, and traccc::cell_module::placement.
is_adjacent()
TRACCC_HOST_DEVICE bool traccc::device::is_adjacent (channel_id ac0, channel_id ac1, channel_id bc0, channel_id bc1) [inline]
                                        {
    unsigned int p0 = (ac0 - bc0);
    unsigned int p1 = (ac1 - bc1);
    return p0 * p0 <= 1 && p1 * p1 <= 1;
}
Referenced by reduce_problem_cell().
make_barcode_sequence()
TRACCC_DEVICE void traccc::device::make_barcode_sequence (std::size_t globalIndex, measurement_collection_types::const_view uniques_view, vecmem::data::vector_view< detray::geometry::barcode > barcodes_view) [inline]
Function filling the barcode sequence
Parameters
 in globalIndex The index of the current thread
 in uniques_view Measurement container view object
 out barcodes_view Unsorted module map of <module ID, header ID>
                                                                {
    measurement_collection_types::const_device uniques(uniques_view);
    vecmem::device_vector barcodes(barcodes_view);
    if (globalIndex >= uniques.size()) {
        return;
    }
    // Assign barcode
    barcodes.at(globalIndex) = uniques.at(globalIndex).surface_link;
}
make_prefix_sum_buffer()
TRACCC_HOST prefix_sum_buffer_t traccc::device::make_prefix_sum_buffer (const std::vector< prefix_sum_size_t > & sizes, vecmem::copy & copy, const traccc::memory_resource & mr)
Function providing the prefix sum for a `size vector`
This simple function is just meant to translate the received `size vector` into its prefix sum. I.e. Each element of the output vector equals the summation of all the elements up to that point of the input vector
Parameters
sizes The sizes of the `inner vectors` of a jagged vector
copy A `copy object` capable of dealing with the view
mr The memory resource to use of the result
Returns
A class containing the prefix sum view, a memory posessing object on the view elements, and the total summation of the size vector
                                     {
    if (sizes.size() == 0) {
        return {{}, {}, 0};
    }
    // Create vector with summation of sizes
    vecmem::vector<prefix_sum_size_t> sizes_sum(sizes.size(),
                                                mr.host ? mr.host : &(mr.main));
    std::partial_sum(sizes.begin(), sizes.end(), sizes_sum.begin(),
                     std::plus<prefix_sum_size_t>());
    const prefix_sum_size_t totalSize = sizes_sum.back();
    if (mr.host != nullptr) {
        // Create buffer and view objects
        vecmem::data::vector_buffer<prefix_sum_size_t> sizes_sum_buff(
            sizes_sum.size(), mr.main);
        copy.setup(sizes_sum_buff);
        (copy)(vecmem::get_data(sizes_sum), sizes_sum_buff)->wait();
        vecmem::data::vector_view<prefix_sum_size_t> sizes_sum_view(
            sizes_sum_buff);
        return {sizes_sum_view, std::move(sizes_sum_buff), totalSize};
    } else {
        // Create view object
        vecmem::data::vector_view<prefix_sum_size_t> sizes_sum_view =
            vecmem::get_data(sizes_sum);
        return {sizes_sum_view, std::move(sizes_sum), totalSize};
    }
}
References traccc::get_data(), traccc::memory_resource::host, and traccc::memory_resource::main.
Referenced by traccc::kokkos::make_prefix_sum_buff(), and traccc::alpaka::make_prefix_sum_buff().
populate_grid()
TRACCC_DEVICE void traccc::device::populate_grid (unsigned int globalIndex, const seedfinder_config & config, const spacepoint_collection_types::const_view & spacepoints, sp_grid_view grid) [inline]
Function populating the spacepoint grid
Parameters
 in globalIndex The index of the current thread
 in config Seedfinder configuration
 in spacepoints All the spacepoints of the event
 out grid The spacepoint grid to populate
Check out if the spacepoint can be used for seeding.
                            {
    // Check if anything needs to be done.
    const spacepoint_collection_types::const_device spacepoints(
        spacepoints_view);
    if (globalIndex >= spacepoints.size()) {
        return;
    }
    const spacepoint sp = spacepoints.at(globalIndex);
    if (is_valid_sp(config, sp) != detray::detail::invalid_value<size_t>()) {
        // Set up the spacepoint grid object(s).
        sp_grid_device grid(grid_view);
        const sp_grid_device::axis_p0_type& phi_axis = grid.axis_p0();
        const sp_grid_device::axis_p1_type& z_axis = grid.axis_p1();
        // Find the grid bin that the spacepoint belongs to.
        const internal_spacepoint<spacepoint> isp(sp, globalIndex,
                                                  config.beamPos);
        const std::size_t bin_index =
            phi_axis.bin(isp.phi()) + phi_axis.bins() * z_axis.bin(isp.z());
        // Add the spacepoint to the grid.
        grid.bin(bin_index).push_back(std::move(isp));
    }
}
References traccc::seedfinder_config::beamPos, traccc::is_valid_sp(), traccc::internal_spacepoint< spacepoint_t >::phi(), and traccc::internal_spacepoint< spacepoint_t >::z().
Referenced by traccc::kokkos::spacepoint_binning::operator()().
propagate_to_next_surface()
template<typename propagator_t , typename bfield_t , typename config_t >
TRACCC_DEVICE void traccc::device::propagate_to_next_surface (std::size_t globalIndex, const config_t cfg, typename propagator_t::detector_type::view_type det_data, bfield_t field_data, vecmem::data::jagged_vector_view< typename propagator_t::intersection_type > nav_candidates_buffer, bound_track_parameters_collection_types::const_view in_params_view, vecmem::data::vector_view< const candidate_link > links_view, const unsigned int step, const unsigned int & n_in_params, bound_track_parameters_collection_types::view out_params_view, vecmem::data::vector_view< unsigned int > param_to_link_view, vecmem::data::vector_view< typename candidate_link::link_index_type > tips_view, unsigned int & n_out_params) [inline]
Function for propagating the kalman-updated tracks to the next surface
If a track finds a surface that contains measurements, its bound track parameter on the surface will be used for the next step. Otherwise, the link is added into the tip link container so that we can know which links in the link container are the final measurements of full tracks
Parameters
 in globalIndex The index of the current thread
 in cfg Track finding config object
 in det_data Detector view object
 in nav_candidates_buffer Navgation buffer
 in in_params_view Input parameters
 in links_view Link container for the current step
 in step Step index
 in n_in_params The number of input parameters
 out out_params_view Output parameters
 out param_to_link_view Container for param index -> link index
 out tips_view Tip link container for the current step
 out n_out_params The number of output parameters
                                {
    if (globalIndex >= n_in_params) {
        return;
    }
    // Detector
    typename propagator_t::detector_type det(det_data);
    // Navigation candidate buffer
    vecmem::jagged_device_vector<typename propagator_t::intersection_type>
        nav_candidates(nav_candidates_buffer);
    // Input parameters
    bound_track_parameters_collection_types::const_device in_params(
        in_params_view);
    // Links
    vecmem::device_vector<const candidate_link> links(links_view);
    // Out parameters
    bound_track_parameters_collection_types::device out_params(out_params_view);
    // Param to Link ID
    vecmem::device_vector<unsigned int> param_to_link(param_to_link_view);
    // tips
    vecmem::device_vector<typename candidate_link::link_index_type> tips(
        tips_view);
    // Input bound track parameter
    const bound_track_parameters in_par = in_params.at(globalIndex);
    // Create propagator
    propagator_t propagator({}, {});
    // Create propagator state
    typename propagator_t::state propagation(
        in_par, field_data, det, std::move(nav_candidates.at(globalIndex)));
    propagation._stepping
        .template set_constraint<detray::step::constraint::e_accuracy>(
            cfg.constrained_step_size);
    // Actor state
    // @TODO: simplify the syntax here
    // @NOTE: Post material interaction might be required here
    using actor_list_type =
        typename propagator_t::actor_chain_type::actor_list_type;
    typename detray::detail::tuple_element<0, actor_list_type>::type::state
        s0{};
    typename detray::detail::tuple_element<1, actor_list_type>::type::state
        s1{};
    typename detray::detail::tuple_element<3, actor_list_type>::type::state
        s3{};
    typename detray::detail::tuple_element<2, actor_list_type>::type::state s2{
        s3};
    typename detray::detail::tuple_element<4, actor_list_type>::type::state s4{
        cfg.min_step_length_for_surface_aborter};
    // @TODO: Should be removed once detray is fixed to set the volume in the
    // constructor
    propagation._navigation.set_volume(in_par.surface_link().volume());
    // Propagate to the next surface
    propagator.propagate_sync(propagation, std::tie(s0, s1, s2, s3, s4));
    // If a surface found, add the parameter for the next step
    if (s4.success) {
        vecmem::device_atomic_ref<unsigned int> num_out_params(n_out_params);
        const unsigned int out_param_id = num_out_params.fetch_add(1);
        out_params[out_param_id] = propagation._stepping._bound_params;
        param_to_link[out_param_id] = static_cast<unsigned int>(globalIndex);
    }
    // Unless the track found a surface, it is considered a tip
    else if (!s4.success && step >= cfg.min_track_candidates_per_track - 1) {
        tips.push_back({step, globalIndex});
    }
}
reduce_problem_cell()
TRACCC_HOST_DEVICE void traccc::device::reduce_problem_cell (const cell_collection_types::const_device & cells, const unsigned short cid, const unsigned int start, const unsigned int end, unsigned char & adjc, unsigned short adjv[8]) [inline]
Function for looking for adjacent cells. The cell ids will range from 0 to max_cells_per_partition and the number of blocks will equal the number of partitions, hence checking all cells.
Parameters
 in cells Collection of cells
 in cid Current cell id
 in start Current partition start point
 in end Current partition end point
 out ajc Number of adjacent cells
 out ajv Indices of adjacent cells
                            {
    const unsigned int pos = cid + start;
    // Check if this code can benefit from changing to structs of arrays, as the
    // recurring accesses to cell data in global memory is slow right now.
    const channel_id c0 = cells[pos].channel0;
    const channel_id c1 = cells[pos].channel1;
    const unsigned int mod_id = cells[pos].module_link;
    /*
     * First, we traverse the cells backwards, starting from the current
     * cell and working back to the first, collecting adjacent cells
     * along the way.
     */
    for (unsigned int j = pos - 1; j < pos; --j) {
        /*
         * Since the data is sorted, we can assume that if we see a cell
         * sufficiently far away in both directions, it becomes
         * impossible for that cell to ever be adjacent to this one.
         * This is a small optimisation.
         */
        if (cells[j].channel1 + 1 < c1 || cells[j].module_link != mod_id) {
            break;
        }
        /*
         * If the cell examined is adjacent to the current cell, save it
         * in the current cell's adjacency set.
         */
        if (is_adjacent(c0, c1, cells[j].channel0, cells[j].channel1)) {
            adjv[adjc++] = j - start;
        }
    }
    /*
     * Now we examine all the cells past the current one, using almost
     * the same logic as in the backwards pass.
     */
    for (unsigned int j = pos + 1; j < end; ++j) {
        /*
         * Note that this check now looks in the opposite direction! An
         * important difference.
         */
        if (cells[j].channel1 > c1 + 1 || cells[j].module_link != mod_id) {
            break;
        }
        if (is_adjacent(c0, c1, cells[j].channel0, cells[j].channel1)) {
            adjv[adjc++] = j - start;
        }
    }
}
References is_adjacent().
Referenced by ccl_kernel().
reduce_triplet_counts()
TRACCC_HOST_DEVICE void traccc::device::reduce_triplet_counts (std::size_t globalIndex, const doublet_counter_collection_types::const_view & dc_view, triplet_counter_spM_collection_types::view spM_tc_view, unsigned int & num_triplets) [inline]
Function used for performing a reduction on the triplet counters
The count_triplets function will only count the number of triplets per each middle spacepoint independently. Thus, we need to perform a sum over all middle spacepoints, as well as correctly claim the positions in which the triplets will be filled in find:triplets
Parameters
 in globalIndex The index of the current thread
 in dc_view Collection of doublet counters
 in,out spM_tc_view Collection of triplet counters per middle spacepoint
 out num_triplets The total number of triplets
                                {
    // Get device copy of input parameters
    triplet_counter_spM_collection_types::device spM_counts(spM_tc_view);
    // Check if anything needs to be done.
    if (globalIndex >= spM_counts.size()) {
        return;
    }
    const doublet_counter_collection_types::const_device doublet_counts(
        dc_view);
    // This should only ever be called with two collections of equal size
    assert(doublet_counts.size() == spM_counts.size());
    // Get triplet counter for this middle spacepoint
    triplet_counter_spM& this_spM_counter = spM_counts.at(globalIndex);
    // Check if anything needs to be done.
    if (this_spM_counter.m_nTriplets == 0) {
        return;
    }
    // Fill the middle spacepoint information of the spM triplet counter
    this_spM_counter.spM = doublet_counts.at(globalIndex).m_spM;
    // Increment total number of triplets and claim position for this middle
    // spacepoint's triplets
    vecmem::device_atomic_ref<unsigned int> nTriplets(num_triplets);
    this_spM_counter.posTriplets =
        nTriplets.fetch_add(this_spM_counter.m_nTriplets);
}
References traccc::device::triplet_counter_spM::m_nTriplets, traccc::device::triplet_counter_spM::posTriplets, and traccc::device::triplet_counter_spM::spM.
select_seeds()
TRACCC_HOST_DEVICE void traccc::device::select_seeds (std::size_t globalIndex, const seedfilter_config & filter_config, const spacepoint_collection_types::const_view & spacepoints_view, const sp_grid_const_view & internal_sp_view, const triplet_counter_spM_collection_types::const_view & spM_tc_view, const triplet_counter_collection_types::const_view & tc_view, const device_triplet_collection_types::const_view & triplet_view, triplet * data, seed_collection_types::view seed_view) [inline]
Function used for selecting good triplets to be recorded into seed collection
Parameters
 in globalIndex The index of the current thread
 in filter_config Seed filter config
 in spacepoints_view Collection of spacepoints
 in internal_sp_view The spacepoint grid
 in spM_tc_view Collection with the number of triplets per spM
 in triplet_view Collection of triplets
 in data Array for temporary storage of triplets for comparison
 out seed_view Collection of seeds
                                                        {
    // Check if anything needs to be done.
    const triplet_counter_spM_collection_types::const_device triplet_counts_spM(
        spM_tc_view);
    if (globalIndex >= triplet_counts_spM.size()) {
        return;
    }
    // Set up the device containers
    const triplet_counter_collection_types::const_device triplet_counts(
        tc_view);
    const spacepoint_collection_types::const_device spacepoints_device(
        spacepoints_view);
    const const_sp_grid_device internal_sp_device(internal_sp_view);
    device_triplet_collection_types::const_device triplets(triplet_view);
    seed_collection_types::device seeds_device(seed_view);
    // Current work item = middle spacepoint
    const triplet_counter_spM spM_counter = triplet_counts_spM.at(globalIndex);
    const sp_location spM_loc = spM_counter.spM;
    const internal_spacepoint<spacepoint> spM =
        internal_sp_device.bin(spM_loc.bin_idx)[spM_loc.sp_idx];
    // Number of triplets added for this spM
    unsigned int n_triplets_per_spM = 0;
    const unsigned int end_triplets_spM =
        spM_counter.posTriplets + spM_counter.m_nTriplets;
    // iterate over the triplets in the bin
    for (unsigned int i = spM_counter.posTriplets; i < end_triplets_spM; ++i) {
        device_triplet aTriplet = triplets[i];
        // spacepoints bottom and top for this triplet
        const sp_location spB_loc =
            triplet_counts.at(aTriplet.counter_link).spB;
        const sp_location spT_loc = aTriplet.spT;
        const internal_spacepoint<spacepoint> spB =
            internal_sp_device.bin(spB_loc.bin_idx)[spB_loc.sp_idx];
        const internal_spacepoint<spacepoint> spT =
            internal_sp_device.bin(spT_loc.bin_idx)[spT_loc.sp_idx];
        // update weight of triplet
        seed_selecting_helper::seed_weight(filter_config, spM, spB, spT,
                                           aTriplet.weight);
        // check if it is a good triplet
        if (!seed_selecting_helper::single_seed_cut(filter_config, spM, spB,
                                                    spT, aTriplet.weight)) {
            continue;
        }
        // if the number of good triplets is larger than the threshold,
        // the triplet with the lowest weight is removed
        if (n_triplets_per_spM >= filter_config.max_triplets_per_spM) {
            const int min_index =
                details::min_elem(data, 0, filter_config.max_triplets_per_spM,
                                  [](const triplet lhs, const triplet rhs) {
                                      return lhs.weight > rhs.weight;
                                  });
            const scalar& min_weight = data[min_index].weight;
            if (aTriplet.weight > min_weight) {
                data[min_index] = {spB_loc, spM_loc,
                                   spT_loc, aTriplet.curvature,
                                   aTriplet.weight, aTriplet.z_vertex};
            }
        }
        // if the number of good triplets is below the threshold, add
        // the current triplet to the array
        else if (n_triplets_per_spM < filter_config.max_triplets_per_spM) {
            data[n_triplets_per_spM] = {spB_loc, spM_loc,
                                        spT_loc, aTriplet.curvature,
                                        aTriplet.weight, aTriplet.z_vertex};
            n_triplets_per_spM++;
        }
    }
    // sort the triplets per spM
    details::insertionSort(
        data, 0, n_triplets_per_spM, [&](triplet& lhs, triplet& rhs) {
            if (lhs.weight != rhs.weight) {
                return lhs.weight > rhs.weight;
            } else {
                scalar seed1_sum = 0;
                scalar seed2_sum = 0;
                const internal_spacepoint<spacepoint>& ispB1 =
                    internal_sp_device.bin(lhs.sp1.bin_idx)[lhs.sp1.sp_idx];
                const internal_spacepoint<spacepoint>& ispT1 =
                    internal_sp_device.bin(lhs.sp3.bin_idx)[lhs.sp3.sp_idx];
                const internal_spacepoint<spacepoint>& ispB2 =
                    internal_sp_device.bin(rhs.sp1.bin_idx)[rhs.sp1.sp_idx];
                const internal_spacepoint<spacepoint>& ispT2 =
                    internal_sp_device.bin(rhs.sp3.bin_idx)[rhs.sp3.sp_idx];
                const spacepoint& spB1 = spacepoints_device.at(ispB1.m_link);
                const spacepoint& spT1 = spacepoints_device.at(ispT1.m_link);
                const spacepoint& spB2 = spacepoints_device.at(ispB2.m_link);
                const spacepoint& spT2 = spacepoints_device.at(ispT2.m_link);
                constexpr scalar exp = 2;
                seed1_sum += std::pow(spB1.y(), exp) + std::pow(spB1.z(), exp);
                seed1_sum += std::pow(spT1.y(), exp) + std::pow(spT1.z(), exp);
                seed2_sum += std::pow(spB2.y(), exp) + std::pow(spB2.z(), exp);
                seed2_sum += std::pow(spT2.y(), exp) + std::pow(spT2.z(), exp);
                return seed1_sum > seed2_sum;
            }
        });
    // the number of good seed per compatible middle spacepoint
    unsigned int n_seeds_per_spM = 0;
    // iterate over the good triplets for final selection of seeds
    for (unsigned int i = 0; i < n_triplets_per_spM; ++i) {
        const triplet& aTriplet = data[i];
        const sp_location& spB_loc = aTriplet.sp1;
        const sp_location& spT_loc = aTriplet.sp3;
        const internal_spacepoint<spacepoint>& spB =
            internal_sp_device.bin(spB_loc.bin_idx)[spB_loc.sp_idx];
        const internal_spacepoint<spacepoint>& spT =
            internal_sp_device.bin(spT_loc.bin_idx)[spT_loc.sp_idx];
        // if the number of seeds reaches the threshold, break
        if (n_seeds_per_spM >= filter_config.maxSeedsPerSpM + 1) {
            break;
        }
        seed aSeed({spB.m_link, spM.m_link, spT.m_link, aTriplet.weight,
                    aTriplet.z_vertex});
        // check if it is a good triplet
        if (seed_selecting_helper::cut_per_middle_sp(
                filter_config, spacepoints_device, aSeed, aTriplet.weight) ||
            n_seeds_per_spM == 0) {
            n_seeds_per_spM++;
            seeds_device.push_back(aSeed);
        }
    }
}
References traccc::sp_location::bin_idx, traccc::device::device_triplet::counter_link, traccc::device::device_triplet::curvature, traccc::seed_selecting_helper::cut_per_middle_sp(), traccc::device::details::insertionSort(), traccc::internal_spacepoint< spacepoint_t >::m_link, traccc::device::triplet_counter_spM::m_nTriplets, traccc::seedfilter_config::max_triplets_per_spM, traccc::seedfilter_config::maxSeedsPerSpM, traccc::device::details::min_elem(), traccc::device::triplet_counter_spM::posTriplets, traccc::seed_selecting_helper::seed_weight(), traccc::seed_selecting_helper::single_seed_cut(), traccc::triplet::sp1, traccc::triplet::sp3, traccc::sp_location::sp_idx, traccc::device::triplet_counter_spM::spM, traccc::device::device_triplet::spT, traccc::device::device_triplet::weight, traccc::triplet::weight, traccc::device::device_triplet::z_vertex, and traccc::triplet::z_vertex.
update_triplet_weights()
TRACCC_HOST_DEVICE void traccc::device::update_triplet_weights (std::size_t globalIndex, const seedfilter_config & filter_config, const sp_grid_const_view & sp_view, const triplet_counter_spM_collection_types::const_view & spM_tc_view, const triplet_counter_collection_types::const_view & tc_view, scalar * data, device_triplet_collection_types::view triplet_view) [inline]
Function used for updating the triplets' weights
Parameters
 in globalIndex The index of the current thread
 in filter_config Seedfilter configuration
 in sp_view The spacepoint grid
 in spM_tc_view Collection of triplet counts per spM
 in tc_view Collection of triplet counts per midBot doublet
 in data Array for temporary storage of quality parameters for comparison of triplets
 in,out triplet_view Collection of triplets
                                                      {
    // Check if anything needs to be done.
    device_triplet_collection_types::device triplets(triplet_view);
    if (globalIndex >= triplets.size()) {
        return;
    }
    // Set up the device containers
    const const_sp_grid_device sp_grid(sp_view);
    const triplet_counter_spM_collection_types::const_device triplet_counts_spM(
        spM_tc_view);
    const triplet_counter_collection_types::const_device triplet_counts(
        tc_view);
    // Current work item
    device_triplet this_triplet = triplets[globalIndex];
    const sp_location& spT_idx = this_triplet.spT;
    const traccc::internal_spacepoint<traccc::spacepoint> current_spT =
        sp_grid.bin(spT_idx.bin_idx)[spT_idx.sp_idx];
    const scalar currentTop_r = current_spT.radius();
    // if two compatible seeds with high distance in r are found, compatible
    // seeds span 5 layers
    // -> very good seed
    const scalar lowerLimitCurv =
        this_triplet.curvature - filter_config.deltaInvHelixDiameter;
    const scalar upperLimitCurv =
        this_triplet.curvature + filter_config.deltaInvHelixDiameter;
    std::size_t num_compat_seedR = 0;
    const triplet_counter mb_count =
        triplet_counts.at(this_triplet.counter_link);
    // Check if anything needs to be done.
    if (mb_count.m_nTriplets <= 1) {
        return;
    }
    // Get the position of the triplets which share this sabe midBottom doublet
    const unsigned int triplets_mb_begin =
        mb_count.posTriplets +
        triplet_counts_spM.at(mb_count.spM_counter_link).posTriplets;
    const unsigned int triplets_mb_end =
        triplets_mb_begin + mb_count.m_nTriplets;
    // iterate over triplets
    for (unsigned int i = triplets_mb_begin; i < triplets_mb_end; ++i) {
        // skip same triplet
        if (i == globalIndex) {
            continue;
        }
        const device_triplet other_triplet = triplets[i];
        const sp_location other_spT_idx = other_triplet.spT;
        const traccc::internal_spacepoint<traccc::spacepoint> other_spT =
            sp_grid.bin(other_spT_idx.bin_idx)[other_spT_idx.sp_idx];
        // compared top SP should have at least deltaRMin distance
        const scalar otherTop_r = other_spT.radius();
        const scalar deltaR = currentTop_r - otherTop_r;
        if (std::abs(deltaR) < filter_config.deltaRMin) {
            continue;
        }
        // curvature difference within limits?
        // TODO: how much slower than sorting all vectors by curvature
        // and breaking out of loop? i.e. is vector size large (e.g. in
        // jets?)
        if (other_triplet.curvature < lowerLimitCurv) {
            continue;
        }
        if (other_triplet.curvature > upperLimitCurv) {
            continue;
        }
        bool newCompSeed = true;
        for (std::size_t i_s = 0; i_s < num_compat_seedR; ++i_s) {
            const scalar previousDiameter = data[i_s];
            // original ATLAS code uses higher min distance for 2nd found
            // compatible seed (20mm instead of 5mm) add new compatible seed
            // only if distance larger than rmin to all other compatible
            // seeds
            if (std::abs(previousDiameter - otherTop_r) <
                filter_config.deltaRMin) {
                newCompSeed = false;
                break;
            }
        }
        if (newCompSeed) {
            data[num_compat_seedR] = otherTop_r;
            this_triplet.weight += filter_config.compatSeedWeight;
            num_compat_seedR++;
        }
        if (num_compat_seedR >= filter_config.compatSeedLimit) {
            break;
        }
    }
    triplets[globalIndex].weight = this_triplet.weight;
}
References traccc::sp_location::bin_idx, traccc::seedfilter_config::compatSeedLimit, traccc::seedfilter_config::compatSeedWeight, traccc::device::device_triplet::counter_link, traccc::device::device_triplet::curvature, traccc::seedfilter_config::deltaInvHelixDiameter, traccc::seedfilter_config::deltaRMin, traccc::device::triplet_counter::m_nTriplets, traccc::device::triplet_counter::posTriplets, traccc::internal_spacepoint< spacepoint_t >::radius(), traccc::sp_location::sp_idx, traccc::device::triplet_counter::spM_counter_link, traccc::device::device_triplet::spT, and traccc::device::device_triplet::weight.