examples/simulation/simulate_toy_detector.cpp File Reference
#include `traccc/definitions/primitives.hpp`
#include `traccc/edm/track_parameters.hpp`
#include `traccc/io/utils.hpp`
#include `traccc/options/common_options.hpp`
#include `traccc/options/handle_argument_errors.hpp`
#include `traccc/options/options.hpp`
#include `traccc/options/particle_gen_options.hpp`
#include `traccc/options/propagation_options.hpp`
#include `traccc/simulation/measurement_smearer.hpp`
#include `traccc/simulation/simulator.hpp`
#include `traccc/simulation/smearing_writer.hpp`
#include `detray/detectors/bfield.hpp`
#include `detray/detectors/create_toy_geometry.hpp`
#include `detray/io/common/detector_writer.hpp`
#include `detray/simulation/event_generator/track_generators.hpp`
#include <vecmem/memory/host_memory_resource.hpp>
#include <boost/filesystem.hpp>
Functions
int simulate (std::string output_directory, unsigned int events, const traccc::particle_gen_options< scalar > &pg_opts, const traccc::propagation_options< scalar > &propagation_opts)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
                                 {
    // Set up the program options
    po::options_description desc("Allowed options");
    // Add options
    desc.add_options()("help,h", "Give some help with the program's options");
    desc.add_options()("output_directory", po::value<std::string>()->required(),
                       "specify the directory of output data");
    desc.add_options()("events", po::value<unsigned int>()->required(),
                       "number of events");
    traccc::particle_gen_options<scalar> pg_opts(desc);
    traccc::propagation_options<scalar> propagation_opts(desc);
    po::variables_map vm;
    po::store(po::parse_command_line(argc, argv, desc), vm);
    // Check errors
    traccc::handle_argument_errors(vm, desc);
    // Read options
    auto output_directory = vm["output_directory"].as<std::string>();
    auto events = vm["events"].as<unsigned int>();
    pg_opts.read(vm);
    propagation_opts.read(vm);
    std::cout << "Running " << argv[0] << " " << output_directory << " "
              << events << std::endl;
    return simulate(output_directory, events, pg_opts, propagation_opts);
}
References traccc::handle_argument_errors(), traccc::propagation_options< scalar_t >::read(), traccc::particle_gen_options< scalar_t >::read(), and simulate().
simulate()
int simulate (std::string output_directory, unsigned int events, const traccc::particle_gen_options< scalar > & pg_opts, const traccc::propagation_options< scalar > & propagation_opts)
                                                                        {
    // Use deterministic random number generator for testing
    using uniform_gen_t =
        detray::random_numbers<scalar, std::uniform_real_distribution<scalar>,
                               std::seed_seq>;
    // Memory resource
    vecmem::host_memory_resource host_mr;
    /*****************************
     * Build a toy geometry
     *****************************/
    // Detector type
    using detector_type = detray::detector<detray::toy_metadata>;
    // B field value and its type
    // @TODO: Set B field as argument
    using b_field_t = covfie::field<detray::bfield::const_bknd_t>;
    const vector3 B{0, 0, 2 * detray::unit<scalar>::T};
    auto field = detray::bfield::create_const_field(B);
    // Create the toy geometry
    const auto [det, name_map] = detray::create_toy_geometry(host_mr, {4u, 7u});
    /***************************
     * Generate simulation data
     ***************************/
    // Origin of particles
    using generator_type =
        detray::random_track_generator<traccc::free_track_parameters,
                                       uniform_gen_t>;
    generator_type::configuration gen_cfg{};
    gen_cfg.n_tracks(pg_opts.gen_nparticles);
    gen_cfg.origin(pg_opts.vertex);
    gen_cfg.origin_stddev(pg_opts.vertex_stddev);
    gen_cfg.phi_range(pg_opts.phi_range[0], pg_opts.phi_range[1]);
    gen_cfg.theta_range(pg_opts.theta_range[0], pg_opts.theta_range[1]);
    gen_cfg.mom_range(pg_opts.mom_range[0], pg_opts.mom_range[1]);
    gen_cfg.charge(pg_opts.charge);
    generator_type generator(gen_cfg);
    // Smearing value for measurements
    traccc::measurement_smearer<transform3> meas_smearer(
        50 * detray::unit<scalar>::um, 50 * detray::unit<scalar>::um);
    // Type declarations
    using writer_type =
        traccc::smearing_writer<traccc::measurement_smearer<transform3>>;
    // Writer config
    typename writer_type::config smearer_writer_cfg{meas_smearer};
    // Run simulator
    const std::string full_path = io::data_directory() + output_directory;
    boost::filesystem::create_directories(full_path);
    auto sim = traccc::simulator<detector_type, b_field_t, generator_type,
                                 writer_type>(
        events, det, field, std::move(generator), std::move(smearer_writer_cfg),
        full_path);
    sim.get_config().step_constraint = propagation_opts.step_constraint;
    sim.get_config().overstep_tolerance = propagation_opts.overstep_tolerance;
    sim.run();
    // Create detector file
    auto writer_cfg = detray::io::detector_writer_config{}
                          .format(detray::io::format::json)
                          .replace_files(true);
    detray::io::write_detector(det, name_map, writer_cfg);
    return 1;
}
References traccc::particle_gen_options< scalar_t >::charge, traccc::tests::data_test::data_directory, traccc::particle_gen_options< scalar_t >::gen_nparticles, traccc::simulator< detector_t, bfield_t, track_generator_t, writer_t >::get_config(), traccc::json, traccc::particle_gen_options< scalar_t >::mom_range, traccc::propagation_options< scalar_t >::overstep_tolerance, traccc::particle_gen_options< scalar_t >::phi_range, traccc::propagation_options< scalar_t >::step_constraint, traccc::simulator< detector_t, bfield_t, track_generator_t, writer_t >::config::step_constraint, traccc::particle_gen_options< scalar_t >::theta_range, traccc::particle_gen_options< scalar_t >::vertex, and traccc::particle_gen_options< scalar_t >::vertex_stddev.
Referenced by main().