traccc::module_map< K, V > Class Template Reference
A fast and GPU-friendly map for consecutive module IDs to values.
#include <module_map.hpp>
Classes
struct module_map_node
The internal representation of nodes in our binary search tree.
Public Member Functions
module_map ()=default
module_map (const std::map< K, V > &input)
Construct a module map from one created by the io library.
const V & operator[] (const K &i) const
Find a given key in the map.
const V & at (const K &i) const
Find a given key in the map, with bounds checking.
std::size_t size (void) const
Get the total number of modules in the module map.
bool contains (const K &i) const
bool empty (void) const
Private Member Functions
void create_tree (const std::vector< module_map_node > &nodes)
Lay out a set of nodes in a binary tree format.
const V * at_helper (const K &i, std::size_t n) const
Helper function to retrieve a value from the map.
Static Private Member Functions
static std::size_t round_up (std::size_t i)
Special rounding function for binary trees.
static std::pair< std::vector< V >, std::vector< module_map_node > > node_list (const std::map< K, V > &input)
Get a list of values and nodes from an existing std::map.
Private Attributes
std::vector< module_map_node > m_nodes
The internal storage of the nodes in our binary search tree.
std::vector< V > m_values
This vector stores the values in a contiguous manner. Our nodes keep indices in this array instead of pointers.
Detailed Description
template<typename K = geometry_id, typename V = transform3>
class traccc::module_map< K, V >
A fast and GPU-friendly map for consecutive module IDs to values.
Using std::map to model the relationship between geometry identifiers and transformation matrices works only on the CPU. std::map is not supported at all on CUDA, and either doesn't work or is inefficient on other platforms.
This class is a more efficient and more GPU-friendly implementation of the geometry ID to transformation mapping concept.
The implementation of this class relies on the idea that module IDs exist in contiguous sub-ranges, and we use this fact to get more efficient accesses. First, we reduce the range of module IDs to a set of contiguous sub-ranges. In the TrackML detector, there are roughly 18,000 modules, but there are only 71 contiguous sub-arrays. Because we can index a contiguous range in constant time, this presents possible speed-up.
Thus, the map is essentially two-layered. First, we determine which contigous sub-range a given value must fall in, and then we get the value from that sub-range in constant time.
The first layer is implemented as a simple balanced binary search tree, which we implement in a GPU-friendly fashion. This means that the cost of finding the relevant sub-range is O(log_2(n)), with n the number of sub-ranges. For the TrackML detector, this means we can find our value in only 7 steps!
Note
In theory, this class can be used for any mapping of key to value, but it relies quite heavily (for performance) on the contiguous nature of the keys inserted into it.
This map supports only construction. You can't update it in any way. To build one, construct a std::map first, and then convert it.
Constructor & Destructor Documentation
module_map() [1/2]
template<typename K = geometry_id, typename V = transform3>
traccc::module_map< K, V >::module_map () [default]
module_map() [2/2]
template<typename K = geometry_id, typename V = transform3>
traccc::module_map< K, V >::module_map (const std::map< K, V > & input) [inline]
Construct a module map from one created by the io library.
This method constructs a module map from an existing module map represented as a std::map.
Parameters
 in input The existing module map to convert.
                                          {
        /*
         * First, construct a list of nodes and values, which are linked
         * together.
         */
        std::vector<module_map_node> nodes;
        std::tie(m_values, nodes) = node_list(input);
        /*
         * Lay out the nodes in memory in an efficient way.
         */
        create_tree(nodes);
    }
References traccc::module_map< K, V >::create_tree(), traccc::module_map< K, V >::m_values, and traccc::module_map< K, V >::node_list().
Member Function Documentation
at()
template<typename K = geometry_id, typename V = transform3>
const V& traccc::module_map< K, V >::at (const K & i) const [inline]
Find a given key in the map, with bounds checking.
Parameters
 in i The key to look-up.
Returns
The value associated with the given key.
                                  {
        const V* r = at_helper(i, 0);
        if (r == nullptr) {
            throw std::out_of_range("Index not found in module map!");
        }
        return *r;
    }
References traccc::module_map< K, V >::at_helper().
Referenced by TEST().
at_helper()
template<typename K = geometry_id, typename V = transform3>
const V* traccc::module_map< K, V >::at_helper (const K & i, std::size_t n) const [inline], [private]
Helper function to retrieve a value from the map.
This function searches recursively for a value in a given sub-tree. Due to the formalism used for node indices, we can identify a subtree simply by the node index of its root node.
Parameters
 in i The value to look for.
 in n The index of the subtree's root node.
                                                      {
        /*
         * For memory safety, if we are out of bounds we will exit.
         */
        if (n >= m_nodes.size()) {
            return nullptr;
        }
        /*
         * Retrieve the current root node.
         */
        const module_map_node& node = m_nodes[n];
        /*
         * If the size is zero, it is essentially an invalid node (i.e. the
         * node does not exist).
         */
        if (node.size == 0) {
            return nullptr;
        }
        /*
         * If the value we are looking for is past the start of the current
         * node, there are three possibilities. Firstly, the value might be in
         * the current node. Secondly, the value might be in the right child of
         * the current node. Thirdly, the value might not be in the map at all.
         */
        if (i >= node.start) {
            /*
             * Next, we check if the value is within the range represented by
             * the current node.
             */
            if (i < node.start + node.size) {
                /*
                 * Found it! Return a pointer to the value within the
                 * contiguous range.
                 */
                return &m_values[node.index + (i - node.start)];
            } else {
                /*
                 * Two possibilties remain, we need to check the right subtree.
                 */
                return at_helper(i, 2 * n + 2);
            }
        }
        /*
         * If the value we want to find is less then the start of this node,
         * there are only two possibilities. Firstly, the value might be in the
         * left subtree, or the value might not be in the map at all.
         */
        else {
            return at_helper(i, 2 * n + 1);
        }
    }
References traccc::module_map< K, V >::module_map_node::index, traccc::module_map< K, V >::m_nodes, traccc::module_map< K, V >::m_values, traccc::module_map< K, V >::module_map_node::size, and traccc::module_map< K, V >::module_map_node::start.
Referenced by traccc::module_map< K, V >::at(), traccc::module_map< K, V >::contains(), and traccc::module_map< K, V >::operator[]().
contains()
template<typename K = geometry_id, typename V = transform3>
bool traccc::module_map< K, V >::contains (const K & i) const [inline]
{ return at_helper(i, 0) != nullptr; }
References traccc::module_map< K, V >::at_helper().
Referenced by TEST().
create_tree()
template<typename K = geometry_id, typename V = transform3>
void traccc::module_map< K, V >::create_tree (const std::vector< module_map_node > & nodes) [inline], [private]
Lay out a set of nodes in a binary tree format.
This method updates the binary tree contained in this object in an in-place fashion.
Parameters
 in nodes The nodes to create a tree from.
                                                              {
        /*
         * First, we resize the number of nodes in the tree to the number of
         * nodes in the input, but rounded up such that we have we end up with
         * 2^n - 1 spaces, where n is the ceiling of log2 of the size of the
         * input, plus one.
         */
        m_nodes.resize(round_up(nodes.size()));
        /*
         * This vector is our work queue for the pre-order insertion that we
         * will be doing. Each of these values contains a position where to
         * insert the next node, and the subset of nodes to insert in that
         * sub-tree.
         */
        std::vector<std::tuple<std::size_t, std::size_t, std::size_t>> z;
        /*
         * To kick-start the algorithm, we want to insert all nodes (from 0 to
         * the last one) at the first spot in the array.
         */
        z.emplace_back(0, 0, nodes.size());
        /*
         * We are done when the work queue is empty, but we will keep adding
         * things to it for a while at the start.
         */
        while (!z.empty()) {
            /*
             * Pop the current index and node range off the stack.
             */
            std::size_t i, s, e;
            std::tie(i, s, e) = z.back();
            z.pop_back();
            /*
             * Pick a node roughly in the middle of the node range. This will
             * be our next child.
             */
            std::size_t m = (s + e) / 2;
            /*
             * Insert the node we selected as our center in the given position.
             */
            m_nodes[i] = nodes[m];
            /*
             * If we have any nodes on the left side, we will put an element in
             * the work queue to place the left nodes at index 2i + 1.
             */
            if (m - s > 0) {
                z.emplace_back(2 * i + 1, s, m);
            }
            /*
             * Same thing for the right side, but we insert the right side
             * starting at 2i + 2 instead.
             */
            if (e - (m + 1) > 0) {
                z.emplace_back(2 * i + 2, m + 1, e);
            }
        }
    }
References traccc::module_map< K, V >::m_nodes, and traccc::module_map< K, V >::round_up().
Referenced by traccc::module_map< K, V >::module_map().
empty()
template<typename K = geometry_id, typename V = transform3>
bool traccc::module_map< K, V >::empty (void) const [inline]
{ return m_nodes.empty(); }
References traccc::module_map< K, V >::m_nodes.
Referenced by TEST().
node_list()
template<typename K = geometry_id, typename V = transform3>
static std::pair<std::vector<V>, std::vector<module_map_node> > traccc::module_map< K, V >::node_list (const std::map< K, V > & input) [inline], [static], [private]
Get a list of values and nodes from an existing std::map.
Given an existing map, this function will attempt to find all the nodes, that is to say contiguous sub-ranges. It will also put the values into one big, contiguous array.
Parameters
 in input An existing std::map module map.
Returns
A pair of vectors, one has the values, and the other has the nodes.
                                   {
        /*
         * We start out by grabbing a list of all the keys in the map.
         */
        std::vector<K> keys;
        keys.reserve(input.size());
        for (const std::pair<const K, V>& i : input) {
            keys.push_back(i.first);
        }
        /*
         * Next, we declare a vector of values, which is one of the two things
         * that we will return in the end.
         */
        std::vector<V> values;
        values.reserve(keys.size());
        /*
         * To find contiguous sub-ranges, the keys must be sorted. In general,
         * it is likely that they will be pre-sorted.
         */
        std::sort(keys.begin(), keys.end());
        /*
         * This vector will hold our nodes. We'll update it as we go, and we
         * start out with an incomplete first node, which represents the single
         * value at the start of the key vector. We will add to this later!
         */
        std::vector<module_map_node> nodes;
        nodes.push_back(module_map_node(keys.front(), 1, values.size()));
        values.push_back(input.at(keys.front()));
        /*
         * Starting from the second key, we check if they are contiuous with
         * the last key, and store them if so.
         */
        for (std::size_t i = 1; i < keys.size(); ++i) {
            /*
             * If the key is not adjacent to the last one, we push a new
             * partial node onto the node vector.
             */
            if (keys.at(i) != keys.at(i - 1) + 1) {
                nodes.push_back(module_map_node(keys.at(i), 0, values.size()));
            }
            /*
             * Push the current value into the value array, and register one
             * additional element in the current node.
             */
            ++nodes.back().size;
            values.push_back(input.at(keys.at(i)));
        }
        /*
         * Return both the generated values.
         */
        return {values, nodes};
    }
Referenced by traccc::module_map< K, V >::module_map().
operator[]()
template<typename K = geometry_id, typename V = transform3>
const V& traccc::module_map< K, V >::operator[] (const K & i) const [inline]
Find a given key in the map.
Parameters
 in i The key to look-up.
Returns
The value associated with the given key.
Warning
This method does no bounds checking, and will result in undefined behaviour if the key does not exist in the map.
{ return *at_helper(i, 0); }
References traccc::module_map< K, V >::at_helper().
round_up()
template<typename K = geometry_id, typename V = transform3>
static std::size_t traccc::module_map< K, V >::round_up (std::size_t i) [inline], [static], [private]
Special rounding function for binary trees.
This function computes 2^n - 1, where n is the ceiling of log2 of the input plus one.
This sounds like an odd operation, but consider that a binary tree (when complete) of depth k, can contain at most 2^k - 1 nodes. That is the number of spaces we need. However, our bottom level may have some empty slots, because it is rather unlikely that we will have exactly 2^k - 1 nodes. Thus, we need to round up k from log2 of the input. However, we need to also keep in mind that 2^l (for some integer l) should be rounded up to 2^(l+1), not 2^l! Since we are computing l, this would mean we would be short one space in some edge cases.
Parameters
 in i The number to round up.
Returns
The specially rounded number.
                                           {
        std::size_t n = 1;
        while (n < i + 1) {
            n *= 2;
        }
        return n - 1;
    }
Referenced by traccc::module_map< K, V >::create_tree().
size()
template<typename K = geometry_id, typename V = transform3>
std::size_t traccc::module_map< K, V >::size (void) const [inline]
Get the total number of modules in the module map.
This iterates over all of the nodes in the map and sums up their sizes.
Returns
The total number of modules in this module map.
                               {
        std::size_t c = 0;
        for (const module_map_node& n : m_nodes) {
            c += n.size;
        }
        return c;
    }
References traccc::module_map< K, V >::m_nodes.
Referenced by TEST().
Member Data Documentation
m_nodes
template<typename K = geometry_id, typename V = transform3>
std::vector<module_map_node> traccc::module_map< K, V >::m_nodes [private]
The internal storage of the nodes in our binary search tree.
This follows the well-known formalism where the root node resides at index 0, while for any node at position n, the left child is at index 2n
1, and the right child is at index 2n + 2.
Referenced by traccc::module_map< K, V >::at_helper(), traccc::module_map< K, V >::create_tree(), traccc::module_map< K, V >::empty(), and traccc::module_map< K, V >::size().
m_values
template<typename K = geometry_id, typename V = transform3>
std::vector<V> traccc::module_map< K, V >::m_values [private]
This vector stores the values in a contiguous manner. Our nodes keep indices in this array instead of pointers.
Referenced by traccc::module_map< K, V >::at_helper(), and traccc::module_map< K, V >::module_map().
The documentation for this class was generated from the following file:
core/include/traccc/geometry/module_map.hpp