traccc::gain_matrix_updater< algebra_t > Struct Template Reference
Type unrolling functor for Kalman updating.
#include <gain_matrix_updater.hpp>
Public Types
using matrix_operator = typename algebra_t::matrix_actor
using size_type = typename matrix_operator::size_ty
template<size_type ROWS, size_type COLS>
using matrix_type = typename matrix_operator::template matrix_type< ROWS, COLS >
Public Member Functions
template<typename mask_group_t , typename index_t >
TRACCC_HOST_DEVICE void operator() (const mask_group_t &, const index_t &, track_state< algebra_t > &trk_state, bound_track_parameters &bound_params) const
Based on `Application of Kalman filtering to track and vertex
fitting`, R.Frühwirth, NIM A.
template<size_type D, typename shape_t >
TRACCC_HOST_DEVICE void update (track_state< algebra_t > &trk_state, bound_track_parameters &bound_params) const
Detailed Description
template<typename algebra_t>
struct traccc::gain_matrix_updater< algebra_t >
Type unrolling functor for Kalman updating.
Member Typedef Documentation
matrix_operator
template<typename algebra_t >
using traccc::gain_matrix_updater< algebra_t >::matrix_operator = typename algebra_t::matrix_actor
matrix_type
template<typename algebra_t >
template<size_type ROWS, size_type COLS>
using traccc::gain_matrix_updater< algebra_t >::matrix_type = typename matrix_operator::template matrix_type<ROWS, COLS>
size_type
template<typename algebra_t >
using traccc::gain_matrix_updater< algebra_t >::size_type = typename matrix_operator::size_ty
Member Function Documentation
operator()()
template<typename algebra_t >
template<typename mask_group_t , typename index_t >
TRACCC_HOST_DEVICE void traccc::gain_matrix_updater< algebra_t >::operator() (const mask_group_t & , const index_t & , track_state< algebra_t > & trk_state, bound_track_parameters & bound_params) const [inline]
Based on `Application of Kalman filtering to track and vertex
fitting`, R.Frühwirth, NIM A.
Gain matrix updater operation
Parameters
mask_group mask group that contains the mask of surface
index mask index of surface
trk_state track state of the surface
bound_params bound parameter
Returns
true if the update succeeds
                                                    {
        using shape_type = typename mask_group_t::value_type::shape;
        const auto D = trk_state.get_measurement().meas_dim;
        assert(D == 1u || D == 2u);
        if (D == 1u) {
            update<1u, shape_type>(trk_state, bound_params);
        } else if (D == 2u) {
            update<2u, shape_type>(trk_state, bound_params);
        }
    }
References traccc::track_state< algebra_t >::get_measurement().
update()
template<typename algebra_t >
template<size_type D, typename shape_t >
TRACCC_HOST_DEVICE void traccc::gain_matrix_updater< algebra_t >::update (track_state< algebra_t > & trk_state, bound_track_parameters & bound_params) const [inline]
                                                    {
        static_assert(((D == 1u) || (D == 2u)),
                      "The measurement dimension should be 1 or 2");
        const auto meas = trk_state.get_measurement();
        // Some identity matrices
        // @Note: Make constexpr work
        const matrix_type<e_bound_size, e_bound_size> I66 =
            matrix_operator().template identity<e_bound_size, e_bound_size>();
        const matrix_type<D, D> I_m =
            matrix_operator().template identity<D, D>();
        matrix_type<D, e_bound_size> H = meas.subs.template projector<D>();
        // Measurement data on surface
        const matrix_type<D, 1>& meas_local =
            trk_state.template measurement_local<D>();
        // Predicted vector of bound track parameters
        const matrix_type<e_bound_size, 1>& predicted_vec =
            bound_params.vector();
        // Predicted covaraince of bound track parameters
        const matrix_type<e_bound_size, e_bound_size>& predicted_cov =
            bound_params.covariance();
        // Set track state parameters
        trk_state.predicted().set_vector(predicted_vec);
        trk_state.predicted().set_covariance(predicted_cov);
        if constexpr (std::is_same_v<shape_t, detray::line<true>> ||
                      std::is_same_v<shape_t, detray::line<false>>) {
            if (getter::element(predicted_vec, e_bound_loc0, 0u) < 0) {
                getter::element(H, 0u, e_bound_loc0) = -1;
            }
        }
        // Spatial resolution (Measurement covariance)
        const matrix_type<D, D> V =
            trk_state.template measurement_covariance<D>();
        const matrix_type<D, D> M =
            H * predicted_cov * matrix_operator().transpose(H) + V;
        // Kalman gain matrix
        const matrix_type<6, D> K = predicted_cov *
                                    matrix_operator().transpose(H) *
                                    matrix_operator().inverse(M);
        // Calculate the filtered track parameters
        const matrix_type<6, 1> filtered_vec =
            predicted_vec + K * (meas_local - H * predicted_vec);
        const matrix_type<6, 6> filtered_cov = (I66 - K * H) * predicted_cov;
        // Residual between measurement and (projected) filtered vector
        const matrix_type<D, 1> residual = meas_local - H * filtered_vec;
        // Calculate the chi square
        const matrix_type<D, D> R = (I_m - H * K) * V;
        const matrix_type<1, 1> chi2 = matrix_operator().transpose(residual) *
                                       matrix_operator().inverse(R) * residual;
        // Set the stepper parameter
        bound_params.set_vector(filtered_vec);
        bound_params.set_covariance(filtered_cov);
        // Set the track state parameters
        trk_state.filtered().set_vector(filtered_vec);
        trk_state.filtered().set_covariance(filtered_cov);
        trk_state.filtered_chi2() = matrix_operator().element(chi2, 0, 0);
        return;
    }
References traccc::e_bound_loc0, traccc::track_state< algebra_t >::filtered(), traccc::track_state< algebra_t >::filtered_chi2(), traccc::track_state< algebra_t >::get_measurement(), and traccc::track_state< algebra_t >::predicted().
The documentation for this struct was generated from the following file:
core/include/traccc/fitting/kalman_filter/gain_matrix_updater.hpp