traccc::detail Namespace Reference
Functions
TRACCC_HOST_DEVICE scalar signal_cell_modelling (scalar signal_in, const cell_module &)
Function used for retrieving the cell signal based on the module id.
TRACCC_HOST_DEVICE vector2 position_from_cell (const cell &cell, const cell_module &module)
Function for pixel segmentation.
template<typename cell_collection_t >
TRACCC_HOST void calc_cluster_properties (const cell_collection_t &cluster, const cell_module &module, point2 &mean, point2 &var, scalar &totalWeight)
TRACCC_HOST void fill_measurement (measurement_collection_types::host &measurements, const cell_collection_types::host &cluster, const cell_module &module, const unsigned int module_link)
template<typename ccl_vector_t >
TRACCC_HOST_DEVICE unsigned int find_root (const ccl_vector_t &L, unsigned int e)
template<typename ccl_vector_t >
TRACCC_HOST_DEVICE unsigned int make_union (ccl_vector_t &L, unsigned int e1, unsigned int e2)
TRACCC_HOST_DEVICE bool is_adjacent (traccc::cell a, traccc::cell b)
TRACCC_HOST_DEVICE bool is_far_enough (traccc::cell a, traccc::cell b)
template<typename cell_collection_t , typename ccl_vector_t >
TRACCC_HOST_DEVICE unsigned int sparse_ccl (const cell_collection_t &cells, ccl_vector_t &L)
template<typename value_t , typename converter_t >
void parse_variable (std::istream &is, std::vector< value_t > &values, converter_t &&convert)
template<typename value_t , typename converter_t >
void parse_fixed (std::istream &is, size_t size, value_t *values, converter_t &&convert)
Detailed Description
TRACCC library, part of the ACTS project (R&D line)
(c) 2021-2023 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
Implemementation of SparseCCL, following [DOI: 10.1109/DASIP48288.2019.9049184]
Requires cells to be sorted in column major
Function Documentation
calc_cluster_properties()
template<typename cell_collection_t >
TRACCC_HOST void traccc::detail::calc_cluster_properties (const cell_collection_t & cluster, const cell_module & module, point2 & mean, point2 & var, scalar & totalWeight) [inline]
Function used for calculating the properties of the cluster during measurement creation
Parameters
 in cluster The vector of cells describing the identified cluster
 in module The cell module
 out mean The mean position of the cluster/measurement
 out var The variation on the mean position of the cluster/measurement
 out totalWeight The total weight of the cluster/measurement
                                      {
    // Loop over the cells of the cluster.
    for (const cell& cell : cluster) {
        // Translate the cell readout value into a weight.
        const scalar weight = signal_cell_modelling(cell.activation, module);
        // Only consider cells over a minimum threshold.
        if (weight > module.threshold) {
            // Update all output properties with this cell.
            totalWeight += cell.activation;
            const point2 cell_position = position_from_cell(cell, module);
            const point2 prev = mean;
            const point2 diff = cell_position - prev;
            mean = prev + (weight / totalWeight) * diff;
            for (std::size_t i = 0; i < 2; ++i) {
                var[i] =
                    var[i] + weight * (diff[i]) * (cell_position[i] - mean[i]);
            }
        }
    }
}
References traccc::cell::activation, position_from_cell(), signal_cell_modelling(), and traccc::cell_module::threshold.
Referenced by fill_measurement().
fill_measurement()
TRACCC_HOST void traccc::detail::fill_measurement (measurement_collection_types::host & measurements, const cell_collection_types::host & cluster, const cell_module & module, const unsigned int module_link) [inline]
Function used for calculating the properties of the cluster during measurement creation
Parameters
 out measurements is the measurement collection where the measurement object will be filled
 in cluster is the input cell vector
 in module is the cell module where the cluster belongs to
 in module_link is the module index
                                    {
    // To calculate the mean and variance with high numerical stability
    // we use a weighted variant of Welford's algorithm. This is a
    // single-pass online algorithm that works well for large numbers
    // of samples, as well as samples with very high values.
    //
    // To learn more about this algorithm please refer to:
    // [1] https://doi.org/10.1080/00401706.1962.10490022
    // [2] The Art of Computer Programming, Donald E. Knuth, second
    // edition, chapter 4.2.2.
    // Calculate the cluster properties
    scalar totalWeight = 0.;
    point2 mean{0., 0.}, var{0., 0.};
    detail::calc_cluster_properties(cluster, module, mean, var, totalWeight);
    if (totalWeight > 0.) {
        measurement m;
        m.module_link = module_link;
        m.surface_link = module.surface_link;
        // normalize the cell position
        m.local = mean;
        // normalize the variance
        m.variance[0] = var[0] / totalWeight;
        m.variance[1] = var[1] / totalWeight;
        // plus pitch^2 / 12
        const auto pitch = module.pixel.get_pitch();
        m.variance =
            m.variance + point2{pitch[0] * pitch[0] / static_cast<scalar>(12.),
                                pitch[1] * pitch[1] / static_cast<scalar>(12.)};
        // @todo add variance estimation
        measurements.push_back(std::move(m));
    }
}
References calc_cluster_properties(), traccc::pixel_data::get_pitch(), traccc::measurement::local, traccc::measurement::module_link, traccc::cell_module::pixel, traccc::cell_module::surface_link, traccc::measurement::surface_link, and traccc::measurement::variance.
Referenced by traccc::measurement_creation::operator()().
find_root()
template<typename ccl_vector_t >
TRACCC_HOST_DEVICE unsigned int traccc::detail::find_root (const ccl_vector_t & L, unsigned int e) [inline]
Find root of the tree for entry
Parameters
e
L an equivalance table
Returns
the root of
Parameters
e
                                                                 {
    unsigned int r = e;
    assert(r < L.size());
    while (L[r] != r) {
        r = L[r];
        assert(r < L.size());
    }
    return r;
}
Referenced by sparse_ccl().
is_adjacent()
TRACCC_HOST_DEVICE bool traccc::detail::is_adjacent (traccc::cell a, traccc::cell b) [inline]
Helper method to find adjacent cells
Parameters
a the first cell
b the second cell
Returns
boolan to indicate 8-cell connectivity
                                                                       {
    return (a.channel0 - b.channel0) * (a.channel0 - b.channel0) <= 1 and
           (a.channel1 - b.channel1) * (a.channel1 - b.channel1) <= 1 and
           a.module_link == b.module_link;
}
References traccc::cell::channel0, traccc::cell::channel1, and traccc::cell::module_link.
Referenced by sparse_ccl().
is_far_enough()
TRACCC_HOST_DEVICE bool traccc::detail::is_far_enough (traccc::cell a, traccc::cell b) [inline]
Helper method to find define distance, does not need abs, as channels are sorted in column major
Parameters
a the first cell
b the second cell
Returns
boolan to indicate !8-cell connectivity
                                                                         {
    return (a.channel1 - b.channel1) > 1 || a.module_link != b.module_link;
}
References traccc::cell::channel1, and traccc::cell::module_link.
Referenced by sparse_ccl().
make_union()
template<typename ccl_vector_t >
TRACCC_HOST_DEVICE unsigned int traccc::detail::make_union (ccl_vector_t & L, unsigned int e1, unsigned int e2) [inline]
Create a union of two entries
Parameters
e1 and
e2
L an equivalance table
Returns
the rleast common ancestor of the entries
                                                                   {
    int e;
    if (e1 < e2) {
        e = e1;
        assert(e2 < L.size());
        L[e2] = e;
    } else {
        e = e2;
        assert(e1 < L.size());
        L[e1] = e;
    }
    return e;
}
Referenced by sparse_ccl().
parse_fixed()
template<typename value_t , typename converter_t >
void traccc::detail::parse_fixed (std::istream & is, size_t size, value_t * values, converter_t && convert)
                                        {
    // reserve space for the expected number of values
    std::vector<value_t> tmp(size, 0);
    parse_variable(is, tmp, std::forward<converter_t>(convert));
    if (tmp.size() < size) {
        throw std::invalid_argument(
            "Not enough values for fixed-size user option, expected " +
            std::to_string(size) + " received " + std::to_string(tmp.size()));
    }
    if (size < tmp.size()) {
        throw std::invalid_argument(
            "Too many values for fixed-size user option, expected " +
            std::to_string(size) + " received " + std::to_string(tmp.size()));
    }
    std::copy(tmp.begin(), tmp.end(), values);
}
References parse_variable().
Referenced by traccc::operator>>().
parse_variable()
template<typename value_t , typename converter_t >
void traccc::detail::parse_variable (std::istream & is, std::vector< value_t > & values, converter_t && convert)
                                           {
    values.clear();
    std::string buf;
    is >> buf;
    std::vector<std::string> stringValues;
    boost::split(stringValues, buf, boost::is_any_of(s_separator));
    for (const std::string& stringValue : stringValues) {
        values.push_back(convert(stringValue));
    }
}
Referenced by parse_fixed().
position_from_cell()
TRACCC_HOST_DEVICE vector2 traccc::detail::position_from_cell (const cell & cell, const cell_module & module) [inline]
Function for pixel segmentation.
                                                                               {
    // Retrieve the specific values based on module idx
    return {module.pixel.min_center_x + cell.channel0 * module.pixel.pitch_x,
            module.pixel.min_center_y + cell.channel1 * module.pixel.pitch_y};
}
References traccc::cell::channel0, traccc::cell::channel1, traccc::pixel_data::min_center_x, traccc::pixel_data::min_center_y, traccc::pixel_data::pitch_x, traccc::pixel_data::pitch_y, and traccc::cell_module::pixel.
Referenced by traccc::device::aggregate_cluster(), and calc_cluster_properties().
signal_cell_modelling()
TRACCC_HOST_DEVICE scalar traccc::detail::signal_cell_modelling (scalar signal_in, const cell_module &) [inline]
Function used for retrieving the cell signal based on the module id.
                                                          {
    return signal_in;
}
Referenced by traccc::device::aggregate_cluster(), and calc_cluster_properties().
sparse_ccl()
template<typename cell_collection_t , typename ccl_vector_t >
TRACCC_HOST_DEVICE unsigned int traccc::detail::sparse_ccl (const cell_collection_t & cells, ccl_vector_t & L) [inline]
Sparce CCL algorithm
Parameters
cells is the cell collection
L is the vector of the output indices (to which cluster a cell belongs to)
labels is the number of clusters found
Returns
number of clusters
                                                     {
    unsigned int labels = 0;
    // The number of cells.
    const unsigned int n_cells = cells.size();
    // first scan: pixel association
    unsigned int start_j = 0;
    for (unsigned int i = 0; i < n_cells; ++i) {
        L[i] = i;
        unsigned int ai = i;
        for (unsigned int j = start_j; j < i; ++j) {
            if (is_adjacent(cells[i], cells[j])) {
                ai = make_union(L, ai, find_root(L, j));
            } else if (is_far_enough(cells[i], cells[j])) {
                ++start_j;
            }
        }
    }
    // second scan: transitive closure
    for (unsigned int i = 0; i < n_cells; ++i) {
        if (L[i] == i) {
            L[i] = labels++;
        } else {
            L[i] = L[L[i]];
        }
    }
    return labels;
}
References find_root(), is_adjacent(), is_far_enough(), and make_union().
Referenced by traccc::component_connection::operator()().