traccc::details::is_same_object< spacepoint > Class Reference
traccc::is_same_object specialisation for traccc::spacepoint
Public Member Functions
 Implementation for @c traccc::details::is_same_object<spacepoint>
is_same_object (const spacepoint &ref, scalar unc=float_epsilon)
Constructor with a reference object, and an allowed uncertainty.
bool operator() (const spacepoint &obj) const
Specialised implementation for traccc::spacepoint.
Private Attributes
std::reference_wrapper< const spacepoint > m_ref
The reference object.
scalar m_unc
The uncertainty.
Detailed Description
traccc::is_same_object specialisation for traccc::spacepoint
Constructor & Destructor Documentation
is_same_object()
traccc::details::is_same_object< spacepoint >::is_same_object (const spacepoint & ref, scalar unc = float_epsilon)
Constructor with a reference object, and an allowed uncertainty.
    : m_ref(ref), m_unc(unc) {}
Member Function Documentation
operator()()
bool traccc::details::is_same_object< spacepoint >::operator() (const spacepoint & obj) const
Specialised implementation for traccc::spacepoint.
                                                                       {
    return (is_same_scalar(obj.x(), m_ref.get().x(), m_unc) &&
            is_same_scalar(obj.y(), m_ref.get().y(), m_unc) &&
            is_same_scalar(obj.z(), m_ref.get().z(), m_unc) &&
            is_same_object<measurement>(m_ref.get().meas, m_unc)(obj.meas));
}
References traccc::details::is_same_scalar(), traccc::details::is_same_object< T >::m_ref, traccc::spacepoint::meas, traccc::spacepoint::x(), traccc::spacepoint::y(), and traccc::spacepoint::z().
Member Data Documentation
m_ref
std::reference_wrapper<const spacepoint> traccc::details::is_same_object< spacepoint >::m_ref [private]
The reference object.
m_unc
scalar traccc::details::is_same_object< spacepoint >::m_unc [private]
The uncertainty.
The documentation for this class was generated from the following files:
performance/include/traccc/performance/impl/is_same_spacepoint.ipp
performance/src/performance/details/is_same_object.cpp