traccc::cuda::stream Class Reference
#include <stream.hpp>
Public Member Functions
stream (int device=INVALID_DEVICE)
Construct a new stream (possibly for a specified device)
stream (stream &&parent)
Move constructor.
~stream ()
Destructor.
stream & operator= (stream &&rhs)
Move assignment.
void * cudaStream () const
Access a typeless pointer to the managed cudaStream_t object.
void synchronize () const
Wait for all queued tasks from the stream to complete.
Static Public Attributes
static constexpr int INVALID_DEVICE = -1
Invalid/default device identifier.
Private Attributes
std::unique_ptr< details::opaque_stream > m_stream
Smart pointer to the managed cudaStream_t object.
Detailed Description
Owning wrapper class around cudaStream_t
It is necessary for passing around CUDA stream objects in code that should not be directly exposed to the CUDA header(s).
Constructor & Destructor Documentation
stream() [1/2]
traccc::cuda::stream::stream (int device = INVALID_DEVICE)
Construct a new stream (possibly for a specified device)
                         {
    // Make sure that the stream is constructed on the correct device.
    details::select_device dev_selector{
        device == INVALID_DEVICE ? details::get_device() : device};
    // Construct the stream.
    m_stream = std::make_unique<details::opaque_stream>();
}
References traccc::cuda::details::get_device(), INVALID_DEVICE, and m_stream.
stream() [2/2]
traccc::cuda::stream::stream (stream && parent)
Move constructor.
: m_stream(std::move(parent.m_stream)) {}
 stream()
traccc::cuda::stream::~stream ()
Destructor.
The destructor is implemented explicitly to avoid clients of the class having to know how to destruct traccc::cuda::details::opaque_stream.
{}
Member Function Documentation
cudaStream()
void * traccc::cuda::stream::cudaStream () const
Access a typeless pointer to the managed cudaStream_t object.
                               {
    return m_stream->m_stream;
}
References m_stream.
Referenced by traccc::cuda::details::get_stream(), main(), seq_run(), TEST(), and TEST_P().
operator=()
stream & traccc::cuda::stream::operator= (stream && rhs)
Move assignment.
                                      {
    // Avoid self-assignment.
    if (this == &rhs) {
        return *this;
    }
    // Move the managed queue object.
    m_stream = std::move(rhs.m_stream);
    // Return this object.
    return *this;
}
References m_stream.
synchronize()
void traccc::cuda::stream::synchronize () const
Wait for all queued tasks from the stream to complete.
                               {
    CUDA_ERROR_CHECK(cudaStreamSynchronize(m_stream->m_stream));
}
References CUDA_ERROR_CHECK, and m_stream.
Referenced by seq_run().
Member Data Documentation
INVALID_DEVICE
constexpr int traccc::cuda::stream::INVALID_DEVICE = -1 [static], [constexpr]
Invalid/default device identifier.
Referenced by stream().
m_stream
std::unique_ptr<details::opaque_stream> traccc::cuda::stream::m_stream [private]
Smart pointer to the managed cudaStream_t object.
Referenced by cudaStream(), operator=(), stream(), and synchronize().
The documentation for this class was generated from the following files:
device/cuda/include/traccc/cuda/utils/stream.hpp
device/cuda/src/utils/stream.cpp