traccc::array_wrapper< F, T >::handle Struct Reference
#include <array_wrapper.hpp>
Public Types
using handle_t = typename details::functor::reapply< F, typename T< details::functor::identity >::tuple_t >::type::handle
Public Member Functions
handle (const owner &o)
TRACCC_HOST_DEVICE std::size_t size () const
template<std::size_t I>
constexpr TRACCC_HOST_DEVICE auto & get (std::size_t i)
template<std::size_t I>
constexpr TRACCC_HOST_DEVICE auto get (std::size_t i) const
template<std::size_t... Ns>
constexpr TRACCC_HOST_DEVICE T< details::functor::identity > _construct_helper_identity (std::index_sequence< Ns... >, std::size_t i) const
template<std::size_t... Ns>
constexpr TRACCC_HOST_DEVICE T< details::functor::reference > _construct_helper_reference (std::index_sequence< Ns... >, std::size_t i)
constexpr TRACCC_HOST_DEVICE T< details::functor::identity > operator[] (std::size_t i) const
constexpr TRACCC_HOST_DEVICE T< details::functor::reference > operator[] (std::size_t i)
Public Attributes
handle_t data
Member Typedef Documentation
handle_t
template<template< typename... > typename F, template< template< typename > typename > typename T>
using traccc::array_wrapper< F, T >::handle::handle_t = typename details::functor::reapply< F, typename T<details::functor::identity>::tuple_t>::type::handle
Constructor & Destructor Documentation
handle()
template<template< typename... > typename F, template< template< typename > typename > typename T>
traccc::array_wrapper< F, T >::handle::handle (const owner & o) [inline]
: data(o.data) {}
Member Function Documentation
_construct_helper_identity()
template<template< typename... > typename F, template< template< typename > typename > typename T>
template<std::size_t... Ns>
constexpr TRACCC_HOST_DEVICE T<details::functor::identity> traccc::array_wrapper< F, T >::handle::_construct_helper_identity (std::index_sequence< Ns... > , std::size_t i) const [inline], [constexpr]
                                                      {
            return T<details::functor::identity>{get<Ns>(i)...};
        }
Referenced by traccc::array_wrapper< F, T >::handle::operator[]().
_construct_helper_reference()
template<template< typename... > typename F, template< template< typename > typename > typename T>
template<std::size_t... Ns>
constexpr TRACCC_HOST_DEVICE T<details::functor::reference> traccc::array_wrapper< F, T >::handle::_construct_helper_reference (std::index_sequence< Ns... > , std::size_t i) [inline], [constexpr]
                                                                           {
            return T<details::functor::reference>{get<Ns>(i)...};
        }
Referenced by traccc::array_wrapper< F, T >::handle::operator[]().
get() [1/2]
template<template< typename... > typename F, template< template< typename > typename > typename T>
template<std::size_t I>
constexpr TRACCC_HOST_DEVICE auto& traccc::array_wrapper< F, T >::handle::get (std::size_t i) [inline], [constexpr]
                                                            {
            return data.get<I>(i);
        }
References traccc::array_wrapper< F, T >::handle::data.
get() [2/2]
template<template< typename... > typename F, template< template< typename > typename > typename T>
template<std::size_t I>
constexpr TRACCC_HOST_DEVICE auto traccc::array_wrapper< F, T >::handle::get (std::size_t i) const [inline], [constexpr]
                                                                 {
            return data.get<I>(i);
        }
References traccc::array_wrapper< F, T >::handle::data.
operator[]() [1/2]
template<template< typename... > typename F, template< template< typename > typename > typename T>
constexpr TRACCC_HOST_DEVICE T<details::functor::reference> traccc::array_wrapper< F, T >::handle::operator[] (std::size_t i) [inline], [constexpr]
                         {
            return _construct_helper_reference(
                std::make_index_sequence<std::tuple_size_v<
                    typename T<details::functor::identity>::tuple_t>>(),
                i);
        }
References traccc::array_wrapper< F, T >::handle::_construct_helper_reference().
operator[]() [2/2]
template<template< typename... > typename F, template< template< typename > typename > typename T>
constexpr TRACCC_HOST_DEVICE T<details::functor::identity> traccc::array_wrapper< F, T >::handle::operator[] (std::size_t i) const [inline], [constexpr]
                               {
            return _construct_helper_identity(
                std::make_index_sequence<std::tuple_size_v<
                    typename T<details::functor::identity>::tuple_t>>(),
                i);
        }
References traccc::array_wrapper< F, T >::handle::_construct_helper_identity().
size()
template<template< typename... > typename F, template< template< typename > typename > typename T>
TRACCC_HOST_DEVICE std::size_t traccc::array_wrapper< F, T >::handle::size () const [inline]
{ return data.size(); }
References traccc::array_wrapper< F, T >::handle::data.
Member Data Documentation
data
template<template< typename... > typename F, template< template< typename > typename > typename T>
handle_t traccc::array_wrapper< F, T >::handle::data
Referenced by traccc::array_wrapper< F, T >::handle::get(), and traccc::array_wrapper< F, T >::handle::size().
The documentation for this struct was generated from the following file:
core/include/traccc/utils/array_wrapper.hpp