traccc::alpaka::PopulateGridKernel Struct Reference
Public Member Functions
template<typename Acc >
ALPAKA_FN_ACC void operator() (Acc const &acc, const seedfinder_config &config, const spacepoint_collection_types::const_view &spacepoints_view, sp_grid_view *grid_view) const
Member Function Documentation
operator()()
template<typename Acc >
ALPAKA_FN_ACC void traccc::alpaka::PopulateGridKernel::operator() (Acc const & acc, const seedfinder_config & config, const spacepoint_collection_types::const_view & spacepoints_view, sp_grid_view * grid_view) const [inline]
Check out if the spacepoint can be used for seeding.
                                       {
        auto const globalThreadIdx =
            ::alpaka::getIdx<::alpaka::Grid, ::alpaka::Threads>(acc)[0u];
        // Check if anything needs to be done.
        const spacepoint_collection_types::const_device spacepoints(
            spacepoints_view);
        if (globalThreadIdx >= spacepoints.size()) {
            return;
        }
        const spacepoint sp = spacepoints.at(globalThreadIdx);
        if (is_valid_sp(config, sp) !=
            detray::detail::invalid_value<size_t>()) {
            // Set up the spacepoint grid object(s).
            sp_grid_device grid(*grid_view);
            const sp_grid_device::axis_p0_type& phi_axis = grid.axis_p0();
            const sp_grid_device::axis_p1_type& z_axis = grid.axis_p1();
            // Find the grid bin that the spacepoint belongs to.
            const internal_spacepoint<spacepoint> isp(sp, globalThreadIdx,
                                                      config.beamPos);
            const std::size_t bin_index =
                phi_axis.bin(isp.phi()) + phi_axis.bins() * z_axis.bin(isp.z());
            // Add the spacepoint to the grid.
            grid.bin(bin_index).push_back(std::move(isp));
        }
    }
References traccc::seedfinder_config::beamPos, traccc::is_valid_sp(), traccc::internal_spacepoint< spacepoint_t >::phi(), and traccc::internal_spacepoint< spacepoint_t >::z().
The documentation for this struct was generated from the following file:
device/alpaka/src/seeding/spacepoint_binning.cpp