traccc::io::details Namespace Reference
Functions
std::map< geometry_id, transform3 > read_surfaces (std::string_view filename, data_format format=data_format::csv)
template<typename container_t >
container_t read_binary_container (std::string_view filename, vecmem::memory_resource *mr=nullptr)
template<typename collection_t >
void read_binary_collection (collection_t &result, std::string_view filename)
template<typename container_t >
void write_binary_container (std::string_view filename, const container_t &container)
template<typename collection_t >
void write_binary_collection (std::string_view filename, const collection_t &collection)
Detailed Description
TRACCC library, part of the ACTS project (R&D line)
(c) 2022 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
Function Documentation
read_binary_collection()
template<typename collection_t >
void traccc::io::details::read_binary_collection (collection_t & result, std::string_view filename)
Function for reading a collection from a binary file
Parameters
filename The full input filename
mr Is the memory resource to create the result collection with
                                                                           {
    // Make sure that the chosen types work.
    static_assert(std::is_standard_layout_v<typename collection_t::value_type>,
                  "Collection item type must be standard layout.");
    // Open the input file.
    std::ifstream in_file(filename.data(), std::ios::binary);
    // Read the size of the header vector.
    std::size_t size;
    in_file.read(reinterpret_cast<char*>(&size), sizeof(std::size_t));
    // Set result to the correct size.
    result.resize(size);
    // Read the items into memory.
    in_file.read(reinterpret_cast<char*>(result.data()),
                 size * sizeof(typename collection_t::value_type));
}
References traccc::binary.
read_binary_container()
template<typename container_t >
container_t traccc::io::details::read_binary_container (std::string_view filename, vecmem::memory_resource * mr = nullptr)
Function for reading a container from a binary file
Parameters
filename The full input filename
mr Is the memory resource to create the result container with
TODO: Change container reading to not own its result object
                                                                       {
    // Make sure that the chosen types work.
    static_assert(std::is_standard_layout_v<typename container_t::header_type>,
                  "Container header type must be standard layout.");
    static_assert(std::is_standard_layout_v<typename container_t::item_type>,
                  "Container item type must be standard layout.");
    // Open the input file.
    std::ifstream in_file(filename.data(), std::ios::binary);
    // Read the size of the header vector.
    std::size_t headers_size;
    in_file.read(reinterpret_cast<char*>(&headers_size), sizeof(std::size_t));
    // Read the sizes of the item vector.
    std::vector<std::size_t> items_size(headers_size);
    in_file.read(reinterpret_cast<char*>(items_size.data()),
                 headers_size * sizeof(typename std::size_t));
    // Create the result container, and set it to the correct (outer) size right
    // away.
    container_t result(headers_size, mr);
    // Read the header payload into memory.
    in_file.read(reinterpret_cast<char*>(result.get_headers().data()),
                 headers_size * sizeof(typename container_t::header_type));
    // Read the items in multiple steps.
    for (std::size_t i = 0; i < headers_size; ++i) {
        result.get_items().at(i).resize(items_size.at(i));
        in_file.read(
            reinterpret_cast<char*>(result.get_items().at(i).data()),
            items_size.at(i) * sizeof(typename container_t::item_type));
    }
    // Return the newly created container.
    return result;
}
References traccc::binary.
read_surfaces()
std::map< geometry_id, transform3 > traccc::io::details::read_surfaces (std::string_view filename, data_format format = data_format::csv)
Read the geometry information for the modules into a map
Parameters
filename The file to read the information from
format The format of the input file
Returns
A map of transformations for each geometry ID
                                                                    {
    // Decide how to read the file.
    switch (format) {
        case data_format::csv:
            return csv::read_surfaces(filename);
        default:
            throw std::invalid_argument("Unsupported data format");
    }
}
References traccc::csv, and traccc::io::csv::read_surfaces().
Referenced by traccc::io::read_geometry(), TEST(), and TEST_F().
write_binary_collection()
template<typename collection_t >
void traccc::io::details::write_binary_collection (std::string_view filename, const collection_t & collection)
Function for writing a collection into a binary file
Parameters
filename is the output filename which includes the path
collection is the traccc collection to write
                                                             {
    // Make sure that the chosen types work.
    static_assert(std::is_standard_layout_v<typename collection_t::value_type>,
                  "Collection item type must have standard layout.");
    // Open the output file.
    std::ofstream out_file(filename.data(), std::ios::binary);
    // Write the size of the vector.
    const std::size_t size = collection.size();
    out_file.write(reinterpret_cast<const char*>(&size), sizeof(std::size_t));
    // Write the items.
    out_file.write(reinterpret_cast<const char*>(collection.data()),
                   size * sizeof(typename collection_t::value_type));
}
References traccc::binary.
Referenced by traccc::io::write().
write_binary_container()
template<typename container_t >
void traccc::io::details::write_binary_container (std::string_view filename, const container_t & container)
Function for writing a container into a binary file
Parameters
filename is the output filename which includes the path
container is the traccc container to write
                                                          {
    // Make sure that the chosen types work.
    static_assert(std::is_standard_layout_v<typename container_t::header_type>,
                  "Container header type must have standard layout.");
    static_assert(std::is_standard_layout_v<typename container_t::item_type>,
                  "Container item type must have standard layout.");
    // Open the output file.
    std::ofstream out_file(filename.data(), std::ios::binary);
    // Write the size of the header vector.
    const std::size_t headers_size = container.size();
    out_file.write(reinterpret_cast<const char*>(&headers_size),
                   sizeof(std::size_t));
    // Write the sizes of the item vectors.
    std::vector<std::size_t> item_sizes;
    item_sizes.reserve(headers_size);
    for (const typename container_t::item_vector::value_type& i :
         container.get_items()) {
        item_sizes.push_back(i.size());
    }
    out_file.write(reinterpret_cast<const char*>(item_sizes.data()),
                   headers_size * sizeof(std::size_t));
    // Write header elements.
    out_file.write(
        reinterpret_cast<const char*>(container.get_headers().data()),
        container.get_headers().size() *
            sizeof(typename container_t::header_type));
    // Write the items.
    for (const typename container_t::item_vector::value_type& i :
         container.get_items()) {
        out_file.write(reinterpret_cast<const char*>(i.data()),
                       i.size() * sizeof(typename container_t::item_type));
    }
}
References traccc::binary.