traccc::spacepoint_binning Class Reference
spacepoint binning
#include <spacepoint_binning.hpp>
Public Member Functions
spacepoint_binning (const seedfinder_config &config, const spacepoint_grid_config &grid_config, vecmem::memory_resource &mr)
output_type operator() (const spacepoint_collection_types::host &sp_collection) const override
Private Attributes
seedfinder_config m_config
spacepoint_grid_config m_grid_config
std::pair< output_type::axis_p0_type, output_type::axis_p1_type > m_axes
std::reference_wrapper< vecmem::memory_resource > m_mr
Detailed Description
spacepoint binning
Constructor & Destructor Documentation
spacepoint_binning()
traccc::spacepoint_binning::spacepoint_binning (const seedfinder_config & config, const spacepoint_grid_config & grid_config, vecmem::memory_resource & mr)
Constructor for the spacepoint binning
Parameters
config is seed finder configuration parameters
grid_config is for spacepoint grid parameter
mr is the vecmem memory resource
    : m_config(config),
      m_grid_config(grid_config),
      m_axes(get_axes(grid_config, mr)),
      m_mr(mr) {}
Member Function Documentation
operator()()
spacepoint_binning::output_type traccc::spacepoint_binning::operator() (const spacepoint_collection_types::host & sp_collection) const [override]
Operator executing the algorithm
Parameters
sp_collection All of the spacepoints of the event
Returns
The spacepoints arranged in a Phi-Z grid
                                                                {
    output_type g2(m_axes.first, m_axes.second, m_mr.get());
    auto& phi_axis = g2.axis_p0();
    auto& z_axis = g2.axis_p1();
    for (unsigned int i = 0; i < sp_collection.size(); i++) {
        const spacepoint& sp = sp_collection[i];
        internal_spacepoint<spacepoint> isp(sp, i, m_config.beamPos);
        if (is_valid_sp(m_config, sp) !=
            detray::detail::invalid_value<size_t>()) {
            const std::size_t bin_index =
                phi_axis.bin(isp.phi()) + phi_axis.bins() * z_axis.bin(isp.z());
            g2.bin(bin_index).push_back(std::move(isp));
        }
    }
    return g2;
}
References traccc::seedfinder_config::beamPos, traccc::is_valid_sp(), m_axes, m_config, m_mr, traccc::internal_spacepoint< spacepoint_t >::phi(), and traccc::internal_spacepoint< spacepoint_t >::z().
Member Data Documentation
m_axes
std::pair<output_type::axis_p0_type, output_type::axis_p1_type> traccc::spacepoint_binning::m_axes [private]
Referenced by operator()().
m_config
seedfinder_config traccc::spacepoint_binning::m_config [private]
Referenced by operator()().
m_grid_config
spacepoint_grid_config traccc::spacepoint_binning::m_grid_config [private]
m_mr
std::reference_wrapper<vecmem::memory_resource> traccc::spacepoint_binning::m_mr [private]
Referenced by operator()().
The documentation for this class was generated from the following files:
core/include/traccc/seeding/spacepoint_binning.hpp
core/src/seeding/spacepoint_binning.cpp