traccc::doublet_finding_helper Struct Reference
#include <doublet_finding_helper.hpp>
Public Member Functions
template<details::spacepoint_type otherSpType>
bool isCompatible (const internal_spacepoint< spacepoint > &sp1, const internal_spacepoint< spacepoint > &sp2, const seedfinder_config &config)
template<details::spacepoint_type otherSpType>
lin_circle transform_coordinates (const internal_spacepoint< spacepoint > &sp1, const internal_spacepoint< spacepoint > &sp2)
Static Public Member Functions
template<details::spacepoint_type otherSpType>
static TRACCC_HOST_DEVICE bool isCompatible (const internal_spacepoint< spacepoint > &sp1, const internal_spacepoint< spacepoint > &sp2, const seedfinder_config &config)
template<details::spacepoint_type otherSpType>
static TRACCC_HOST_DEVICE lin_circle transform_coordinates (const internal_spacepoint< spacepoint > &sp1, const internal_spacepoint< spacepoint > &sp2)
Member Function Documentation
isCompatible() [1/2]
template<details::spacepoint_type otherSpType>
static TRACCC_HOST_DEVICE bool traccc::doublet_finding_helper::isCompatible (const internal_spacepoint< spacepoint > & sp1, const internal_spacepoint< spacepoint > & sp2, const seedfinder_config & config) [inline], [static]
Check if two spacepoints form doublets
Parameters
sp1 is middle spacepoint
sp2 is bottom or top spacepoint
config is configuration parameter
Template Parameters
otherSpType is whether it is for middle-bottom or middle-top doublet
Returns
boolean value for compatibility
Referenced by traccc::device::count_doublets(), and traccc::device::find_doublets().
isCompatible() [2/2]
template<details::spacepoint_type otherSpType>
bool traccc::doublet_finding_helper::isCompatible (const internal_spacepoint< spacepoint > & sp1, const internal_spacepoint< spacepoint > & sp2, const seedfinder_config & config)
                                     {
    static_assert(otherSpType == details::spacepoint_type::bottom ||
                  otherSpType == details::spacepoint_type::top);
    if constexpr (otherSpType == details::spacepoint_type::bottom) {
        // check if R distance is too small, because bins are not R-sorted
        scalar deltaR = sp1.radius() - sp2.radius();
        // actually cotTheta * deltaR to avoid division by 0 statements
        scalar cotTheta = sp1.z() - sp2.z();
        // actually zOrigin * deltaR to avoid division by 0 statements
        scalar zOrigin = sp1.z() * deltaR - sp1.radius() * cotTheta;
        if (deltaR > config.deltaRMax || deltaR < config.deltaRMin ||
            std::fabs(cotTheta) > config.cotThetaMax * deltaR ||
            zOrigin < config.collisionRegionMin * deltaR ||
            zOrigin > config.collisionRegionMax * deltaR) {
            return false;
        }
    } else {
        // check if R distance is too small, because bins are not R-sorted
        scalar deltaR = sp2.radius() - sp1.radius();
        // actually cotTheta * deltaR to avoid division by 0 statements
        scalar cotTheta = (sp2.z() - sp1.z());
        // actually zOrigin * deltaR to avoid division by 0 statements
        scalar zOrigin = sp1.z() * deltaR - sp1.radius() * cotTheta;
        if (deltaR > config.deltaRMax || deltaR < config.deltaRMin ||
            std::fabs(cotTheta) > config.cotThetaMax * deltaR ||
            zOrigin < config.collisionRegionMin * deltaR ||
            zOrigin > config.collisionRegionMax * deltaR) {
            return false;
        }
    }
    return true;
}
References traccc::details::bottom, traccc::seedfinder_config::collisionRegionMax, traccc::seedfinder_config::collisionRegionMin, traccc::seedfinder_config::cotThetaMax, traccc::seedfinder_config::deltaRMax, traccc::seedfinder_config::deltaRMin, traccc::internal_spacepoint< spacepoint_t >::radius(), traccc::details::top, and traccc::internal_spacepoint< spacepoint_t >::z().
transform_coordinates() [1/2]
template<details::spacepoint_type otherSpType>
static TRACCC_HOST_DEVICE lin_circle traccc::doublet_finding_helper::transform_coordinates (const internal_spacepoint< spacepoint > & sp1, const internal_spacepoint< spacepoint > & sp2) [inline], [static]
Do the conformal transformation on doublet's coordinate
Parameters
sp1 is middle spacepoint
sp2 is bottom or top spacepoint
Template Parameters
otherSpType is whether it is for middle-bottom or middle-top doublet
@reutrn lin_circle which contains the transformed coordinate information
Referenced by traccc::device::count_triplets(), traccc::device::find_triplets(), and traccc::doublet_finding< details::spacepoint_type::bottom >::operator()().
transform_coordinates() [2/2]
template<details::spacepoint_type otherSpType>
lin_circle traccc::doublet_finding_helper::transform_coordinates (const internal_spacepoint< spacepoint > & sp1, const internal_spacepoint< spacepoint > & sp2)
                                                {
    static_assert(otherSpType == details::spacepoint_type::bottom ||
                  otherSpType == details::spacepoint_type::top);
    const scalar& xM = sp1.x();
    const scalar& yM = sp1.y();
    const scalar& zM = sp1.z();
    const scalar& rM = sp1.radius();
    const scalar& varianceZM = sp1.varianceZ();
    const scalar& varianceRM = sp1.varianceR();
    scalar cosPhiM = xM / rM;
    scalar sinPhiM = yM / rM;
    scalar deltaX = sp2.x() - xM;
    scalar deltaY = sp2.y() - yM;
    scalar deltaZ = sp2.z() - zM;
    // calculate projection fraction of spM->sp vector pointing in same
    // direction as
    // vector origin->spM (x) and projection fraction of spM->sp vector pointing
    // orthogonal to origin->spM (y)
    scalar x = deltaX * cosPhiM + deltaY * sinPhiM;
    scalar y = deltaY * cosPhiM - deltaX * sinPhiM;
    // 1/(length of M -> SP)
    scalar iDeltaR2 =
        static_cast<scalar>(1.) / (deltaX * deltaX + deltaY * deltaY);
    scalar iDeltaR = std::sqrt(iDeltaR2);
    // cot_theta = (deltaZ/deltaR)
    scalar cot_theta = deltaZ * iDeltaR;
    if constexpr (otherSpType == details::spacepoint_type::bottom) {
        cot_theta = -cot_theta;
    }
    // VERY frequent (SP^3) access
    lin_circle l;
    l.m_cotTheta = cot_theta;
    // location on z-axis of this SP-duplet
    l.m_Zo = zM - rM * cot_theta;
    l.m_iDeltaR = iDeltaR;
    // transformation of circle equation (x,y) into linear equation (u,v)
    // x^2 + y^2 - 2x_0*x - 2y_0*y = 0
    // is transformed into
    // 1 - 2x_0*u - 2y_0*v = 0
    // using the following m_U and m_V
    // (u = A + B*v); A and B are created later on
    l.m_U = x * iDeltaR2;
    l.m_V = y * iDeltaR2;
    // error term for sp-pair without correlation of middle space point
    l.m_Er = ((varianceZM + sp2.varianceZ()) +
              (cot_theta * cot_theta) * (varianceRM + sp2.varianceR())) *
             iDeltaR2;
    return l;
}
References traccc::details::bottom, traccc::lin_circle::m_cotTheta, traccc::lin_circle::m_Er, traccc::lin_circle::m_iDeltaR, traccc::lin_circle::m_U, traccc::lin_circle::m_V, traccc::lin_circle::m_Zo, traccc::internal_spacepoint< spacepoint_t >::radius(), traccc::details::top, traccc::internal_spacepoint< spacepoint_t >::varianceR(), traccc::internal_spacepoint< spacepoint_t >::varianceZ(), traccc::internal_spacepoint< spacepoint_t >::x(), traccc::internal_spacepoint< spacepoint_t >::y(), and traccc::internal_spacepoint< spacepoint_t >::z().
The documentation for this struct was generated from the following file:
core/include/traccc/seeding/doublet_finding_helper.hpp