examples/run/cpu/seq_example.cpp File Reference
#include `traccc/io/read_cells.hpp`
#include `traccc/io/read_digitization_config.hpp`
#include `traccc/io/read_geometry.hpp`
#include `traccc/clusterization/clusterization_algorithm.hpp`
#include `traccc/clusterization/spacepoint_formation.hpp`
#include `traccc/seeding/seeding_algorithm.hpp`
#include `traccc/seeding/track_params_estimation.hpp`
#include `traccc/efficiency/seeding_performance_writer.hpp`
#include `traccc/options/common_options.hpp`
#include `traccc/options/detector_input_options.hpp`
#include `traccc/options/full_tracking_input_options.hpp`
#include `traccc/options/handle_argument_errors.hpp`
#include <vecmem/memory/host_memory_resource.hpp>
#include <exception>
#include <iostream>
Functions
int seq_run (const traccc::full_tracking_input_config &i_cfg, const traccc::common_options &common_opts, const traccc::detector_input_options &det_opts)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
                                 {
    // Set up the program options
    po::options_description desc("Allowed options");
    // Add options
    desc.add_options()("help,h", "Give some help with the program's options");
    traccc::common_options common_opts(desc);
    traccc::detector_input_options det_opts(desc);
    traccc::full_tracking_input_config full_tracking_input_cfg(desc);
    po::variables_map vm;
    po::store(po::parse_command_line(argc, argv, desc), vm);
    // Check errors
    traccc::handle_argument_errors(vm, desc);
    // Read options
    common_opts.read(vm);
    det_opts.read(vm);
    full_tracking_input_cfg.read(vm);
    std::cout << "Running " << argv[0] << " "
              << full_tracking_input_cfg.detector_file << " "
              << common_opts.input_directory << " " << common_opts.events
              << std::endl;
    return seq_run(full_tracking_input_cfg, common_opts, det_opts);
}
References traccc::full_tracking_input_config::detector_file, traccc::common_options::events, traccc::handle_argument_errors(), traccc::common_options::input_directory, traccc::full_tracking_input_config::read(), traccc::detector_input_options::read(), traccc::common_options::read(), and seq_run().
seq_run()
int seq_run (const traccc::full_tracking_input_config & i_cfg, const traccc::common_options & common_opts, const traccc::detector_input_options & det_opts)
TRACCC library, part of the ACTS project (R&D line)
(c) 2021-2023 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
                                                          {
    // Read the surface transforms
    auto surface_transforms = traccc::io::read_geometry(det_opts.detector_file);
    // Read the digitization configuration file
    auto digi_cfg =
        traccc::io::read_digitization_config(i_cfg.digitization_config_file);
    // Output stats
    uint64_t n_cells = 0;
    uint64_t n_modules = 0;
    uint64_t n_measurements = 0;
    uint64_t n_spacepoints = 0;
    uint64_t n_seeds = 0;
    // Configs
    traccc::seedfinder_config finder_config;
    traccc::spacepoint_grid_config grid_config(finder_config);
    traccc::seedfilter_config filter_config;
    // Memory resource used by the EDM.
    vecmem::host_memory_resource host_mr;
    traccc::clusterization_algorithm ca(host_mr);
    traccc::spacepoint_formation sf(host_mr);
    traccc::seeding_algorithm sa(finder_config, grid_config, filter_config,
                                 host_mr);
    traccc::track_params_estimation tp(host_mr);
    // performance writer
    traccc::seeding_performance_writer sd_performance_writer(
        traccc::seeding_performance_writer::config{});
    // Loop over events
    for (unsigned int event = common_opts.skip;
         event < common_opts.events + common_opts.skip; ++event) {
        traccc::io::cell_reader_output readOut(&host_mr);
        // Read the cells from the relevant event file
        traccc::io::read_cells(readOut, event, common_opts.input_directory,
                               common_opts.input_data_format,
                               &surface_transforms, &digi_cfg);
        traccc::cell_collection_types::host& cells_per_event = readOut.cells;
        traccc::cell_module_collection_types::host& modules_per_event =
            readOut.modules;
        /*-------------------
            Clusterization
          -------------------*/
        auto measurements_per_event = ca(cells_per_event, modules_per_event);
        /*------------------------
            Spacepoint formation
          ------------------------*/
        auto spacepoints_per_event =
            sf(measurements_per_event, modules_per_event);
        /*-----------------------
          Seeding algorithm
          -----------------------*/
        auto seeds = sa(spacepoints_per_event);
        /*----------------------------
          Track params estimation
          ----------------------------*/
        auto params = tp(spacepoints_per_event, seeds,
                         {0.f, 0.f, finder_config.bFieldInZ});
        /*----------------------------
          Statistics
          ----------------------------*/
        n_modules += modules_per_event.size();
        n_cells += cells_per_event.size();
        n_measurements += measurements_per_event.size();
        n_spacepoints += spacepoints_per_event.size();
        n_seeds += seeds.size();
        /*------------
             Writer
          ------------*/
        if (common_opts.check_performance) {
            traccc::event_map evt_map(
                event, det_opts.detector_file, i_cfg.digitization_config_file,
                common_opts.input_directory, common_opts.input_directory,
                common_opts.input_directory, host_mr);
            sd_performance_writer.write(vecmem::get_data(seeds),
                                        vecmem::get_data(spacepoints_per_event),
                                        evt_map);
        }
    }
    if (common_opts.check_performance) {
        sd_performance_writer.finalize();
    }
    std::cout << "==> Statistics ... " << std::endl;
    std::cout << "- read " << n_cells << " cells from " << n_modules
              << " modules" << std::endl;
    std::cout << "- created " << n_measurements << " measurements. "
              << std::endl;
    std::cout << "- created " << n_spacepoints << " space points. "
              << std::endl;
    std::cout << "- created " << n_seeds << " seeds" << std::endl;
    return 0;
}
References traccc::seedfinder_config::bFieldInZ, traccc::io::cell_reader_output::cells, traccc::common_options::check_performance, traccc::detector_input_options::detector_file, traccc::full_tracking_input_config::digitization_config_file, event, traccc::common_options::events, traccc::get_data(), traccc::common_options::input_data_format, traccc::common_options::input_directory, traccc::io::cell_reader_output::modules, traccc::io::read_cells(), traccc::io::read_digitization_config(), traccc::io::read_geometry(), and traccc::common_options::skip.
Referenced by main().