ccl_generator Namespace Reference
Functions
def neighbourhood (p, m)
def rand (d)
def generate_file (name, Md, Hd, size, N)
Variables
parser = argparse.ArgumentParser(description=`Generate some CCL examples`)
type
help
default
args = parser.parse_args()
hits_dist = scipy.stats.lognorm(args.Ms, scale=math.exp(args.Mm))
cell_dist = scipy.stats.lognorm(args.Hs, scale=math.exp(args.Hm))
Function Documentation
generate_file()
def ccl_generator.generate_file (name, Md, Hd, size, N)
def generate_file(name, Md, Hd, size, N):
    print("Generating file %s..." % name)
    with open(name, "w") as f:
        h = 0
        w = csv.DictWriter(
            f,
            fieldnames=[
                "geometry_id",
                "hit_id",
                "channel0",
                "channel1",
                "timestamp",
                "value",
            ],
            lineterminator="\n",
        )
        w.writeheader()
        for m in range(N):
            acts = 0
            hits = rand(Md)
            points = set()
            for q in range(hits):
                cells = rand(Hd)
                center = (random.randint(0, size - 1), random.randint(0, size - 1))
                cands = [center]
                seen = set()
                for c in range(cells):
                    if not cands:
                        break
                    p = random.choice(cands)
                    if p not in points:
                        w.writerow(
                            {
                                "geometry_id": m,
                                "hit_id": h,
                                "channel0": p[0],
                                "channel1": p[1],
                                "timestamp": 0,
                                "value": random.uniform(0.1, 1.0),
                            }
                        )
                    acts += 1
                    seen.add(p)
                    cands += neighbourhood(p, size)
                    cands = [x for x in cands if x not in seen and x not in points]
                h += 1
                points |= seen
References neighbourhood(), rand(), and set().
neighbourhood()
def ccl_generator.neighbourhood (p, m)
def neighbourhood(p, m):
    return [
        (x, y)
        for (x, y) in [
            (p[0] + 1, p[1]),
            (p[0] - 1, p[1]),
            (p[0] + 1, p[1] - 1),
            (p[0] - 1, p[1] - 1),
            (p[0] + 1, p[1] + 1),
            (p[0] - 1, p[1] + 1),
            (p[0], p[1] - 1),
            (p[0], p[1] + 1),
        ]
        if x >= 0 and y >= 0 and x < m and y < m
    ]
Referenced by generate_file().
rand()
def ccl_generator.rand (d)
def rand(d):
    return int(round(d.rvs()))
Referenced by generate_file(), traccc.throughput_mt(), and traccc.throughput_st().
Variable Documentation
args
ccl_generator.args = parser.parse_args()
Referenced by traccc::futhark::wrapper< T, std::tuple< IArgs... >, std::tuple< OArgs... > >.run(), and traccc::futhark::wrapper< T, std::tuple< IArgs... >, std::tuple< OArgs... > >.run_helper().
cell_dist
ccl_generator.cell_dist = scipy.stats.lognorm(args.Hs, scale=math.exp(args.Hm))
default
ccl_generator.default
help
ccl_generator.help
hits_dist
ccl_generator.hits_dist = scipy.stats.lognorm(args.Ms, scale=math.exp(args.Mm))
parser
ccl_generator.parser = argparse.ArgumentParser(description=`Generate some CCL examples`)
type
ccl_generator.type
Referenced by traccc::device::container_d2h_copy_alg< CONTAINER_TYPES >.operator()().