traccc::kokkos Namespace Reference
Classes
class spacepoint_binning
Spacepoing binning executed on a Kokkos device.
Typedefs
using ExecSpace = MemSpace::execution_space
using range_policy = Kokkos::RangePolicy< ExecSpace >
typedef Kokkos::TeamPolicy< ExecSpace > team_policy
typedef Kokkos::TeamPolicy< ExecSpace >::member_type member_type
Functions
vecmem::data::vector_buffer< device::prefix_sum_element_t > make_prefix_sum_buff (const std::vector< device::prefix_sum_size_t > &sizes, vecmem::copy &copy, const traccc::memory_resource &mr)
Detailed Description
TRACCC library, part of the ACTS project (R&D line)
(c) 2021-2022 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
TRACCC library, part of the ACTS project (R&D line)
(c) 2021 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
TRACCC library, part of the ACTS project (R&D line)
(c) 2022 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
Typedef Documentation
ExecSpace
using traccc::kokkos::ExecSpace = typedef MemSpace::execution_space
member_type
typedef Kokkos::TeamPolicy<ExecSpace>::member_type traccc::kokkos::member_type
range_policy
using traccc::kokkos::range_policy = typedef Kokkos::RangePolicy<ExecSpace>
team_policy
typedef Kokkos::TeamPolicy<ExecSpace> traccc::kokkos::team_policy
Function Documentation
make_prefix_sum_buff()
vecmem::data::vector_buffer< device::prefix_sum_element_t > traccc::kokkos::make_prefix_sum_buff (const std::vector< device::prefix_sum_size_t > & sizes, vecmem::copy & copy, const traccc::memory_resource & mr)
Function that returns vector of prefix_sum_element_t for accessing a jagged vector's elements in device Example: Jagged vector with sizes = {3,2,1,...} Returns: {[0,0], [0,1], [0,2], [1,0], [1,1], [2,0], ...}
Parameters
 in sizes The sizes of the jagged vector
   copy A `copy object` capable of dealing with the view
Returns
A vector buffer of prefix_sum element
                                     {
    const device::prefix_sum_buffer_t make_sum_result =
        device::make_prefix_sum_buffer(sizes, copy, mr);
    const vecmem::data::vector_view<const device::prefix_sum_size_t>
        sizes_sum_view = make_sum_result.view;
    const unsigned int totalSize = make_sum_result.totalSize;
    // Create buffer and view objects for prefix sum vector
    vecmem::data::vector_buffer<device::prefix_sum_element_t> prefix_sum_buff(
        totalSize, mr.main);
    copy.setup(prefix_sum_buff);
    // Fill the prefix sum vector
    // kernels::fill_prefix_sum<<<(sizes_sum_view.size() / 32) + 1, 32>>>(
    // sizes_sum_view, prefix_sum_buff);
    uint64_t num_blocks = (sizes_sum_view.size() / 32) + 1;
    uint64_t num_threads = 32;
    auto data_prefix_sum_buff = vecmem::get_data(prefix_sum_buff);
    Kokkos::parallel_for(
        "fill_prefix_sum", team_policy(num_blocks, num_threads),
        KOKKOS_LAMBDA(const member_type& team_member) {
            device::fill_prefix_sum(
                team_member.league_rank() * team_member.team_size() +
                    team_member.team_rank(),
                sizes_sum_view, data_prefix_sum_buff);
        });
    return prefix_sum_buff;
}
References traccc::device::fill_prefix_sum(), traccc::get_data(), traccc::memory_resource::main, traccc::device::make_prefix_sum_buffer(), traccc::device::prefix_sum_buffer::totalSize, and traccc::device::prefix_sum_buffer::view.