traccc::fitting_performance_writer Class Reference
#include <fitting_performance_writer.hpp>
Classes
struct config
Public Member Functions
fitting_performance_writer (const config &cfg)
Constructor with writer config.
~fitting_performance_writer ()
Destructor that closes the file.
template<typename detector_t >
void write (const track_state_collection_types::host &track_states_per_track, const fitter_info< transform3 > &fit_info, const detector_t &det, event_map2 &evt_map)
void finalize ()
Writing caches into the file.
Private Member Functions
void write_res (const bound_track_parameters &truth_param, const bound_track_parameters &fit_param, const particle &ptc)
Non-templated part of the write(...) function.
void write_stat (const fitter_info< transform3 > &fit_info, const track_state_collection_types::host &track_states)
Non-templated part of the write(...) function.
Private Attributes
config m_cfg
Configuration for the tool.
std::unique_ptr< details::fitting_performance_writer_data > m_data
Opaque data members for the class.
Constructor & Destructor Documentation
fitting_performance_writer()
traccc::fitting_performance_writer::fitting_performance_writer (const config & cfg)
Constructor with writer config.
    : m_cfg(cfg),
      m_data(std::make_unique<details::fitting_performance_writer_data>(cfg)) {
    m_data->m_res_plot_tool.book(m_data->m_res_plot_cache);
    m_data->m_stat_plot_tool.book(m_data->m_stat_plot_cache);
}
References m_data.
 fitting_performance_writer()
traccc::fitting_performance_writer::~fitting_performance_writer ()
Destructor that closes the file.
{}
Member Function Documentation
finalize()
void traccc::fitting_performance_writer::finalize ()
Writing caches into the file.
                                          {
#ifdef TRACCC_HAVE_ROOT
    // Open the output file.
    std::unique_ptr<TFile> ofile(
        TFile::Open(m_cfg.file_path.c_str(), m_cfg.file_mode.c_str()));
    if ((!ofile) || ofile->IsZombie()) {
        throw std::runtime_error("Could not open output file \"" +
                                 m_cfg.file_path + "\" in mode \"" +
                                 m_cfg.file_mode + "\"");
    }
    ofile->cd();
#else
    std::cout << "ROOT file \"" << m_cfg.file_path << "\" is NOT created"
              << std::endl;
#endif // TRACCC_HAVE_ROOT
    m_data->m_res_plot_tool.write(m_data->m_res_plot_cache);
    m_data->m_stat_plot_tool.write(m_data->m_stat_plot_cache);
}
References traccc::fitting_performance_writer::config::file_mode, traccc::fitting_performance_writer::config::file_path, m_cfg, and m_data.
Referenced by TEST_P().
write()
template<typename detector_t >
void traccc::fitting_performance_writer::write (const track_state_collection_types::host & track_states_per_track, const fitter_info< transform3 > & fit_info, const detector_t & det, event_map2 & evt_map) [inline]
Fill the tracking results into the histograms
Parameters
track_states_per_track vector of track states of a track
det detector object
evt_map event map to find the truth values
                                    {
        auto& m_p_map = evt_map.meas_ptc_map;
        // Get the track state at the first surface
        const auto& trk_state = track_states_per_track[0];
        const measurement meas = trk_state.get_measurement();
        // Find the contributing particle
        // @todo: Use identify_contributing_particles function
        std::map<particle, uint64_t> contributing_particles = m_p_map[meas];
        const particle ptc = contributing_particles.begin()->first;
        // Find the truth global position and momentum
        const auto global_pos = evt_map.meas_xp_map[meas].first;
        const auto global_mom = evt_map.meas_xp_map[meas].second;
        const detray::surface<detector_t> sf{det, meas.surface_link};
        using cxt_t = typename detector_t::geometry_context;
        const cxt_t ctx{};
        const auto truth_local =
            sf.global_to_local(ctx, global_pos, vector::normalize(global_mom));
        // Return value
        bound_track_parameters truth_param;
        auto& truth_vec = truth_param.vector();
        getter::element(truth_vec, e_bound_loc0, 0) = truth_local[0];
        getter::element(truth_vec, e_bound_loc1, 0) = truth_local[1];
        getter::element(truth_vec, e_bound_phi, 0) = getter::phi(global_mom);
        getter::element(truth_vec, e_bound_theta, 0) =
            getter::theta(global_mom);
        // @todo: Assign a proper value to time
        getter::element(truth_vec, e_bound_time, 0) = 0.;
        getter::element(truth_vec, e_bound_qoverp, 0) =
            ptc.charge / getter::norm(global_mom);
        // For the moment, only fill with the first measurements
        if (fit_info.ndf > 0 && !trk_state.is_hole) {
            write_res(truth_param, trk_state.smoothed(), ptc);
        }
        write_stat(fit_info, track_states_per_track);
    }
References traccc::particle::charge, traccc::e_bound_loc0, traccc::e_bound_loc1, traccc::e_bound_phi, traccc::e_bound_qoverp, traccc::e_bound_theta, traccc::e_bound_time, traccc::event_map2::meas_ptc_map, traccc::event_map2::meas_xp_map, traccc::fitter_info< algebra_t >::ndf, traccc::measurement::surface_link, write_res(), and write_stat().
Referenced by TEST_P().
write_res()
void traccc::fitting_performance_writer::write_res (const bound_track_parameters & truth_param, const bound_track_parameters & fit_param, const particle & ptc) [private]
Non-templated part of the write(...) function.
                                                                  {
    m_data->m_res_plot_tool.fill(m_data->m_res_plot_cache, truth_param,
                                 fit_param, ptc);
}
References m_data.
Referenced by write().
write_stat()
void traccc::fitting_performance_writer::write_stat (const fitter_info< transform3 > & fit_info, const track_state_collection_types::host & track_states) [private]
Non-templated part of the write(...) function.
                                                          {
    m_data->m_stat_plot_tool.fill(m_data->m_stat_plot_cache, fit_info);
    for (const auto& trk_state : track_states) {
        m_data->m_stat_plot_tool.fill(m_data->m_stat_plot_cache, trk_state);
    }
}
References m_data.
Referenced by write().
Member Data Documentation
m_cfg
config traccc::fitting_performance_writer::m_cfg [private]
Configuration for the tool.
Referenced by finalize().
m_data
std::unique_ptr<details::fitting_performance_writer_data> traccc::fitting_performance_writer::m_data [private]
Opaque data members for the class.
Referenced by finalize(), fitting_performance_writer(), write_res(), and write_stat().
The documentation for this class was generated from the following files:
performance/include/traccc/resolution/fitting_performance_writer.hpp
performance/src/resolution/fitting_performance_writer.cpp