traccc::event_map2 Struct Reference
#include <event_map2.hpp>
Public Types
using measurement_xp_map = std::map< measurement, std::pair< point3, point3 > >
Map for measurement to truth global position and momentum.
using measurement_particle_map = std::map< measurement, std::map< particle, uint64_t > >
Map for measurement to the contributing particles.
using particle_measurement_map = std::map< particle, std::vector< measurement > >
Map for particle to the vector of (geometry_id, measurement)
using particle_id = uint64_t
using particle_map = std::map< particle_id, particle >
Public Member Functions
event_map2 (std::size_t event, const std::string &measurement_dir, const std::string &hit_dir, const std::string particle_dir)
Constructor without cell information.
template<typename seed_generator_t >
track_candidate_container_types::host generate_truth_candidates (seed_generator_t &sg, vecmem::memory_resource &resource)
Public Attributes
particle_map ptc_map
measurement_xp_map meas_xp_map
measurement_particle_map meas_ptc_map
particle_measurement_map ptc_meas_map
Member Typedef Documentation
measurement_particle_map
using traccc::event_map2::measurement_particle_map = std::map<measurement, std::map<particle, uint64_t> >
Map for measurement to the contributing particles.
measurement_xp_map
using traccc::event_map2::measurement_xp_map = std::map<measurement, std::pair<point3, point3> >
Map for measurement to truth global position and momentum.
particle_id
using traccc::event_map2::particle_id = uint64_t
particle_map
using traccc::event_map2::particle_map = std::map<particle_id, particle>
particle_measurement_map
using traccc::event_map2::particle_measurement_map = std::map<particle, std::vector<measurement> >
Map for particle to the vector of (geometry_id, measurement)
Constructor & Destructor Documentation
event_map2()
traccc::event_map2::event_map2 (std::size_t event, const std::string & measurement_dir, const std::string & hit_dir, const std::string particle_dir)
Constructor without cell information.
                                                     {
    std::string io_measurement_hit_id_file =
        io::data_directory() + hit_dir +
        io::get_event_filename(event, "-measurement-simhit-map.csv");
    std::string io_particle_file =
        io::data_directory() + particle_dir +
        io::get_event_filename(event, "-particles.csv");
    std::string io_hit_file = io::data_directory() + hit_dir +
                              io::get_event_filename(event, "-hits.csv");
    std::string io_measurement_file =
        io::data_directory() + measurement_dir +
        io::get_event_filename(event, "-measurements.csv");
    auto mreader = io::csv::make_measurement_reader(io_measurement_file);
    auto hreader = io::csv::make_hit_reader(io_hit_file);
    auto preader = io::csv::make_particle_reader(io_particle_file);
    auto mhid_reader =
        io::csv::make_measurement_hit_id_reader(io_measurement_hit_id_file);
    std::vector<traccc::io::csv::measurement_hit_id> measurement_hit_ids;
    std::vector<traccc::io::csv::particle> particles;
    std::vector<traccc::io::csv::hit> hits;
    std::vector<traccc::io::csv::measurement> measurements;
    traccc::io::csv::measurement_hit_id io_mh_id;
    while (mhid_reader.read(io_mh_id)) {
        measurement_hit_ids.push_back(io_mh_id);
    }
    traccc::io::csv::particle io_particle;
    while (preader.read(io_particle)) {
        point3 pos{io_particle.vx, io_particle.vy, io_particle.vz};
        vector3 mom{io_particle.px, io_particle.py, io_particle.pz};
        particles.push_back(io_particle);
        ptc_map[io_particle.particle_id] =
            particle{io_particle.particle_id, io_particle.particle_type,
                     io_particle.process, pos,
                     io_particle.vt, mom,
                     io_particle.m, io_particle.q};
    }
    traccc::io::csv::hit io_hit;
    while (hreader.read(io_hit)) {
        hits.push_back(io_hit);
    }
    traccc::io::csv::measurement io_measurement;
    while (mreader.read(io_measurement)) {
        measurements.push_back(io_measurement);
    }
    for (const auto& csv_meas : measurements) {
        // Hit index
        const auto h_id = measurement_hit_ids[csv_meas.measurement_id].hit_id;
        // Make spacepoint
        const auto csv_hit = hits[h_id];
        point3 global_pos{csv_hit.tx, csv_hit.ty, csv_hit.tz};
        point3 global_mom{csv_hit.tpx, csv_hit.tpy, csv_hit.tpz};
        // Make particle
        const auto csv_ptc = particles[csv_hit.particle_id];
        point3 pos{csv_ptc.vx, csv_ptc.vy, csv_ptc.vz};
        vector3 mom{csv_ptc.px, csv_ptc.py, csv_ptc.pz};
        particle ptc{csv_ptc.particle_id, csv_ptc.particle_type,
                     csv_ptc.process, pos,
                     csv_ptc.vt, mom,
                     csv_ptc.m, csv_ptc.q};
        // Construct the measurement object.
        traccc::measurement meas;
        std::array<typename transform3::size_type, 2u> indices{0u, 0u};
        meas.meas_dim = 0u;
        // Local key is a 8 bit char and first and last bit are dummy value. 2 -
        // 7th bits are for 6 bound track parameters.
        // Ex1) 0000010 or 2 -> meas dim = 1 and [loc0] active -> strip or wire
        // Ex2) 0000110 or 6 -> meas dim = 2 and [loc0, loc1] active -> pixel
        // Ex3) 0000100 or 4 -> meas dim = 1 and [loc1] active -> annulus
        for (unsigned int ipar = 0; ipar < 2u; ++ipar) {
            if (((csv_meas.local_key) & (1 << (ipar + 1))) != 0) {
                switch (ipar) {
                    case e_bound_loc0: {
                        meas.local[0] = csv_meas.local0;
                        meas.variance[0] = csv_meas.var_local0;
                        indices[meas.meas_dim++] = ipar;
                    }; break;
                    case e_bound_loc1: {
                        meas.local[1] = csv_meas.local1;
                        meas.variance[1] = csv_meas.var_local1;
                        indices[meas.meas_dim++] = ipar;
                    }; break;
                }
            }
        }
        meas.subs.set_indices(indices);
        meas.surface_link = detray::geometry::barcode{csv_meas.geometry_id};
        // Fill measurement to truth global position and momentum map
        meas_xp_map[meas] = std::make_pair(global_pos, global_mom);
        // Fill particle to measurement map
        ptc_meas_map[ptc].push_back(meas);
        // Fill measurement to particle map
        auto& contributing_particles = meas_ptc_map[meas];
        contributing_particles[ptc]++;
    }
}
References traccc::tests::data_test::data_directory, traccc::e_bound_loc0, traccc::e_bound_loc1, event, traccc::io::get_event_filename(), traccc::measurement::local, traccc::io::csv::particle::m, traccc::io::csv::make_hit_reader(), traccc::io::csv::make_measurement_hit_id_reader(), traccc::io::csv::make_measurement_reader(), traccc::io::csv::make_particle_reader(), traccc::measurement::meas_dim, meas_ptc_map, meas_xp_map, traccc::particle::particle_id, traccc::io::csv::particle::particle_id, traccc::io::csv::particle::particle_type, traccc::io::csv::particle::process, ptc_map, ptc_meas_map, traccc::io::csv::particle::px, traccc::io::csv::particle::py, traccc::io::csv::particle::pz, traccc::io::csv::particle::q, traccc::subspace< algebra_t, kFullSize, kSize >::set_indices(), traccc::measurement::subs, traccc::measurement::surface_link, traccc::measurement::variance, traccc::io::csv::particle::vt, traccc::io::csv::particle::vx, traccc::io::csv::particle::vy, and traccc::io::csv::particle::vz.
Member Function Documentation
generate_truth_candidates()
template<typename seed_generator_t >
track_candidate_container_types::host traccc::event_map2::generate_truth_candidates (seed_generator_t & sg, vecmem::memory_resource & resource) [inline]
                                                               {
        traccc::track_candidate_container_types::host track_candidates(
            &resource);
        for (auto const& [ptc, measurements] : ptc_meas_map) {
            const auto& xp = meas_xp_map[measurements[0]];
            const free_track_parameters free_param(xp.first, 0.f, xp.second,
                                                   ptc.charge);
            auto seed_params = sg(measurements[0].surface_link, free_param);
            // Candidate objects
            vecmem::vector<track_candidate> candidates;
            candidates.reserve(measurements.size());
            for (const auto& meas : measurements) {
                candidates.push_back(meas);
            }
            track_candidates.push_back(std::move(seed_params),
                                       std::move(candidates));
        }
        return track_candidates;
    }
References meas_xp_map, ptc_meas_map, and traccc::host_container< header_t, item_t >::push_back().
Referenced by main(), seq_run(), and TEST_P().
Member Data Documentation
meas_ptc_map
measurement_particle_map traccc::event_map2::meas_ptc_map
Referenced by event_map2(), TEST(), traccc::fitting_performance_writer::write(), traccc::finding_performance_writer::write(), and traccc::seeding_performance_writer::write().
meas_xp_map
measurement_xp_map traccc::event_map2::meas_xp_map
Referenced by event_map2(), generate_truth_candidates(), and traccc::fitting_performance_writer::write().
ptc_map
particle_map traccc::event_map2::ptc_map
Referenced by event_map2(), traccc::finding_performance_writer::write(), and traccc::seeding_performance_writer::write().
ptc_meas_map
particle_measurement_map traccc::event_map2::ptc_meas_map
Referenced by event_map2(), generate_truth_candidates(), and TEST().
The documentation for this struct was generated from the following files:
io/include/traccc/io/event_map2.hpp
io/src/event_map2.cpp