tests/io/test_binary.cpp File Reference
#include `traccc/io/read_cells.hpp`
#include `traccc/io/read_digitization_config.hpp`
#include `traccc/io/read_geometry.hpp`
#include `traccc/io/read_measurements.hpp`
#include `traccc/io/read_spacepoints.hpp`
#include `traccc/io/utils.hpp`
#include `traccc/io/write.hpp`
#include <vecmem/memory/host_memory_resource.hpp>
#include <gtest/gtest.h>
#include <cstdio>
#include <fstream>
Functions
TEST (io_binary, cell)
TEST (io_binary, spacepoint)
TEST (io_binary, measurement)
Function Documentation
TEST() [1/3]
TEST (io_binary , cell)
TRACCC library, part of the ACTS project (R&D line)
(c) 2022 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
                      {
    // Set event configuration
    const std::size_t event = 0;
    const std::string cells_directory = "tml_full/ttbar_mu200/";
    // Memory resource used by the EDM.
    vecmem::host_memory_resource host_mr;
    // Read the surface transforms
    auto surface_transforms =
        traccc::io::read_geometry("tml_detector/trackml-detector.csv");
    // Read the digitization configuration file
    auto digi_cfg = traccc::io::read_digitization_config(
        "tml_detector/default-geometric-config-generic.json");
    // Read csv file
    traccc::io::cell_reader_output reader_csv(&host_mr);
    traccc::io::read_cells(reader_csv, event, cells_directory,
                           traccc::data_format::csv, &surface_transforms,
                           &digi_cfg);
    const traccc::cell_collection_types::host& cells_csv = reader_csv.cells;
    const traccc::cell_module_collection_types::host& modules_csv =
        reader_csv.modules;
    // Write binary file
    traccc::io::write(event, cells_directory, traccc::data_format::binary,
                      vecmem::get_data(cells_csv),
                      vecmem::get_data(modules_csv));
    // Read binary file
    traccc::io::cell_reader_output reader_binary(&host_mr);
    traccc::io::read_cells(reader_binary, event, cells_directory,
                           traccc::data_format::binary, &surface_transforms,
                           &digi_cfg);
    const traccc::cell_collection_types::host& cells_binary =
        reader_binary.cells;
    const traccc::cell_module_collection_types::host& modules_binary =
        reader_binary.modules;
    // Delete binary file
    std::string io_cells_file =
        traccc::io::data_directory() + cells_directory +
        traccc::io::get_event_filename(event, "-cells.dat");
    std::remove(io_cells_file.c_str());
    ASSERT_TRUE(!std::ifstream(io_cells_file));
    std::string io_modules_file =
        traccc::io::data_directory() + cells_directory +
        traccc::io::get_event_filename(event, "-modules.dat");
    std::remove(io_modules_file.c_str());
    ASSERT_TRUE(!std::ifstream(io_modules_file));
    // Check cells size
    ASSERT_TRUE(cells_csv.size() > 0);
    ASSERT_EQ(cells_csv.size(), cells_binary.size());
    // Check modules size
    ASSERT_TRUE(modules_csv.size() > 0);
    ASSERT_EQ(modules_csv.size(), modules_binary.size());
    for (std::size_t i = 0; i < cells_csv.size(); i++) {
        ASSERT_EQ(cells_csv[i], cells_binary[i]);
    }
    for (std::size_t i = 0; i < modules_csv.size(); i++) {
        ASSERT_EQ(modules_csv[i].surface_link, modules_binary[i].surface_link);
        ASSERT_EQ(modules_csv[i].placement, modules_binary[i].placement);
    }
}
References traccc::binary, traccc::io::cell_reader_output::cells, traccc::csv, traccc::io::data_directory(), event, traccc::get_data(), traccc::io::get_event_filename(), traccc::io::cell_reader_output::modules, traccc::io::read_cells(), traccc::io::read_digitization_config(), traccc::io::read_geometry(), and traccc::io::write().
TEST() [2/3]
TEST (io_binary , measurement)
                             {
    // Set event configuration
    const std::size_t event = 0;
    const std::string measurements_directory = "tml_full/ttbar_mu200/";
    // Memory resource used by the EDM.
    vecmem::host_memory_resource host_mr;
    // Read csv file
    traccc::io::measurement_reader_output reader_csv(&host_mr);
    traccc::io::read_measurements(reader_csv, event, measurements_directory,
                                  traccc::data_format::csv);
    const traccc::measurement_collection_types::host& measurements_csv =
        reader_csv.measurements;
    const traccc::cell_module_collection_types::host& modules_csv =
        reader_csv.modules;
    // Write binary file
    traccc::io::write(
        event, measurements_directory, traccc::data_format::binary,
        vecmem::get_data(measurements_csv), vecmem::get_data(modules_csv));
    // Read binary file
    traccc::io::measurement_reader_output reader_binary(&host_mr);
    traccc::io::read_measurements(reader_binary, event, measurements_directory,
                                  traccc::data_format::binary);
    const traccc::measurement_collection_types::host& measurements_binary =
        reader_binary.measurements;
    const traccc::cell_module_collection_types::host& modules_binary =
        reader_binary.modules;
    // Delete binary file
    std::string io_measurements_file =
        traccc::io::data_directory() + measurements_directory +
        traccc::io::get_event_filename(event, "-measurements.dat");
    std::remove(io_measurements_file.c_str());
    ASSERT_TRUE(!std::ifstream(io_measurements_file));
    std::string io_modules_file =
        traccc::io::data_directory() + measurements_directory +
        traccc::io::get_event_filename(event, "-modules.dat");
    std::remove(io_modules_file.c_str());
    ASSERT_TRUE(!std::ifstream(io_modules_file));
    // Check header size
    ASSERT_TRUE(measurements_csv.size() > 0);
    ASSERT_EQ(measurements_csv.size(), measurements_binary.size());
    // Check modules size
    ASSERT_TRUE(modules_csv.size() > 0);
    ASSERT_EQ(modules_csv.size(), modules_binary.size());
    for (std::size_t i = 0; i < measurements_csv.size(); i++) {
        ASSERT_EQ(measurements_csv[i], measurements_binary[i]);
    }
    for (std::size_t i = 0; i < modules_csv.size(); i++) {
        ASSERT_EQ(modules_csv[i].surface_link, modules_binary[i].surface_link);
    }
}
References traccc::binary, traccc::csv, traccc::io::data_directory(), event, traccc::get_data(), traccc::io::get_event_filename(), traccc::io::measurement_reader_output::measurements, traccc::io::measurement_reader_output::modules, traccc::io::read_measurements(), and traccc::io::write().
TEST() [3/3]
TEST (io_binary , spacepoint)
                            {
    // Set event configuration
    const std::size_t event = 0;
    const std::string hits_directory = "tml_full/ttbar_mu200/";
    // Memory resource used by the EDM.
    vecmem::host_memory_resource host_mr;
    // Read the surface transforms
    auto surface_transforms =
        traccc::io::read_geometry("tml_detector/trackml-detector.csv");
    // Read csv file
    traccc::io::spacepoint_reader_output reader_csv(&host_mr);
    traccc::io::read_spacepoints(reader_csv, event, hits_directory,
                                 surface_transforms, traccc::data_format::csv);
    const traccc::spacepoint_collection_types::host& spacepoints_csv =
        reader_csv.spacepoints;
    const traccc::cell_module_collection_types::host& modules_csv =
        reader_csv.modules;
    // // Write binary file
    traccc::io::write(event, hits_directory, traccc::data_format::binary,
                      vecmem::get_data(spacepoints_csv),
                      vecmem::get_data(modules_csv));
    // Read binary file
    traccc::io::spacepoint_reader_output reader_binary(&host_mr);
    traccc::io::read_spacepoints(reader_binary, event, hits_directory,
                                 surface_transforms,
                                 traccc::data_format::binary);
    const traccc::spacepoint_collection_types::host& spacepoints_binary =
        reader_binary.spacepoints;
    const traccc::cell_module_collection_types::host& modules_binary =
        reader_binary.modules;
    // Delete binary file
    std::string io_spacepoints_file =
        traccc::io::data_directory() + hits_directory +
        traccc::io::get_event_filename(event, "-hits.dat");
    std::remove(io_spacepoints_file.c_str());
    ASSERT_TRUE(!std::ifstream(io_spacepoints_file));
    std::string io_modules_file =
        traccc::io::data_directory() + hits_directory +
        traccc::io::get_event_filename(event, "-modules.dat");
    std::remove(io_modules_file.c_str());
    ASSERT_TRUE(!std::ifstream(io_modules_file));
    // Check spacepoints size
    ASSERT_TRUE(spacepoints_csv.size() > 0);
    ASSERT_EQ(spacepoints_csv.size(), spacepoints_binary.size());
    // Check modules size
    ASSERT_TRUE(modules_csv.size() > 0);
    ASSERT_EQ(modules_csv.size(), modules_binary.size());
    for (std::size_t i = 0; i < spacepoints_csv.size(); i++) {
        ASSERT_EQ(spacepoints_csv[i], spacepoints_binary[i]);
    }
    for (std::size_t i = 0; i < modules_csv.size(); i++) {
        ASSERT_EQ(modules_csv[i], modules_binary[i]);
    }
}
References traccc::binary, traccc::csv, traccc::io::data_directory(), event, traccc::get_data(), traccc::io::get_event_filename(), traccc::io::spacepoint_reader_output::modules, traccc::io::read_geometry(), traccc::io::read_spacepoints(), traccc::io::spacepoint_reader_output::spacepoints, and traccc::io::write().