traccc::lin_circle Struct Reference
Header: unsigned int for the number of lin_circles per spacepoint bin.
#include <lin_circle.hpp>
Public Member Functions
TRACCC_HOST_DEVICE const scalar & Zo () const
TRACCC_HOST_DEVICE const scalar & cotTheta () const
TRACCC_HOST_DEVICE const scalar & iDeltaR () const
TRACCC_HOST_DEVICE const scalar & Er () const
TRACCC_HOST_DEVICE const scalar & U () const
TRACCC_HOST_DEVICE const scalar & V () const
Public Attributes
scalar m_Zo
scalar m_cotTheta
scalar m_iDeltaR
scalar m_Er
scalar m_U
scalar m_V
Detailed Description
Header: unsigned int for the number of lin_circles per spacepoint bin.
Item: transformed coordinate of doublet of middle-bottom or middle-top
Member Function Documentation
cotTheta()
TRACCC_HOST_DEVICE const scalar& traccc::lin_circle::cotTheta () const [inline]
{ return m_cotTheta; }
References m_cotTheta.
Referenced by traccc::device::count_triplets(), traccc::device::find_triplets(), traccc::triplet_finding_helper::isCompatible(), and traccc::triplet_finding::operator()().
Er()
TRACCC_HOST_DEVICE const scalar& traccc::lin_circle::Er () const [inline]
{ return m_Er; }
References m_Er.
Referenced by traccc::triplet_finding_helper::isCompatible().
iDeltaR()
TRACCC_HOST_DEVICE const scalar& traccc::lin_circle::iDeltaR () const [inline]
{ return m_iDeltaR; }
References m_iDeltaR.
Referenced by traccc::triplet_finding_helper::isCompatible().
U()
TRACCC_HOST_DEVICE const scalar& traccc::lin_circle::U () const [inline]
{ return m_U; }
References m_U.
Referenced by traccc::triplet_finding_helper::isCompatible().
V()
TRACCC_HOST_DEVICE const scalar& traccc::lin_circle::V () const [inline]
{ return m_V; }
References m_V.
Referenced by traccc::triplet_finding_helper::isCompatible().
Zo()
TRACCC_HOST_DEVICE const scalar& traccc::lin_circle::Zo () const [inline]
{ return m_Zo; }
References m_Zo.
Referenced by traccc::device::find_triplets(), and traccc::triplet_finding::operator()().
Member Data Documentation
m_cotTheta
scalar traccc::lin_circle::m_cotTheta
Referenced by cotTheta(), and traccc::doublet_finding_helper::transform_coordinates().
m_Er
scalar traccc::lin_circle::m_Er
Referenced by Er(), and traccc::doublet_finding_helper::transform_coordinates().
m_iDeltaR
scalar traccc::lin_circle::m_iDeltaR
Referenced by iDeltaR(), and traccc::doublet_finding_helper::transform_coordinates().
m_U
scalar traccc::lin_circle::m_U
Referenced by traccc::doublet_finding_helper::transform_coordinates(), and U().
m_V
scalar traccc::lin_circle::m_V
Referenced by traccc::doublet_finding_helper::transform_coordinates(), and V().
m_Zo
scalar traccc::lin_circle::m_Zo
Referenced by traccc::doublet_finding_helper::transform_coordinates(), and Zo().
The documentation for this struct was generated from the following file:
core/include/traccc/seeding/detail/lin_circle.hpp