traccc::triplet_finding_helper Struct Reference
#include <triplet_finding_helper.hpp>
Static Public Member Functions
static TRACCC_HOST_DEVICE bool isCompatible (const internal_spacepoint< spacepoint > &spM, const lin_circle &lb, const lin_circle &lt, const seedfinder_config &config, const scalar &iSinTheta2, const scalar &scatteringInRegion2, scalar &curvature, scalar &impact_parameter)
Member Function Documentation
isCompatible()
bool traccc::triplet_finding_helper::isCompatible (const internal_spacepoint< spacepoint > & spM, const lin_circle & lb, const lin_circle & lt, const seedfinder_config & config, const scalar & iSinTheta2, const scalar & scatteringInRegion2, scalar & curvature, scalar & impact_parameter) [inline], [static]
Check if two doublets with common middle spacepoint can form a triplet
Parameters
spM is middle spacepoint
lb is transformed coordinate of middle-bottom doublet
lt is transformed coordinate of middle-top doublet
config is configuration parameter
iSinTheta2 is the square of sin of pitch angle
scatteringInRegion2 is the threshold for scattering angle for the lower pT cut
curvature is curvature of triplet
impact_parameter is impact parameter of triplet
Returns
boolean value for compatibility
                                                 {
    // add errors of spB-spM and spM-spT pairs and add the correlation term
    // for errors on spM
    scalar error2 = lt.Er() + lb.Er() +
                    static_cast<scalar>(2.f) *
                        (lb.cotTheta() * lt.cotTheta() * spM.varianceR() +
                         spM.varianceZ()) *
                        lb.iDeltaR() * lt.iDeltaR();
    scalar deltaCotTheta = lb.cotTheta() - lt.cotTheta();
    scalar deltaCotTheta2 = deltaCotTheta * deltaCotTheta;
    scalar error;
    scalar dCotThetaMinusError2;
    // if the error is larger than the difference in theta, no need to
    // compare with scattering
    if (deltaCotTheta2 - error2 > 0) {
        deltaCotTheta = std::abs(deltaCotTheta);
        // if deltaTheta larger than the scattering for the lower pT cut, skip
        error = std::sqrt(error2);
        dCotThetaMinusError2 = deltaCotTheta2 + error2 -
                               static_cast<scalar>(2.) * deltaCotTheta * error;
        // avoid taking root of scatteringInRegion
        // if left side of ">" is positive, both sides of unequality can be
        // squared
        // (scattering is always positive)
        if (dCotThetaMinusError2 > scatteringInRegion2) {
            return false;
        }
    }
    // protects against division by 0
    scalar dU = lt.U() - lb.U();
    if (dU == static_cast<scalar>(0.)) {
        return false;
    }
    // A and B are evaluated as a function of the circumference parameters
    // x_0 and y_0
    scalar A = (lt.V() - lb.V()) / dU;
    scalar S2 = static_cast<scalar>(1.) + A * A;
    scalar B = lb.V() - A * lb.U();
    scalar B2 = B * B;
    // sqrt(S2)/B = 2 * helixradius
    // calculated radius must not be smaller than minimum radius
    if (S2 < B2 * config.minHelixDiameter2) {
        return false;
    }
    // 1/helixradius: (B/sqrt(S2))*2 (we leave everything squared)
    scalar iHelixDiameter2 = B2 / S2;
    // calculate scattering for p(T) calculated from seed curvature
    scalar pT2scatter =
        static_cast<scalar>(4.) * iHelixDiameter2 * config.pT2perRadius;
    // if pT > maxPtScattering, calculate allowed scattering angle using
    // maxPtScattering instead of pt.
    scalar pT =
        config.pTPerHelixRadius * std::sqrt(S2 / B2) / static_cast<scalar>(2.);
    if (pT > config.maxPtScattering) {
        scalar pTscatter = config.highland / config.maxPtScattering;
        pT2scatter = pTscatter * pTscatter;
    }
    // convert p(T) to p scaling by sin^2(theta) AND scale by 1/sin^4(theta)
    // from rad to deltaCotTheta
    scalar p2scatter = pT2scatter * iSinTheta2;
    // if deltaTheta larger than allowed scattering for calculated pT, skip
    if ((deltaCotTheta2 - error2 > static_cast<scalar>(0.)) &&
        (dCotThetaMinusError2 >
         p2scatter * config.sigmaScattering * config.sigmaScattering)) {
        return false;
    }
    // calculate curvature
    curvature = B / std::sqrt(S2);
    // A and B allow calculation of impact params in U/V plane with linear
    // function
    // (in contrast to having to solve a quadratic function in x/y plane)
    impact_parameter = std::abs((A - B * spM.radius()) * spM.radius());
    if (impact_parameter > config.impactMax) {
        return false;
    }
    return true;
}
References traccc::lin_circle::cotTheta(), traccc::lin_circle::Er(), traccc::seedfinder_config::highland, traccc::lin_circle::iDeltaR(), traccc::seedfinder_config::impactMax, traccc::seedfinder_config::maxPtScattering, traccc::seedfinder_config::minHelixDiameter2, traccc::seedfinder_config::pT2perRadius, traccc::seedfinder_config::pTPerHelixRadius, traccc::internal_spacepoint< spacepoint_t >::radius(), traccc::seedfinder_config::sigmaScattering, traccc::lin_circle::U(), traccc::lin_circle::V(), traccc::internal_spacepoint< spacepoint_t >::varianceR(), and traccc::internal_spacepoint< spacepoint_t >::varianceZ().
Referenced by traccc::device::count_triplets(), traccc::device::find_triplets(), and traccc::triplet_finding::operator()().
The documentation for this struct was generated from the following file:
core/include/traccc/seeding/triplet_finding_helper.hpp