traccc::internal_spacepoint< spacepoint_t > Struct Template Reference
Item: A internal spacepoint definition.
#include <internal_spacepoint.hpp>
Public Types
using link_type = typename collection_types< spacepoint_t >::host::size_type
Public Member Functions
internal_spacepoint ()=default
TRACCC_HOST_DEVICE internal_spacepoint (const spacepoint_t &sp, const link_type sp_link, const vector2 &offsetXY)
TRACCC_HOST_DEVICE internal_spacepoint (const link_type &sp_link)
TRACCC_HOST_DEVICE const scalar & x () const
TRACCC_HOST_DEVICE scalar y () const
TRACCC_HOST_DEVICE scalar z () const
TRACCC_HOST_DEVICE scalar radius () const
TRACCC_HOST_DEVICE scalar phi () const
TRACCC_HOST_DEVICE scalar varianceR () const
TRACCC_HOST_DEVICE scalar varianceZ () const
Static Public Member Functions
static TRACCC_HOST_DEVICE internal_spacepoint< spacepoint_t > invalid_value ()
Public Attributes
link_type m_link
scalar m_x
scalar m_y
scalar m_z
scalar m_r
scalar m_phi
Detailed Description
template<typename spacepoint_t>
struct traccc::internal_spacepoint< spacepoint_t >
Item: A internal spacepoint definition.
Member Typedef Documentation
link_type
template<typename spacepoint_t >
using traccc::internal_spacepoint< spacepoint_t >::link_type = typename collection_types<spacepoint_t>::host::size_type
Constructor & Destructor Documentation
internal_spacepoint() [1/3]
template<typename spacepoint_t >
traccc::internal_spacepoint< spacepoint_t >::internal_spacepoint () [default]
internal_spacepoint() [2/3]
template<typename spacepoint_t >
TRACCC_HOST_DEVICE traccc::internal_spacepoint< spacepoint_t >::internal_spacepoint (const spacepoint_t & sp, const link_type sp_link, const vector2 & offsetXY) [inline]
        : m_link(sp_link) {
        m_x = sp.global[0] - offsetXY[0];
        m_y = sp.global[1] - offsetXY[1];
        m_z = sp.global[2];
        m_r = algebra::math::sqrt(m_x * m_x + m_y * m_y);
        m_phi = algebra::math::atan2(m_y, m_x);
    }
References traccc::internal_spacepoint< spacepoint_t >::m_phi, traccc::internal_spacepoint< spacepoint_t >::m_r, traccc::internal_spacepoint< spacepoint_t >::m_x, traccc::internal_spacepoint< spacepoint_t >::m_y, and traccc::internal_spacepoint< spacepoint_t >::m_z.
internal_spacepoint() [3/3]
template<typename spacepoint_t >
TRACCC_HOST_DEVICE traccc::internal_spacepoint< spacepoint_t >::internal_spacepoint (const link_type & sp_link) [inline]
                                                  : m_link(sp_link) {
        m_x = 0;
        m_y = 0;
        m_z = 0;
        m_r = 0;
        m_phi = 0;
    }
References traccc::internal_spacepoint< spacepoint_t >::m_phi, traccc::internal_spacepoint< spacepoint_t >::m_r, traccc::internal_spacepoint< spacepoint_t >::m_x, traccc::internal_spacepoint< spacepoint_t >::m_y, and traccc::internal_spacepoint< spacepoint_t >::m_z.
Member Function Documentation
invalid_value()
template<typename spacepoint_t >
static TRACCC_HOST_DEVICE internal_spacepoint<spacepoint_t> traccc::internal_spacepoint< spacepoint_t >::invalid_value () [inline], [static]
                                                                    {
        link_type l = detray::detail::invalid_value<link_type>();
        return internal_spacepoint<spacepoint_t>({std::move(l)});
    }
phi()
template<typename spacepoint_t >
TRACCC_HOST_DEVICE scalar traccc::internal_spacepoint< spacepoint_t >::phi () const [inline]
{ return m_phi; }
References traccc::internal_spacepoint< spacepoint_t >::m_phi.
Referenced by traccc::device::count_doublets(), traccc::device::count_grid_capacities(), traccc::device::find_doublets(), traccc::spacepoint_binning::operator()(), traccc::alpaka::PopulateGridKernel::operator()(), and traccc::device::populate_grid().
radius()
template<typename spacepoint_t >
TRACCC_HOST_DEVICE scalar traccc::internal_spacepoint< spacepoint_t >::radius () const [inline]
{ return m_r; }
References traccc::internal_spacepoint< spacepoint_t >::m_r.
Referenced by traccc::triplet_finding_helper::isCompatible(), traccc::doublet_finding_helper::isCompatible(), traccc::operator<(), traccc::seed_selecting_helper::seed_weight(), traccc::seed_selecting_helper::single_seed_cut(), traccc::doublet_finding_helper::transform_coordinates(), and traccc::device::update_triplet_weights().
varianceR()
template<typename spacepoint_t >
TRACCC_HOST_DEVICE scalar traccc::internal_spacepoint< spacepoint_t >::varianceR () const [inline]
{ return 0.; }
Referenced by traccc::triplet_finding_helper::isCompatible(), and traccc::doublet_finding_helper::transform_coordinates().
varianceZ()
template<typename spacepoint_t >
TRACCC_HOST_DEVICE scalar traccc::internal_spacepoint< spacepoint_t >::varianceZ () const [inline]
{ return 0.; }
Referenced by traccc::triplet_finding_helper::isCompatible(), and traccc::doublet_finding_helper::transform_coordinates().
x()
template<typename spacepoint_t >
TRACCC_HOST_DEVICE const scalar& traccc::internal_spacepoint< spacepoint_t >::x () const [inline]
{ return m_x; }
References traccc::internal_spacepoint< spacepoint_t >::m_x.
Referenced by traccc::doublet_finding_helper::transform_coordinates().
y()
template<typename spacepoint_t >
TRACCC_HOST_DEVICE scalar traccc::internal_spacepoint< spacepoint_t >::y () const [inline]
{ return m_y; }
References traccc::internal_spacepoint< spacepoint_t >::m_y.
Referenced by traccc::doublet_finding_helper::transform_coordinates().
z()
template<typename spacepoint_t >
TRACCC_HOST_DEVICE scalar traccc::internal_spacepoint< spacepoint_t >::z () const [inline]
{ return m_z; }
References traccc::internal_spacepoint< spacepoint_t >::m_z.
Referenced by traccc::device::count_doublets(), traccc::device::count_grid_capacities(), traccc::device::find_doublets(), traccc::doublet_finding_helper::isCompatible(), traccc::spacepoint_binning::operator()(), traccc::alpaka::PopulateGridKernel::operator()(), traccc::device::populate_grid(), and traccc::doublet_finding_helper::transform_coordinates().
Member Data Documentation
m_link
template<typename spacepoint_t >
link_type traccc::internal_spacepoint< spacepoint_t >::m_link
Referenced by traccc::device::select_seeds().
m_phi
template<typename spacepoint_t >
scalar traccc::internal_spacepoint< spacepoint_t >::m_phi
Referenced by traccc::internal_spacepoint< spacepoint_t >::internal_spacepoint(), and traccc::internal_spacepoint< spacepoint_t >::phi().
m_r
template<typename spacepoint_t >
scalar traccc::internal_spacepoint< spacepoint_t >::m_r
Referenced by traccc::internal_spacepoint< spacepoint_t >::internal_spacepoint(), and traccc::internal_spacepoint< spacepoint_t >::radius().
m_x
template<typename spacepoint_t >
scalar traccc::internal_spacepoint< spacepoint_t >::m_x
Referenced by traccc::internal_spacepoint< spacepoint_t >::internal_spacepoint(), and traccc::internal_spacepoint< spacepoint_t >::x().
m_y
template<typename spacepoint_t >
scalar traccc::internal_spacepoint< spacepoint_t >::m_y
Referenced by traccc::internal_spacepoint< spacepoint_t >::internal_spacepoint(), and traccc::internal_spacepoint< spacepoint_t >::y().
m_z
template<typename spacepoint_t >
scalar traccc::internal_spacepoint< spacepoint_t >::m_z
Referenced by traccc::internal_spacepoint< spacepoint_t >::internal_spacepoint(), and traccc::internal_spacepoint< spacepoint_t >::z().
The documentation for this struct was generated from the following file:
core/include/traccc/edm/internal_spacepoint.hpp