traccc::details Namespace Reference
Namespaces
 functor
Classes
class comparator_factory
class comparator_factory< seed >
traccc::details::comparator_factory specialisation for traccc::seed
struct finding_performance_writer_data
struct fitting_performance_writer_data
struct is_same_nc
struct is_same_nc< const TYPE, TYPE >
struct is_same_nc< TYPE, TYPE >
class is_same_object
class is_same_object< bound_track_parameters >
class is_same_object< fitter_info< transform3 > >
traccc::is_same_object specialisation for traccc::fitter_info
class is_same_object< measurement >
traccc::is_same_object specialisation for traccc::measurement
class is_same_object< seed >
traccc::is_same_object specialisation for traccc::seed
class is_same_object< spacepoint >
traccc::is_same_object specialisation for traccc::spacepoint
class is_same_object< track_candidate_collection_types::host >
struct seeding_performance_writer_data
Enumerations
enum spacepoint_type : int { spacepoint_type::bottom = 0,
spacepoint_type::middle = 1,
spacepoint_type::top = 2
 }
Type of a space point.
Functions
bool is_same_angle (scalar lhs, scalar rhs, scalar unc=float_epsilon)
bool is_same_scalar (scalar lhs, scalar rhs, scalar unc=float_epsilon)
Detailed Description
TRACCC library, part of the ACTS project (R&D line)
(c) 2021-2022 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
TRACCC library, part of the ACTS project (R&D line)
(c) 2022 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
TRACCC library, part of the ACTS project (R&D line)
(c) 2023 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
TRACCC library, part of the ACTS project (R&D line)
(c) 2022-2023 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
Enumeration Type Documentation
spacepoint_type
enum traccc::details::spacepoint_type : int [strong]
Type of a space point.
Enumerator
bottom
middle
top
                           : int {
    bottom = 0, //< The referenced type is a "bottom" spacepoint
    middle = 1, //< The referenced type is a "middle" spacepoint
    top = 2 //< The referenced type is a "top" spacepoint
};
Function Documentation
is_same_angle()
bool traccc::details::is_same_angle (scalar lhs, scalar rhs, scalar unc = float_epsilon)
Comparison of angles, used in algorithmic code validation
This helper function can be used to decide if two angle values are `the
same` within some specific uncertainty.
It is different from traccc::details:is_same_scalar in that it considers values just above -Pi and just below Pi to be close to each other.
Parameters
lhs The Left Hand Side of the comparison
rhs The Right Hand Side of the comparison
unc The uncertainty percentage expressed in the 0.0-1.0 range
Returns
true if the two values are `the same` within uncertainty, false otherwise
                                                       {
    return (std::abs(wrap_to_pi(lhs - rhs)) <=
            (unc * std::abs(angle_mean(lhs, rhs))));
}
Referenced by traccc::details::is_same_object< fitter_info< transform3 > >::operator()(), and traccc::details::is_same_object< bound_track_parameters >::operator()().
is_same_scalar()
bool traccc::details::is_same_scalar (scalar lhs, scalar rhs, scalar unc = float_epsilon)
Comparison of scalars, used in algorithmic code validation
This helper function can be used to decide if two scalar values are `the
same` within some specific uncertainty.
Parameters
lhs The Left Hand Side of the comparison
rhs The Right Hand Side of the comparison
unc The uncertainty percentage expressed in the 0.0-1.0 range
Returns
true if the two values are `the same` within uncertainty, false otherwise
                                                        {
    // The difference of the two values is meant to be smaller than
    // their average times the uncertainty.
    return (std::abs(lhs - rhs) <=
            (unc * ((std::abs(lhs) + std::abs(rhs)) / 2.f)));
}
Referenced by traccc::details::is_same_object< measurement >::operator()(), traccc::details::is_same_object< spacepoint >::operator()(), traccc::details::is_same_object< bound_track_parameters >::operator()(), and traccc::details::is_same_object< seed >::operator()().