var searchData=
[
  ['tbb_5ftask_5fexample_2ecpp_1985',['tbb_task_example.cpp',['../d7/dee/tbb__task__example_8cpp.html',1,'']]],
  ['telescope_5fdetector_5foptions_2ehpp_1986',['telescope_detector_options.hpp',['../df/dc0/telescope__detector__options_8hpp.html',1,'']]],
  ['test_5falgorithm_2ecpp_1987',['test_algorithm.cpp',['../df/de8/test__algorithm_8cpp.html',1,'']]],
  ['test_5fbinary_2ecpp_1988',['test_binary.cpp',['../d0/d3f/test__binary_8cpp.html',1,'']]],
  ['test_5fcca_2ecpp_1989',['test_cca.cpp',['../dd/d42/cpu_2test__cca_8cpp.html',1,'(Global Namespace)'],['../dd/dd1/cuda_2test__cca_8cpp.html',1,'(Global Namespace)'],['../d9/dca/futhark_2test__cca_8cpp.html',1,'(Global Namespace)']]],
  ['test_5fckf_5fsparse_5ftracks_5ftelescope_2ecpp_1990',['test_ckf_sparse_tracks_telescope.cpp',['../df/deb/cpu_2test__ckf__sparse__tracks__telescope_8cpp.html',1,'(Global Namespace)'],['../de/dfc/cuda_2test__ckf__sparse__tracks__telescope_8cpp.html',1,'(Global Namespace)']]],
  ['test_5fclusterization_2ecpp_1991',['test_clusterization.cpp',['../d2/dd3/test__clusterization_8cpp.html',1,'']]],
  ['test_5fclusterization_5fresolution_2ecpp_1992',['test_clusterization_resolution.cpp',['../d2/da8/test__clusterization__resolution_8cpp.html',1,'']]],
  ['test_5fcopy_2ecpp_1993',['test_copy.cpp',['../dc/dc3/test__copy_8cpp.html',1,'']]],
  ['test_5fcsv_2ecpp_1994',['test_csv.cpp',['../dd/db8/test__csv_8cpp.html',1,'']]],
  ['test_5fevent_5fmap_2ecpp_1995',['test_event_map.cpp',['../d3/d9d/test__event__map_8cpp.html',1,'']]],
  ['test_5fkalman_5ffitter_5ftelescope_2ecpp_1996',['test_kalman_fitter_telescope.cpp',['../d8/d63/cpu_2test__kalman__fitter__telescope_8cpp.html',1,'(Global Namespace)'],['../d2/d53/cuda_2test__kalman__fitter__telescope_8cpp.html',1,'(Global Namespace)']]],
  ['test_5fkalman_5ffitter_5fwire_5fchamber_2ecpp_1997',['test_kalman_fitter_wire_chamber.cpp',['../d9/dbe/test__kalman__fitter__wire__chamber_8cpp.html',1,'']]],
  ['test_5fmapper_2ecpp_1998',['test_mapper.cpp',['../df/d35/test__mapper_8cpp.html',1,'']]],
  ['test_5fmodule_5fmap_2ecpp_1999',['test_module_map.cpp',['../dd/d5c/test__module__map_8cpp.html',1,'']]],
  ['test_5foptions_2ecpp_2000',['test_options.cpp',['../d4/d6e/test__options_8cpp.html',1,'']]],
  ['test_5franges_2ecpp_2001',['test_ranges.cpp',['../d9/d5a/test__ranges_8cpp.html',1,'']]],
  ['test_5fseeding_2ecpp_2002',['test_seeding.cpp',['../db/d06/test__seeding_8cpp.html',1,'']]],
  ['test_5fsimulation_2ecpp_2003',['test_simulation.cpp',['../db/d42/test__simulation_8cpp.html',1,'']]],
  ['test_5fspacepoint_5fformation_2ecpp_2004',['test_spacepoint_formation.cpp',['../d4/d17/cpu_2test__spacepoint__formation_8cpp.html',1,'(Global Namespace)'],['../d0/db6/cuda_2test__spacepoint__formation_8cpp.html',1,'(Global Namespace)']]],
  ['test_5ftrack_5fparams_5festimation_2ecpp_2005',['test_track_params_estimation.cpp',['../df/dd9/test__track__params__estimation_8cpp.html',1,'']]],
  ['throughput_2ecpp_2006',['throughput.cpp',['../d9/d89/throughput_8cpp.html',1,'']]],
  ['throughput_2ehpp_2007',['throughput.hpp',['../db/d3a/throughput_8hpp.html',1,'']]],
  ['throughput_5fmt_2ecpp_2008',['throughput_mt.cpp',['../d4/d4a/cpu_2throughput__mt_8cpp.html',1,'(Global Namespace)'],['../d2/def/cuda_2throughput__mt_8cpp.html',1,'(Global Namespace)'],['../d1/d7f/sycl_2throughput__mt_8cpp.html',1,'(Global Namespace)']]],
  ['throughput_5fmt_2ehpp_2009',['throughput_mt.hpp',['../d7/ddb/throughput__mt_8hpp.html',1,'']]],
  ['throughput_5fmt_2eipp_2010',['throughput_mt.ipp',['../d9/ddd/throughput__mt_8ipp.html',1,'']]],
  ['throughput_5foptions_2ecpp_2011',['throughput_options.cpp',['../d8/d0c/throughput__options_8cpp.html',1,'']]],
  ['throughput_5foptions_2ehpp_2012',['throughput_options.hpp',['../db/d6c/throughput__options_8hpp.html',1,'']]],
  ['throughput_5fst_2ecpp_2013',['throughput_st.cpp',['../db/dd9/cpu_2throughput__st_8cpp.html',1,'(Global Namespace)'],['../da/d78/cuda_2throughput__st_8cpp.html',1,'(Global Namespace)'],['../d5/d39/sycl_2throughput__st_8cpp.html',1,'(Global Namespace)']]],
  ['throughput_5fst_2ehpp_2014',['throughput_st.hpp',['../d0/dcd/throughput__st_8hpp.html',1,'']]],
  ['throughput_5fst_2eipp_2015',['throughput_st.ipp',['../d9/d60/throughput__st_8ipp.html',1,'']]],
  ['timer_2ecpp_2016',['timer.cpp',['../dc/de5/timer_8cpp.html',1,'']]],
  ['timer_2ehpp_2017',['timer.hpp',['../df/d05/timer_8hpp.html',1,'']]],
  ['timing_5finfo_2ecpp_2018',['timing_info.cpp',['../da/daa/timing__info_8cpp.html',1,'']]],
  ['timing_5finfo_2ehpp_2019',['timing_info.hpp',['../d1/d3c/timing__info_8hpp.html',1,'']]],
  ['traccc_5fthroughput_5fmt_5fplotter_2epy_2020',['traccc_throughput_mt_plotter.py',['../dc/daf/traccc__throughput__mt__plotter_8py.html',1,'']]],
  ['track_5fcandidate_2ehpp_2021',['track_candidate.hpp',['../d6/d06/track__candidate_8hpp.html',1,'']]],
  ['track_5fclassification_2ehpp_2022',['track_classification.hpp',['../d4/d67/track__classification_8hpp.html',1,'']]],
  ['track_5ffilter_2ecpp_2023',['track_filter.cpp',['../d1/d2a/track__filter_8cpp.html',1,'']]],
  ['track_5ffilter_2ehpp_2024',['track_filter.hpp',['../d7/d36/track__filter_8hpp.html',1,'']]],
  ['track_5fmatcher_2ecpp_2025',['track_matcher.cpp',['../d2/d5f/track__matcher_8cpp.html',1,'']]],
  ['track_5fmatcher_2ehpp_2026',['track_matcher.hpp',['../d2/dc5/track__matcher_8hpp.html',1,'']]],
  ['track_5fparameters_2ehpp_2027',['track_parameters.hpp',['../d8/df1/track__parameters_8hpp.html',1,'']]],
  ['track_5fparametrization_2ehpp_2028',['track_parametrization.hpp',['../dc/dfd/track__parametrization_8hpp.html',1,'']]],
  ['track_5fparams_5festimation_2ecpp_2029',['track_params_estimation.cpp',['../d6/d21/track__params__estimation_8cpp.html',1,'']]],
  ['track_5fparams_5festimation_2ehpp_2030',['track_params_estimation.hpp',['../dc/d5e/core_2include_2traccc_2seeding_2track__params__estimation_8hpp.html',1,'(Global Namespace)'],['../d8/d4c/device_2cuda_2include_2traccc_2cuda_2seeding_2track__params__estimation_8hpp.html',1,'(Global Namespace)'],['../db/d7c/device_2sycl_2include_2traccc_2sycl_2seeding_2track__params__estimation_8hpp.html',1,'(Global Namespace)']]],
  ['track_5fparams_5festimation_5fhelper_2ehpp_2031',['track_params_estimation_helper.hpp',['../d1/dd0/track__params__estimation__helper_8hpp.html',1,'']]],
  ['track_5fstate_2ehpp_2032',['track_state.hpp',['../da/d88/track__state_8hpp.html',1,'']]],
  ['triplet_2ehpp_2033',['triplet.hpp',['../d2/da1/triplet_8hpp.html',1,'']]],
  ['triplet_5fcounter_2ehpp_2034',['triplet_counter.hpp',['../d4/df9/triplet__counter_8hpp.html',1,'']]],
  ['triplet_5ffinding_2ehpp_2035',['triplet_finding.hpp',['../dc/d7c/triplet__finding_8hpp.html',1,'']]],
  ['triplet_5ffinding_5fhelper_2ehpp_2036',['triplet_finding_helper.hpp',['../dd/da8/triplet__finding__helper_8hpp.html',1,'']]],
  ['truth_5ffinding_5fexample_2ecpp_2037',['truth_finding_example.cpp',['../d2/dbe/truth__finding__example_8cpp.html',1,'']]],
  ['truth_5ffinding_5fexample_5fcuda_2ecpp_2038',['truth_finding_example_cuda.cpp',['../d8/df4/truth__finding__example__cuda_8cpp.html',1,'']]],
  ['truth_5ffitting_5fexample_2ecpp_2039',['truth_fitting_example.cpp',['../de/d43/truth__fitting__example_8cpp.html',1,'']]],
  ['truth_5ffitting_5fexample_5fcuda_2ecpp_2040',['truth_fitting_example_cuda.cpp',['../d6/d89/truth__fitting__example__cuda_8cpp.html',1,'']]],
  ['type_5ftraits_2ehpp_2041',['type_traits.hpp',['../dc/d54/type__traits_8hpp.html',1,'']]]
];
