traccc::subspace< algebra_t, kFullSize, kSize > Struct Template Reference
#include <subspace.hpp>
Public Types
using matrix_operator = typename algebra_t::matrix_actor
using size_type = typename matrix_operator::size_ty
template<size_type ROWS, size_type COLS>
using matrix_type = typename matrix_operator::template matrix_type< ROWS, COLS >
using subspace_vector = matrix_type< kSize, 1u >
using fullspace_vector = matrix_type< kFullSize, 1u >
using projection_matrix = matrix_type< kSize, kFullSize >
using expansion_matrix = matrix_type< kFullSize, kSize >
Public Member Functions
constexpr TRACCC_HOST_DEVICE subspace (const std::array< size_type, kSize > &indices)
constexpr TRACCC_HOST_DEVICE const std::array< size_type, kSize > & get_indices () const
TRACCC_HOST_DEVICE void set_indices (const std::array< size_type, kSize > &indices)
Function that sets the m_axes.
template<size_type D>
TRACCC_HOST_DEVICE auto projector () const -> matrix_type< D, kFullSize >
Projection matrix that maps from the full space into the subspace.
template<size_type D>
TRACCC_HOST_DEVICE auto expander () const -> matrix_type< kFullSize, D >
Expansion matrix that maps from the subspace into the full space.
Static Public Attributes
static const size_type size = kSize
static const size_type fullSize = kFullSize
Private Attributes
std::array< size_type, kSize > m_axes
Member Typedef Documentation
expansion_matrix
template<typename algebra_t , typename algebra_t::size_type kFullSize, typename algebra_t::size_type kSize = 2u>
using traccc::subspace< algebra_t, kFullSize, kSize >::expansion_matrix = matrix_type<kFullSize, kSize>
fullspace_vector
template<typename algebra_t , typename algebra_t::size_type kFullSize, typename algebra_t::size_type kSize = 2u>
using traccc::subspace< algebra_t, kFullSize, kSize >::fullspace_vector = matrix_type<kFullSize, 1u>
matrix_operator
template<typename algebra_t , typename algebra_t::size_type kFullSize, typename algebra_t::size_type kSize = 2u>
using traccc::subspace< algebra_t, kFullSize, kSize >::matrix_operator = typename algebra_t::matrix_actor
matrix_type
template<typename algebra_t , typename algebra_t::size_type kFullSize, typename algebra_t::size_type kSize = 2u>
template<size_type ROWS, size_type COLS>
using traccc::subspace< algebra_t, kFullSize, kSize >::matrix_type = typename matrix_operator::template matrix_type<ROWS, COLS>
projection_matrix
template<typename algebra_t , typename algebra_t::size_type kFullSize, typename algebra_t::size_type kSize = 2u>
using traccc::subspace< algebra_t, kFullSize, kSize >::projection_matrix = matrix_type<kSize, kFullSize>
size_type
template<typename algebra_t , typename algebra_t::size_type kFullSize, typename algebra_t::size_type kSize = 2u>
using traccc::subspace< algebra_t, kFullSize, kSize >::size_type = typename matrix_operator::size_ty
subspace_vector
template<typename algebra_t , typename algebra_t::size_type kFullSize, typename algebra_t::size_type kSize = 2u>
using traccc::subspace< algebra_t, kFullSize, kSize >::subspace_vector = matrix_type<kSize, 1u>
Constructor & Destructor Documentation
subspace()
template<typename algebra_t , typename algebra_t::size_type kFullSize, typename algebra_t::size_type kSize = 2u>
constexpr TRACCC_HOST_DEVICE traccc::subspace< algebra_t, kFullSize, kSize >::subspace (const std::array< size_type, kSize > & indices) [inline], [constexpr]
Construct from a container of axis indices.
Parameters
indices Unique, ordered indices
                                                                  {
        for (size_type i = 0u; i < kSize; ++i) {
            assert((indices[i] < kFullSize) and
                   "Axis indices must be within the full space");
        }
        for (size_type i = 0; i < kSize; ++i) {
            m_axes[i] = static_cast<size_type>(indices[i]);
        }
    }
Member Function Documentation
expander()
template<typename algebra_t , typename algebra_t::size_type kFullSize, typename algebra_t::size_type kSize = 2u>
template<size_type D>
TRACCC_HOST_DEVICE auto traccc::subspace< algebra_t, kFullSize, kSize >::expander () const -> matrix_type<kFullSize, D> [inline]
Expansion matrix that maps from the subspace into the full space.
                                                                          {
        static_assert(D <= kSize,
                      "The dimension of projection should be smaller than "
                      "subspace dimension");
        matrix_type<kFullSize, D> expn =
            matrix_operator().template zero<kFullSize, D>();
        for (size_type i = 0u; i < kSize; ++i) {
            getter::element(expn, m_axes[i], i) = 1;
        }
        return expn;
    }
get_indices()
template<typename algebra_t , typename algebra_t::size_type kFullSize, typename algebra_t::size_type kSize = 2u>
constexpr TRACCC_HOST_DEVICE const std::array<size_type, kSize>& traccc::subspace< algebra_t, kFullSize, kSize >::get_indices () const [inline], [constexpr]
Axis indices that comprise the subspace.
The specific container and index type should be considered an implementation detail. Users should treat the return type as a generic container whose elements are convertible to size_t.
                                                                    {
        return m_axes;
    }
projector()
template<typename algebra_t , typename algebra_t::size_type kFullSize, typename algebra_t::size_type kSize = 2u>
template<size_type D>
TRACCC_HOST_DEVICE auto traccc::subspace< algebra_t, kFullSize, kSize >::projector () const -> matrix_type<D, kFullSize> [inline]
Projection matrix that maps from the full space into the subspace.
                                                                           {
        static_assert(D <= kSize,
                      "The dimension of projection should be smaller than "
                      "subspace dimension");
        matrix_type<D, kFullSize> proj =
            matrix_operator().template zero<D, kFullSize>();
        for (size_type i = 0u; i < D; ++i) {
            getter::element(proj, i, m_axes[i]) = 1;
        }
        return proj;
    }
Referenced by traccc::measurement_smearer< transform3_t >::operator()().
set_indices()
template<typename algebra_t , typename algebra_t::size_type kFullSize, typename algebra_t::size_type kSize = 2u>
TRACCC_HOST_DEVICE void traccc::subspace< algebra_t, kFullSize, kSize >::set_indices (const std::array< size_type, kSize > & indices) [inline]
Function that sets the m_axes.
                                                                {
        m_axes = indices;
    }
Referenced by traccc::event_map2::event_map2(), and traccc::io::csv::read_measurements().
Member Data Documentation
fullSize
template<typename algebra_t , typename algebra_t::size_type kFullSize, typename algebra_t::size_type kSize = 2u>
const size_type traccc::subspace< algebra_t, kFullSize, kSize >::fullSize = kFullSize [static]
m_axes
template<typename algebra_t , typename algebra_t::size_type kFullSize, typename algebra_t::size_type kSize = 2u>
std::array<size_type, kSize> traccc::subspace< algebra_t, kFullSize, kSize >::m_axes [private]
Referenced by traccc::subspace< transform3, e_bound_size, 2u >::expander(), traccc::subspace< transform3, e_bound_size, 2u >::get_indices(), traccc::subspace< transform3, e_bound_size, 2u >::projector(), traccc::subspace< transform3, e_bound_size, 2u >::set_indices(), and traccc::subspace< transform3, e_bound_size, 2u >::subspace().
size
template<typename algebra_t , typename algebra_t::size_type kFullSize, typename algebra_t::size_type kSize = 2u>
const size_type traccc::subspace< algebra_t, kFullSize, kSize >::size = kSize [static]
The documentation for this struct was generated from the following file:
core/include/traccc/utils/subspace.hpp