traccc Namespace Reference
Namespaces
 alpaka
 cuda
 detail
 details
 device
 experimental
 futhark
 io
 kokkos
 performance
 plot_helpers
 sycl
 tests
Classes
class algorithm
class algorithm< R(A...)>
Unified algorithm semantics which convert an input to an output.
struct aos
An array-of-structs (Aos) layout scheme.
struct array_wrapper
An array wrapper that can swap between SoA and AoS layouts almost transparently.
struct candidate_link
struct cell
struct cell_module
class CkfSparseTrackTelescopeTests
Combinatorial Kalman Finding Test with Sparse tracks.
class CkfSparseTrackWireChamberTests
Combinatorial Kalman Finding Test with Sparse tracks.
class clusterization_algorithm
class collection_comparator
struct collection_types
Type trait defining all `collection types` for an EDM class.
struct common_options
class component_connection
class container_base
struct container_buffer
Structure holding (all of the) data about the container in host code.
class container_comparator
struct container_data
Structure holding (some of the) data about the container in host code.
struct container_element
View class for an element in a header-vector container.
struct container_types
Type trait defining all `container types` for an EDM class pair.
struct container_view
struct detector_input_options
class device_container
Host container describing objects in a given event.
struct doublet
Item: doublet of middle-bottom or middle-top.
struct doublet_finding
struct doublet_finding_helper
class duplication_plot_tool
class eff_plot_tool
struct event_map
struct event_map2
struct exact
Matcher requiring exact particle matching.
class finding_algorithm
Track Finding algorithm for a set of tracks.
struct finding_config
Configuration struct for track finding.
struct finding_input_config
class finding_performance_writer
struct fitter_info
Fitting result per track.
class fitting_algorithm
Fitting algorithm for a set of tracks.
struct fitting_config
Configuration struct for track fitting.
class fitting_performance_writer
class full_chain_algorithm
struct full_tracking_input_config
struct gain_matrix_smoother
struct gain_matrix_updater
Type unrolling functor for Kalman updating.
class host_container
Host container describing objects in a given event.
struct interaction_register
struct internal_spacepoint
Item: A internal spacepoint definition.
struct kalman_actor
Detray actor for Kalman filtering.
class kalman_fitter
Kalman fitter algorithm to fit a single track.
class KalmanFittingTelescopeTests
Combinatorial Kalman Finding Test with Sparse tracks.
class KalmanFittingTests
class KalmanFittingWireChamberTests
Combinatorial Kalman Finding Test with Sparse tracks.
struct lin_circle
Header: unsigned int for the number of lin_circles per spacepoint bin.
struct measurement
class measurement_creation
struct measurement_equal_comp
struct measurement_smearer
struct measurement_sort_comp
Comparator based on detray barcode value.
struct memory_resource
struct module_digitization_config
Type describing the digitization configuration of a detector module.
class module_map
A fast and GPU-friendly map for consecutive module IDs to values.
struct mt_options
Options for multi-threaded code execution.
struct nseed
Seed of arbitrary size.
class nseed_performance_writer
struct particle
struct particle_gen_options
struct particle_hit_count
struct pixel_data
struct pod
Tuple of plain-old-data types.
struct pod< T, Ts... >
struct pod<>
struct propagation_options
class Reals
class res_plot_tool
struct res_plot_tool_config
Configuration structure for traccc::res_plot_tool.
struct result
struct seed
Seed consisting of three spacepoints, z origin and weight.
class seed_filtering
Seed filtering to filter out the bad triplets.
class seed_finding
Seed finding.
struct seed_generator
Seed track parameter generator.
struct seed_selecting_helper
struct seedfilter_config
struct seedfinder_config
class seeding_algorithm
Main algorithm for performing the track seeding on the CPU.
struct seeding_input_config
class seeding_performance_writer
struct simple_charged_eta_pt_cut
Simple η and pT cut for charged particles.
struct simulator
struct smearing_writer
struct soa
A struct-of-arrays (SoA) layout scheme.
struct sp_location
location of spacepoint in internal spacepoint container
struct spacepoint
class spacepoint_binning
spacepoint binning
class spacepoint_formation
struct spacepoint_grid_config
class stat_plot_tool
struct stat_plot_tool_config
Configuration structure for traccc::stat_plot_tool.
struct statistics_updater
Type unrolling functor to update the fitting quality.
struct stepped_percentage
Matcher based on minimum majority size.
struct subspace
struct telescope_detector_options
struct throughput_options
Command line options used in the throughput tests.
struct track_filter
Abstract track filtering descriptor.
struct track_matcher
Abstract track matching descriptor.
class track_params_estimation
struct track_state
Fitting result per measurement.
struct triplet
Item: triplets of middle-bottom-top.
struct triplet_finding
struct triplet_finding_helper
Typedefs
template<typename scalar_t >
using unit = detray::unit< scalar_t >
using geometry_id = uint64_t
using channel_id = unsigned int
using vector2 = __plugin::point2< traccc::scalar >
using point2 = __plugin::point2< traccc::scalar >
using variance2 = __plugin::point2< traccc::scalar >
using point3 = __plugin::point3< traccc::scalar >
using vector3 = __plugin::point3< traccc::scalar >
using variance3 = __plugin::point3< traccc::scalar >
using transform3 = __plugin::transform3< traccc::scalar >
using cell_module_collection_types = collection_types< cell_module >
Declare all cell module collection types.
using cell_collection_types = collection_types< cell >
Declare all cell collection types.
using cluster_container_types = container_types< std::monostate, cell >
Declare all cluster container types.
using measurement_collection_types = collection_types< measurement >
Declare all measurement collection types.
using measurement_container_types = container_types< cell_module, measurement >
Declare all measurement container types.
using particle_collection_types = collection_types< particle >
Declare all particle collection types.
using seed_collection_types = collection_types< seed >
Declare all seed collection types.
using spacepoint_collection_types = collection_types< spacepoint >
Declare all spacepoint collection types.
using track_candidate = measurement
Track candidate is the measurement.
using track_candidate_collection_types = collection_types< track_candidate >
Declare a track candidates collection types.
using track_candidate_container_types = container_types< bound_track_parameters, track_candidate >
Declare a track candidates container type.
using free_track_parameters = detray::free_track_parameters< transform3 >
using bound_track_parameters = detray::bound_track_parameters< transform3 >
using free_vector = free_track_parameters::vector_type
using free_covariance = free_track_parameters::covariance_type
using bound_vector = bound_track_parameters::vector_type
using bound_covariance = bound_track_parameters::covariance_type
using bound_track_parameters_collection_types = collection_types< bound_track_parameters >
Declare all track_parameters collection types.
using track_state_collection_types = collection_types< track_state< transform3 > >
Declare all track_state collection types.
using track_state_container_types = container_types< fitter_info< transform3 >, track_state< transform3 > >
Declare all track_state container types.
using geometry = traccc::module_map<>
using doublet_collection_types = collection_types< doublet >
Declare all doublet collection types.
using doublet_container_types = container_types< std::monostate, doublet >
Declare all doublet container types.
using lin_circle_collection_types = collection_types< lin_circle >
Declare all lin_circle collection types.
using sp_grid = detray::grid2< detray::attach_populator, detray::axis::circular, detray::axis::regular, detray::serializer2, detray::dvector, detray::djagged_vector, detray::darray, detray::dtuple, internal_spacepoint< spacepoint >, false >
using sp_grid_device = detray::grid2< detray::attach_populator, detray::axis::circular, detray::axis::regular, detray::serializer2, vecmem::device_vector, vecmem::jagged_device_vector, detray::darray, detray::dtuple, internal_spacepoint< spacepoint >, false >
using const_sp_grid_device = detray::grid2< detray::attach_populator, detray::axis::circular, detray::axis::regular, detray::serializer2, vecmem::device_vector, vecmem::jagged_device_vector, detray::darray, detray::dtuple, const internal_spacepoint< spacepoint >, false >
using sp_grid_data = detray::grid2_data< sp_grid >
using sp_grid_const_data = detray::const_grid2_data< sp_grid >
using sp_grid_view = detray::grid2_view< sp_grid >
using sp_grid_const_view = detray::const_grid2_view< sp_grid >
using sp_grid_buffer = detray::grid2_buffer< sp_grid >
using triplet_collection_types = collection_types< triplet >
Declare all triplet collection types.
using triplet_container_types = container_types< std::monostate, triplet >
Declare all triplet container types.
template<typename T >
using rvalue_or_const_lvalue = std::disjunction< std::is_rvalue_reference< T >, std::conjunction< std::is_lvalue_reference< T >, std::is_const< std::remove_reference_t< T > >> >
using demonstrator_input = vecmem::vector< io::cell_reader_output >
using demonstrator_result = vecmem::vector< result >
using digitization_config = Acts::GeometryHierarchyMap< module_digitization_config >
Type describing the digitization configuration for the whole detector.
using hit_id = uint64_t
using particle_id = uint64_t
using particle_map = std::map< particle_id, particle >
using hit_particle_map = std::map< spacepoint, particle >
using hit_map = std::map< hit_id, spacepoint >
using hit_cell_map = std::map< spacepoint, std::vector< cell > >
using geoId_link_map = std::map< geometry_id, unsigned int >
using cell_particle_map = std::map< cell, particle >
using measurement_cell_map = std::map< measurement, vecmem::vector< cell > >
using measurement_particle_map = std::map< measurement, std::map< particle, uint64_t > >
using scalar = TRACCC_CUSTOM_SCALARTYPE
template<typename value_type , unsigned int kDIM>
using darray = std::array< value_type, kDIM >
template<typename value_type >
using dvector = vecmem::vector< value_type >
template<typename value_type >
using djagged_vector = vecmem::jagged_vector< value_type >
template<typename key_type , typename value_type >
using dmap = std::map< key_type, value_type >
template<class... types>
using dtuple = std::tuple< types... >
Enumerations
enum bound_indices : unsigned int {
e_bound_loc0 = 0,
e_bound_loc1 = 1,
e_bound_phi = 2,
e_bound_theta = 3,
e_bound_qoverp = 4,
e_bound_time = 5,
e_bound_size
 }
enum free_indices : unsigned int {
e_free_pos0 = 0u,
e_free_pos1 = e_free_pos0 + 1u,
e_free_pos2 = e_free_pos0 + 2u,
e_free_time = 3u,
e_free_dir0 = 4u,
e_free_dir1 = e_free_dir0 + 1u,
e_free_dir2 = e_free_dir0 + 2u,
e_free_qoverp = 7u,
e_free_size
 }
enum data_format : int { csv = 0,
binary = 1,
json = 2
 }
Format for an input or output file.
Functions
TRACCC_HOST_DEVICE bool operator== (const cell_module &lhs, const cell_module &rhs)
Equality operator for cell module.
TRACCC_HOST_DEVICE bool operator< (const cell &lhs, const cell &rhs)
TRACCC_HOST_DEVICE bool operator== (const cell &lhs, const cell &rhs)
Equality operator for cells.
template<typename spacepoint_t >
bool operator< (const internal_spacepoint< spacepoint_t > &lhs, const internal_spacepoint< spacepoint_t > &rhs)
TRACCC_HOST_DEVICE bool operator< (const measurement &lhs, const measurement &rhs)
Comparison / ordering operator for measurements.
TRACCC_HOST_DEVICE bool operator== (const measurement &lhs, const measurement &rhs)
Equality operator for measurements.
bool operator< (const particle &lhs, const particle &rhs)
TRACCC_HOST_DEVICE bool operator< (const spacepoint &lhs, const spacepoint &rhs)
Comparison / ordering operator for spacepoints.
TRACCC_HOST_DEVICE bool operator== (const spacepoint &lhs, const spacepoint &rhs)
Equality operator for spacepoints.
TRACCC_HOST_DEVICE bool operator== (const doublet &lhs, const doublet &rhs)
TRACCC_HOST_DEVICE bool operator== (const sp_location &lhs, const sp_location &rhs)
TRACCC_HOST_DEVICE bool operator!= (const sp_location &lhs, const sp_location &rhs)
TRACCC_HOST_DEVICE bool operator== (const triplet &lhs, const triplet &rhs)
TRACCC_HOST_DEVICE bool operator!= (const triplet &lhs, const triplet &rhs)
TRACCC_HOST_DEVICE bool operator< (const triplet &lhs, const triplet &rhs)
std::pair< detray::axis::circular<>, detray::axis::regular<> > get_axes (const spacepoint_grid_config &grid_config, vecmem::memory_resource &mr)
TRACCC_HOST_DEVICE size_t is_valid_sp (const seedfinder_config &config, const spacepoint &sp)
TRACCC_HOST_DEVICE vector2 uv_transform (const scalar &x, const scalar &y)
template<typename spacepoint_collection_t >
TRACCC_HOST_DEVICE bound_vector seed_to_bound_vector (const spacepoint_collection_t &sp_collection, const seed &seed, const vector3 &bfield, const scalar mass)
template<typename A , typename B , typename C , typename... R>
auto compose (std::function< std::remove_const_t< std::remove_reference_t< B >>(A)> f, std::function< C(B)> g, R... rs)
template<typename A , typename B , typename C >
std::function< B(A &&)> side_effect (std::function< B(A)> f, std::function< void(const C &)> s)
template<std::size_t I, typename... Ts>
constexpr auto & pod_get (pod< Ts... > &p)
Get a given value from a POD tuple.
template<std::size_t... Ns, typename... Ts>
std::tuple< Ts *... > _get_ptrs (std::index_sequence< Ns... >, const std::tuple< vecmem::unique_alloc_ptr< Ts[]>... > &o)
Helper function to convert a list of unique pointers to raw pointers.
void handle_argument_errors (po::variables_map &vm, const po::options_description &desc)
std::ostream & operator<< (std::ostream &out, const mt_options &opt)
Printout helper for traccc::mt_options.
template<typename scalar_t , size_t kSize>
std::istream & operator>> (std::istream &is, Reals< scalar_t, kSize > &values)
template<typename scalar_t , size_t kSize>
std::ostream & operator<< (std::ostream &os, const Reals< scalar_t, kSize > &values)
Print a fixed number of doubles as x:y:z.
std::ostream & operator<< (std::ostream &out, const throughput_options &opt)
Printout helper for traccc::throughput_options.
template<typename FULL_CHAIN_ALG , typename HOST_MR = vecmem::host_memory_resource>
int throughput_mt (std::string_view description, int argc, char *argv[], bool use_host_caching=false)
template<typename FULL_CHAIN_ALG , typename HOST_MR = vecmem::host_memory_resource>
int throughput_st (std::string_view description, int argc, char *argv[], bool use_host_caching=false)
std::ostream & operator<< (std::ostream &out, data_format format)
Printout helper for traccc::data_format.
particle_map generate_particle_map (std::size_t event, const std::string &particle_dir)
hit_particle_map generate_hit_particle_map (std::size_t event, const std::string &hits_dir, const std::string &particle_dir, const geoId_link_map &link_map=geoId_link_map())
hit_map generate_hit_map (std::size_t event, const std::string &hits_dir)
hit_cell_map generate_hit_cell_map (std::size_t event, const std::string &cells_dir, const std::string &hits_dir, const geoId_link_map &link_map=geoId_link_map())
cell_particle_map generate_cell_particle_map (std::size_t event, const std::string &cells_dir, const std::string &hits_dir, const std::string &particle_dir, const geoId_link_map &link_map=geoId_link_map())
std::tuple< measurement_cell_map, cell_module_collection_types::host > generate_measurement_cell_map (std::size_t event, const std::string &detector_file, const std::string &digi_config_file, const std::string &cells_dir, vecmem::memory_resource &resource)
measurement_particle_map generate_measurement_particle_map (std::size_t event, const std::string &detector_file, const std::string &digi_config_file, const std::string &cells_dir, const std::string &hits_dir, const std::string &particle_dir, vecmem::memory_resource &resource)
measurement_particle_map generate_measurement_particle_map (std::size_t event, const std::string &detector_file, const std::string &hits_dir, const std::string &particle_dir, vecmem::memory_resource &resource)
void from_json (const nlohmann::json &json, module_digitization_config &cfg)
template<typename range_t >
TRACCC_HOST_DEVICE range_t eta_to_theta_range (const range_t &eta_range)
bool operator== (const particle_hit_count &lhs, const particle &rhs)
bool operator< (const particle_hit_count &lhs, const particle_hit_count &rhs)
template<typename measurements_t , typename map_t >
std::vector< particle_hit_count > identify_contributing_particles (const measurements_t &measurements, const map_t &m_p_map)
Variables
constexpr scalar float_epsilon = 1e-5
constexpr scalar PION_MASS_MEV = 139.57018 * unit<scalar>::MeV
Detailed Description
TRACCC library, part of the ACTS project (R&D line)
(c) 2021-2022 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
TRACCC library, part of the ACTS project (R&D line)
(c) 2022 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
TRACCC library, part of the ACTS project (R&D line)
(c) 2021-2023 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
TRACCC library, part of the ACTS project (R&D line)
(c) 2023 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
TRACCC library, part of the ACTS project (R&D line)
(c) 2022-2023 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
TRACCC library, part of the ACTS project (R&D line)
(c) 2021 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
Detray library, part of the ACTS project (R&D line)
(c) 2022-2023 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
Detray library, part of the ACTS project (R&D line)
(c) 2023 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
Typedef Documentation
bound_covariance
using traccc::bound_covariance = typedef bound_track_parameters::covariance_type
bound_track_parameters
using traccc::bound_track_parameters = typedef detray::bound_track_parameters<transform3>
bound_track_parameters_collection_types
using traccc::bound_track_parameters_collection_types = typedef collection_types<bound_track_parameters>
Declare all track_parameters collection types.
bound_vector
using traccc::bound_vector = typedef bound_track_parameters::vector_type
cell_collection_types
using traccc::cell_collection_types = typedef collection_types<cell>
Declare all cell collection types.
cell_module_collection_types
using traccc::cell_module_collection_types = typedef collection_types<cell_module>
Declare all cell module collection types.
cell_particle_map
using traccc::cell_particle_map = typedef std::map<cell, particle>
channel_id
using traccc::channel_id = typedef unsigned int
cluster_container_types
using traccc::cluster_container_types = typedef container_types<std::monostate, cell>
Declare all cluster container types.
const_sp_grid_device
using traccc::const_sp_grid_device = typedef detray::grid2<detray::attach_populator, detray::axis::circular, detray::axis::regular, detray::serializer2, vecmem::device_vector, vecmem::jagged_device_vector, detray::darray, detray::dtuple, const internal_spacepoint<spacepoint>, false>
darray
template<typename value_type , unsigned int kDIM>
using traccc::darray = typedef std::array<value_type, kDIM>
demonstrator_input
using traccc::demonstrator_input = typedef vecmem::vector<io::cell_reader_output>
demonstrator_result
using traccc::demonstrator_result = typedef vecmem::vector<result>
digitization_config
using traccc::digitization_config = typedef Acts::GeometryHierarchyMap<module_digitization_config>
Type describing the digitization configuration for the whole detector.
djagged_vector
template<typename value_type >
using traccc::djagged_vector = typedef vecmem::jagged_vector<value_type>
dmap
template<typename key_type , typename value_type >
using traccc::dmap = typedef std::map<key_type, value_type>
doublet_collection_types
using traccc::doublet_collection_types = typedef collection_types<doublet>
Declare all doublet collection types.
doublet_container_types
using traccc::doublet_container_types = typedef container_types<std::monostate, doublet>
Declare all doublet container types.
dtuple
template<class... types>
using traccc::dtuple = typedef std::tuple<types...>
dvector
template<typename value_type >
using traccc::dvector = typedef vecmem::vector<value_type>
free_covariance
using traccc::free_covariance = typedef free_track_parameters::covariance_type
free_track_parameters
using traccc::free_track_parameters = typedef detray::free_track_parameters<transform3>
free_vector
using traccc::free_vector = typedef free_track_parameters::vector_type
geoId_link_map
using traccc::geoId_link_map = typedef std::map<geometry_id, unsigned int>
geometry
using traccc::geometry = typedef traccc::module_map<>
geometry_id
using traccc::geometry_id = typedef uint64_t
hit_cell_map
using traccc::hit_cell_map = typedef std::map<spacepoint, std::vector<cell> >
hit_id
using traccc::hit_id = typedef uint64_t
hit_map
using traccc::hit_map = typedef std::map<hit_id, spacepoint>
hit_particle_map
using traccc::hit_particle_map = typedef std::map<spacepoint, particle>
lin_circle_collection_types
using traccc::lin_circle_collection_types = typedef collection_types<lin_circle>
Declare all lin_circle collection types.
measurement_cell_map
using traccc::measurement_cell_map = typedef std::map<measurement, vecmem::vector<cell> >
measurement_collection_types
using traccc::measurement_collection_types = typedef collection_types<measurement>
Declare all measurement collection types.
measurement_container_types
using traccc::measurement_container_types = typedef container_types<cell_module, measurement>
Declare all measurement container types.
measurement_particle_map
using traccc::measurement_particle_map = typedef std::map<measurement, std::map<particle, uint64_t> >
particle_collection_types
using traccc::particle_collection_types = typedef collection_types<particle>
Declare all particle collection types.
particle_id
using traccc::particle_id = typedef uint64_t
particle_map
using traccc::particle_map = typedef std::map<particle_id, particle>
point2
using traccc::point2 = typedef __plugin::point2<traccc::scalar>
point3
using traccc::point3 = typedef __plugin::point3<traccc::scalar>
rvalue_or_const_lvalue
template<typename T >
using traccc::rvalue_or_const_lvalue = typedef std::disjunction< std::is_rvalue_reference<T>, std::conjunction<std::is_lvalue_reference<T>, std::is_const<std::remove_reference_t<T> >> >
scalar
typedef TRACCC_CUSTOM_SCALARTYPE traccc::scalar
seed_collection_types
using traccc::seed_collection_types = typedef collection_types<seed>
Declare all seed collection types.
sp_grid
using traccc::sp_grid = typedef detray::grid2<detray::attach_populator, detray::axis::circular, detray::axis::regular, detray::serializer2, detray::dvector, detray::djagged_vector, detray::darray, detray::dtuple, internal_spacepoint<spacepoint>, false>
sp_grid_buffer
using traccc::sp_grid_buffer = typedef detray::grid2_buffer<sp_grid>
sp_grid_const_data
using traccc::sp_grid_const_data = typedef detray::const_grid2_data<sp_grid>
sp_grid_const_view
using traccc::sp_grid_const_view = typedef detray::const_grid2_view<sp_grid>
sp_grid_data
using traccc::sp_grid_data = typedef detray::grid2_data<sp_grid>
sp_grid_device
using traccc::sp_grid_device = typedef detray::grid2< detray::attach_populator, detray::axis::circular, detray::axis::regular, detray::serializer2, vecmem::device_vector, vecmem::jagged_device_vector, detray::darray, detray::dtuple, internal_spacepoint<spacepoint>, false>
sp_grid_view
using traccc::sp_grid_view = typedef detray::grid2_view<sp_grid>
spacepoint_collection_types
using traccc::spacepoint_collection_types = typedef collection_types<spacepoint>
Declare all spacepoint collection types.
track_candidate
using traccc::track_candidate = typedef measurement
Track candidate is the measurement.
track_candidate_collection_types
using traccc::track_candidate_collection_types = typedef collection_types<track_candidate>
Declare a track candidates collection types.
track_candidate_container_types
using traccc::track_candidate_container_types = typedef container_types<bound_track_parameters, track_candidate>
Declare a track candidates container type.
track_state_collection_types
using traccc::track_state_collection_types = typedef collection_types<track_state<transform3> >
Declare all track_state collection types.
track_state_container_types
using traccc::track_state_container_types = typedef container_types<fitter_info<transform3>, track_state<transform3> >
Declare all track_state container types.
transform3
using traccc::transform3 = typedef __plugin::transform3<traccc::scalar>
triplet_collection_types
using traccc::triplet_collection_types = typedef collection_types<triplet>
Declare all triplet collection types.
triplet_container_types
using traccc::triplet_container_types = typedef container_types<std::monostate, triplet>
Declare all triplet container types.
unit
template<typename scalar_t >
using traccc::unit = typedef detray::unit<scalar_t>
variance2
using traccc::variance2 = typedef __plugin::point2<traccc::scalar>
variance3
using traccc::variance3 = typedef __plugin::point3<traccc::scalar>
vector2
using traccc::vector2 = typedef __plugin::point2<traccc::scalar>
vector3
using traccc::vector3 = typedef __plugin::point3<traccc::scalar>
Enumeration Type Documentation
bound_indices
enum traccc::bound_indices : unsigned int
Components of a bound track parameters vector.
TODO: consider to use enum class instead of enum
Enumerator
e_bound_loc0
e_bound_loc1
e_bound_phi
e_bound_theta
e_bound_qoverp
e_bound_time
e_bound_size
                   : unsigned int {
    // Local position on the reference surface.
    // This is intentionally named different from the position components in
    // the other data vectors, to clarify that this is defined on a surface
    // while the others are defined in free space.
    e_bound_loc0 = 0,
    e_bound_loc1 = 1,
    // Direction angles
    e_bound_phi = 2,
    e_bound_theta = 3,
    // Global inverse-momentum-like parameter, i.e. q/p or 1/p
    // The naming is inconsistent for the case of neutral track parameters where
    // the value is interpreted as 1/p not as q/p. This is intentional to avoid
    // having multiple aliases for the same element and for lack of an
    // acceptable
    // common name.
    e_bound_qoverp = 4,
    e_bound_time = 5,
    // Last uninitialized value contains the total number of components
    e_bound_size,
};
data_format
enum traccc::data_format : int
Format for an input or output file.
Enumerator
csv
binary
json
                 : int {
    csv = 0,
    binary = 1,
    json = 2,
};
free_indices
enum traccc::free_indices : unsigned int
Components of a free track parameters vector.
To be used to access components by named indices instead of just numbers. This must be a regular enum and not a scoped enum class to allow implicit conversion to an integer. The enum value are thus visible directly in namespace Acts and are prefixed to avoid naming collisions.
Enumerator
e_free_pos0
e_free_pos1
e_free_pos2
e_free_time
e_free_dir0
e_free_dir1
e_free_dir2
e_free_qoverp
e_free_size
                  : unsigned int {
    // Spatial position
    // The spatial position components must be stored as one continous block.
    e_free_pos0 = 0u,
    e_free_pos1 = e_free_pos0 + 1u,
    e_free_pos2 = e_free_pos0 + 2u,
    // Time
    e_free_time = 3u,
    // (Unit) direction
    // The direction components must be stored as one continous block.
    e_free_dir0 = 4u,
    e_free_dir1 = e_free_dir0 + 1u,
    e_free_dir2 = e_free_dir0 + 2u,
    // Global inverse-momentum-like parameter, i.e. q/p or 1/p
    // See BoundIndices for further information
    e_free_qoverp = 7u,
    // Last uninitialized value contains the total number of components
    e_free_size,
};
Function Documentation
_get_ptrs()
template<std::size_t... Ns, typename... Ts>
std::tuple<Ts*...> traccc::_get_ptrs (std::index_sequence< Ns... > , const std::tuple< vecmem::unique_alloc_ptr< Ts[]>... > & o)
Helper function to convert a list of unique pointers to raw pointers.
                                                        {
    return {std::get<Ns>(o).get()...};
}
compose()
template<typename A , typename B , typename C , typename... R>
auto traccc::compose (std::function< std::remove_const_t< std::remove_reference_t< B >>(A)> f, std::function< C(B)> g, R... rs)
                                  {
    if constexpr (sizeof...(R) > 0) {
        auto h = compose(g, rs...);
        return [f, h](A&& i) { return h(f(std::forward<A>(i))); };
    } else {
        return [f, g](A&& i) { return g(f(std::forward<A>(i))); };
    }
}
Referenced by TEST().
eta_to_theta_range()
template<typename range_t >
TRACCC_HOST_DEVICE range_t traccc::eta_to_theta_range (const range_t & eta_range) [inline]
                                                                               {
    // @NOTE: eta_range[0] is converted to theta_range[1] and eta_range[1]
    // to theta_range[0] because theta(minEta) > theta(maxEta)
    return {2 * std::atan(std::exp(-eta_range[1])),
            2 * std::atan(std::exp(-eta_range[0]))};
}
Referenced by traccc::particle_gen_options< scalar_t >::read(), TEST(), and TEST_P().
from_json()
void traccc::from_json (const nlohmann::json & json, module_digitization_config & cfg)
Function allowing the read of traccc::module_digitization_config objects
Note that this function must be declared in the same namespace as traccc::module_digitization_config for nlohmann_json to work correctly.
                                                                          {
    // Names/keywords used in the JSON file.
    static const char* geometric = "geometric";
    static const char* segmentation = "segmentation";
    // Read the object, if possible.
    if (json.find(geometric) != json.end()) {
        from_json(json[geometric][segmentation], cfg.segmentation);
    }
}
References json, and traccc::module_digitization_config::segmentation.
generate_cell_particle_map()
cell_particle_map traccc::generate_cell_particle_map (std::size_t event, const std::string & cells_dir, const std::string & hits_dir, const std::string & particle_dir, const geoId_link_map & link_map = geoId_link_map())
                                                                             {
    cell_particle_map result;
    auto h_p_map =
        generate_hit_particle_map(event, hits_dir, particle_dir, link_map);
    auto h_c_map = generate_hit_cell_map(event, cells_dir, hits_dir, link_map);
    for (auto const& [hit, ptc] : h_p_map) {
        auto& cells = h_c_map[hit];
        for (auto& c : cells) {
            result[c] = ptc;
        }
    }
    return result;
}
References cells_dir, event, generate_hit_cell_map(), generate_hit_particle_map(), and hits_dir.
Referenced by generate_measurement_particle_map(), and TEST().
generate_hit_cell_map()
hit_cell_map traccc::generate_hit_cell_map (std::size_t event, const std::string & cells_dir, const std::string & hits_dir, const geoId_link_map & link_map = geoId_link_map())
                                                                   {
    hit_cell_map result;
    auto hmap = generate_hit_map(event, hits_dir);
    // Read the cells from the relevant event file
    std::string io_cells_file = io::data_directory() + cells_dir +
                                io::get_event_filename(event, "-cells.csv");
    auto creader = io::csv::make_cell_reader(io_cells_file);
    io::csv::cell iocell;
    while (creader.read(iocell)) {
        unsigned int link = 0;
        auto it = link_map.find(iocell.geometry_id);
        if (it != link_map.end()) {
            link = (*it).second;
        }
        result[hmap[iocell.hit_id]].push_back(
            cell{iocell.channel0, iocell.channel1, iocell.value,
                 iocell.timestamp, link});
    }
    return result;
}
References cells_dir, traccc::io::csv::cell::channel0, traccc::io::csv::cell::channel1, traccc::tests::data_test::data_directory, event, generate_hit_map(), traccc::io::csv::cell::geometry_id, traccc::io::get_event_filename(), traccc::io::csv::cell::hit_id, hits_dir, traccc::io::csv::make_cell_reader(), traccc::io::csv::cell::timestamp, and traccc::io::csv::cell::value.
Referenced by generate_cell_particle_map(), and TEST().
generate_hit_map()
hit_map traccc::generate_hit_map (std::size_t event, const std::string & hits_dir)
                                                                     {
    hit_map result;
    // Read the hits from the relevant event file
    std::string io_hits_file = io::data_directory() + hits_dir +
                               io::get_event_filename(event, "-hits.csv");
    auto hreader = io::csv::make_hit_reader(io_hits_file);
    io::csv::hit iohit;
    // Read the hits from the relevant event file
    std::string io_measurement_hit_id_file =
        io::data_directory() + hits_dir +
        io::get_event_filename(event, "-measurement-simhit-map.csv");
    auto mhid_reader =
        io::csv::make_measurement_hit_id_reader(io_measurement_hit_id_file);
    io::csv::measurement_hit_id mh_id;
    std::map<uint64_t, uint64_t> mh_id_map;
    while (mhid_reader.read(mh_id)) {
        mh_id_map[mh_id.hit_id] = mh_id.measurement_id;
    }
    hit_id hid = 0;
    while (hreader.read(iohit)) {
        spacepoint sp;
        sp.global = {iohit.tx, iohit.ty, iohit.tz};
        // result[hid] = sp;
        result[mh_id_map[hid]] = sp;
        hid++;
    }
    return result;
}
References traccc::tests::data_test::data_directory, event, traccc::io::get_event_filename(), traccc::spacepoint::global, traccc::io::csv::measurement_hit_id::hit_id, hits_dir, traccc::io::csv::make_hit_reader(), traccc::io::csv::make_measurement_hit_id_reader(), traccc::io::csv::measurement_hit_id::measurement_id, traccc::io::csv::hit::tx, traccc::io::csv::hit::ty, and traccc::io::csv::hit::tz.
Referenced by generate_hit_cell_map(), and TEST().
generate_hit_particle_map()
hit_particle_map traccc::generate_hit_particle_map (std::size_t event, const std::string & hits_dir, const std::string & particle_dir, const geoId_link_map & link_map = geoId_link_map())
                                                                           {
    hit_particle_map result;
    auto pmap = generate_particle_map(event, particle_dir);
    // Read the hits from the relevant event file
    std::string io_hits_file = io::data_directory() + hits_dir +
                               io::get_event_filename(event, "-hits.csv");
    auto hreader = io::csv::make_hit_reader(io_hits_file);
    io::csv::hit iohit;
    while (hreader.read(iohit)) {
        spacepoint sp;
        sp.global = {iohit.tx, iohit.ty, iohit.tz};
        unsigned int link = 0;
        auto it = link_map.find(iohit.geometry_id);
        if (it != link_map.end()) {
            link = (*it).second;
        }
        sp.meas.module_link = link;
        particle ptc = pmap[iohit.particle_id];
        result[sp] = ptc;
    }
    return result;
}
References traccc::tests::data_test::data_directory, event, generate_particle_map(), traccc::io::csv::hit::geometry_id, traccc::io::get_event_filename(), traccc::spacepoint::global, hits_dir, traccc::io::csv::make_hit_reader(), traccc::spacepoint::meas, traccc::measurement::module_link, traccc::io::csv::hit::particle_id, traccc::io::csv::hit::tx, traccc::io::csv::hit::ty, and traccc::io::csv::hit::tz.
Referenced by generate_cell_particle_map(), generate_measurement_particle_map(), and TEST().
generate_measurement_cell_map()
std::tuple< measurement_cell_map, cell_module_collection_types::host > traccc::generate_measurement_cell_map (std::size_t event, const std::string & detector_file, const std::string & digi_config_file, const std::string & cells_dir, vecmem::memory_resource & resource)
                                                               {
    measurement_cell_map result;
    // CCA algorithms
    component_connection cc(resource);
    measurement_creation mc(resource);
    // Read the surface transforms
    auto surface_transforms = io::read_geometry(detector_file);
    // Read the digitization configuration file
    auto digi_cfg = io::read_digitization_config(digi_config_file);
    // Read the cells from the relevant event file
    traccc::io::cell_reader_output readOut(&resource);
    io::read_cells(readOut, event, cells_dir, traccc::data_format::csv,
                   &surface_transforms, &digi_cfg);
    cell_collection_types::host& cells_per_event = readOut.cells;
    cell_module_collection_types::host& modules_per_event = readOut.modules;
    auto clusters_per_event = cc(cells_per_event);
    auto measurements_per_event = mc(clusters_per_event, modules_per_event);
    assert(measurements_per_event.size() == clusters_per_event.size());
    for (unsigned int i = 0; i < measurements_per_event.size(); ++i) {
        const auto& clus = clusters_per_event.get_items()[i];
        result[measurements_per_event[i]] = clus;
    }
    return {result, modules_per_event};
}
References traccc::io::cell_reader_output::cells, cells_dir, csv, detector_file, digi_config_file, event, traccc::io::cell_reader_output::modules, traccc::io::read_cells(), traccc::io::read_digitization_config(), and traccc::io::read_geometry().
Referenced by generate_measurement_particle_map(), and TEST().
generate_measurement_particle_map() [1/2]
measurement_particle_map traccc::generate_measurement_particle_map (std::size_t event, const std::string & detector_file, const std::string & digi_config_file, const std::string & cells_dir, const std::string & hits_dir, const std::string & particle_dir, vecmem::memory_resource & resource)
                                     {
    measurement_particle_map result;
    // generate measurement cell map
    auto gen_m_c_map = generate_measurement_cell_map(
        event, detector_file, digi_config_file, cells_dir, resource);
    auto& m_c_map = std::get<0>(gen_m_c_map);
    auto& modules = std::get<1>(gen_m_c_map);
    // generate geometry_id link map
    geoId_link_map link_map;
    for (unsigned int i = 0; i < modules.size(); ++i) {
        link_map[modules[i].surface_link.value()] = i;
    }
    // generate cell particle map
    auto c_p_map = generate_cell_particle_map(event, cells_dir, hits_dir,
                                              particle_dir, link_map);
    for (auto const& [meas, cells] : m_c_map) {
        for (const auto& c : cells) {
            result[meas][c_p_map[c]]++;
        }
    }
    return result;
}
References cells_dir, detector_file, digi_config_file, event, generate_cell_particle_map(), generate_measurement_cell_map(), and hits_dir.
Referenced by traccc::event_map::event_map(), and TEST().
generate_measurement_particle_map() [2/2]
measurement_particle_map traccc::generate_measurement_particle_map (std::size_t event, const std::string & detector_file, const std::string & hits_dir, const std::string & particle_dir, vecmem::memory_resource & resource)
                                     {
    measurement_particle_map result;
    // Read the surface transforms
    auto surface_transforms = io::read_geometry(detector_file);
    // Read the spacepoints from the relevant event file
    traccc::io::spacepoint_reader_output readOut(&resource);
    io::read_spacepoints(readOut, event, hits_dir, surface_transforms,
                         traccc::data_format::csv);
    spacepoint_collection_types::host& spacepoints_per_event =
        readOut.spacepoints;
    cell_module_collection_types::host& modules = readOut.modules;
    geoId_link_map link_map;
    for (unsigned int i = 0; i < modules.size(); ++i) {
        link_map[modules[i].surface_link.value()] = i;
    }
    auto h_p_map =
        generate_hit_particle_map(event, hits_dir, particle_dir, link_map);
    for (const auto& hit : spacepoints_per_event) {
        const auto& meas = hit.meas;
        spacepoint new_hit;
        new_hit.global = hit.global;
        const auto& ptc = h_p_map[new_hit];
        result[meas][ptc]++;
    }
    return result;
}
References csv, detector_file, event, generate_hit_particle_map(), traccc::spacepoint::global, hits_dir, traccc::io::spacepoint_reader_output::modules, traccc::io::read_geometry(), traccc::io::read_spacepoints(), and traccc::io::spacepoint_reader_output::spacepoints.
generate_particle_map()
particle_map traccc::generate_particle_map (std::size_t event, const std::string & particle_dir)
                                                                  {
    particle_map result;
    // Read the particles from the relevant event file
    std::string io_particles_file =
        io::data_directory() + particle_dir +
        io::get_event_filename(event, "-particles_initial.csv");
    auto preader = io::csv::make_particle_reader(io_particles_file);
    io::csv::particle ioptc;
    while (preader.read(ioptc)) {
        point3 pos{ioptc.vx, ioptc.vy, ioptc.vz};
        vector3 mom{ioptc.px, ioptc.py, ioptc.pz};
        result[ioptc.particle_id] =
            particle{ioptc.particle_id, ioptc.particle_type,
                     ioptc.process, pos,
                     ioptc.vt, mom,
                     ioptc.m, ioptc.q};
    }
    return result;
}
References traccc::tests::data_test::data_directory, event, traccc::io::get_event_filename(), traccc::io::csv::particle::m, traccc::io::csv::make_particle_reader(), traccc::io::csv::particle::particle_id, traccc::io::csv::particle::particle_type, traccc::io::csv::particle::process, traccc::io::csv::particle::px, traccc::io::csv::particle::py, traccc::io::csv::particle::pz, traccc::io::csv::particle::q, traccc::io::csv::particle::vt, traccc::io::csv::particle::vx, traccc::io::csv::particle::vy, and traccc::io::csv::particle::vz.
Referenced by traccc::event_map::event_map(), generate_hit_particle_map(), and TEST().
get_axes()
std::pair<detray::axis::circular<>, detray::axis::regular<> > traccc::get_axes (const spacepoint_grid_config & grid_config, vecmem::memory_resource & mr) [inline]
                                                                          {
    detray::dindex phiBins;
    if (grid_config.bFieldInZ == 0) {
        phiBins = 100;
    } else {
        // calculate circle intersections of helix and max detector radius
        scalar minHelixRadius = grid_config.minPt / grid_config.bFieldInZ;
        // sanity check: if yOuter takes the square root of a negative number
        if (minHelixRadius < grid_config.rMax / 2) {
            throw std::domain_error(
                "The value of minHelixRadius cannot be smaller than rMax / 2. "
                "Please "
                "check the configuration of bFieldInZ and minPt");
        }
        scalar maxR2 = grid_config.rMax * grid_config.rMax;
        scalar xOuter = maxR2 / (2 * minHelixRadius);
        scalar yOuter = std::sqrt(maxR2 - xOuter * xOuter);
        scalar outerAngle = std::atan(xOuter / yOuter);
        // intersection of helix and max detector radius minus maximum R
        // distance from middle SP to top SP
        scalar innerAngle = 0;
        scalar rMin = grid_config.rMax;
        if (grid_config.rMax > grid_config.deltaRMax) {
            rMin = grid_config.rMax - grid_config.deltaRMax;
            scalar innerCircleR2 = (grid_config.rMax - grid_config.deltaRMax) *
                                   (grid_config.rMax - grid_config.deltaRMax);
            scalar xInner = innerCircleR2 / (2 * minHelixRadius);
            scalar yInner = std::sqrt(innerCircleR2 - xInner * xInner);
            innerAngle = std::atan(xInner / yInner);
        }
        // evaluating the azimutal deflection including the maximum impact
        // parameter
        scalar deltaAngleWithMaxD0 =
            std::abs(std::asin(grid_config.impactMax / (rMin)) -
                     std::asin(grid_config.impactMax / grid_config.rMax));
        // evaluating delta Phi based on the inner and outer angle, and the
        // azimutal deflection including the maximum impact parameter Divide by
        // config.phiBinDeflectionCoverage since we combine
        // config.phiBinDeflectionCoverage number of consecutive phi bins in the
        // seed making step. So each individual bin should cover
        // 1/config.phiBinDeflectionCoverage of the maximum expected azimutal
        // deflection
        scalar deltaPhi = (outerAngle - innerAngle + deltaAngleWithMaxD0) /
                          grid_config.phiBinDeflectionCoverage;
        // sanity check: if the delta phi is equal to or less than zero, we'll
        // be creating an infinite or a negative number of bins, which would be
        // bad!
        if (deltaPhi <= 0.) {
            throw std::domain_error(
                "Delta phi value is equal to or less than zero, leading to an "
                "impossible number of bins (negative or infinite)");
        }
        // divide 2pi by angle delta to get number of phi-bins
        // size is always 2pi even for regions of interest
        phiBins = std::ceil(2 * M_PI / deltaPhi);
        // need to scale the number of phi bins accordingly to the number of
        // consecutive phi bins in the seed making step.
        // Each individual bin should be approximately a fraction (depending on
        // this number) of the maximum expected azimutal deflection.
    }
    detray::axis::circular m_phi_axis{phiBins, grid_config.phiMin,
                                      grid_config.phiMax, mr};
    // TODO: can probably be optimized using smaller z bins
    // and returning (multiple) neighbors only in one z-direction for forward
    // seeds
    // FIXME: zBinSize must include scattering
    scalar zBinSize = grid_config.cotThetaMax * grid_config.deltaRMax;
    detray::dindex zBins = std::max(
        1, (int)std::floor((grid_config.zMax - grid_config.zMin) / zBinSize));
    detray::axis::regular m_z_axis{zBins, grid_config.zMin, grid_config.zMax,
                                   mr};
    return {m_phi_axis, m_z_axis};
}
References traccc::spacepoint_grid_config::bFieldInZ, traccc::spacepoint_grid_config::cotThetaMax, traccc::spacepoint_grid_config::deltaRMax, if(), traccc::spacepoint_grid_config::impactMax, traccc::spacepoint_grid_config::minPt, traccc::spacepoint_grid_config::phiBinDeflectionCoverage, traccc::spacepoint_grid_config::phiMax, traccc::spacepoint_grid_config::phiMin, traccc::spacepoint_grid_config::rMax, traccc::spacepoint_grid_config::zMax, and traccc::spacepoint_grid_config::zMin.
get_data() [1/2]
template<typename header_t , typename item_t >
container_data<const header_t, const item_t> traccc::get_data (const host_container< header_t, item_t > & cc, vecmem::memory_resource * resource = nullptr) [inline]
Helper function for making a `simple` object out of the container (const)
                                               {
    return {{vecmem::get_data(cc.get_headers())},
            {vecmem::get_data(cc.get_items(), resource)}};
}
References traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::get_headers(), and traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::get_items().
Referenced by get_data().
get_data() [2/2]
template<typename header_t , typename item_t >
container_data<header_t, item_t> traccc::get_data (host_container< header_t, item_t > & cc, vecmem::memory_resource * resource = nullptr) [inline]
Helper function for making a `simple` object out of the container (non-const)
                                               {
    return {{vecmem::get_data(cc.get_headers())},
            {vecmem::get_data(cc.get_items(), resource)}};
}
References get_data(), traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::get_headers(), and traccc::container_base< header_t, item_t, vecmem::vector, vecmem::jagged_vector >::get_items().
Referenced by create_binaries(), main(), traccc::kokkos::make_prefix_sum_buff(), traccc::alpaka::make_prefix_sum_buff(), traccc::device::make_prefix_sum_buffer(), traccc::cuda::full_chain_algorithm::operator()(), seq_run(), TEST(), and TEST_P().
handle_argument_errors()
void traccc::handle_argument_errors (po::variables_map & vm, const po::options_description & desc)
Referenced by main(), throughput_mt(), and throughput_st().
identify_contributing_particles()
template<typename measurements_t , typename map_t >
std::vector<particle_hit_count> traccc::identify_contributing_particles (const measurements_t & measurements, const map_t & m_p_map)
                                                              {
    std::vector<particle_hit_count> result;
    for (const auto& meas : measurements) {
        const auto mp_it = m_p_map.find(meas);
        if (mp_it == m_p_map.end()) {
            continue;
        }
        const auto& ptcs = mp_it->second;
        for (auto const& [ptc, count] : ptcs) {
            auto it = std::find(result.begin(), result.end(), ptc);
            // particle has been already added to the result vector
            if (it != result.end()) {
                it->hit_counts += count;
            }
            // particle has not been added
            else {
                result.push_back({ptc, count});
            }
        }
    }
    std::sort(result.rbegin(), result.rend());
    return result;
}
Referenced by traccc::finding_performance_writer::write(), and traccc::seeding_performance_writer::write().
is_valid_sp()
TRACCC_HOST_DEVICE size_t traccc::is_valid_sp (const seedfinder_config & config, const spacepoint & sp) [inline]
                                                                   {
    if (sp.z() > config.zMax || sp.z() < config.zMin) {
        return detray::detail::invalid_value<size_t>();
    }
    scalar spPhi = algebra::math::atan2(sp.y(), sp.x());
    if (spPhi > config.phiMax || spPhi < config.phiMin) {
        return detray::detail::invalid_value<size_t>();
    }
    size_t r_index = getter::perp(
        vector2{sp.x() - config.beamPos[0], sp.y() - config.beamPos[1]});
    if (r_index < config.get_num_rbins()) {
        return r_index;
    }
    return detray::detail::invalid_value<size_t>();
}
References traccc::seedfinder_config::beamPos, traccc::seedfinder_config::get_num_rbins(), traccc::seedfinder_config::phiMax, traccc::seedfinder_config::phiMin, traccc::spacepoint::x(), traccc::spacepoint::y(), traccc::spacepoint::z(), traccc::seedfinder_config::zMax, and traccc::seedfinder_config::zMin.
Referenced by traccc::device::count_grid_capacities(), traccc::spacepoint_binning::operator()(), traccc::alpaka::PopulateGridKernel::operator()(), and traccc::device::populate_grid().
operator!=() [1/2]
TRACCC_HOST_DEVICE bool traccc::operator!= (const sp_location & lhs, const sp_location & rhs) [inline]
                                                                  {
    return (lhs.bin_idx != rhs.bin_idx || lhs.sp_idx != rhs.sp_idx);
}
References traccc::sp_location::bin_idx, and traccc::sp_location::sp_idx.
operator!=() [2/2]
TRACCC_HOST_DEVICE bool traccc::operator!= (const triplet & lhs, const triplet & rhs) [inline]
                                                              {
    return !(lhs == rhs);
}
operator<() [1/7]
TRACCC_HOST_DEVICE bool traccc::operator< (const cell & lhs, const cell & rhs) [inline]
                                                        {
    if (lhs.module_link != rhs.module_link) {
        return lhs.module_link < rhs.module_link;
    } else if (lhs.channel0 != rhs.channel0) {
        return (lhs.channel0 < rhs.channel0);
    } else if (lhs.channel1 != rhs.channel1) {
        return (lhs.channel1 < rhs.channel1);
    } else {
        return lhs.activation < rhs.activation;
    }
}
References traccc::cell::activation, traccc::cell::channel0, traccc::cell::channel1, and traccc::cell::module_link.
operator<() [2/7]
template<typename spacepoint_t >
bool traccc::operator< (const internal_spacepoint< spacepoint_t > & lhs, const internal_spacepoint< spacepoint_t > & rhs) [inline]
                                                                    {
    return (lhs.radius() < rhs.radius());
}
References traccc::internal_spacepoint< spacepoint_t >::radius().
operator<() [3/7]
TRACCC_HOST_DEVICE bool traccc::operator< (const measurement & lhs, const measurement & rhs) [inline]
Comparison / ordering operator for measurements.
                                                                 {
    if (lhs.surface_link != rhs.surface_link) {
        return lhs.surface_link < rhs.surface_link;
    } else if (std::abs(lhs.local[0] - rhs.local[0]) > float_epsilon) {
        return (lhs.local[0] < rhs.local[0]);
    } else {
        return (lhs.local[1] < rhs.local[1]);
    }
}
References float_epsilon, traccc::measurement::local, and traccc::measurement::surface_link.
operator<() [4/7]
bool traccc::operator< (const particle & lhs, const particle & rhs) [inline]
                                                                {
    if (lhs.particle_id < rhs.particle_id) {
        return true;
    }
    return false;
}
References traccc::particle::particle_id.
operator<() [5/7]
bool traccc::operator< (const particle_hit_count & lhs, const particle_hit_count & rhs) [inline]
                                                     {
    if (lhs.hit_counts < rhs.hit_counts) {
        return true;
    }
    return false;
}
References traccc::particle_hit_count::hit_counts.
operator<() [6/7]
TRACCC_HOST_DEVICE bool traccc::operator< (const spacepoint & lhs, const spacepoint & rhs) [inline]
Comparison / ordering operator for spacepoints.
                                                                    {
    if (std::abs(lhs.x() - rhs.x()) > float_epsilon) {
        return (lhs.x() < rhs.x());
    } else if (std::abs(lhs.y() - rhs.y()) > float_epsilon) {
        return (lhs.y() < rhs.y());
    } else {
        return (lhs.z() < rhs.z());
    }
}
References float_epsilon, traccc::spacepoint::x(), traccc::spacepoint::y(), and traccc::spacepoint::z().
operator<() [7/7]
TRACCC_HOST_DEVICE bool traccc::operator< (const triplet & lhs, const triplet & rhs) [inline]
                                                             {
    return lhs.weight < rhs.weight;
}
References traccc::triplet::weight.
operator<<() [1/4]
template<typename scalar_t , size_t kSize>
std::ostream& traccc::operator<< (std::ostream & os, const Reals< scalar_t, kSize > & values) [inline]
Print a fixed number of doubles as x:y:z.
                                                                      {
    const auto data = values.data();
    for (size_t i = 0; i < kSize; ++i) {
        if (0u < i) {
            os << s_separator;
        }
        os << data[i];
    }
    return os;
}
operator<<() [2/4]
std::ostream & traccc::operator<< (std::ostream & out, const mt_options & opt)
Printout helper for traccc::mt_options.
                                                               {
    out << ">>> Multi-threading options <<<\n"
        << "CPU threads: " << opt.threads;
    return out;
}
References traccc::mt_options::threads.
operator<<() [3/4]
std::ostream & traccc::operator<< (std::ostream & out, const throughput_options & opt)
Printout helper for traccc::throughput_options.
                                                                       {
    out << ">>> Throughput options <<<\n"
        << "Input data format : " << opt.input_data_format << "\n"
        << "Input directory : " << opt.input_directory << "\n"
        << "Detector geometry : " << opt.detector_file << "\n"
        << "Digitization config : " << opt.digitization_config_file
        << "\n"
        << "Target cells per partition : " << opt.target_cells_per_partition
        << "\n"
        << "Loaded event(s) : " << opt.loaded_events << "\n"
        << "Cold run event(s) : " << opt.cold_run_events << "\n"
        << "Processed event(s) : " << opt.processed_events << "\n"
        << "Log_file : " << opt.log_file;
    return out;
}
References traccc::throughput_options::cold_run_events, traccc::throughput_options::detector_file, traccc::throughput_options::digitization_config_file, traccc::throughput_options::input_data_format, traccc::throughput_options::input_directory, traccc::throughput_options::loaded_events, traccc::throughput_options::log_file, traccc::throughput_options::processed_events, and traccc::throughput_options::target_cells_per_partition.
operator<<() [4/4]
std::ostream & traccc::operator<< (std::ostream & out, data_format format)
Printout helper for traccc::data_format.
                                                            {
    switch (format) {
        case data_format::csv:
            out << "csv";
            break;
        case data_format::binary:
            out << "binary";
            break;
        case data_format::json:
            out << "json";
            break;
        default:
            out << "?!?unknown?!?";
            break;
    }
    return out;
}
References binary, csv, and json.
operator==() [1/8]
TRACCC_HOST_DEVICE bool traccc::operator== (const cell & lhs, const cell & rhs) [inline]
Equality operator for cells.
                                                         {
    return ((lhs.module_link == rhs.module_link) &&
            (lhs.channel0 == rhs.channel0) && (lhs.channel1 == rhs.channel1) &&
            (std::abs(lhs.activation - rhs.activation) < float_epsilon) &&
            (std::abs(lhs.time - rhs.time) < float_epsilon));
}
References traccc::cell::activation, traccc::cell::channel0, traccc::cell::channel1, float_epsilon, traccc::cell::module_link, and traccc::cell::time.
operator==() [2/8]
TRACCC_HOST_DEVICE bool traccc::operator== (const cell_module & lhs, const cell_module & rhs) [inline]
Equality operator for cell module.
                                                                       {
    return lhs.surface_link == rhs.surface_link;
}
References traccc::cell_module::surface_link.
operator==() [3/8]
TRACCC_HOST_DEVICE bool traccc::operator== (const doublet & lhs, const doublet & rhs) [inline]
                                                              {
    return (lhs.sp1.bin_idx == rhs.sp1.bin_idx &&
            lhs.sp1.sp_idx == rhs.sp1.sp_idx &&
            lhs.sp2.bin_idx == rhs.sp2.bin_idx &&
            lhs.sp2.sp_idx == rhs.sp2.sp_idx);
}
References traccc::sp_location::bin_idx, traccc::doublet::sp1, traccc::doublet::sp2, and traccc::sp_location::sp_idx.
operator==() [4/8]
TRACCC_HOST_DEVICE bool traccc::operator== (const measurement & lhs, const measurement & rhs) [inline]
Equality operator for measurements.
                                                                       {
    return ((lhs.surface_link == rhs.surface_link) &&
            (std::abs(lhs.local[0] - rhs.local[0]) < float_epsilon) &&
            (std::abs(lhs.local[1] - rhs.local[1]) < float_epsilon) &&
            (std::abs(lhs.variance[0] - rhs.variance[0]) < float_epsilon) &&
            (std::abs(lhs.variance[1] - rhs.variance[1]) < float_epsilon));
}
References float_epsilon, traccc::measurement::local, traccc::measurement::surface_link, and traccc::measurement::variance.
operator==() [5/8]
bool traccc::operator== (const particle_hit_count & lhs, const particle & rhs) [inline]
                                                                           {
    if (lhs.ptc.particle_id == rhs.particle_id) {
        return true;
    }
    return false;
}
References traccc::particle::particle_id, and traccc::particle_hit_count::ptc.
operator==() [6/8]
TRACCC_HOST_DEVICE bool traccc::operator== (const sp_location & lhs, const sp_location & rhs) [inline]
                                                                  {
    return (lhs.bin_idx == rhs.bin_idx && lhs.sp_idx == rhs.sp_idx);
}
References traccc::sp_location::bin_idx, and traccc::sp_location::sp_idx.
operator==() [7/8]
TRACCC_HOST_DEVICE bool traccc::operator== (const spacepoint & lhs, const spacepoint & rhs) [inline]
Equality operator for spacepoints.
                                                                     {
    return ((std::abs(lhs.x() - rhs.x()) < float_epsilon) &&
            (std::abs(lhs.y() - rhs.y()) < float_epsilon) &&
            (std::abs(lhs.z() - rhs.z()) < float_epsilon) &&
            (lhs.meas == rhs.meas));
}
References float_epsilon, traccc::spacepoint::meas, traccc::spacepoint::x(), traccc::spacepoint::y(), and traccc::spacepoint::z().
operator==() [8/8]
TRACCC_HOST_DEVICE bool traccc::operator== (const triplet & lhs, const triplet & rhs) [inline]
                                                              {
    return (lhs.sp1.bin_idx == rhs.sp1.bin_idx &&
            lhs.sp1.sp_idx == rhs.sp1.sp_idx &&
            lhs.sp2.bin_idx == rhs.sp2.bin_idx &&
            lhs.sp2.sp_idx == rhs.sp2.sp_idx &&
            lhs.sp3.bin_idx == rhs.sp3.bin_idx &&
            lhs.sp3.sp_idx == rhs.sp3.sp_idx);
}
References traccc::sp_location::bin_idx, traccc::triplet::sp1, traccc::triplet::sp2, traccc::triplet::sp3, and traccc::sp_location::sp_idx.
operator>>()
template<typename scalar_t , size_t kSize>
std::istream& traccc::operator>> (std::istream & is, Reals< scalar_t, kSize > & values) [inline]
Extract a fixed number of doubles from an input of the form 'x:y:z'.
Note
If the values would be separated by whitespace, negative values and additional command line both start with - and would be undistinguishable.
                                                                {
    detail::parse_fixed(is, kSize, values.data(),
                        [](const std::string& s) { return std::stod(s); });
    return is;
}
References traccc::detail::parse_fixed().
pod_get()
template<std::size_t I, typename... Ts>
constexpr auto& traccc::pod_get (pod< Ts... > & p) [constexpr]
Get a given value from a POD tuple.
Template Parameters
I The index in the POD type to retrieve.
Ts The types of the POD tuple.
Parameters
p A valid of the POD tuple type described by Ts....
Returns
A value of type Ts[I] as contained in p.
                                       {
    if constexpr (I == 0) {
        return p.v;
    } else {
        return pod_get<I - 1>(p.r);
    }
}
seed_to_bound_vector()
template<typename spacepoint_collection_t >
TRACCC_HOST_DEVICE bound_vector traccc::seed_to_bound_vector (const spacepoint_collection_t & sp_collection, const seed & seed, const vector3 & bfield, const scalar mass) [inline]
helper functions (for both cpu and gpu) to calculate bound track parameter at the bottom spacepoint
Parameters
seed is the input seed
bfield is the magnetic field
mass is the mass of particle
                                              {
    bound_vector params;
    const auto& spB = sp_collection.at(seed.spB_link);
    const auto& spM = sp_collection.at(seed.spM_link);
    const auto& spT = sp_collection.at(seed.spT_link);
    darray<vector3, 3> sp_global_positions;
    sp_global_positions[0] = spB.global;
    sp_global_positions[1] = spM.global;
    sp_global_positions[2] = spT.global;
    // Define a new coordinate frame with its origin at the bottom space
    // point, z axis long the magnetic field direction and y axis
    // perpendicular to vector from the bottom to middle space point.
    // Hence, the projection of the middle space point on the tranverse
    // plane will be located at the x axis of the new frame.
    vector3 relVec = sp_global_positions[1] - sp_global_positions[0];
    vector3 newZAxis = vector::normalize(bfield);
    vector3 newYAxis = vector::normalize(vector::cross(newZAxis, relVec));
    vector3 newXAxis = vector::cross(newYAxis, newZAxis);
    // The center of the new frame is at the bottom space point
    vector3 translation = sp_global_positions[0];
    transform3 trans(translation, newZAxis, newXAxis);
    // The coordinate of the middle and top space point in the new frame
    auto local1 = trans.point_to_local(sp_global_positions[1]);
    auto local2 = trans.point_to_local(sp_global_positions[2]);
    // The uv1.y() should be zero
    vector2 uv1 = uv_transform(local1[0], local1[1]);
    vector2 uv2 = uv_transform(local2[0], local2[1]);
    // A,B are slope and intercept of the straight line in the u,v plane
    // connecting the three points
    scalar A = (uv2[1] - uv1[1]) / (uv2[0] - uv1[0]);
    scalar B = uv2[1] - A * uv2[0];
    // Curvature (with a sign) estimate
    scalar rho = -2.0f * B / getter::perp(vector2{1., A});
    // The projection of the top space point on the transverse plane of
    // the new frame
    scalar rn = local2[0] * local2[0] + local2[1] * local2[1];
    // The (1/tanTheta) of momentum in the new frame
    static constexpr scalar G = static_cast<scalar>(1.f / 24.f);
    scalar invTanTheta =
        local2[2] * std::sqrt(1.f / rn) / (1.f + G * rho * rho * rn);
    // The momentum direction in the new frame (the center of the circle
    // has the coordinate (-1.*A/(2*B), 1./(2*B)))
    vector3 transDirection =
        vector3({1., A, scalar(getter::perp(vector2{1., A})) * invTanTheta});
    // Transform it back to the original frame
    vector3 direction =
        transform3::rotate(trans._data, vector::normalize(transDirection));
    // The estimated phi and theta
    getter::element(params, e_bound_phi, 0) = getter::phi(direction);
    getter::element(params, e_bound_theta, 0) = getter::theta(direction);
    // The measured loc0 and loc1
    const auto& meas_for_spB = spB.meas;
    getter::element(params, e_bound_loc0, 0) = meas_for_spB.local[0];
    getter::element(params, e_bound_loc1, 0) = meas_for_spB.local[1];
    // The estimated q/pt in [GeV/c]^-1 (note that the pt is the
    // projection of momentum on the transverse plane of the new frame)
    scalar qOverPt = rho / getter::norm(bfield);
    // The estimated q/p in [GeV/c]^-1
    getter::element(params, e_bound_qoverp, 0) =
        qOverPt / getter::perp(vector2{1., invTanTheta});
    // The estimated momentum, and its projection along the magnetic
    // field diretion
    scalar pInGeV = std::abs(1.0f / getter::element(params, e_bound_qoverp, 0));
    scalar pzInGeV = 1.0f / std::abs(qOverPt) * invTanTheta;
    scalar massInGeV = mass / unit<scalar>::GeV;
    // The estimated velocity, and its projection along the magnetic
    // field diretion
    scalar v = pInGeV / getter::perp(vector2{pInGeV, massInGeV});
    scalar vz = pzInGeV / getter::perp(vector2{pInGeV, massInGeV});
    // The z coordinate of the bottom space point along the magnetic
    // field direction
    scalar pathz =
        vector::dot(sp_global_positions[0], bfield) / getter::norm(bfield);
    // The estimated time (use path length along magnetic field only if
    // it's not zero)
    if (pathz != 0) {
        getter::element(params, e_bound_time, 0) = pathz / vz;
    } else {
        getter::element(params, e_bound_time, 0) =
            getter::norm(sp_global_positions[0]) / v;
    }
    return params;
}
References e_bound_loc0, e_bound_loc1, e_bound_phi, e_bound_qoverp, e_bound_theta, e_bound_time, traccc::seed::spB_link, traccc::seed::spM_link, traccc::seed::spT_link, and uv_transform().
Referenced by traccc::device::estimate_track_params(), and traccc::track_params_estimation::operator()().
side_effect()
template<typename A , typename B , typename C >
std::function<B(A&&)> traccc::side_effect (std::function< B(A)> f, std::function< void(const C &)> s)
                                                                 {
    return [=](A&& i) -> B {
        s(i);
        return f(std::forward<A>(i));
    };
}
Referenced by TEST().
throughput_mt()
template<typename FULL_CHAIN_ALG , typename HOST_MR = vecmem::host_memory_resource>
int traccc::throughput_mt (std::string_view description, int argc, char * argv[], bool use_host_caching = false)
Helper function running a multi-threaded throughput test
Template Parameters
FULL_CHAIN_ALG The type of the full chain algorithm to use
HOST_MR The host memory resource type to use
Parameters
description A short description of the application
argc The count of command line arguments (from main(...))
argv The command line arguments (from main(...))
use_host_caching Flag specifying whether host-side memory caching should be used
Returns
The value to be returned from main(...)
                                         {
    // Convenience typedef.
    namespace po = boost::program_options;
    // Read in the command line options.
    po::options_description desc{description.data()};
    desc.add_options()("help,h", "Give help with the program's options");
    throughput_options throughput_cfg{desc};
    mt_options mt_cfg{desc};
    po::variables_map vm;
    po::store(po::parse_command_line(argc, argv, desc), vm);
    handle_argument_errors(vm, desc);
    throughput_cfg.read(vm);
    mt_cfg.read(vm);
    // Greet the user.
    std::cout << "\n"
              << description << "\n\n"
              << throughput_cfg << "\n"
              << mt_cfg << "\n"
              << std::endl;
    // Set seeding config
    // @FIXME: Seeding config should be configured by options
    seedfinder_config finder_config;
    spacepoint_grid_config grid_config(finder_config);
    seedfilter_config filter_config;
    // Set up the timing info holder.
    performance::timing_info times;
    // Set up the TBB arena and thread group.
    tbb::global_control global_thread_limit(
        tbb::global_control::max_allowed_parallelism, mt_cfg.threads + 1);
    tbb::task_arena arena{static_cast<int>(mt_cfg.threads), 0};
    tbb::task_group group;
    // Memory resource to use in the test.
    HOST_MR uncached_host_mr;
    // Read in all input events into memory.
    demonstrator_input input(&uncached_host_mr);
    {
        performance::timer t{"File reading", times};
        // Create empty inputs using the correct memory resource
        for (std::size_t i = 0; i < throughput_cfg.loaded_events; ++i) {
            input.push_back(demonstrator_input::value_type(&uncached_host_mr));
        }
        // Read event data into input vector
        io::read(input, throughput_cfg.loaded_events,
                 throughput_cfg.input_directory, throughput_cfg.detector_file,
                 throughput_cfg.digitization_config_file,
                 throughput_cfg.input_data_format);
    }
    // Set up cached memory resources on top of the host memory resource
    // separately for each CPU thread.
    std::vector<std::unique_ptr<vecmem::binary_page_memory_resource> >
        cached_host_mrs{mt_cfg.threads + 1};
    // Set up the full-chain algorithm(s). One for each thread.
    std::vector<FULL_CHAIN_ALG> algs;
    algs.reserve(mt_cfg.threads + 1);
    for (std::size_t i = 0; i < mt_cfg.threads + 1; ++i) {
        cached_host_mrs.at(i) =
            std::make_unique<vecmem::binary_page_memory_resource>(
                uncached_host_mr);
        vecmem::memory_resource& alg_host_mr =
            use_host_caching
                ? static_cast<vecmem::memory_resource&>(
                      *(cached_host_mrs.at(i)))
                : static_cast<vecmem::memory_resource&>(uncached_host_mr);
        algs.push_back({alg_host_mr, throughput_cfg.target_cells_per_partition,
                        finder_config, grid_config, filter_config});
    }
    // Seed the random number generator.
    std::srand(std::time(0));
    // Dummy count uses output of tp algorithm to ensure the compiler
    // optimisations don't skip any step
    std::atomic_size_t rec_track_params = 0;
    // Cold Run events. To discard any "initialisation issues" in the
    // measurements.
    {
        // Measure the time of execution.
        performance::timer t{"Warm-up processing", times};
        // Process the requested number of events.
        for (std::size_t i = 0; i < throughput_cfg.cold_run_events; ++i) {
            // Choose which event to process.
            const std::size_t event =
                std::rand() % throughput_cfg.loaded_events;
            // Launch the processing of the event.
            arena.execute([&, event]() {
                group.run([&, event]() {
                    rec_track_params.fetch_add(
                        algs.at(tbb::this_task_arena::current_thread_index())(
                                input[event].cells, input[event].modules)
                            .size());
                });
            });
        }
        // Wait for all tasks to finish.
        group.wait();
    }
    // Reset the dummy counter.
    rec_track_params = 0;
    {
        // Measure the total time of execution.
        performance::timer t{"Event processing", times};
        // Process the requested number of events.
        for (std::size_t i = 0; i < throughput_cfg.processed_events; ++i) {
            // Choose which event to process.
            const std::size_t event =
                std::rand() % throughput_cfg.loaded_events;
            // std::cout << "running event " << i << " : " << event <<
            // std::endl;
            // Launch the processing of the event.
            arena.execute([&, event]() {
                group.run([&, event]() {
                    rec_track_params.fetch_add(
                        algs.at(tbb::this_task_arena::current_thread_index())(
                                input[event].cells, input[event].modules)
                            .size());
                });
            });
        }
        // Wait for all tasks to finish.
        group.wait();
    }
    // Delete the algorithms and host memory caches explicitly before their
    // parent object would go out of scope.
    algs.clear();
    cached_host_mrs.clear();
    // Print some results.
    std::cout << "Reconstructed track parameters: " << rec_track_params.load()
              << std::endl;
    std::cout << "Time totals:" << std::endl;
    std::cout << times << std::endl;
    std::cout << "Throughput:" << std::endl;
    std::cout << performance::throughput{throughput_cfg.cold_run_events, times,
                                         "Warm-up processing"}
              << "\n"
              << performance::throughput{throughput_cfg.processed_events, times,
                                         "Event processing"}
              << std::endl;
    // Print results to log file
    if (throughput_cfg.log_file != "\0") {
        std::ofstream logFile;
        logFile.open(throughput_cfg.log_file, std::fstream::app);
        logFile << "\"" << throughput_cfg.input_directory << "\""
                << "," << mt_cfg.threads << "," << throughput_cfg.loaded_events
                << "," << throughput_cfg.cold_run_events << ","
                << throughput_cfg.processed_events << ","
                << throughput_cfg.target_cells_per_partition << ","
                << times.get_time("Warm-up processing").count() << ","
                << times.get_time("Event processing").count() << std::endl;
        logFile.close();
    }
    // Return gracefully.
    return 0;
}
References event, traccc::performance::timing_info::get_time(), handle_argument_errors(), ccl_generator::rand(), and traccc::io::read().
Referenced by main().
throughput_st()
template<typename FULL_CHAIN_ALG , typename HOST_MR = vecmem::host_memory_resource>
int traccc::throughput_st (std::string_view description, int argc, char * argv[], bool use_host_caching = false)
Helper function running a single-threaded throughput test
Template Parameters
FULL_CHAIN_ALG The type of the full chain algorithm to use
HOST_MR The host memory resource type to use
Parameters
description A short description of the application
argc The count of command line arguments (from main(...))
argv The command line arguments (from main(...))
use_host_caching Flag specifying whether host-side memory caching should be used
Returns
The value to be returned from main(...)
                                         {
    // Convenience typedef.
    namespace po = boost::program_options;
    // Read in the command line options.
    po::options_description desc{description.data()};
    desc.add_options()("help,h", "Give help with the program's options");
    throughput_options throughput_cfg{desc};
    po::variables_map vm;
    po::store(po::parse_command_line(argc, argv, desc), vm);
    handle_argument_errors(vm, desc);
    throughput_cfg.read(vm);
    // Greet the user.
    std::cout << "\n"
              << description << "\n\n"
              << throughput_cfg << "\n"
              << std::endl;
    // Set seeding config
    // @FIXME: Seeding config should be configured by options
    seedfinder_config finder_config;
    spacepoint_grid_config grid_config(finder_config);
    seedfilter_config filter_config;
    // Set up the timing info holder.
    performance::timing_info times;
    // Memory resource to use in the test.
    HOST_MR uncached_host_mr;
    std::unique_ptr<vecmem::binary_page_memory_resource> cached_host_mr =
        std::make_unique<vecmem::binary_page_memory_resource>(uncached_host_mr);
    vecmem::memory_resource& alg_host_mr =
        use_host_caching
            ? static_cast<vecmem::memory_resource&>(*cached_host_mr)
            : static_cast<vecmem::memory_resource&>(uncached_host_mr);
    // Read in all input events into memory.
    demonstrator_input input(&uncached_host_mr);
    {
        performance::timer t{"File reading", times};
        // Create empty inputs using the correct memory resource
        for (std::size_t i = 0; i < throughput_cfg.loaded_events; ++i) {
            input.push_back(demonstrator_input::value_type(&uncached_host_mr));
        }
        // Read event data into input vector
        io::read(input, throughput_cfg.loaded_events,
                 throughput_cfg.input_directory, throughput_cfg.detector_file,
                 throughput_cfg.digitization_config_file,
                 throughput_cfg.input_data_format);
    }
    // Set up the full-chain algorithm.
    std::unique_ptr<FULL_CHAIN_ALG> alg = std::make_unique<FULL_CHAIN_ALG>(
        alg_host_mr, throughput_cfg.target_cells_per_partition, finder_config,
        grid_config, filter_config);
    // Seed the random number generator.
    std::srand(std::time(0));
    // Dummy count uses output of tp algorithm to ensure the compiler
    // optimisations don't skip any step
    std::size_t rec_track_params = 0;
    // Cold Run events. To discard any "initialisation issues" in the
    // measurements.
    {
        // Measure the time of execution.
        performance::timer t{"Warm-up processing", times};
        // Process the requested number of events.
        for (std::size_t i = 0; i < throughput_cfg.cold_run_events; ++i) {
            // Choose which event to process.
            const std::size_t event =
                std::rand() % throughput_cfg.loaded_events;
            // Process one event.
            rec_track_params +=
                (*alg)(input[event].cells, input[event].modules).size();
        }
    }
    // Reset the dummy counter.
    rec_track_params = 0;
    {
        // Measure the total time of execution.
        performance::timer t{"Event processing", times};
        // Process the requested number of events.
        for (std::size_t i = 0; i < throughput_cfg.processed_events; ++i) {
            // Choose which event to process.
            const std::size_t event =
                std::rand() % throughput_cfg.loaded_events;
            // Process one event.
            rec_track_params +=
                (*alg)(input[event].cells, input[event].modules).size();
        }
    }
    // Explicitly delete the objects in the correct order.
    alg.reset();
    cached_host_mr.reset();
    // Print some results.
    std::cout << "Reconstructed track parameters: " << rec_track_params
              << std::endl;
    std::cout << "Time totals:" << std::endl;
    std::cout << times << std::endl;
    std::cout << "Throughput:" << std::endl;
    std::cout << performance::throughput{throughput_cfg.cold_run_events, times,
                                         "Warm-up processing"}
              << "\n"
              << performance::throughput{throughput_cfg.processed_events, times,
                                         "Event processing"}
              << std::endl;
    // Return gracefully.
    return 0;
}
References event, handle_argument_errors(), ccl_generator::rand(), and traccc::io::read().
Referenced by main().
uv_transform()
TRACCC_HOST_DEVICE vector2 traccc::uv_transform (const scalar & x, const scalar & y) [inline]
helper functions (for both cpu and gpu) to perform conformal transformation
Parameters
x is the x value
y is the y value
Returns
is the conformal transformation result
                                                                {
    vector2 uv;
    scalar denominator = x * x + y * y;
    uv[0] = x / denominator;
    uv[1] = y / denominator;
    return uv;
}
Referenced by seed_to_bound_vector().
Variable Documentation
float_epsilon
constexpr scalar traccc::float_epsilon = 1e-5 [constexpr]
Referenced by operator<(), operator==(), and operator==().
PION_MASS_MEV
constexpr scalar traccc::PION_MASS_MEV = 139.57018 * unit<scalar>::MeV [constexpr]
Referenced by traccc::device::estimate_track_params(), and traccc::track_params_estimation::operator()().