tests/cuda/test_ckf_sparse_tracks_telescope.cpp File Reference
#include `traccc/cuda/finding/finding_algorithm.hpp`
#include `traccc/cuda/fitting/fitting_algorithm.hpp`
#include `traccc/device/container_d2h_copy_alg.hpp`
#include `traccc/device/container_h2d_copy_alg.hpp`
#include `traccc/edm/track_candidate.hpp`
#include `traccc/io/read_measurements.hpp`
#include `traccc/io/utils.hpp`
#include `traccc/resolution/fitting_performance_writer.hpp`
#include `traccc/simulation/simulator.hpp`
#include `traccc/utils/memory_resource.hpp`
#include `traccc/utils/ranges.hpp`
#include `traccc/utils/seed_generator.hpp`
#include `tests/ckf_telescope_test.hpp`
#include `detray/detectors/create_telescope_detector.hpp`
#include `detray/io/common/detector_reader.hpp`
#include `detray/io/common/detector_writer.hpp`
#include `detray/propagator/propagator.hpp`
#include `detray/simulation/event_generator/track_generators.hpp`
#include <vecmem/memory/cuda/device_memory_resource.hpp>
#include <vecmem/memory/cuda/managed_memory_resource.hpp>
#include <vecmem/memory/host_memory_resource.hpp>
#include <vecmem/utils/cuda/async_copy.hpp>
#include <gtest/gtest.h>
#include <filesystem>
#include <string>
Functions
TEST_P (CkfSparseTrackTelescopeTests, Run)
INSTANTIATE_TEST_SUITE_P (CkfSparseTrackTelescopeValidation0, CkfSparseTrackTelescopeTests, ::testing::Values(std::make_tuple(`cuda_telescope_single_tracks`, std::array< scalar, 3u >{0.f, 0.f, 0.f}, std::array< scalar, 3u >{0.f, 200.f, 200.f}, std::array< scalar, 2u >{1.f, 1.f}, std::array< scalar, 2u >{0.f, 0.f}, std::array< scalar, 2u >{0.f, 0.f}, -1.f, 1, 5000)))
INSTANTIATE_TEST_SUITE_P (CkfSparseTrackTelescopeValidation1, CkfSparseTrackTelescopeTests, ::testing::Values(std::make_tuple(`cuda_telescope_double_tracks`, std::array< scalar, 3u >{0.f, 0.f, 0.f}, std::array< scalar, 3u >{0.f, 200.f, 200.f}, std::array< scalar, 2u >{1.f, 1.f}, std::array< scalar, 2u >{0.f, 0.f}, std::array< scalar, 2u >{0.f, 0.f}, -1.f, 2, 2500)))
INSTANTIATE_TEST_SUITE_P (CkfSparseTrackTelescopeValidation2, CkfSparseTrackTelescopeTests, ::testing::Values(std::make_tuple(`cuda_telescope_quadra_tracks`, std::array< scalar, 3u >{0.f, 0.f, 0.f}, std::array< scalar, 3u >{0.f, 200.f, 200.f}, std::array< scalar, 2u >{1.f, 1.f}, std::array< scalar, 2u >{0.f, 0.f}, std::array< scalar, 2u >{0.f, 0.f}, -1.f, 4, 1250)))
INSTANTIATE_TEST_SUITE_P (CkfSparseTrackTelescopeValidation3, CkfSparseTrackTelescopeTests, ::testing::Values(std::make_tuple(`cuda_telescope_decade_tracks`, std::array< scalar, 3u >{0.f, 0.f, 0.f}, std::array< scalar, 3u >{0.f, 200.f, 200.f}, std::array< scalar, 2u >{1.f, 1.f}, std::array< scalar, 2u >{0.f, 0.f}, std::array< scalar, 2u >{0.f, 0.f}, -1.f, 10, 500)))
Function Documentation
INSTANTIATE_TEST_SUITE_P() [1/4]
INSTANTIATE_TEST_SUITE_P (CkfSparseTrackTelescopeValidation0 , CkfSparseTrackTelescopeTests , [::testing::Values(std::make_tuple(`cuda_telescope_single_tracks`, std::array< scalar, 3u >{0.f, 0.f, 0.f}, std::array< scalar, 3u >{0.f, 200.f, 200.f}, std::array< scalar, 2u >{1.f, 1.f}, std::array< scalar, 2u >{0.f, 0.f}, std::array< scalar, 2u >{0.f, 0.f}, -1.f, 1, 5000))])
INSTANTIATE_TEST_SUITE_P() [2/4]
INSTANTIATE_TEST_SUITE_P (CkfSparseTrackTelescopeValidation1 , CkfSparseTrackTelescopeTests , [::testing::Values(std::make_tuple(`cuda_telescope_double_tracks`, std::array< scalar, 3u >{0.f, 0.f, 0.f}, std::array< scalar, 3u >{0.f, 200.f, 200.f}, std::array< scalar, 2u >{1.f, 1.f}, std::array< scalar, 2u >{0.f, 0.f}, std::array< scalar, 2u >{0.f, 0.f}, -1.f, 2, 2500))])
INSTANTIATE_TEST_SUITE_P() [3/4]
INSTANTIATE_TEST_SUITE_P (CkfSparseTrackTelescopeValidation2 , CkfSparseTrackTelescopeTests , [::testing::Values(std::make_tuple(`cuda_telescope_quadra_tracks`, std::array< scalar, 3u >{0.f, 0.f, 0.f}, std::array< scalar, 3u >{0.f, 200.f, 200.f}, std::array< scalar, 2u >{1.f, 1.f}, std::array< scalar, 2u >{0.f, 0.f}, std::array< scalar, 2u >{0.f, 0.f}, -1.f, 4, 1250))])
INSTANTIATE_TEST_SUITE_P() [4/4]
INSTANTIATE_TEST_SUITE_P (CkfSparseTrackTelescopeValidation3 , CkfSparseTrackTelescopeTests , [::testing::Values(std::make_tuple(`cuda_telescope_decade_tracks`, std::array< scalar, 3u >{0.f, 0.f, 0.f}, std::array< scalar, 3u >{0.f, 200.f, 200.f}, std::array< scalar, 2u >{1.f, 1.f}, std::array< scalar, 2u >{0.f, 0.f}, std::array< scalar, 2u >{0.f, 0.f}, -1.f, 10, 500))])
TEST_P()
TEST_P (CkfSparseTrackTelescopeTests , Run)
                                          {
    // Get the parameters
    const std::string name = std::get<0>(GetParam());
    const std::array<scalar, 3u> origin = std::get<1>(GetParam());
    const std::array<scalar, 3u> origin_stddev = std::get<2>(GetParam());
    const std::array<scalar, 2u> mom_range = std::get<3>(GetParam());
    const std::array<scalar, 2u> eta_range = std::get<4>(GetParam());
    const std::array<scalar, 2u> theta_range = eta_to_theta_range(eta_range);
    const std::array<scalar, 2u> phi_range = std::get<5>(GetParam());
    const scalar charge = std::get<6>(GetParam());
    const unsigned int n_truth_tracks = std::get<7>(GetParam());
    const unsigned int n_events = std::get<8>(GetParam());
    // Performance writer
    traccc::fitting_performance_writer::config fit_writer_cfg;
    fit_writer_cfg.file_path = "performance_track_fitting_" + name + ".root";
    traccc::fitting_performance_writer fit_performance_writer(fit_writer_cfg);
    /*****************************
     * Build a telescope geometry
     *****************************/
    // Memory resources used by the application.
    vecmem::host_memory_resource host_mr;
    vecmem::cuda::device_memory_resource device_mr;
    traccc::memory_resource mr{device_mr, &host_mr};
    vecmem::cuda::managed_memory_resource mng_mr;
    // Read back detector file
    const std::string path = name + "/";
    detray::io::detector_reader_config reader_cfg{};
    reader_cfg.add_file(path + "telescope_detector_geometry.json")
        .add_file(path + "telescope_detector_homogeneous_material.json");
    auto [host_det, names] =
        detray::io::read_detector<host_detector_type>(mng_mr, reader_cfg);
    auto field = detray::bfield::create_const_field(B);
    // Detector view object
    auto det_view = detray::get_data(host_det);
    /***************************
     * Generate simulation data
     ***************************/
    // Track generator
    using generator_type =
        detray::random_track_generator<traccc::free_track_parameters,
                                       uniform_gen_t>;
    generator_type::configuration gen_cfg{};
    gen_cfg.n_tracks(n_truth_tracks);
    gen_cfg.origin(origin);
    gen_cfg.origin_stddev(origin_stddev);
    gen_cfg.phi_range(phi_range[0], phi_range[1]);
    gen_cfg.theta_range(theta_range[0], theta_range[1]);
    gen_cfg.mom_range(mom_range[0], mom_range[1]);
    gen_cfg.charge(charge);
    generator_type generator(gen_cfg);
    // Smearing value for measurements
    traccc::measurement_smearer<transform3> meas_smearer(smearing[0],
                                                         smearing[1]);
    using writer_type =
        traccc::smearing_writer<traccc::measurement_smearer<transform3>>;
    typename writer_type::config smearer_writer_cfg{meas_smearer};
    // Run simulator
    const std::string full_path = io::data_directory() + path;
    std::filesystem::create_directories(full_path);
    auto sim = traccc::simulator<host_detector_type, b_field_t, generator_type,
                                 writer_type>(
        n_events, host_det, field, std::move(generator),
        std::move(smearer_writer_cfg), full_path);
    sim.run();
    /*****************************
     * Do the reconstruction
     *****************************/
    // Stream object
    traccc::cuda::stream stream;
    // Copy objects
    vecmem::cuda::async_copy copy{stream.cudaStream()};
    traccc::device::container_h2d_copy_alg<traccc::measurement_container_types>
        measurement_h2d{mr, copy};
    traccc::device::container_d2h_copy_alg<
        traccc::track_candidate_container_types>
        track_candidate_d2h{mr, copy};
    traccc::device::container_d2h_copy_alg<traccc::track_state_container_types>
        track_state_d2h{mr, copy};
    // Seed generator
    seed_generator<host_detector_type> sg(host_det, stddevs);
    // Finding algorithm configuration
    typename traccc::cuda::finding_algorithm<
        rk_stepper_type, device_navigator_type>::config_type cfg;
    // few tracks (~1 out of 1000 tracks) are missed when chi2_max = 15
    cfg.chi2_max = 30.f;
    // Finding algorithm object
    traccc::cuda::finding_algorithm<rk_stepper_type, device_navigator_type>
        device_finding(cfg, mr, copy, stream);
    // Fitting algorithm object
    typename traccc::cuda::fitting_algorithm<device_fitter_type>::config_type
        fit_cfg;
    traccc::cuda::fitting_algorithm<device_fitter_type> device_fitting(
        fit_cfg, mr, copy, stream);
    // Iterate over events
    for (std::size_t i_evt = 0; i_evt < n_events; i_evt++) {
        // Truth Track Candidates
        traccc::event_map2 evt_map(i_evt, path, path, path);
        traccc::track_candidate_container_types::host truth_track_candidates =
            evt_map.generate_truth_candidates(sg, mng_mr);
        ASSERT_EQ(truth_track_candidates.size(), n_truth_tracks);
        // Prepare truth seeds
        traccc::bound_track_parameters_collection_types::host seeds(mr.host);
        for (unsigned int i_trk = 0; i_trk < n_truth_tracks; i_trk++) {
            seeds.push_back(truth_track_candidates.at(i_trk).header);
        }
        ASSERT_EQ(seeds.size(), n_truth_tracks);
        traccc::bound_track_parameters_collection_types::buffer seeds_buffer{
            static_cast<unsigned int>(seeds.size()), mr.main};
        copy.setup(seeds_buffer);
        copy(vecmem::get_data(seeds), seeds_buffer,
             vecmem::copy::type::host_to_device);
        // Read measurements
        traccc::io::measurement_reader_output readOut(&host_mr);
        traccc::io::read_measurements(readOut, i_evt, path,
                                      traccc::data_format::csv);
        traccc::measurement_collection_types::host& measurements_per_event =
            readOut.measurements;
        traccc::measurement_collection_types::buffer measurements_buffer(
            measurements_per_event.size(), mr.main);
        copy(vecmem::get_data(measurements_per_event), measurements_buffer);
        // Instantiate output cuda containers/collections
        traccc::track_candidate_container_types::buffer
            track_candidates_cuda_buffer{{{}, *(mr.host)},
                                         {{}, *(mr.host), mr.host}};
        copy.setup(track_candidates_cuda_buffer.headers);
        copy.setup(track_candidates_cuda_buffer.items);
        // Navigation buffer
        auto navigation_buffer = detray::create_candidates_buffer(
            host_det,
            device_finding.get_config().max_num_branches_per_seed *
                seeds.size(),
            mr.main, mr.host);
        // Run finding
        track_candidates_cuda_buffer =
            device_finding(det_view, field, navigation_buffer,
                           measurements_buffer, seeds_buffer);
        traccc::track_candidate_container_types::host track_candidates_cuda =
            track_candidate_d2h(track_candidates_cuda_buffer);
        ASSERT_EQ(track_candidates_cuda.size(), n_truth_tracks);
        // Instantiate cuda containers/collections
        traccc::track_state_container_types::buffer track_states_cuda_buffer{
            {{}, *(mr.host)}, {{}, *(mr.host), mr.host}};
        // Run fitting
        track_states_cuda_buffer = device_fitting(
            det_view, field, navigation_buffer, track_candidates_cuda_buffer);
        traccc::track_state_container_types::host track_states_cuda =
            track_state_d2h(track_states_cuda_buffer);
        ASSERT_EQ(track_states_cuda.size(), n_truth_tracks);
        for (unsigned int i_trk = 0; i_trk < n_truth_tracks; i_trk++) {
            const auto& track_states_per_track = track_states_cuda[i_trk].items;
            const auto& fit_info = track_states_cuda[i_trk].header;
            consistency_tests(track_states_per_track);
            ndf_tests(fit_info, track_states_per_track);
            fit_performance_writer.write(track_states_per_track, fit_info,
                                         host_det, evt_map);
        }
    }
    fit_performance_writer.finalize();
    /********************
     * Pull value test
     ********************/
    static const std::vector<std::string> pull_names{
        "pull_d0", "pull_z0", "pull_phi", "pull_theta", "pull_qop"};
    pull_value_tests(fit_writer_cfg.file_path, pull_names);
    /********************
     * Success rate test
     ********************/
    scalar success_rate =
        static_cast<scalar>(n_success) / (n_truth_tracks * n_events);
    ASSERT_FLOAT_EQ(success_rate, 1.00f);
}
References traccc::host_container< header_t, item_t >::at(), traccc::csv, traccc::cuda::stream::cudaStream(), traccc::tests::data_test::data_directory, traccc::eta_to_theta_range(), traccc::fitting_performance_writer::config::file_path, traccc::fitting_performance_writer::finalize(), traccc::event_map2::generate_truth_candidates(), traccc::cuda::finding_algorithm< stepper_t, navigator_t >::get_config(), traccc::get_data(), traccc::container_element< header_reference_t, vector_reference_t >::header, traccc::finding_config< scalar_t >::max_num_branches_per_seed, traccc::io::measurement_reader_output::measurements, traccc::io::read_measurements(), traccc::simulator< detector_t, bfield_t, track_generator_t, writer_t >::run(), traccc::host_container< header_t, item_t >::size(), and traccc::fitting_performance_writer::write().