tests/core/test_module_map.cpp File Reference
#include `traccc/definitions/primitives.hpp`
#include `traccc/geometry/module_map.hpp`
#include `traccc/io/details/read_surfaces.hpp`
#include `traccc/io/utils.hpp`
#include <gtest/gtest.h>
#include <map>
#include <string>
Functions
TEST (geometry, module_map_simple)
TEST (geometry, module_map_operator_eq)
TEST (geometry, module_map_empty)
TEST (geometry, module_map_contains)
TEST (geometry, module_map_failure)
TEST (geometry, module_map_read_trackml)
Function Documentation
TEST() [1/6]
TEST (geometry , module_map_contains)
                                    {
    std::map<std::size_t, std::string> inp{{0, "zero"}, {1, "one"},
                                           {2, "two"}, {5, "five"},
                                           {11, "eleven"}, {21, "twenty-one"}};
    /*
     * Convert the old-style map to a module map.
     */
    traccc::module_map<std::size_t, std::string> map(inp);
    ASSERT_TRUE(map.contains(0));
    ASSERT_TRUE(map.contains(1));
    ASSERT_TRUE(map.contains(2));
    ASSERT_TRUE(map.contains(5));
    ASSERT_TRUE(map.contains(11));
    ASSERT_TRUE(map.contains(21));
    ASSERT_FALSE(map.contains(3));
    ASSERT_FALSE(map.contains(4));
    ASSERT_FALSE(map.contains(6));
    ASSERT_FALSE(map.contains(15));
    ASSERT_FALSE(map.contains(510482));
}
References traccc::module_map< K, V >::contains().
TEST() [2/6]
TEST (geometry , module_map_empty)
                                 {
    std::map<std::size_t, std::string> inp{{0, "zero"}, {1, "one"},
                                           {2, "two"}, {5, "five"},
                                           {11, "eleven"}, {21, "twenty-one"}};
    /*
     * Convert the old-style map to a module map.
     */
    traccc::module_map<std::size_t, std::string> map(inp);
    ASSERT_FALSE(map.empty());
}
References traccc::module_map< K, V >::empty().
TEST() [3/6]
TEST (geometry , module_map_failure)
                                   {
    std::map<std::size_t, std::string> inp{{0, "zero"}, {1, "one"}, {2, "two"}};
    /*
     * Convert the old-style map to a module map.
     */
    traccc::module_map<std::size_t, std::string> map(inp);
    /*
     * This value is not in the map, so it should throw.
     */
    ASSERT_THROW(map.at(100), std::out_of_range);
}
References traccc::module_map< K, V >::at().
TEST() [4/6]
TEST (geometry , module_map_operator_eq)
                                       {
    std::map<std::size_t, std::string> inp{{0, "zero"}, {1, "one"},
                                           {2, "two"}, {5, "five"},
                                           {11, "eleven"}, {21, "twenty-one"}};
    /*
     * Convert the old-style map to a module map.
     */
    traccc::module_map<std::size_t, std::string> map(inp);
    /*
     * Check if these are all the same.
     */
    ASSERT_EQ(map.at(0), map[0]);
    ASSERT_EQ(map.at(1), map[1]);
    ASSERT_EQ(map.at(2), map[2]);
    ASSERT_EQ(map.at(5), map[5]);
    ASSERT_EQ(map.at(11), map[11]);
    ASSERT_EQ(map.at(21), map[21]);
}
References traccc::module_map< K, V >::at().
TEST() [5/6]
TEST (geometry , module_map_read_trackml)
                                        {
    const std::string file =
        traccc::io::data_directory() + "tml_detector/trackml-detector.csv";
    /*
     * Next, we read the surfaces from the TrackML data file, and we get back a
     * std::map.
     */
    std::map<traccc::geometry_id, traccc::transform3> inp =
        traccc::io::details::read_surfaces(file);
    /*
     * Convert the old-style map to a module map.
     */
    traccc::module_map map(inp);
    /*
     * Obviously, the two maps need to be the same size!
     */
    ASSERT_EQ(map.size(), inp.size());
    /*
     * Next, iterate over all geometry IDs in the old map, and check whether
     * the two maps return exactly the same result.
     */
    for (const std::map<traccc::geometry_id, traccc::transform3>::value_type
             &i : inp) {
        ASSERT_EQ(map.at(i.first), i.second);
    }
}
References traccc::module_map< K, V >::at(), traccc::io::data_directory(), traccc::io::details::read_surfaces(), and traccc::module_map< K, V >::size().
TEST() [6/6]
TEST (geometry , module_map_simple)
TRACCC library, part of the ACTS project (R&D line)
(c) 2021-2022 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
                                  {
    std::map<std::size_t, std::string> inp{{0, "zero"}, {1, "one"},
                                           {2, "two"}, {5, "five"},
                                           {11, "eleven"}, {21, "twenty-one"}};
    /*
     * Convert the old-style map to a module map.
     */
    traccc::module_map<std::size_t, std::string> map(inp);
    /*
     * Check whether the two maps are the same size!
     */
    ASSERT_EQ(map.size(), inp.size());
    ASSERT_EQ(map.at(0), "zero");
    ASSERT_EQ(map.at(1), "one");
    ASSERT_EQ(map.at(2), "two");
    ASSERT_EQ(map.at(5), "five");
    ASSERT_EQ(map.at(11), "eleven");
    ASSERT_EQ(map.at(21), "twenty-one");
}
References traccc::module_map< K, V >::at(), and traccc::module_map< K, V >::size().