traccc::finding_performance_writer Class Reference
#include <finding_performance_writer.hpp>
Classes
struct config
Configuration for the tool.
Public Member Functions
finding_performance_writer (const config &cfg)
~finding_performance_writer ()
Destructor.
void write (const track_candidate_container_types::const_view &track_candidates_view, const event_map2 &evt_map)
void finalize ()
Private Attributes
config m_cfg
Configuration for the tool.
std::unique_ptr< details::finding_performance_writer_data > m_data
Opaque data members for the class.
Constructor & Destructor Documentation
finding_performance_writer()
traccc::finding_performance_writer::finding_performance_writer (const config & cfg)
Construct from configuration and log level.
Parameters
cfg The configuration
    : m_cfg(cfg),
      m_data(std::make_unique<details::finding_performance_writer_data>(cfg)) {
    m_data->m_eff_plot_tool.book("finding", m_data->m_eff_plot_cache);
    m_data->m_duplication_plot_tool.book("finding",
                                         m_data->m_duplication_plot_cache);
}
References m_data.
 finding_performance_writer()
traccc::finding_performance_writer::~finding_performance_writer ()
Destructor.
{}
Member Function Documentation
finalize()
void traccc::finding_performance_writer::finalize ()
                                          {
#ifdef TRACCC_HAVE_ROOT
    // Open the output file.
    std::unique_ptr<TFile> ofile(
        TFile::Open(m_cfg.file_path.c_str(), m_cfg.file_mode.c_str()));
    if ((!ofile) || ofile->IsZombie()) {
        throw std::runtime_error("Could not open output file \"" +
                                 m_cfg.file_path + "\" in mode \"" +
                                 m_cfg.file_mode + "\"");
    }
    ofile->cd();
#else
    std::cout << "ROOT file \"" << m_cfg.file_path << "\" is NOT created"
              << std::endl;
#endif // TRACCC_HAVE_ROOT
    m_data->m_eff_plot_tool.write(m_data->m_eff_plot_cache);
    m_data->m_duplication_plot_tool.write(m_data->m_duplication_plot_cache);
}
References traccc::finding_performance_writer::config::file_mode, traccc::finding_performance_writer::config::file_path, m_cfg, and m_data.
write()
void traccc::finding_performance_writer::write (const track_candidate_container_types::const_view & track_candidates_view, const event_map2 & evt_map)
                               {
    std::map<particle_id, std::size_t> match_counter;
    // Iterate over the tracks.
    track_candidate_container_types::const_device track_candidates(
        track_candidates_view);
    const unsigned int n_tracks = track_candidates.size();
    for (unsigned int i = 0; i < n_tracks; i++) {
        const auto& cands = track_candidates.at(i).items;
        std::vector<measurement> measurements;
        measurements.reserve(cands.size());
        for (const auto& cand : cands) {
            measurements.push_back(cand);
        }
        // Check which particle matches this seed.
        std::vector<particle_hit_count> particle_hit_counts =
            identify_contributing_particles(measurements, evt_map.meas_ptc_map);
        if (particle_hit_counts.size() == 1) {
            auto pid = particle_hit_counts.at(0).ptc.particle_id;
            match_counter[pid]++;
        }
    }
    for (auto const& [pid, ptc] : evt_map.ptc_map) {
        // Count only charged particles which satisfiy pT_cut
        if (ptc.charge == 0 || getter::perp(ptc.mom) < m_cfg.pT_cut) {
            continue;
        }
        bool is_matched = false;
        std::size_t n_matched_seeds_for_particle = 0;
        auto it = match_counter.find(pid);
        if (it != match_counter.end()) {
            is_matched = true;
            n_matched_seeds_for_particle = it->second;
        }
        m_data->m_eff_plot_tool.fill(m_data->m_eff_plot_cache, ptc, is_matched);
        m_data->m_duplication_plot_tool.fill(m_data->m_duplication_plot_cache,
                                             ptc,
                                             n_matched_seeds_for_particle - 1);
    }
}
References traccc::device_container< header_t, item_t >::at(), traccc::identify_contributing_particles(), traccc::container_element< header_reference_t, vector_reference_t >::items, m_cfg, m_data, traccc::event_map2::meas_ptc_map, traccc::finding_performance_writer::config::pT_cut, traccc::event_map2::ptc_map, and traccc::device_container< header_t, item_t >::size().
Member Data Documentation
m_cfg
config traccc::finding_performance_writer::m_cfg [private]
Configuration for the tool.
Referenced by finalize(), and write().
m_data
std::unique_ptr<details::finding_performance_writer_data> traccc::finding_performance_writer::m_data [private]
Opaque data members for the class.
Referenced by finalize(), finding_performance_writer(), and write().
The documentation for this class was generated from the following files:
performance/include/traccc/efficiency/finding_performance_writer.hpp
performance/src/efficiency/finding_performance_writer.cpp