traccc::device_container< header_t, item_t > Class Template Reference
Host container describing objects in a given event.
#include <device_container.hpp>
Public Types
using base_type = container_base< header_t, item_t, vecmem::device_vector, vecmem::jagged_device_vector >
Base class type.
Public Member Functions
template<template< typename, typename > class view_t>
TRACCC_HOST_DEVICE device_container (const view_t< header_t, item_t > &view)
TRACCC_HOST_DEVICE base_type::element_view at (typename base_type::size_type i)
Bounds-checking mutable element accessor.
TRACCC_HOST_DEVICE base_type::const_element_view at (typename base_type::size_type i) const
Bounds-checking immutable element accessor.
TRACCC_HOST_DEVICE base_type::item_type & at (const typename base_type::link_type &link)
Bounds-checking mutable item vector element accessor.
TRACCC_HOST_DEVICE const base_type::item_type & at (const typename base_type::link_type &link) const
Bounds-checking immutable item vector element accessor.
TRACCC_HOST_DEVICE base_type::element_view operator[] (typename base_type::size_type i)
Mutable element accessor.
TRACCC_HOST_DEVICE base_type::const_element_view operator[] (typename base_type::size_type i) const
Immutable element accessor.
TRACCC_HOST_DEVICE base_type::item_type & operator[] (const typename base_type::link_type &link)
Mutable item vector element accessor.
TRACCC_HOST_DEVICE const base_type::item_type & operator[] (const typename base_type::link_type &link) const
Immutable item vector element accessor.
TRACCC_HOST_DEVICE base_type::size_type size (void) const
Return the size of the container.
TRACCC_HOST_DEVICE base_type::size_type total_size () const
Additional Inherited Members
Detailed Description
template<typename header_t, typename item_t>
class traccc::device_container< header_t, item_t >
Host container describing objects in a given event.
Member Typedef Documentation
base_type
template<typename header_t , typename item_t >
using traccc::device_container< header_t, item_t >::base_type = container_base<header_t, item_t, vecmem::device_vector, vecmem::jagged_device_vector>
Base class type.
Constructor & Destructor Documentation
device_container()
template<typename header_t , typename item_t >
template<template< typename, typename > class view_t>
TRACCC_HOST_DEVICE traccc::device_container< header_t, item_t >::device_container (const view_t< header_t, item_t > & view) [inline]
Constructor from a `view object`
Note that it may also be a `data` or `buffer` object. It just needs to look like a `view object`.
        : base_type(view.headers, view.items) {}
Member Function Documentation
at() [1/4]
template<typename header_t , typename item_t >
TRACCC_HOST_DEVICE base_type::item_type& traccc::device_container< header_t, item_t >::at (const typename base_type::link_type & link) [inline]
Bounds-checking mutable item vector element accessor.
                                                 {
        return this->m_items.at(link.first).at(link.second);
    }
References traccc::container_base< header_t, item_t, vecmem::device_vector, vecmem::jagged_device_vector >::m_items.
at() [2/4]
template<typename header_t , typename item_t >
TRACCC_HOST_DEVICE const base_type::item_type& traccc::device_container< header_t, item_t >::at (const typename base_type::link_type & link) const [inline]
Bounds-checking immutable item vector element accessor.
                                                       {
        return this->m_items.at(link.first).at(link.second);
    }
References traccc::container_base< header_t, item_t, vecmem::device_vector, vecmem::jagged_device_vector >::m_items.
at() [3/4]
template<typename header_t , typename item_t >
TRACCC_HOST_DEVICE base_type::element_view traccc::device_container< header_t, item_t >::at (typename base_type::size_type i) [inline]
Bounds-checking mutable element accessor.
                                                                     {
        return {this->m_headers.at(i), this->m_items.at(i)};
    }
References traccc::container_base< header_t, item_t, vecmem::device_vector, vecmem::jagged_device_vector >::m_headers, and traccc::container_base< header_t, item_t, vecmem::device_vector, vecmem::jagged_device_vector >::m_items.
Referenced by traccc::device::build_tracks(), and traccc::finding_performance_writer::write().
at() [4/4]
template<typename header_t , typename item_t >
TRACCC_HOST_DEVICE base_type::const_element_view traccc::device_container< header_t, item_t >::at (typename base_type::size_type i) const [inline]
Bounds-checking immutable element accessor.
                                             {
        return {this->m_headers.at(i), this->m_items.at(i)};
    }
References traccc::container_base< header_t, item_t, vecmem::device_vector, vecmem::jagged_device_vector >::m_headers, and traccc::container_base< header_t, item_t, vecmem::device_vector, vecmem::jagged_device_vector >::m_items.
operator[]() [1/4]
template<typename header_t , typename item_t >
TRACCC_HOST_DEVICE base_type::item_type& traccc::device_container< header_t, item_t >::operator[] (const typename base_type::link_type & link) [inline]
Mutable item vector element accessor.
                                                 {
        return this->m_items[link.first][link.second];
    }
References traccc::container_base< header_t, item_t, vecmem::device_vector, vecmem::jagged_device_vector >::m_items.
operator[]() [2/4]
template<typename header_t , typename item_t >
TRACCC_HOST_DEVICE const base_type::item_type& traccc::device_container< header_t, item_t >::operator[] (const typename base_type::link_type & link) const [inline]
Immutable item vector element accessor.
                                                       {
        return this->m_items[link.first][link.second];
    }
References traccc::container_base< header_t, item_t, vecmem::device_vector, vecmem::jagged_device_vector >::m_items.
operator[]() [3/4]
template<typename header_t , typename item_t >
TRACCC_HOST_DEVICE base_type::element_view traccc::device_container< header_t, item_t >::operator[] (typename base_type::size_type i) [inline]
Mutable element accessor.
                                       {
        return {this->m_headers[i], this->m_items[i]};
    }
References traccc::container_base< header_t, item_t, vecmem::device_vector, vecmem::jagged_device_vector >::m_headers, and traccc::container_base< header_t, item_t, vecmem::device_vector, vecmem::jagged_device_vector >::m_items.
operator[]() [4/4]
template<typename header_t , typename item_t >
TRACCC_HOST_DEVICE base_type::const_element_view traccc::device_container< header_t, item_t >::operator[] (typename base_type::size_type i) const [inline]
Immutable element accessor.
                                             {
        return {this->m_headers[i], this->m_items[i]};
    }
References traccc::container_base< header_t, item_t, vecmem::device_vector, vecmem::jagged_device_vector >::m_headers, and traccc::container_base< header_t, item_t, vecmem::device_vector, vecmem::jagged_device_vector >::m_items.
size()
template<typename header_t , typename item_t >
TRACCC_HOST_DEVICE base_type::size_type traccc::device_container< header_t, item_t >::size (void) const [inline]
Return the size of the container.
In principle, the size of the two internal vectors should always be equal, but we can assert this at runtime for debug builds.
                                                 {
        assert(this->m_headers.size() == this->m_items.size());
        return this->m_headers.size();
    }
References traccc::container_base< header_t, item_t, vecmem::device_vector, vecmem::jagged_device_vector >::m_headers.
Referenced by traccc::device::fit(), and traccc::finding_performance_writer::write().
total_size()
template<typename header_t , typename item_t >
TRACCC_HOST_DEVICE base_type::size_type traccc::device_container< header_t, item_t >::total_size () const [inline]
@breif Get number of items of jagged vector
                                                   {
        typename base_type::size_type ret = 0;
        for (const typename base_type::item_vector::value_type& item :
             this->m_items) {
            ret += item.size();
        }
        return ret;
    }
References traccc::container_base< header_t, item_t, vecmem::device_vector, vecmem::jagged_device_vector >::m_items.
The documentation for this class was generated from the following file:
core/include/traccc/edm/details/device_container.hpp