examples/run/kokkos/seeding_example_kokkos.cpp File Reference
#include `traccc/efficiency/seeding_performance_writer.hpp`
#include `traccc/io/read_geometry.hpp`
#include `traccc/io/read_spacepoints.hpp`
#include `traccc/kokkos/seeding/spacepoint_binning.hpp`
#include `traccc/options/common_options.hpp`
#include `traccc/options/detector_input_options.hpp`
#include `traccc/options/handle_argument_errors.hpp`
#include `traccc/options/seeding_input_options.hpp`
#include `traccc/performance/collection_comparator.hpp`
#include `traccc/performance/timer.hpp`
#include `traccc/seeding/seeding_algorithm.hpp`
#include `traccc/seeding/track_params_estimation.hpp`
#include <vecmem/memory/host_memory_resource.hpp>
#include <chrono>
#include <exception>
#include <iomanip>
#include <iostream>
#include <Kokkos_Core.hpp>
Functions
int seq_run (const traccc::seeding_input_config &, const traccc::common_options &common_opts, const traccc::detector_input_options &det_opts, bool run_cpu)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
                                 {
    // Initialise both Kokkos and GoogleTest.
    Kokkos::initialize(argc, argv);
    // Set up the program options
    po::options_description desc("Allowed options");
    // Add options
    desc.add_options()("help,h", "Give some help with the program's options");
    traccc::common_options common_opts(desc);
    traccc::detector_input_options det_opts(desc);
    traccc::seeding_input_config seeding_input_cfg(desc);
    desc.add_options()("run_cpu", po::value<bool>()->default_value(false),
                       "run cpu tracking as well");
    po::variables_map vm;
    po::store(po::parse_command_line(argc, argv, desc), vm);
    // Check errors
    traccc::handle_argument_errors(vm, desc);
    // Read options
    common_opts.read(vm);
    det_opts.read(vm);
    seeding_input_cfg.read(vm);
    auto run_cpu = vm["run_cpu"].as<bool>();
    std::cout << "Running " << argv[0] << " " << det_opts.detector_file << " "
              << common_opts.input_directory << " " << common_opts.events
              << std::endl;
    int ret = seq_run(seeding_input_cfg, common_opts, det_opts, run_cpu);
    // Finalise Kokkos.
    Kokkos::finalize();
    return ret;
}
References traccc::detector_input_options::detector_file, traccc::common_options::events, traccc::handle_argument_errors(), traccc::common_options::input_directory, traccc::seeding_input_config::read(), traccc::detector_input_options::read(), traccc::common_options::read(), and seq_run().
seq_run()
int seq_run (const traccc::seeding_input_config & , const traccc::common_options & common_opts, const traccc::detector_input_options & det_opts, bool run_cpu)
TRACCC library, part of the ACTS project (R&D line)
(c) 2021-2022 CERN for the benefit of the ACTS project
Mozilla Public License Version 2.0
                                                                        {
    // Read the surface transforms
    auto surface_transforms = traccc::io::read_geometry(det_opts.detector_file);
    // Output stats
    uint64_t n_modules = 0;
    uint64_t n_spacepoints = 0;
    uint64_t n_seeds = 0;
    uint64_t n_seeds_kokkos = 0;
    // Configs
    traccc::seedfinder_config finder_config;
    traccc::spacepoint_grid_config grid_config(finder_config);
    traccc::seedfilter_config filter_config;
    // Memory resources used by the application.
    vecmem::host_memory_resource host_mr;
    traccc::memory_resource mr{host_mr, &host_mr};
    traccc::seeding_algorithm sa(finder_config, grid_config, filter_config,
                                 host_mr);
    traccc::track_params_estimation tp(host_mr);
    // KOKKOS Spacepoint Binning
    traccc::kokkos::spacepoint_binning m_spacepoint_binning(finder_config,
                                                            grid_config, mr);
    // performance writer
    traccc::seeding_performance_writer sd_performance_writer(
        traccc::seeding_performance_writer::config{});
    traccc::performance::timing_info elapsedTimes;
    // Loop over events
    for (unsigned int event = common_opts.skip;
         event < common_opts.events + common_opts.skip; ++event) {
        traccc::io::spacepoint_reader_output reader_output(&host_mr);
        traccc::seeding_algorithm::output_type seeds;
        traccc::track_params_estimation::output_type params;
        { // Start measuring wall time
            traccc::performance::timer wall_t("Wall time", elapsedTimes);
            /*-----------------
            hit file reading
            -----------------*/
            {
                traccc::performance::timer t("Hit reading (cpu)",
                                             elapsedTimes);
                // Read the hits from the relevant event file
                traccc::io::read_spacepoints(
                    reader_output, event, common_opts.input_directory,
                    surface_transforms, common_opts.input_data_format);
            } // stop measuring hit reading timer
            traccc::spacepoint_collection_types::host& spacepoints_per_event =
                reader_output.spacepoints;
            { // Spacepoin binning for kokkos
                traccc::performance::timer t("Spacepoint binning (kokkos)",
                                             elapsedTimes);
                m_spacepoint_binning(vecmem::get_data(spacepoints_per_event));
            }
            /*----------------------------
                Seeding algorithm
            ----------------------------*/
            // CPU
            if (run_cpu) {
                traccc::performance::timer t("Seeding (cpu)", elapsedTimes);
                seeds = sa(spacepoints_per_event);
            } // stop measuring seeding cpu timer
            /*----------------------------
            Track params estimation
            ----------------------------*/
            // CPU
            if (run_cpu) {
                traccc::performance::timer t("Track params (cpu)",
                                             elapsedTimes);
                params = tp(std::move(spacepoints_per_event), seeds,
                            {0.f, 0.f, finder_config.bFieldInZ});
            } // stop measuring track params cpu timer
        } // Stop measuring wall time
    }
    if (common_opts.check_performance) {
        sd_performance_writer.finalize();
    }
    std::cout << "==> Statistics ... " << std::endl;
    std::cout << "- read " << n_spacepoints << " spacepoints from "
              << n_modules << " modules" << std::endl;
    std::cout << "- created (cpu) " << n_seeds << " seeds" << std::endl;
    std::cout << "- created (kokkos) " << n_seeds_kokkos << " seeds"
              << std::endl;
    std::cout << "==>Elapsed times...\n" << elapsedTimes << std::endl;
    return 0;
}
References traccc::seedfinder_config::bFieldInZ, traccc::common_options::check_performance, traccc::detector_input_options::detector_file, event, traccc::common_options::events, traccc::get_data(), traccc::common_options::input_data_format, traccc::common_options::input_directory, traccc::io::read_geometry(), traccc::io::read_spacepoints(), traccc::common_options::skip, and traccc::io::spacepoint_reader_output::spacepoints.
Referenced by main().