SpacePoint Struct Reference
#include <space_point.hpp>
Public Member Functions
float x () const
float y () const
float z () const
float r () const
Public Attributes
float m_x
float m_y
float m_z
float m_r
int layer
float varianceR
float varianceZ
Member Function Documentation
r()
float SpacePoint::r () const [inline]
{ return m_r; }
References m_r.
x()
float SpacePoint::x () const [inline]
{ return m_x; }
References m_x.
Referenced by operator==(), and TEST_P().
y()
float SpacePoint::y () const [inline]
{ return m_y; }
References m_y.
Referenced by operator==(), and TEST_P().
z()
float SpacePoint::z () const [inline]
{ return m_z; }
References m_z.
Referenced by operator==(), and TEST_P().
Member Data Documentation
layer
int SpacePoint::layer
m_r
float SpacePoint::m_r
Referenced by r().
m_x
float SpacePoint::m_x
Referenced by operator==(), and x().
m_y
float SpacePoint::m_y
Referenced by operator==(), and y().
m_z
float SpacePoint::m_z
Referenced by operator==(), and z().
varianceR
float SpacePoint::varianceR
Referenced by TEST_P().
varianceZ
float SpacePoint::varianceZ
Referenced by TEST_P().
The documentation for this struct was generated from the following file:
tests/common/tests/space_point.hpp