traccc::event_map Struct Reference
#include <event_map.hpp>
Public Member Functions
event_map ()=delete
event_map (std::size_t event, const std::string &detector_file, const std::string &digi_config_file, const std::string &cell_dir, const std::string &hit_dir, const std::string particle_dir, vecmem::memory_resource &resource)
event_map (std::size_t event, const std::string &detector_file, const std::string &hit_dir, const std::string particle_dir, vecmem::memory_resource &resource)
Public Attributes
particle_map ptc_map
measurement_particle_map meas_ptc_map
Constructor & Destructor Documentation
event_map() [1/3]
traccc::event_map::event_map () [delete]
event_map() [2/3]
traccc::event_map::event_map (std::size_t event, const std::string & detector_file, const std::string & digi_config_file, const std::string & cell_dir, const std::string & hit_dir, const std::string particle_dir, vecmem::memory_resource & resource) [inline]
                                               {
        ptc_map = generate_particle_map(event, particle_dir);
        meas_ptc_map = generate_measurement_particle_map(
            event, detector_file, digi_config_file, cell_dir, hit_dir,
            particle_dir, resource);
    }
References detector_file, digi_config_file, event, traccc::generate_measurement_particle_map(), traccc::generate_particle_map(), meas_ptc_map, and ptc_map.
event_map() [3/3]
traccc::event_map::event_map (std::size_t event, const std::string & detector_file, const std::string & hit_dir, const std::string particle_dir, vecmem::memory_resource & resource) [inline]
                                               {
        ptc_map = generate_particle_map(event, particle_dir);
        meas_ptc_map = generate_measurement_particle_map(
            event, detector_file, hit_dir, particle_dir, resource);
    }
References detector_file, event, traccc::generate_measurement_particle_map(), traccc::generate_particle_map(), meas_ptc_map, and ptc_map.
Member Data Documentation
meas_ptc_map
measurement_particle_map traccc::event_map::meas_ptc_map
Referenced by event_map(), and traccc::seeding_performance_writer::write().
ptc_map
particle_map traccc::event_map::ptc_map
Referenced by event_map(), and traccc::seeding_performance_writer::write().
The documentation for this struct was generated from the following file:
io/include/traccc/io/event_map.hpp