traccc::spacepoint Struct Reference
#include <spacepoint.hpp>
Public Member Functions
TRACCC_HOST_DEVICE const scalar & x () const
TRACCC_HOST_DEVICE const scalar & y () const
TRACCC_HOST_DEVICE const scalar & z () const
TRACCC_HOST_DEVICE scalar radius () const
Public Attributes
point3 global {0., 0., 0.}
The global position of the spacepoint in 3D space.
measurement meas
The local measurement of the spacepoint on the detector surface.
Detailed Description
A spacepoint expressed in global coordinates
It describes the 3D position of the spacepoint, and the 2D measurement that the spacepoint was created from.
Member Function Documentation
radius()
TRACCC_HOST_DEVICE scalar traccc::spacepoint::radius () const [inline]
                          {
        return std::sqrt(global[0] * global[0] + global[1] * global[1]);
    }
References global.
x()
TRACCC_HOST_DEVICE const scalar& traccc::spacepoint::x () const [inline]
{ return global[0]; }
References global.
Referenced by traccc::is_valid_sp(), traccc::details::is_same_object< spacepoint >::operator()(), traccc::operator<(), and traccc::operator==().
y()
TRACCC_HOST_DEVICE const scalar& traccc::spacepoint::y () const [inline]
{ return global[1]; }
References global.
Referenced by traccc::is_valid_sp(), traccc::details::is_same_object< spacepoint >::operator()(), traccc::operator<(), and traccc::operator==().
z()
TRACCC_HOST_DEVICE const scalar& traccc::spacepoint::z () const [inline]
{ return global[2]; }
References global.
Referenced by traccc::is_valid_sp(), traccc::details::is_same_object< spacepoint >::operator()(), traccc::operator<(), and traccc::operator==().
Member Data Documentation
global
point3 traccc::spacepoint::global {0., 0., 0.}
The global position of the spacepoint in 3D space.
Referenced by traccc::generate_hit_map(), traccc::generate_hit_particle_map(), traccc::generate_measurement_particle_map(), operator==(), radius(), TEST(), x(), y(), and z().
meas
measurement traccc::spacepoint::meas
The local measurement of the spacepoint on the detector surface.
Referenced by traccc::generate_hit_particle_map(), traccc::details::is_same_object< spacepoint >::operator()(), and traccc::operator==().
The documentation for this struct was generated from the following file:
core/include/traccc/edm/spacepoint.hpp